import type {Island} from '../core/types';
import {adaptationLock,adaptationDuration,willing,adaptationTech,adaptationFee} from '../core/AdaptationManager';
import {characterPortrait} from '../renderer/CharacterTextures';
import {hasPower,powerStatus} from '../core/PowerManager';
import {COMMODITIES} from '../core/civilization';
let preferredLab:string|undefined;
export function selectAdaptationLab(id:string):void{preferredLab=id;}
export function adaptationPanelHTML(s:Island):string{
 const branch=s.civilization?.anomalyBranch;if(!branch)return '';
 const data={
 hightech:{name:'Thiết bị hỗ trợ',research:'Thiết bị hỗ trợ tự nguyện',fee:'1 vi mạch + 2 linh kiện',care:'1 linh kiện',form:'thiết bị',effect:'Vòng tay nhỏ hỗ trợ +15% tiến độ công nghiệp khi có nguyên liệu và chỗ thành phẩm, dùng đủ công thức.'},
 mystic:{name:'Cộng hưởng linh khí',research:'Cộng hưởng tự nguyện',fee:'2 tinh chất + 1 vải',care:'1 tinh chất',form:'cộng hưởng',effect:'Ngọc/lá nhỏ hỗ trợ +20% tiến độ tinh luyện/dệt/xay/nướng trong 4 ô tháp có thợ/điện/tinh chất, nguồn ổn định ≥40. Ngoài vùng/nguồn yếu/tháp ngừng không có lợi ích hoặc tiêu lượt. Không cộng dồn từ nhiều tháp.'},
 eldritch:{name:'Thích nghi sinh chất',research:'Thích nghi sinh chất tự nguyện',fee:'2 sinh chất + 1 vải',care:'1 sinh chất',form:'thích nghi sinh chất',effect:'Lớp bảo vệ mềm giảm phơi nhiễm cá nhân mỗi mẻ thu: thường 5→3 hoặc lọc 2→1. Nhiễm nguồn, đầu ra và ngưỡng dừng nguồn 60/người 30 giữ nguyên. Không miễn nhiễm: vẫn cần nghỉ/cách ly/lọc mẫu. Trước đăng ký cần phơi nhiễm dưới 15; không giết/hiến tế/lây cả đảo.'}
 }[branch];if(!data)return '';
 const labs=s.buildings.filter(b=>b.type==='measurement_lab'&&b.complete&&!b.upgrade),a=s.adaptationProcess,learned=s.civilization!.unlocks.includes(adaptationTech(s));
 const chosen=labs.find(b=>b.id===(a?.labId??preferredLab))??labs[0],staff=chosen?.workers.some(id=>s.npcs.some(n=>n.id===id&&n.isAlive&&n.position&&n.age>=18)),gener=s.buildings.find(b=>b.type==='steam_generator'&&b.complete&&!b.upgrade);
 const stock=(mode:'apply'|'service'|'remove')=>Object.entries(adaptationFee(mode,branch)).map(([id,amount])=>({id:id as keyof typeof COMMODITIES,amount:amount!,have:s.civilization!.inventory[id as keyof typeof COMMODITIES]}));
 const lack=(mode:'apply'|'service'|'remove')=>stock(mode).filter(g=>g.have<g.amount).map(g=>`${COMMODITIES[g.id]} ${g.have}/${g.amount}`).join(', ');
 const people=s.npcs.filter(n=>n.isAlive&&n.position&&n.age>=18&&n.occupation!=='child').sort((x,y)=>(y.adaptation?2:willing(y)?1:0)-(x.adaptation?2:willing(x)?1:0)),ready=people.filter(n=>n.adaptation||a?.npcId===n.id||willing(n)),others=people.filter(n=>!ready.includes(n));
 return `<section class="era-summary adaptation-panel"><h3>Thích nghi tự nguyện · ${data.name}</h3><p>Nghiên cứu ${data.research} trước khi đăng ký. Chỉ người trưởng thành khỏe, đủ ăn/ngủ, ít sợ và tin tưởng cộng đồng mới đồng ý; không ép hoặc đổi toàn dân.</p><p>${data.fee}, 10 nhịp cư dân/thợ tại viện có 2 công suất. ${data.effect} Có 100 lượt hỗ trợ; thiếu chăm sóc ngừng lợi ích, không gây chết. Chăm sóc ${data.care}/4 nhịp; gỡ miễn phí/5 nhịp tại viện. Giữ nghề, quan hệ và tính cách, không tự di truyền.</p><label>Viện hỗ trợ <select id="adapt-lab" ${a?'disabled':''}>${labs.map(b=>`<option value="${b.id}" ${b.id===chosen?.id?'selected':''}>(${b.tileX},${b.tileY}) · ${b.workers.length} thợ</option>`).join('')}</select></label><div class="adaptation-readiness"><h4>Chuẩn bị viện trước khi đăng ký</h4><p data-adapt-staff>${!chosen?'Cần xây một viện hoàn thành.':staff?`Đã phân công ${chosen.workers.length} thợ; người đang đi/ăn/ngủ thì giữ tiến độ.`:'Viện chưa có thợ: phân công một người lớn trước khi trả phí.'}</p><p data-adapt-power>${chosen?powerStatus(s,chosen):'Chưa có viện'}${chosen&&chosen.powerEnabled!==false&&!hasPower(s,chosen)?' · cần 2 công suất, bật nguồn/ưu tiên hoặc chờ giao than.':''}</p><p data-adapt-stock>Vật tư đăng ký đã về kho: ${stock('apply').map(g=>`${COMMODITIES[g.id]} ${g.have}/${g.amount}`).join(' · ')}. Chăm sóc: ${stock('service').map(g=>`${COMMODITIES[g.id]} ${g.have}/${g.amount}`).join(' · ')}.</p>${chosen?`<button data-adapt-manage="${chosen.id}">Phân công / xem viện</button><button id="adapt-lab-toggle">${chosen.powerEnabled===false?'Bật':'Tắt'} viện</button>`:''}${gener?`<button id="adapt-generator-toggle">${gener.powerEnabled===false?'Bật':'Tắt'} máy phát</button><button data-adapt-manage="${gener.id}">Xem nhiên liệu máy phát</button>`:''}<p>Thợ và người đăng ký cần tới viện; mất điện hoặc ăn/ngủ giữ tiến độ. Vật tư chỉ trừ khi xác nhận, hủy hoàn một lần. Sau phân công, trở về Nhiệm vụ.</p></div><p role="status" class="adaptation-state">${s.adaptationMessage??'Chọn cư dân và xem trước trước khi xác nhận.'}${a?` · ${a.workTicks}/${adaptationDuration(a.mode)}`:''}</p>${a?'<button id="cancel-adaptation">Hủy và hoàn vật tư chưa sử dụng</button>':''}${ready.map(n=>{
 const mode=n.adaptation?'service':'apply',reason=adaptationLock(s,n,mode)??(chosen?.workers.includes(n.id)?'Người này đang trực viện; chọn cư dân khác.':!staff?'Phân công thợ viện trước.':lack(mode)?'Thiếu vật tư đã về kho: '+lack(mode):null),disabled=!learned||!labs.length||!!reason;
 return `<details data-decision-key="adapt-${n.id}" data-adapt-person="${n.id}"><summary>${characterPortrait(n,'anomaly')} ${n.name.replace('#',' · ')} · ${n.adaptation?`đã hỗ trợ · còn ${n.adaptation.charge}/100 lượt`:'xem trước/đồng ý'}</summary>${n.adaptation?.charge===0?`<p data-adapt-upkeep="${n.id}" role="status">Đã hết lượt hỗ trợ: lợi ích tạm ngừng. Chăm sóc bằng ${data.care} tại viện hoặc gỡ miễn phí; sức khỏe không bị trừ vì hết lượt.</p>`:''}<p>${n.adaptation?'Có thể chăm sóc hoặc gỡ, không đổi nghề.':data.effect}${branch==='eldritch'?` Phơi nhiễm hiện tại: ${n.exposure??0}/30.`:''}</p>${reason?`<p>${reason}</p>`:''}<button data-adapt-start="${n.id}" data-adapt-mode="${mode}" ${disabled?'disabled':''}>${n.adaptation?`Xác nhận chăm sóc · ${data.care}`:`Xác nhận ${data.form} · ${data.fee}`}</button>${n.adaptation?`<button data-adapt-start="${n.id}" data-adapt-mode="remove" ${s.adaptationProcess?'disabled':''}>Gỡ ${data.form} · miễn phí</button>`:''}</details>`;
 }).join('')}<details data-decision-key="adapt-not-ready"><summary>Chưa sẵn sàng (${others.length} người) · xem lý do</summary>${others.map(n=>`<p>${characterPortrait(n,'anomaly')} ${n.name.replace('#',' · ')} · Sức khỏe ${Math.round(n.health??100)}% · đói ${Math.round(n.needs.hunger)} · mệt ${Math.round(n.needs.rest)} · sợ ${Math.round(n.needs.safety)}. ${adaptationLock(s,n,'apply')??'Chưa đồng ý thay đổi; chọn người khác hoặc chăm sóc nhu cầu trước.'}</p>`).join('')}</details><button data-era-panel="research">Mở nghiên cứu</button></section>`;
}
