import {FOUNDATION_LABELS} from '../core/AnalysisManager';
import {hasPower} from '../core/PowerManager';
import type {Island} from '../core/types';
import {SURVEY_LABELS} from '../core/SurveyManager';
export function analysisPanelHTML(s:Island):string{
 if(s.civilization?.era!=='modern'||!s.civilization.unlocks.includes('field_surveys'))return '';
 const labs=s.buildings.filter(b=>b.type==='measurement_lab'&&b.complete&&!b.upgrade),state=s.analysis;
 const active=state?.active??state?.foundation,foundation=!!state?.foundation;
 const activeLab=active?labs.find(b=>b.id===active.labId):undefined;
 const status=active?(!activeLab||activeLab.powerEnabled===false||!hasPower(s,activeLab)?`Thiếu điện hoặc đã tắt cơ sở · giữ tiến độ ${foundation?'dự án nền tảng':'phân tích'}.`:`Đủ điện; ${foundation?'dự án nền tảng':'phân tích'} tiếp khi thợ làm tại chỗ và mô phỏng chạy.`):state?.message;
 return `<section class="era-summary analysis-panel"><h3>Phân tích tại cơ sở đo đạc · ${s.surveys?.sites.filter(p=>p.analyzed).length??0}/3 hồ sơ</h3><p>Nghiên cứu Đo đạc hiện đại bằng 6 linh kiện +1 bộ phận máy, xây cơ sở và phân công thợ. Mỗi hồ sơ cần 2 linh kiện, 40 nhịp tại chỗ, 2 công suất.</p><p>Điện của cùng một cơ sở có thợ: ${Math.min(5,Math.max(0,...labs.map(b=>b.labPoweredTicks??0))/10).toFixed(1)}/5 ngày liên tiếp. Mất điện/bỏ thợ reset riêng; không ghép nhiều viện hoặc mượn thời gian xưởng máy. Bộ đếm là điện kết nối, không khẳng định thợ làm 24 giờ không nghỉ.</p>${state?`<p class="analysis-status" role="status">${status}</p>`:''}<button data-era-panel="research">Nghiên cứu đo đạc</button><button data-era-panel="build">Xây cơ sở</button>${active?`<p>Tiến độ ${foundation?'dự án nền tảng':'phân tích'} ${active.workTicks}/${foundation?60:40}</p><button id="${foundation?'cancel-foundation':'cancel-analysis'}">Hủy, xóa tiến độ và hoàn ${foundation?4:2} linh kiện</button>`:`<label>Cơ sở tiếp nhận <select id="analysis-lab">${labs.map(b=>`<option value="${b.id}">Cơ sở (${b.tileX}, ${b.tileY})</option>`).join('')}</select></label>${s.surveys?.sites.filter(p=>p.surveyed).map(p=>`<article class="survey-site"><h4>${SURVEY_LABELS[p.kind]}</h4><p>${p.analyzed?'Đã phân tích':'Hồ sơ chưa phân tích'}</p>${p.analyzed?decisionHTML(s,p):''}<button data-start-analysis="${p.id}" ${p.analyzed||!labs.length||s.civilization!.inventory.components<2?'disabled':''}>Phân tích · 2 linh kiện</button></article>`).join('')??''}`}<p>Dị Tượng vẫn khóa. Dự án nền tảng chỉ tạo hồ sơ kiến thức; cần kinh tế nhánh có nguồn và nơi dùng sản phẩm. Không tự chọn nhánh chủ đạo hay biến đổi cư dân.</p></section>`;
}

function decisionHTML(s:Island,p:NonNullable<Island['surveys']>['sites'][number]):string{
 if(p.decision==='contain')return '<p>Đã phong tỏa · khép nghiên cứu tại điểm này, không khai thác; kinh tế đảo tiếp tục bình thường.</p>';
 if(p.decision==='research')return `<p>${p.foundationComplete?'Đã hoàn tất':'Đang thực hiện'} ${FOUNDATION_LABELS[p.kind]}. Chưa chuyển nhánh chủ đạo.</p>`;
 return `<p>${p.decision==='ignore'?'Đang tạm bỏ qua · có thể quay lại sau.':'Chọn hướng xử lý sau khi xem chi phí và hệ quả:'}</p><details class="site-decision" data-decision-key="${p.id}-research"><summary>Nghiên cứu · 4 linh kiện</summary><p>${FOUNDATION_LABELS[p.kind]}: 60 nhịp tại cơ sở có thợ và 2 công suất. Mất điện giữ tiến độ; hủy hoàn 4 linh kiện và xóa tiến độ. Hoàn tất tạo hồ sơ nền tảng cho dự án khai thác sau; chưa có sản phẩm nhánh hoặc biến thể.</p><button data-site-decision="research" data-site="${p.id}" ${s.civilization!.inventory.components<4?'disabled':''}>Xác nhận nghiên cứu</button></details><details class="site-decision" data-decision-key="${p.id}-contain"><summary>Phong tỏa · 4 vải +2 đá xây</summary><p>Khép nghiên cứu và khai thác tại điểm này, không mở nhánh. Quyết định cố định; không gây hại dân cư hoặc khóa công nghiệp hiện tại.</p><button data-site-decision="contain" data-site="${p.id}" ${s.civilization!.inventory.cloth<4||s.civilization!.inventory.cutStone<2?'disabled':''}>Xác nhận phong tỏa</button></details><details class="site-decision" data-decision-key="${p.id}-ignore"><summary>Bỏ qua · miễn phí</summary><p>Dừng theo đuổi điểm lạ, không nhận sản phẩm hay mở nhánh. Có thể quay lại nghiên cứu hoặc phong tỏa; kinh tế Hiện Đại tiếp tục.</p><button data-site-decision="ignore" data-site="${p.id}" ${p.decision==='ignore'?'disabled':''}>Xác nhận bỏ qua</button></details>`;
}
