import {hasPower} from '../core/PowerManager';
import type {Island} from '../core/types';
import {anomalyRequirements,branchName} from '../core/AnomalyManager';
export function anomalyPanelHTML(s:Island):string{
 const c=s.civilization;if(!c||!['modern','anomaly'].includes(c.era))return '';
 if(c.anomalyBranch)return `<section class="era-summary anomaly-panel"><h3>Dị Tượng · ${branchName(c.anomalyBranch)}</h3><p>${c.branchMessage??'Đã chọn nhánh.'}</p><p>${c.anomalyBranch==='eldritch'?'Nguồn di tích và sinh chất cần kiểm soát. Trong chi tiết trạm có thể bật lọc mẫu:1 sinh chất cho 5 mẻ, nhiễm nguồn4/phơi nhiễm2 mỗi mẻ thay8/5; thiếu nhiên liệu ngừng an toàn. Không tự biến đổi dân.':c.anomalyBranch==='mystic'?'Nguồn hồi phục khi nghỉ; giữ ổn định ít nhất40 và giao tinh chất tới tháp để chăm sóc. Chăm sóc vẫn cần người tại chỗ và điện, không cho hàng miễn phí.':'Điện và người điều phối tăng tốc xưởng; mở chi tiết xưởng trong vùng điều khiển để lập định mức3 hoặc5 mẻ. Máy tự dừng theo hàng đã chế tạo, kể cả còn tại xưởng/đang giao. Vật tư và vận chuyển vẫn cần đầy đủ.'}</p><p>Ba hướng có thích nghi tự nguyện từng người ở bảng bên dưới, cần nghiên cứu/vật tư/chăm sóc và có đường gỡ. Đổi nhánh/hạt nhân còn thiếu. Cư dân giữ nghề và thuộc tính.</p></section>`;
 if(c.branchDevelopment){const lab=s.buildings.find(b=>b.id===c.branchDevelopment!.labId),status=!lab||lab.powerEnabled===false||!hasPower(s,lab)?'Thiếu điện viện · giữ tiến độ chuyển nhánh.':(lab.labPoweredTicks??0)<50?`Điện riêng viện ${((lab.labPoweredTicks??0)/10).toFixed(1)}/5 ngày · chờ phục hồi, giữ tiến độ.`:c.branchMessage;return `<section class="era-summary anomaly-panel"><h3>Dự án ${branchName(c.branchDevelopment.branch)} · ${c.branchDevelopment.workTicks}/50 nhịp tại viện</h3><p>${status??''}</p><p>50 nhịp làm tại viện tương đương5 ngày công; nghỉ/mất điện giữ tiến độ. Mất điện đặt lại chứng minh5ngày điện riêng, cần phục hồi trước khi làm tiếp. Không trả lại phí khi tải game.</p><button id="cancel-branch">Hủy, xóa tiến độ và hoàn 50 linh kiện +20 thép</button></section>`;}
 const labs=s.buildings.filter(b=>b.type==='measurement_lab'&&b.complete&&!b.upgrade).sort((a,b)=>(b.labPoweredTicks??0)-(a.labPoweredTicks??0));
 return `<section class="era-summary anomaly-panel"><h3>Bước ngoặt Dị Tượng · chọn nhánh chủ đạo</h3><label>Viện thực hiện <select id="branch-lab">${labs.map(b=>`<option value="${b.id}">Viện (${b.tileX},${b.tileY}) · ${((b.labPoweredTicks??0)/10).toFixed(1)} ngày điện</option>`).join('')}</select></label>${(['hightech','mystic','eldritch'] as const).map(branch=>{const rows=anomalyRequirements(s,labs[0]?.id,branch),ready=rows.every(r=>r.met)&&!c.research&&!c.transition&&!s.analysis?.active&&!s.analysis?.foundation;return `<details data-decision-key="branch-${branch}"><summary>${branchName(branch)} · xem chi phí và hệ quả</summary>${rows.map(r=>`<p>${r.met?'✓':'○'} ${r.label}</p>`).join('')}<p>Trả50 linh kiện +20 thép đã về kho,50 nhịp làm tại viện (5 ngày công). Hoàn tất chốt ${branchName(branch)}. ${branch==='eldritch'?'Mở lọc mẫu tại trạm bằng1 sinh chất / 5 mẻ, giảm nhiễm nguồn 8 → 4 / phơi nhiễm 5 → 2; vẫn tiêu nguồn và cần thợ/vận chuyển, không tự biến đổi dân.':branch==='mystic'?'Vận hành linh thạch→tinh chất→tháp chăm sóc, cần giữ nguồn ổn định; không tự biến đổi dân.':'Mở lập định mức tự dừng xưởng qua trung tâm điều khiển có điện/người tại chỗ; không biến đổi dân hoặc cho hàng miễn phí.'}</p><p>Trước hoàn tất có thể hủy hoàn phí và xóa tiến độ. Sau hoàn tất đổi nhánh chưa triển khai; công nghiệp hiện tại tiếp tục dùng được.</p><button data-start-branch="${branch}" ${ready?'':'disabled'}>Xác nhận đầu tư ${branchName(branch)}</button></details>`;}).join('')}<p>Ba hướng cần chuỗi đã vận hành và viện đủ điện riêng. Chỉ trả phí khi đủ điều kiện và bạn xác nhận.</p>${c.branchMessage?`<p role="status">${c.branchMessage}</p>`:''}</section>`;
}
