import type {Island} from '../core/types';
import type {WorldMap} from '../renderer/WorldMap';
import {tideLabel,tidalSource} from '../core/TidalManager';
import {explorationLock} from '../core/ExplorationManager';
let preferred:string|undefined;
export function selectTidalScout(id:string):void{preferred=id;}
export function archipelagoPanelHTML(map:WorldMap,_s:Island):string{
 if(!map.archipelago)return '';
 const s=_s,a=s.tides?.active,adults=s.npcs.filter(n=>n.isAlive&&n.position&&n.age>=18&&n.occupation!=='child'),n=adults.find(n=>n.id===(a?.npcId??preferred))??adults.find(n=>!explorationLock(s,n))??adults[0];preferred=n?.id;
 const lock=n?explorationLock(s,n):'Cần một người trưởng thành đã định cư.',busy=!!a||!!s.exploration?.active||!!s.exploration?.torchOrder||!!s.exploration?.patrol?.enabled;
 return `<section class="era-summary archipelago-panel"><h3>Quần đảo ba đảo</h3><p>Dân định cư trên Thiên Nguyên. Có thể cử trinh sát qua bãi cạn tới bờ Răng Nanh; Thần Ngư vẫn cần tuyến đi biển riêng. Chưa có bộ tộc láng giềng.</p>${map.archipelago.islands.map(r=>`<p data-island-region="${r.id}"><strong>${r.name}</strong> · ${r.id==='thien-nguyen'?'đảo chính, nguồn sinh tồn':r.id==='than-ngu'?'Đông Nam · nhiều cá và rừng':'Tây Bắc · nhiều đá, ít thức ăn'}</p>`).join('')}<button data-region-focus="primary">Đến Thiên Nguyên</button><button data-region-focus="overview">Xem toàn quần đảo</button><div class="tidal-panel"><h4>Bãi cạn Răng Nanh</h4><button data-region-focus="causeway">Xem bãi cạn</button><p data-tide-state role="status">${tideLabel(s.tick,s.clock?.progressMs??0)}</p><p>Đường lộ 09:00–15:00 mỗi ngày. Trinh sát chờ trên bờ nếu không kịp vượt. Khứ hồi cần hai đợt nước rút, có nghỉ đêm trên đất. Công nhân thường chưa dùng tuyến này. Thú trên đường bộ vẫn gây nguy hiểm; nên mang đuốc hoặc giáo.</p><label>Trinh sát <select id="tidal-scout-choice" ${busy?'disabled':''}>${adults.map(person=>`<option value="${person.id}" ${n?.id===person.id?'selected':''}>${person.name}</option>`).join('')}</select></label><p>Hành trang: 20 thức ăn từ kho (${Math.floor(s.sharedFood)} hiện có). Ăn từ hành trang; trả phần còn lại khi về. Thu tối đa 3 đá từ mỏ gần bờ rồi đi bộ giao về làng.</p>${lock&&!a?`<p>${lock}</p>`:''}<p data-tidal-message role="status">${s.tides?.message??'Chưa có chuyến qua bãi cạn.'}</p>${a?`<p>Thức ăn mang theo còn ${a.rations.toFixed(1)} · Đá đang mang ${a.collected} · Gọi về vẫn phải chờ đường an toàn.</p><button id="recall-tidal-scout">Gọi về an toàn</button>`:`<button id="send-tidal-scout" ${lock||busy||s.sharedFood<20||!map.causeway||!tidalSource(s,map)?'disabled':''}>Khảo sát bờ Răng Nanh · mang 20 thức ăn</button>`}<p>Đã về an toàn: ${s.tides?.completed??0} chuyến.</p></div></section>`;
}
