import {resonanceOperating} from '../core/SpiritManager';
import {controlOperating,controlMultiplier} from '../core/ControlManager';
import {powerStatus} from '../core/PowerManager';
import {productive,productionAlert} from '../core/productionWorkforce';
import {buildingLogisticsHTML} from './LogisticsPanel';
import type { Island, Building } from '../core/types';
import { BUILD_LABELS, assignWorker, removeWorker, maxBuildingWorkers, buildingLevel, buildingBenefit, upgradeCost, upgradeBuilding, canAfford } from '../renderer/BuildingManager';
import { buildingTextureURL } from '../renderer/BuildingTextures';
import { buildingLock, COMMODITIES } from '../core/civilization';
import type { PlayerCommand } from '../core/SimulationSession';
import { TRADE_OFFERS, tradeLabel, tradeOfferLock } from '../core/trade';
import { shelterBeds } from '../core/settlement';

export class BuildingInspector {
  private panel: HTMLElement;
  private currentBuildingId: string | null = null;
  private lastMarkup = '';
  private message = '';
  private island?: Island;
  private submit?: (command: PlayerCommand) => string | null;
  onCommand(cb: (command: PlayerCommand) => string | null): void { this.submit = cb; }
  constructor() {
    this.panel = document.createElement('aside'); this.panel.id = 'building-inspector'; this.panel.setAttribute('aria-label','Chi tiết công trình'); this.panel.style.display = 'none'; document.body.appendChild(this.panel);
    this.panel.addEventListener('click', event => {
      const button = (event.target as HTMLElement).closest<HTMLButtonElement>('button');
      const island = this.island, b = island?.buildings.find(b => b.id === this.currentBuildingId);
      if (!button || !island || !b) return;
      if (button.id === 'bi-close') { this.hide(); return; }
      if (button.dataset.removeWorker) { if (this.submit) this.submit({type:'remove_worker',buildingId:b.id,npcId:button.dataset.removeWorker}); else removeWorker(island,b.id,button.dataset.removeWorker); }
      if(button.id==='bi-relic-safety')this.message=this.submit?.({type:'set_relic_safety',buildingId:b.id,enabled:b.relicSafety!==true})??'Đã đổi lọc mẫu.';
      if(button.id==='bi-relic-toggle')this.message=this.submit?.({type:'set_relic_extraction',buildingId:b.id,enabled:b.relicEnabled===false})??'Đã đổi thu mẫu.';
      if(button.id==='bi-spirit-toggle')this.message=this.submit?.({type:'set_spirit_extraction',buildingId:b.id,enabled:b.spiritEnabled===false})??'Đã đổi khai thác.';
      if(button.dataset.quota)this.message=this.submit?.({type:'set_production_quota',buildingId:b.id,batches:Number(button.dataset.quota)})??'Đã đặt định mức.';
      if(button.id==='bi-clear-quota')this.message=this.submit?.({type:'set_production_quota',buildingId:b.id,batches:null})??'Đã bỏ định mức.';
      if(button.id==='bi-auto-staff')this.message=this.submit?.({type:'set_building_auto',buildingId:b.id,enabled:b.autoStaff===false})??'Đã đổi chế độ tự nhận công nhân.';
      if (button.id === 'bi-btn-assign') {
        const id = this.panel.querySelector<HTMLSelectElement>('#bi-select-npc')?.value;
        this.message = id && (this.submit ? !this.submit({type:'assign_worker',buildingId:b.id,npcId:id}) : assignWorker(island,b.id,id)) ? 'Đã phân công. Cư dân sẽ đi đến công trình.' : 'Chọn cư dân trưởng thành còn khả dụng.';
      }
      if (button.id === 'bi-upgrade') this.message = (this.submit ? this.submit({type:'upgrade_building',buildingId:b.id}) : upgradeBuilding(island,b.id)) ?? 'Đã trả chi phí. Phân công thợ để nâng cấp.';
      if(button.dataset.tradeOffer)this.message=this.submit?.({type:'start_trade',buildingId:b.id,offerId:button.dataset.tradeOffer})??'Đã khởi hành; hàng sẽ về khi chuyến hoàn tất.';
      if(button.id==='bi-cancel-trade')this.message=this.submit?.({type:'cancel_trade',buildingId:b.id})??'Đã hủy chuyến và hoàn hàng.';
      this.lastMarkup = ''; this.render(b,island,true);
    });
  }
  show(b: Building, island: Island): void { this.currentBuildingId=b.id;this.island=island;this.message='';this.lastMarkup='';this.panel.style.display='flex';this.render(b,island,true); }
  hide(): void { this.currentBuildingId=null;this.panel.style.display='none'; }
  isVisible(): boolean { return this.currentBuildingId!==null; }
  getCurrentBuildingId(): string | null { return this.currentBuildingId; }
  refresh(island: Island): void { this.island=island; const b=island.buildings.find(b=>b.id===this.currentBuildingId); if(b)this.render(b,island);else this.hide(); }
  private render(b: Building, island: Island, force=false): void {
    const level=buildingLevel(b),max=maxBuildingWorkers(b),progress=b.upgrade?.progress??b.progress;
    if(!force&&this.panel.contains(document.activeElement)){const logistics=this.panel.querySelector('[data-building-logistics]');if(logistics)logistics.innerHTML=buildingLogisticsHTML(island,b);const alert=this.panel.querySelector<HTMLElement>('.bi-production-alert');if(alert)alert.textContent=(b.type==='relic_extractor'?productionAlert(island,b):b.productionAlert??productionAlert(island,b));const fill=this.panel.querySelector<HTMLElement>('.bi-progress-fill');if(fill)fill.style.width=`${progress}%`;return;}
    const workers=b.workers.map(id=>island.npcs.find(n=>n.id===id)).filter(n=>n?.isAlive);
    const available=island.npcs.filter(n=>n.isAlive&&n.age>=18&&n.occupation!=='child'&&n.position&&island.adaptationProcess?.npcId!==n.id&&!b.workers.includes(n.id));
    const cost=upgradeCost(b,island),afford=canAfford(island,cost),lock=buildingLock(island,b.type,level+1);
    const stateText=b.type==='quarantine'&&b.complete?`${powerStatus(island,b)} · ${b.workMessage??'Chờ thợ tại chỗ'}`:b.type==='clinic'&&b.complete?powerStatus(island,b):b.type==='measurement_lab'&&b.complete?`${powerStatus(island,b)} · ${island.adaptationProcess?.labId===b.id?`Hỗ trợ cư dân ${island.adaptationProcess.workTicks}nhịp`:island.analysis?.active?.labId===b.id?`Phân tích ${island.analysis.active.workTicks}/40`:island.analysis?.foundation?.labId===b.id?`Dự án nền tảng ${island.analysis.foundation.workTicks}/60`:'Chờ chọn hồ sơ hoặc dự án nền tảng'}`:b.type==='control_center'?`${powerStatus(island,b)} · ${controlOperating(island,b)?'Đang điều phối +25% trong 6 ô':'Đợi thợ làm tại chỗ; chưa tăng tốc xưởng'}`:b.type==='resonance_tower'?`${powerStatus(island,b)} · ${resonanceOperating(island,b)?'Đang chăm sóc trong4ô':'Chờ người tại chỗ, mạch ổn định40 và tinh chất'}`:['biomatter_workshop','apothecary','microchip_factory','spirit_refinery'].includes(b.type)?`${powerStatus(island,b)}${b.workMessage&&!b.workMessage.includes('Thiếu điện')?` · ${b.workMessage}`:''}`:b.workMessage??'Chờ phân công';
    const html=`<div class="bi-header"><img class="bi-texture" src="${buildingTextureURL(b.type,level,b.technology)}" alt="${BUILD_LABELS[b.type]} cấp ${level}"><div><h3>${BUILD_LABELS[b.type]}</h3><span class="bi-level">Cấp ${level} / ${['relic_extractor','biomatter_workshop','quarantine','apothecary','clinic','spirit_extractor','spirit_refinery','resonance_tower','microchip_factory','control_center','measurement_lab','tent','stockpile','fishing_dock','study_table'].includes(b.type)?1:3} · ${['relic_extractor','biomatter_workshop','quarantine'].includes(b.type)?island.civilization?.anomalyBranch==='eldritch'?'Quỷ Dị':'Hiện Đại · mẫu Quỷ Dị':['spirit_extractor','spirit_refinery','resonance_tower'].includes(b.type)?island.civilization?.anomalyBranch==='mystic'?'Linh Mạch':'Hiện Đại · mẫu Linh Mạch':['relic_extractor','biomatter_workshop','quarantine','apothecary','clinic','microchip_factory','control_center','component_factory','measurement_lab'].includes(b.type)?island.civilization?.anomalyBranch==='hightech'?'Công Nghệ Cao':'Hiện Đại':b.technology==='iron'?'Đồ Sắt':b.technology==='bronze'?'Đồ Đồng':'Đồ Đá'}</span></div><button id="bi-close" aria-label="Đóng chi tiết công trình">✕</button></div>
      ${shelterBeds(b)?`<div class="bi-section bi-occupancy"><h4>Chỗ ngủ</h4><p>${island.npcs.filter(n=>n.isAlive&&n.sleepSite===b.id).length}/${shelterBeds(b)} đang ngủ · ${island.npcs.filter(n=>n.isAlive&&n.sleepSite===b.id).map(n=>n.name.split('#')[0]).join(', ')||'Chưa có người ngủ'}</p></div>`:''}<div class="bi-section"><p class="bi-benefit">${buildingBenefit(b)}</p>${controlMultiplier(island,b)>1?'<p>Được trung tâm điều phối: tốc độ mẻ +25%</p>':''}<p class="bi-state" role="status">${stateText}</p><p>${b.type==='quarantine'?`Đã kiểm soát ${b.quarantineCareTicks??0}nhịp có tác dụng`:b.type==='clinic'?`Đã dùng ${b.clinicalDoses??0} liều · hoàn thành ${b.completedCare??0} liệu trình`:b.type==='control_center'?'Điều phối trong 6 ô · cần người vận hành tại chỗ':b.type==='resonance_tower'?`Đã chăm sóc ${b.resonanceCareTicks??0}nhịp có tác dụng`:`${b.type==='measurement_lab'?'Đã xử lý':'Đã sản xuất'} ${b.productionBatches??0} ${b.type==='measurement_lab'?'hồ sơ':'mẻ'}`}</p>${!b.complete||b.upgrade?`<div class="bi-progress"><div class="bi-progress-fill" style="width:${progress}%"></div></div><p>${Math.floor(progress)}% ${b.upgrade?'nâng cấp':'xây dựng'}</p>`:''}</div>
      ${island.logistics&&b.buffer?`<div class="bi-section" data-building-logistics>${buildingLogisticsHTML(island,b)}</div>`:''}
      <div class="bi-section"><h4>Nhân công (${workers.length}/${max})</h4>${island.workforce&&productive(b)?`<p class="bi-production-alert" role="status">${(b.type==='relic_extractor'?productionAlert(island,b):b.productionAlert??productionAlert(island,b))}</p><button id="bi-auto-staff" aria-pressed="${b.autoStaff!==false}">${b.autoStaff===false?'Bật':'Tắt'} tự nhận công nhân</button><p>Chỉ nhận người rảnh khi tự nhận việc của làng bật. Tắt sẽ trả người tự động sau khi xong mẻ/chuyến; thợ bạn chỉ định được giữ.</p>`:''}${workers.map(n=>`<div class="bi-worker-row"><span>${n!.name.split('#')[0]} · ${b.autoWorkers?.includes(n!.id)?'Tự nhận việc':'Bạn phân công'}</span><button data-remove-worker="${n!.id}">Rút</button></div>`).join('')}${max&&workers.length<max?`<div class="bi-assign-row"><select id="bi-select-npc"><option value="">Chọn người trưởng thành</option>${available.map(n=>`<option value="${n.id}">${n.name.split('#')[0]}${n.researching?' · đang nghiên cứu':''}</option>`).join('')}</select><button id="bi-btn-assign" ${available.length?'':'disabled'}>Phân công</button></div>`:max?'':'<p>Không cần thợ sau khi hoàn thành.</p>'}</div>
      ${b.type==='tradepost'?`<div class="bi-section bi-trade"><h4>Trao đổi với thương nhân</h4><p>Người vận chuyển đi hai chiều; hàng nhập không tính là sản xuất. Chỉ khởi hành khi bạn chọn.</p>${b.shipment?`<p>Chuyến đang ${b.shipment.stage==='outbound'?'đi tới thương nhân':'mang hàng về trạm'} · ${tradeLabel(b.shipment.offerId)}</p><button id="bi-cancel-trade">Hủy chuyến và hoàn hàng</button>`:Object.entries(TRADE_OFFERS).filter(([,o])=>!o.requires||['modern','anomaly'].includes(island.civilization?.era??'')).map(([id,o])=>`<button data-trade-offer="${id}" ${!b.complete||b.upgrade||!workers.length||tradeOfferLock(island,id)||(island.civilization?.inventory[o.give]??0)<o.giveAmount?'disabled':''}>${tradeLabel(id)}</button>${tradeOfferLock(island,id)?`<p class="tc-reason">${tradeOfferLock(island,id)}</p>`:''}`).join('')}</div>`:''}
      ${island.civilization?.anomalyBranch==='hightech'&&['component_factory','microchip_factory','prototype_workshop','steelworks'].includes(b.type)?`<div class="bi-section production-quota"><h4>Định mức tự dừng</h4><p>${b.productionQuota===undefined?'Chưa đặt định mức':b.productionQuota===0?'Đã đủ định mức · xưởng tự dừng':`Còn ${b.productionQuota} mẻ mới`}. Đếm hàng vừa chế tạo, không chờ giao kho. Cần trung tâm có điện/người tại chỗ trong6ô để lập chương trình.</p><button data-quota="3">Làm thêm 3 mẻ</button><button data-quota="5">Làm thêm 5 mẻ</button>${b.productionQuota!==undefined?'<button id="bi-clear-quota">Bỏ định mức</button>':''}</div>`:''}
      ${b.type==='relic_extractor'?`<div class="bi-section relic-extraction"><h4>Di tích biến chất</h4><p>Trữ lượng ${island.eldritchSource?.charge??0}/24 · nhiễm ${island.eldritchSource?.contamination??0}/100. Dừng ở60 hoặc thợ phơi nhiễm30.</p>${island.civilization?.anomalyBranch==='eldritch'?`<p>Lọc mẫu ${b.relicSafety?'bật':'tắt'} · nhiên liệu còn ${b.relicSafetyBatches??0}/5 mẻ. 1 sinh chất giao tới trạm cho 5 mẻ, giảm nhiễm 8 → 4 / phơi nhiễm 5 → 2. Thiếu nhiên liệu ngừng, tắt giữ phần còn lại.</p><button id="bi-relic-safety">${b.relicSafety?'Tắt lọc mẫu':'Bật lọc mẫu'}</button>`:''}<button id="bi-relic-toggle">${b.relicEnabled===false?'Tiếp tục thu mẫu':'Cho di tích nghỉ'}</button></div>`:''}
      ${b.type==='quarantine'?`<div class="bi-section"><p>Sinh chất còn ${b.quarantineFuelTicks??0}/10nhịp; cần người tới làm và nhiễm trong vùng để tiêu nhiên liệu.</p></div>`:''}
      ${b.type==='spirit_extractor'?`<div class="bi-section spirit-extraction"><h4>Nguồn linh mạch</h4><p>Trữ lượng ${island.spiritVein?.charge??0}/24 · ổn định ${island.spiritVein?.stability??0}/100. Thu2/mẻ giảm6ổn định; nguồn tự hồi khi nghỉ.</p><button id="bi-spirit-toggle">${b.spiritEnabled===false?'Tiếp tục thu linh thạch':'Cho mạch nghỉ'}</button></div>`:''}
      ${b.type==='resonance_tower'?`<div class="bi-section resonance-care"><h4>Chăm sóc cộng hưởng</h4><p>Nhiên liệu còn ${b.resonanceFuelTicks??0}/10nhịp làm · đã chăm sóc ${b.resonanceCareTicks??0}nhịp có tác dụng. Chỉ tiêu tinh chất khi đủ điện/thợ tại chỗ/ổn định≥40.</p></div>`:''}
      <div class="bi-section bi-upgrade-section"><h4>Nâng cấp công trình</h4>${['relic_extractor','biomatter_workshop','quarantine','apothecary','clinic','spirit_extractor','spirit_refinery','resonance_tower','microchip_factory','control_center','measurement_lab','tent','stockpile','fishing_dock','study_table'].includes(b.type)?'<p>Công trình này hiện có một cấp.</p>':level>=3?'<p>Đã đạt cấp tối đa.</p>':`<div class="bi-upgrade-preview"><img src="${buildingTextureURL(b.type,level+1,level>=2?'iron':'bronze')}" alt="Hình ảnh cấp ${level+1}"><p>Cấp ${level+1}<br><strong>${buildingBenefit(b,level+1)}</strong></p></div><p class="bi-cost">🪵 ${cost.wood} · 🪨 ${cost.stone} · 🍖 ${cost.food}${Object.entries(cost.goods??{}).map(([id,amount])=>` · ${amount} ${COMMODITIES[id as keyof typeof COMMODITIES]}`).join('')}</p>${lock?`<p class="tc-reason">🔒 ${lock}</p>`:''}<button id="bi-upgrade" ${!b.complete||b.upgrade||b.shipment||!afford||lock?'disabled':''}>Nâng cấp lên cấp ${level+1}</button>${!afford?'<p>Chưa đủ tài nguyên.</p>':''}`}</div>
      ${this.message?`<p class="bi-feedback" role="status">${this.message}</p>`:''}<p class="bi-location">Vị trí (${b.tileX}, ${b.tileY})</p>`;
    if(html===this.lastMarkup)return;this.lastMarkup=html;this.panel.innerHTML=html;
  }
}
