import {explorationPanelHTML} from './ExplorationPanel';
import {adaptationPanelHTML} from './AdaptationPanel';
import {eldritchPanelHTML} from './EldritchPanel';
import {spiritPanelHTML} from './SpiritPanel';
import {anomalyPanelHTML} from './AnomalyPanel';
import {analysisPanelHTML} from './AnalysisPanel';
import {surveyPanelHTML} from './SurveyPanel';
import {modernPreparationHTML} from './ModernPreparationPanel';
import {industryPanelHTML} from './IndustryPanel';
import type { Island } from '../core/types';
import { ERAS, bronzeRequirements, ironRequirements, COMMODITIES, goodsCapacity } from '../core/civilization';
export function eraPanelHTML(island: Island, message = ''): string {
 const c=island.civilization;if(!c)return '<p>Lộ trình mới đang có trong chế độ chơi cục bộ.</p>';
 const rows=c.era==='stone'?bronzeRequirements(island):c.era==='bronze'?ironRequirements(island):[];
 const transition=c.transition,target=c.era==='stone'?'Đồ Đồng':'Đồ Sắt';
 const pct=transition?Math.floor(100*transition.workTicks/transition.ticksNeeded):rows.length?Math.floor(100*rows.filter(r=>r.met).length/rows.length):100;
 const affordable=c.era==='stone'?island.wood>=40&&island.stone>=20:c.inventory.lumber>=30&&c.inventory.copper>=20&&c.inventory.bricks>=20;
 const ready=rows.every(r=>r.met)&&affordable&&!c.research&&!island.npcs.some(n=>n.isAlive&&!n.position);
 const next=['stone','bronze'].includes(c.era)?`<section class="era-next-step"><h3>Phát triển lên ${target}</h3><p>${c.era==='stone'?'Mở luyện đồng, gỗ xẻ và kiến trúc cấp 2.':'Mở luyện sắt, dệt vải, giao thương và kiến trúc cấp 3 theo nghiên cứu.'}</p>
 <div class="era-progress-track"><div style="width:${pct}%"></div></div>
 ${transition?`<p id="era-transition-status">Đang phát triển · ${transition.workTicks}/${transition.ticksNeeded} nhịp · ${pct}%</p><p>Không cần trả thêm phí. Tiến độ được lưu.</p>`:`<div class="era-requirements">${rows.map(r=>`<div class="era-requirement ${r.met?'met':'pending'}"><span>${r.met?'✓':'○'}</span><span>${r.label}</span><strong>${r.progress}</strong>${!r.met&&r.panel?`<button data-era-panel="${r.panel}">Đi tới</button>`:''}</div>`).join('')}</div><p>Phí: ${c.era==='stone'?'40 gỗ +20 đá · thời gian: 2 ngày':'30 gỗ xẻ +20 đồng +20 gạch · thời gian: 3 ngày'}</p>${c.research?'<p>Hoàn tất nghiên cứu đang làm trước.</p>':''}`}
 <button id="btn-develop-era" ${transition||!ready?'disabled':''}>${transition?'Đang phát triển':`Phát triển lên ${target}`}</button></section>`:c.era==='modern'?`<section class="era-next-step modern-industry-goal"><h3>Hiện Đại · sản xuất linh kiện</h3><p>Nghiên cứu Lắp ráp công nghiệp, xây nhà máy và phân công thợ. 2 thép +2 đồng →3 linh kiện, cần 2 công suất. Dùng 6 linh kiện cùng vật tư thường để nâng cấp nhà máy: 2 →3 công nhân.</p><p>Đã sản xuất ${c.produced.components} linh kiện · trong kho ${c.inventory.components}. Nhà máy cấp 2: ${island.buildings.some(b=>b.type==='component_factory'&&(b.level??1)>=2)?'Đã có':'Chưa có'}.</p><div class="modern-supply-goal"><h4>Cung ứng khi mỏ cạn</h4><p>${c.unlocks.includes('industrial_supply')?'Đã ký hợp đồng: 8 vải →10 than hoặc 12 vải →6 đồng tại trạm giao thương.':'Nghiên cứu Hợp đồng cung ứng bằng 3 linh kiện +2 bộ phận máy để mở nhập than/đồng bằng vải.'} Ruộng lanh →sợi →vải là nguồn hàng trao đổi; phân công thợ và chọn từng chuyến, cân bằng với lương thực. Hàng nhập không tính là sản xuất.</p></div><p>Khảo sát Dị Tượng là chặng tiếp theo; kỷ nguyên Dị Tượng chưa mở.</p><button data-era-panel="research">Nghiên cứu lắp ráp</button><button data-era-panel="build">Mở nhà máy</button></section>`:c.era==='anomaly'?'': '<section class="era-next-step"><h3>Đồ Sắt đã mở</h3><p>Quặng sắt +than →sắt; sợi lanh →vải. Nghiên cứu Kiến trúc Đồ Sắt để nâng cấp 3. Hiện Đại mở theo điều kiện và đầu tư; Dị Tượng chưa triển khai.</p></section>';
 return `${explorationPanelHTML(island)}<div class="era-roadmap">${ERAS.map(e=>`<div class="era-stop ${e.id===c.era?'current':''}"><strong>${e.name}</strong><small>${e.implemented?'Đã có':'Chưa triển khai'}</small></div>`).join('')}</div><section class="era-summary"><div class="era-eyebrow">KỶ NGUYÊN HIỆN TẠI</div><h3>${ERAS.find(e=>e.id===c.era)?.name}</h3><p>${ERAS.find(e=>e.id===c.era)?.description}</p>${c.migrationNotice?`<p>${c.migrationNotice}</p>`:''}</section>${next}${surveyPanelHTML(island)}${analysisPanelHTML(island)}${anomalyPanelHTML(island)}${adaptationPanelHTML(island)}${spiritPanelHTML(island)}${eldritchPanelHTML(island)}${c.era==='iron'?modernPreparationHTML(island)+industryPanelHTML(island):['modern','anomaly'].includes(c.era)?industryPanelHTML(island):''}
 ${c.era!=='stone'?'<section class="era-summary"><h3>Chuỗi nghề Đồ Đồng</h3><p>Đất sét →gạch / đồ gốm; lúa mì →bánh vào kho lương. Nghiên cứu Gạch và đồ gốm, Lúa mì và làm bánh để mở công trình.</p><p>Gốm giữ trong kho thêm 10 sức chứa hàng/chiếc, tối đa +100. Gạch và gốm cũng dùng xây lò bánh. Lúa mì thô không được tính vào dự trữ thức ăn.</p></section>':''}
 ${['iron','modern','anomaly'].includes(c.era)?`<section class="era-summary"><h3>Giao thương và vận chuyển</h3><p>Chọn gói trong chi tiết trạm, phân công người vận chuyển và bảo đảm đường tới bờ nước. Hàng nhập chỉ về kho khi chuyến hoàn tất, không tính vào thành tích sản xuất. Hủy chuyến hoàn lại hàng đã giữ.</p><p>Đã hoàn tất ${c.completedTrades??0} chuyến.</p></section>`:''}
 <button data-era-panel="build">Mở công trình</button><button data-era-panel="research">Mở nghiên cứu</button>
 <section class="goods-overview"><h3>Kho hàng</h3>${Object.entries(COMMODITIES).filter(([id])=>(['iron','modern','anomaly'].includes(c.era)&&id!=='components'||['modern','anomaly'].includes(c.era))||!['components','ironOre','coal','iron','fiber','cloth','steel','cutStone','machineParts'].includes(id)).map(([id,name])=>`<div>${name}: <strong data-goods="${id}">${c.inventory[id as keyof typeof c.inventory].toFixed(0)}/${goodsCapacity(island)}</strong><small> Đã sản xuất ${c.produced[id as keyof typeof c.produced].toFixed(0)}</small></div>`).join('')}</section>${message?`<p role="status">${message}</p>`:''}`;
}
