import {effectDuration,TIME_SCALE} from '../core/WorldClock';
import {shieldLock} from '../core/RaidManager';
import {rainfallLock,weatherSummary} from '../core/WeatherManager';
import type {Island} from '../core/types';
import {inciteCost,inciteLock,blessingCost,blessingLock,divinePhase,faithRate,FAITH_CAP} from '../core/FaithManager';
import {iconHTML} from './GameIcons';
export function faithStatus(island:Island):string{const f=island.faith!,b=f.blessing,phase=divinePhase(island);return phase==='blessed'?`Ban Phước +50% · còn ${effectDuration(b!.untilMs-f.clockMs)}`:phase==='exhausted'?`Kiệt sức −50% · còn ${effectDuration(b!.exhaustUntilMs-f.clockMs)}`:'Lao động bình thường';}
export function faithPanelHTML(island:Island):string{
 return `<section class="faith-panel"><h3>${iconHTML('faith')} Niềm tin của làng</h3><p id="faith-panel-stock"></p><div class="faith-track"><div id="faith-panel-fill"></div></div><p>Dân sống đã định cư tạo Niềm tin theo hạnh phúc và sợ hãi. Mỗi cấp đền hoàn thành thêm 0,01 Niềm tin/giây. Niềm tin bắt đầu từ 0, tối đa ${FAITH_CAP}.</p><article class="blessing-card"><h3>${iconHTML('spark')} Ban Phước</h3><p>Toàn bộ lao động trưởng thành: <strong>tốc độ làm việc +50% trong 10 phút</strong>.</p><p class="faith-backlash">Sau đó <strong>tốc độ −50% trong 20 phút</strong> và căng thẳng +10. Đây là phép tăng tốc trước mắt có hậu quả; không dùng lại khi dân đang kiệt sức.</p><p>Hồi chiêu 15 phút. Mỗi lần dùng trong 40 phút gần nhất tăng phí thêm 50 Niềm tin: 50 → 100 → 150… Thời gian theo mô phỏng; tạm dừng đóng băng, ×2 tăng đồng bộ.</p><p id="blessing-status" role="status"></p><p id="blessing-cooldown"></p><button id="cast-blessing"></button><p id="blessing-lock"></p><p id="faith-feedback" role="status"></p></article><article class="blessing-card rain-card"><h3>${iconHTML('rainfall')} Cầu Mưa</h3><p><strong>40 Niềm tin · hồi chiêu 20 phút.</strong> Dập toàn bộ cháy rừng, tăng sản lượng nông trại, ruộng lúa mì và ruộng lanh <strong>30% trong 15 phút</strong>.</p><p>Mưa tự nhiên dập cháy. Khô hạn giảm 20% sản lượng ruộng; Cầu Mưa thay mức giảm này bằng mức tăng 30%. Không tạo hàng trong kho: dân vẫn phải canh tác và vận chuyển.</p><p id="rain-weather" role="status"></p><p id="rain-cycle"></p><p id="rain-cooldown"></p><button id="cast-rainfall">Cầu Mưa · 40 Niềm tin</button><p id="rain-lock"></p></article><article class="blessing-card"><h3>${iconHTML('shield')} Khiên Thần</h3><p>70 Niềm tin · bảo vệ kho thức ăn 10 phút · hồi chiêu 30 phút. Kẻ đột kích tới kho sẽ bỏ cuộc khi khiên còn hiệu lực.</p><p id="shield-status"></p><button id="cast-shield">Khiên Thần · 70 Niềm tin</button><p id="shield-lock"></p></article><article class="blessing-card"><h3>Khích Lệ</h3><p>Giảm20 sợ hãi cho người bảo vệ hiện tại, tăng20% sát thương trong6 phút 40 giây; hồi10 phút. Mỗi lần dùng thêm trong40 phút tăng phí30 Niềm tin. Không chữa máu, không bỏ qua ăn/ngủ.</p><button id="cast-incite"></button><p id="incite-status"></p></article></section>`;
}
export function updateFaithPanel(container:HTMLElement,island:Island,message?:string):void{
 const f=island.faith;if(!f)return;
 const text=(id:string,value:string)=>{const el=container.querySelector('#'+id);if(el)el.textContent=value;};
 text('faith-panel-stock',`${f.amount.toFixed(1)} / ${FAITH_CAP} · +${(faithRate(island)/TIME_SCALE).toFixed(2)}/giây ở tốc độ 1×`);text('blessing-status',faithStatus(island));text('blessing-cooldown',f.clockMs<f.cooldownUntilMs?`Hồi chiêu: ${effectDuration(f.cooldownUntilMs-f.clockMs)}`:'Hồi chiêu đã sẵn sàng');text('blessing-lock',blessingLock(island)??'Sẵn sàng Ban Phước');
 const button=container.querySelector<HTMLButtonElement>('#cast-blessing');if(button){button.textContent=`Ban Phước · ${blessingCost(island)} Niềm tin`;button.disabled=Boolean(blessingLock(island));}
 const w=island.weather;text('rain-cycle',w?`Đợt thời tiết đổi sau ${effectDuration(w.untilMs-w.clockMs)} ở tốc độ 1×. Cháy chỉ hại cây, lan tối đa 8 cây/vụ; dân rảnh gần đó tự dập lửa trong giờ lao động.`:'');text('rain-weather',weatherSummary(island));text('rain-lock',rainfallLock(island)??'Sẵn sàng Cầu Mưa');text('rain-cooldown',w&&w.clockMs<w.rainCooldownUntilMs?`Hồi chiêu: ${effectDuration(w.rainCooldownUntilMs-w.clockMs)}`:'Hồi chiêu đã sẵn sàng');const rainButton=container.querySelector<HTMLButtonElement>('#cast-rainfall');if(rainButton)rainButton.disabled=!!rainfallLock(island);
 const r=island.raids;text('shield-status',r&&r.clockMs<r.shieldUntilMs?`Kho được bảo vệ · còn ${effectDuration(r.shieldUntilMs-r.clockMs)}`:r&&r.clockMs<r.shieldCooldownUntilMs?`Hồi chiêu · còn ${effectDuration(r.shieldCooldownUntilMs-r.clockMs)}`:'Khiên đã sẵn sàng');text('shield-lock',shieldLock(island)??'Sẵn sàng');const shield=container.querySelector<HTMLButtonElement>('#cast-shield');if(shield)shield.disabled=!!shieldLock(island);
 const inc=container.querySelector<HTMLButtonElement>('#cast-incite');if(inc){inc.textContent=`Khích Lệ · ${inciteCost(island)} Niềm tin`;inc.disabled=!!inciteLock(island);}text('incite-status',`${f.incite&&f.clockMs<f.incite.untilMs?`Có hiệu lực ${effectDuration(f.incite.untilMs-f.clockMs)} · `:''}${inciteLock(island)??'Sẵn sàng'}`);
 const fill=container.querySelector<HTMLElement>('#faith-panel-fill');if(fill)fill.style.width=`${100*f.amount/FAITH_CAP}%`;if(message)text('faith-feedback',message);
}
