import type {Island,LogisticsGood} from '../core/types';
import {RESERVE_GOODS,reserveStock,reserveTarget,defaultReserve,needsReserve} from '../core/reserves';
import {GOOD_LABELS} from '../core/logistics';
import {productionAlert} from '../core/productionWorkforce';
import {BUILD_LABELS,foodCapacity,materialCapacity} from '../renderer/BuildingManager';
import {goodsCapacity} from '../core/civilization';
import {iconHTML} from './GameIcons';
export function managementWarnings(island:Island):{id:string;label:string;reason:string}[]{return island.buildings.flatMap(b=>{const reason=b.productionAlert??productionAlert(island,b);return !reason||reason.startsWith('Sẵn sàng')||reason.startsWith('Thợ đang')||reason.startsWith('Đã đủ')?[]:[{id:b.id,label:`${BUILD_LABELS[b.type]} (${b.tileX}, ${b.tileY})`,reason}];});}
const warningHTML=(island:Island)=>managementWarnings(island).map(w=>`<article class="management-warning"><strong>${w.label}</strong><p>${w.reason}</p><button data-manage-building="${w.id}">Tới công trình</button></article>`).join('')||'<p>Chưa có công trình cần xử lý.</p>';
export function managementPanelHTML(island:Island):string{return `<section class="management-panel"><h3>${iconHTML('chart')} Điều hành làng</h3><p>Điều phối chỉ dùng người ở chế độ Tự động khi tự nhận việc của làng bật. Giữ nguyên công nhân bạn phân tay và các mẻ/chuyến đang làm.</p><p>Mục tiêu tính kho làng + thành phẩm tại công trình + hàng đang mang; thức ăn gồm khẩu phần riêng. Sau khi áp dụng, đạt mục tiêu thì nghỉ tích hàng, xuống 80% mới nhận lại việc. Phần đầu vào đã dành cho xưởng không tính là hàng dự trữ.</p><p>Thức ăn giữ tối thiểu 1,5 ngày ăn, gỗ tiếp lửa giữ 16; nguyên liệu xưởng đang cần giữ ít nhất 3 mẻ. Kho có giới hạn: mục tiêu không tự mở rộng kho hay tạo hàng.</p><p id="management-mode"></p><div class="management-actions"><button id="manage-apply">Áp dụng mục tiêu</button><button id="manage-reset">Dùng mức mặc định</button><button id="manage-population">Phân công dân</button><button id="manage-roadmap">Lộ trình kỷ nguyên</button></div><p id="management-feedback" role="status"></p><div class="reserve-grid">${RESERVE_GOODS.map(g=>`<article class="reserve-card"><label for="reserve-${g}">${GOOD_LABELS[g]}</label><input id="reserve-${g}" data-reserve-good="${g}" type="number" min="0" max="10000" step="1" value="${island.reserves?.targets[g]??defaultReserve(island,g)}"><p data-reserve-status="${g}"></p></article>`).join('')}</div><h3>Công trình cần xử lý <span id="management-warning-count"></span></h3><div id="management-warnings">${warningHTML(island)}</div></section>`;}
export function updateManagementPanel(container:HTMLElement,island:Island):void{
 const mode=container.querySelector('#management-mode');if(mode)mode.textContent=island.workforce?.enabled?'Tự nhận việc đang bật · mục tiêu áp dụng cho người ở chế độ Tự động.':'Tự nhận việc đang tắt · mục tiêu được lưu, bật tại Phân công dân để tự điều phối.';
 for(const good of RESERVE_GOODS){const el=container.querySelector(`[data-reserve-status="${good}"]`);if(!el)continue;const target=reserveTarget(island,good),chosen=island.reserves?.targets[good]??defaultReserve(island,good),cap=good==='food'?foodCapacity(island):good==='wood'||good==='stone'?materialCapacity(island):goodsCapacity(island);el.textContent=`Đang có ${reserveStock(island,good).toFixed(1)} · mục tiêu hiệu lực ${target}${target>chosen?' (mức tối thiểu)':''} · ${needsReserve(island,good)?'cần tích thêm':island.reserves?.targets[good]!==undefined?'tạm dừng, chờ mức 80%':'dự trữ đủ theo mức mặc định'}${target>cap?` · vượt sức chứa kho làng ${cap}`:''}`;}
 const count=container.querySelector('#management-warning-count');if(count)count.textContent=`(${managementWarnings(island).length})`;const warnings=container.querySelector('#management-warnings');if(warnings){const html=warningHTML(island);if(warnings.innerHTML!==html)warnings.innerHTML=html;}
}
