import {effectDuration} from '../core/WorldClock';
import {clinicPanelHTML,updateClinicPanel} from './ClinicPanel';
import {characterPortrait} from '../renderer/CharacterTextures';
import {DEFENSE,treatmentLock} from '../core/CareManager';
import {inciteCost,inciteLock,incited} from '../core/FaithManager';
import type {Island} from '../core/types';
import {raidSummary,shieldLock} from '../core/RaidManager';
import {iconHTML} from './GameIcons';
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function militaryPanelHTML(s:Island):string{return `<section class="faith-panel"><h3>${iconHTML('shield')} Phòng vệ làng</h3><p id="raid-status" role="status"></p><p>Đợt nhỏ gồm 2 kẻ đột kích, báo trước 6 phút 40 giây. Chúng đi tới kho để cướp tối đa 40 thức ăn và 20% dự trữ lúc báo động, giữ lại một ngày ăn. Không phá công trình; dân thường tránh nguy hiểm. Người bảo vệ ưu tiên ăn và nghỉ khi cần, trở lại việc cũ sau đột kích.</p><article class="blessing-card"><h3>Khiên Thần</h3><p>70 Niềm tin · bảo vệ toàn bộ kho thức ăn trong 10 phút · hồi chiêu 30 phút. Không bảo vệ sức khỏe người giao chiến.</p><p id="shield-status"></p><button id="cast-shield">Dùng Khiên Thần · 70 Niềm tin</button><p id="shield-lock"></p><p id="raid-feedback" role="status"></p></article><article class="blessing-card"><h3>Khích Lệ</h3><p>Người bảo vệ hiện tại giảm20 sợ hãi và tăng20% sát thương trong6 phút 40 giây, hồi10 phút. Giá tăng30 cho mỗi lần dùng thêm trong40 phút; không chữa máu hoặc bỏ qua ăn/ngủ.</p><button id="cast-incite"></button><p id="incite-status"></p></article>${clinicPanelHTML(s)}<section class="defense-controls"><h3>Chế tạo phòng vệ</h3><p>Giáo đá:6gỗ+4đá, tăng sát thương cơ bản6→8. Áo dệt:4vải/cần nghiên cứu Dệt vải, giảm phản công3→2. Một người rảnh chế tạo tại kho trong5 bước làm việc. Lấy/trả cũng phải tới kho, không cấp đồ từ xa.</p><button data-craft-defense="spear">Chế giáo đá</button><button data-craft-defense="padded_vest">Chế áo dệt</button><p id="defense-craft-state"></p><button id="cancel-defense">Hủy đơn và hoàn vật tư</button></section><h3>Chữa bằng thảo dược và trang bị</h3><p>Nghiên cứu Y học thảo dược; người dưới90 sức khỏe về kho dùng2thảo dược,4 bước đắp thuốc/hồi5máu mỗi bước. Ưu tiên ăn/ngủ, giữ nghề và hàng mang; hủy sau khi dùng thuốc không hoàn thảo dược.</p>${s.npcs.filter(n=>n.isAlive&&n.position&&n.age>=18&&n.occupation!=='child').map(n=>`<article class="care-person" data-care-person="${escape(n.id)}"><div class="care-person-heading">${characterPortrait(n,s.civilization?.era??'stone')}<strong>${escape(n.name.split('#')[0])}</strong></div><p data-care-state="${escape(n.id)}"></p><button data-treat="${escape(n.id)}">Chữa thảo dược</button><button data-gear-npc="${escape(n.id)}" data-defense-kind="spear"></button><button data-gear-npc="${escape(n.id)}" data-defense-kind="padded_vest"></button></article>`).join('')}<h3>Người bảo vệ</h3><p>Chỉ định cư dân trưởng thành. Ngoài đột kích họ tiếp tục nghề và công việc đang làm.</p>${s.npcs.filter(n=>n.isAlive&&n.position&&n.age>=18&&n.occupation!=='child').map(n=>`<label class="guard-row"><input type="checkbox" data-guard="${escape(n.id)}" ${n.guardDuty?'checked':''}> ${escape(n.name)} <span data-guard-state="${escape(n.id)}"></span></label>`).join('')}</section>`;}
export function updateMilitaryPanel(root:HTMLElement,s:Island,message?:string):void{const r=s.raids;if(!r)return;updateClinicPanel(root,s);const text=(id:string,v:string)=>{const e=root.querySelector('#'+id);if(e)e.textContent=v;};const inc=root.querySelector<HTMLButtonElement>('#cast-incite');if(inc){inc.textContent=`Khích Lệ · ${inciteCost(s)} Niềm tin`;inc.disabled=!!inciteLock(s);}text('incite-status',inciteLock(s)??'Sẵn sàng');text('defense-craft-state',s.defense?.order?`Đang chế tạo ${DEFENSE[s.defense.order.kind].name} · ${s.defense.order.workTicks}/5`:`Kho: ${s.defense?.stock.spear??0} giáo · ${s.defense?.stock.padded_vest??0} áo`);const cancel=root.querySelector<HTMLButtonElement>('#cancel-defense');if(cancel)cancel.disabled=!s.defense?.order;for(const n of s.npcs){const state=root.querySelector(`[data-care-state="${CSS.escape(n.id)}"]`);if(state)state.textContent=`Sức khỏe ${Math.round(n.health??100)}% · ${n.weapon?'Giáo đá':'Chưa giáo'} · ${n.armor?'Áo phòng vệ':'Chưa áo'}${n.treatment?` · Thuốc ${n.treatment.workTicks}/4`:''}${incited(s,n)?' · Được Khích Lệ':''}`;const treat=root.querySelector<HTMLButtonElement>(`[data-treat="${CSS.escape(n.id)}"]`);if(treat){treat.textContent=n.treatment?'Hủy liệu trình':'Chữa thảo dược · 2 thảo dược';treat.disabled=!n.treatment&&!!treatmentLock(s,n);}for(const k of ['spear','padded_vest'] as const){const button=root.querySelector<HTMLButtonElement>(`[data-gear-npc="${CSS.escape(n.id)}"][data-defense-kind="${k}"]`);if(button){const own=k==='spear'?n.weapon:n.armor;button.textContent=own?`Trả ${DEFENSE[k].name}`:`Lấy ${DEFENSE[k].name}`;button.disabled=!!n.defenseChoice||!own&&!(s.defense?.stock[k]);}}}
text('raid-status',raidSummary(s));text('shield-status',r.clockMs<r.shieldUntilMs?`Kho đang được bảo vệ · còn ${effectDuration(r.shieldUntilMs-r.clockMs)}`:r.clockMs<r.shieldCooldownUntilMs?`Hồi chiêu · còn ${effectDuration(r.shieldCooldownUntilMs-r.clockMs)}`:'Khiên đã sẵn sàng');text('shield-lock',shieldLock(s)??'Sẵn sàng');const button=root.querySelector<HTMLButtonElement>('#cast-shield');if(button)button.disabled=!!shieldLock(s);for(const n of s.npcs){const label=root.querySelector(`[data-guard-state="${CSS.escape(n.id)}"]`);if(label)label.textContent=n.raidResponse==='guarding'?'Đang chống đỡ':n.raidResponse==='fleeing'?'Đang tránh nguy hiểm':`Sức khỏe ${Math.round(n.health??100)}%`; }if(message)text('raid-feedback',message);}
