import {ERAS} from '../core/civilization';
import {iconHTML} from './GameIcons';
import type {Island} from '../core/types';
import {modernRequirements,MODERN_FEE} from '../core/ModernPreparation';
export function modernPreparationHTML(s:Island):string{
 const rows=modernRequirements(s),met=rows.filter(r=>r.met).length,c=s.civilization!;
 if(c.transition?.target==='modern')return `<section class="era-next-step modern-preparation"><h3>Đang phát triển Hiện Đại</h3><div class="era-progress-track"><div style="width:${100*c.transition.workTicks/c.transition.ticksNeeded}%"></div></div><p id="era-transition-status">${c.transition.workTicks}/${c.transition.ticksNeeded} nhịp · 5 ngày</p><p>Phí đầu tư đã trả. Pause giữ tiến độ, lưu/tải để tiếp tục; không cần trả thêm. Dân vẫn ăn và nghỉ trong giai đoạn chuyển cấp.</p><button id="btn-develop-era" disabled>Đang phát triển</button></section>`;
 return `<section class="era-next-step modern-preparation"><h3>Chuẩn bị lên Hiện Đại</h3><p>Hoàn thành các mục dưới đây bằng sản xuất, vận chuyển và xây dựng thật. Chỗ ngủ tính nhà/lều đã hoàn thành; 15 chỗ tiếp nhận khởi đầu không phải giường ngủ. Lúa mì thô và hàng chưa giao về kho không tính vào dự trữ. Khẩu phần vật nuôi đã thuần hóa cũng được tính.</p><div class="era-progress-track"><div style="width:${100*met/rows.length}%"></div></div><div class="era-requirements">${rows.map((r,i)=>`<div class="era-requirement ${r.met?'met':'pending'}" data-modern-requirement="${i}"><span>${r.met?'✓':'○'}</span><span>${r.label}</span><strong>${r.progress}</strong>${!r.met&&r.panel&&r.panel!=='quests'?`<button data-era-panel="${r.panel}">Đi tới</button>`:''}</div>`).join('')}</div><p>Phí tiến cấp dự kiến: ${MODERN_FEE.steel} thép +${MODERN_FEE.cutStone} đá xây +${MODERN_FEE.cloth} vải · 5 ngày.</p><h4>Vật tư đầu tư</h4><div class="era-requirements">${(Object.entries(MODERN_FEE) as [keyof typeof MODERN_FEE,number][]).map(([good,amount])=>`<div class="era-requirement ${c.inventory[good]>=amount?'met':'pending'}" data-modern-fee="${good}"><span>${iconHTML(good)}</span><span>${{steel:'Thép',cutStone:'Đá xây',cloth:'Vải'}[good]}</span><strong>${Math.floor(c.inventory[good])}/${amount}</strong>${c.inventory[good]<amount?'<button data-era-panel="build">Sản xuất</button>':''}</div>`).join('')}</div><p>Chỉ trừ phí khi bắt đầu tiến cấp; thức ăn vẫn dành cho dân.</p><p>Xưởng máy cũng dùng thép: cần tích đầu vào cho xưởng ngoài 30 thép đầu tư. Khi chờ vật tư, có thể tắt xưởng và máy phát để giữ thép/than, rồi bật lại và đạt lại 3 ngày điện. Sản xuất xong vật tư thì trả bớt thợ về làm lương thực để giữ dự trữ.</p>${ERAS.find(e=>e.id==='modern')?.implemented?`<button id="btn-develop-era" ${met!==rows.length||c.research||s.npcs.some(n=>n.isAlive&&!n.position)||Object.entries(MODERN_FEE).some(([g,a])=>c.inventory[g as keyof typeof MODERN_FEE]<a)?'disabled':''}>Phát triển lên Hiện Đại</button>`:'<button id="modern-not-ready" disabled>Hiện Đại đang hoàn thiện</button><p>Chặng chuẩn bị đã có; chuyển cấp và chuỗi Hiện Đại sẽ mở sau khi kiểm tra đầy đủ.</p>'}</section>`;
}
