import type {Island} from '../core/types';
import {SURVEY_LABELS} from '../core/SurveyManager';
export function surveyPanelHTML(s:Island):string{
 if(s.civilization?.era!=='modern')return '';
 if(!s.civilization.unlocks.includes('field_surveys'))return '<section class="era-summary survey-panel"><h3>Khảo sát điểm lạ</h3><p>Nghiên cứu Khảo sát thực địa: 6 linh kiện +1 bộ phận máy cùng vật tư thường. Đội đi tới điểm lạ và mang hồ sơ về; chưa phân tích hoặc nhận biến thể.</p><button data-era-panel="research">Mở nghiên cứu khảo sát</button></section>';
 const state=s.surveys;if(!state)return '<section class="era-summary survey-panel"><h3>Khảo sát điểm lạ</h3><p>Cần bàn nghiên cứu và ba điểm đất có đường tới. Chạy mô phỏng để xác định vị trí.</p></section>';
 const free=s.npcs.filter(n=>n.isAlive&&n.age>=18&&n.occupation!=='child'&&n.position&&!n.researching&&!n.guardDuty&&!n.cargo&&!n.freight&&!n.haulTask&&!n.actionTarget&&!n.laborTask&&!(n.buildingWork?.ticks)&&s.equipment?.order?.workerId!==n.id&&!s.buildings.some(b=>b.workers.includes(n.id)));
 return `<section class="era-summary survey-panel"><h3>Khảo sát thực địa · ${state.sites.filter(p=>p.surveyed).length}/3 hồ sơ</h3><p>Mỗi chuyến 2 linh kiện +2 vải. Cư dân đi, quan sát 10 nhịp tại điểm rồi quay về bàn mới ghi nhận hồ sơ. Cho cư dân nghỉ và giao xong hàng trước khi cử đi. Phân tích hồ sơ tại cơ sở đo đạc trong bảng bên dưới; Dị Tượng chưa mở.</p><p class="survey-status" role="status">${state.message}</p>${state.active?`<p>Đội: ${s.npcs.find(n=>n.id===state.active!.npcId)?.name.split('#')[0]} · ${state.active.stage==='outbound'?'Đang đi':state.active.stage==='observing'?'Đang quan sát':'Đang trở về'} · ${state.active.workTicks}/10 nhịp quan sát</p><button id="cancel-survey">Hủy chuyến và hoàn vật tư</button>`:`<label>Chọn người trưởng thành rảnh <select id="survey-worker"><option value="">Chọn cư dân</option>${free.map(n=>`<option value="${n.id}">${n.name.split('#')[0]}</option>`).join('')}</select></label>`}${state.sites.map(p=>`<article class="survey-site" data-survey-site="${p.id}"><h4>${SURVEY_LABELS[p.kind]} (${p.x}, ${p.y})</h4><p>${p.surveyed?(p.analyzed?'Hồ sơ đã phân tích':'Hồ sơ đã mang về · chờ phân tích'):'Chưa khảo sát'}</p><button data-start-survey="${p.id}" ${p.surveyed||state.active||!free.length||s.civilization!.inventory.components<2||s.civilization!.inventory.cloth<2?'disabled':''}>Cử người khảo sát</button></article>`).join('')}</section>`;
}
