import {resonanceOperating} from './SpiritManager';
import type {Island,NPC,Building,Commodity} from './types';
import type {WorldMap} from '../renderer/WorldMap';
import {hasPower} from './PowerManager';
import {goodsCapacity} from './civilization';
import {RECIPES,outputRoom} from './logistics';
import {findPath} from './pathfinding';
import {movementSteps} from './dailyLife';
export type AdaptationMode='apply'|'service'|'remove';
export const adaptationTech=(s:Island)=>s.civilization?.anomalyBranch==='eldritch'?'biological_adaptation':s.civilization?.anomalyBranch==='mystic'?'spiritual_attunement':'assistive_augmentation';
export const adaptationFee=(mode:AdaptationMode,kind='hightech'):Partial<Record<Commodity,number>>=>kind==='eldritch'?(mode==='apply'?{biomatter:2,cloth:1}:mode==='service'?{biomatter:1}:{}):kind==='mystic'?(mode==='apply'?{spiritEssence:2,cloth:1}:mode==='service'?{spiritEssence:1}:{}):(mode==='apply'?{microchips:1,components:2}:mode==='service'?{components:1}:{});
export const adaptationDuration=(mode:AdaptationMode)=>mode==='apply'?10:mode==='service'?4:5;
export function willing(n:NPC):boolean{return n.isAlive&&!!n.position&&n.age>=18&&n.occupation!=='child'&&(n.health??100)>=80&&n.needs.hunger<80&&n.needs.rest<80&&n.needs.safety<60&&n.personality.loyalty>=-20&&n.personality.courage>=-30;}
export function adaptationLock(s:Island,n:NPC,mode:AdaptationMode):string|null{if(!n.isAlive||!n.position||n.age<18||n.occupation==='child')return 'Chỉ người trưởng thành đã định cư.';if(s.adaptationProcess)return 'Đang hỗ trợ một cư dân; hoàn thành hoặc hủy trước.';if(mode==='apply'&&(!willing(n)||n.adaptation))return n.adaptation?'Đã có một dạng thích nghi.':'Cư dân chưa đồng ý: cần khỏe/đủ ăn-ngủ/ít sợ và tin tưởng cộng đồng.';if(mode==='apply'&&s.civilization?.anomalyBranch==='eldritch'&&(n.exposure??0)>=15)return 'Cần phơi nhiễm dưới 15; rời nguồn hoặc tới khu cách ly trước khi đăng ký.';if(mode!=='apply'&&!n.adaptation)return 'Cư dân chưa có thiết bị hỗ trợ.';if(mode==='service'&&(n.adaptation?.charge??0)>(n.adaptation?.kind!=='hightech'?99:80))return n.adaptation?.kind==='eldritch'?'Thích nghi còn đủ 100 mẻ hỗ trợ; chưa cần chăm sóc.':n.adaptation?.kind==='mystic'?'Cộng hưởng còn đủ 100 lượt; chưa cần chăm sóc.':'Còn hơn 80 lượt hỗ trợ; chưa cần bảo dưỡng.';if(n.guardDuty||n.researching||n.clinicalCare||n.treatment||s.defense?.order?.npcId===n.id||s.equipment?.order?.workerId===n.id)return 'Rút khỏi bảo vệ/nghiên cứu hoặc hoàn thành chăm sóc/chế tạo trước.';return null;}
export function startAdaptation(s:Island,npcId:string,labId:string,mode:AdaptationMode):string|null{const c=s.civilization,n=s.npcs.find(n=>n.id===npcId),lab=s.buildings.find(b=>b.id===labId&&b.type==='measurement_lab'&&b.complete&&!b.upgrade);if(!['apply','service','remove'].includes(mode)||!c||!['hightech','mystic','eldritch'].includes(c.anomalyBranch??'')||!c.unlocks.includes(adaptationTech(s))||!n||!lab)return 'Cần nhánh đã chốt, nghiên cứu thích nghi tương ứng và viện hoàn thành.';const lock=adaptationLock(s,n,mode);if(lock)return lock;if(s.analysis?.active||s.analysis?.foundation||c.branchDevelopment||lab.workers.includes(n.id))return 'Viện đang bận hoặc cư dân này trực viện; chọn người khác.';const fee=adaptationFee(mode,c.anomalyBranch);for(const [id,amount] of Object.entries(fee))if(c.inventory[id as Commodity]<amount!)return 'Thiếu vật tư thích nghi đã giao về kho.';for(const [id,amount] of Object.entries(fee))c.inventory[id as Commodity]-=amount!;s.adaptationProcess={npcId,labId,mode,workTicks:0};s.adaptationMessage=mode==='remove'?'Đã đăng ký gỡ thiết bị miễn phí;5nhịp tại viện.':'Đã giữ vật tư một lần; cư dân tới viện, cần thợ/2 công suất. Hủy trước hoàn tất hoàn vật tư.';n.laborMessage='Đã đăng ký hỗ trợ tại viện';return null;}
export function cancelAdaptation(s:Island):string|null{const a=s.adaptationProcess,c=s.civilization;if(!a||!c)return 'Không có dự án hỗ trợ cư dân.';const fee=adaptationFee(a.mode,c.anomalyBranch);for(const [id,amount] of Object.entries(fee))if(c.inventory[id as Commodity]+amount!>goodsCapacity(s))return 'Kho đầy; giữ dự án tới khi có chỗ hoàn vật tư.';for(const [id,amount] of Object.entries(fee))c.inventory[id as Commodity]+=amount!;const n=s.npcs.find(n=>n.id===a.npcId);if(n)n.adaptationReady=false;s.adaptationProcess=undefined;s.adaptationMessage='Đã hủy và hoàn vật tư một lần, giữ dạng thích nghi trước đó.';return null;}
export function prepareAdaptation(s:Island,map:WorldMap):void{for(const n of s.npcs)n.adaptationReady=false;const a=s.adaptationProcess;if(!a)return;const n=s.npcs.find(n=>n.id===a.npcId),lab=s.buildings.find(b=>b.id===a.labId&&b.type==='measurement_lab'&&b.complete);if(!n?.isAlive||!n.position||!lab){s.adaptationMessage='Cư dân/cơ sở không còn sẵn sàng; có thể hủy để hoàn vật tư.';return;}if(n.survivalBlocked)return;n.survivalBlocked=true;n.status='idle';const path=findPath(map,n.position.tileX,n.position.tileY,lab.tileX,lab.tileY);if(path===null){n.laborMessage=s.adaptationMessage='Không có đường tới viện · giữ dự án';return;}if(path.length>1){const p=path[Math.min(movementSteps(n,s),path.length-1)-1];n.position={tileX:p.x,tileY:p.y};n.path=undefined;n.laborMessage='Đang tới viện hỗ trợ';return;}n.adaptationReady=true;n.laborMessage='Chờ thợ hỗ trợ/điện tại viện';}
export function tickAdaptation(s:Island):void{const a=s.adaptationProcess;if(!a)return;const n=s.npcs.find(n=>n.id===a.npcId),lab=s.buildings.find(b=>b.id===a.labId&&b.type==='measurement_lab'&&b.complete&&!b.upgrade);if(!n?.isAlive||!n.position||!lab)return;if(a.mode==='apply'&&!willing(n)){s.adaptationMessage='Cư dân chưa sẵn sàng/đồng ý khi mệt hoặc sợ · giữ tiến độ, có thể hủy';return;}if(lab.powerEnabled===false||!hasPower(s,lab)){s.adaptationMessage='Viện thiếu điện · giữ tiến độ hỗ trợ';return;}const mentor=lab.workers.some(id=>s.npcs.some(w=>w.id===id&&w.isAlive&&w.position&&w.age>=18&&!w.survivalBlocked&&!w.cargo&&!w.freight&&!w.actionTarget&&w.status==='working'&&w.laborMessage==='Làm tại cơ sở đo đạc'&&Math.max(Math.abs(w.position.tileX-lab.tileX),Math.abs(w.position.tileY-lab.tileY))<=1));if(!mentor||!n.adaptationReady||Math.max(Math.abs(n.position.tileX-lab.tileX),Math.abs(n.position.tileY-lab.tileY))>1){s.adaptationMessage='Chờ cư dân và thợ làm tại viện; ăn/ngủ giữ tiến độ';return;}a.workTicks++;s.adaptationMessage=`${a.mode==='apply'?(s.civilization?.anomalyBranch==='hightech'?'Lắp thiết bị':s.civilization?.anomalyBranch==='mystic'?'Cộng hưởng':'Thích nghi sinh chất'):a.mode==='remove'?'Gỡ dạng thích nghi':'Chăm sóc'} ${a.workTicks}/${adaptationDuration(a.mode)} nhịp tại viện`;if(a.workTicks>=adaptationDuration(a.mode)){n.adaptation=a.mode==='remove'?undefined:{kind:s.civilization!.anomalyBranch as 'hightech'|'mystic'|'eldritch',charge:100};n.adaptationReady=false;s.adaptationProcess=undefined;s.adaptationMessage=a.mode==='remove'?'Đã gỡ dạng thích nghi, cư dân giữ nghề và thuộc tính cũ.':s.civilization?.anomalyBranch==='eldritch'?'Đã thích nghi sinh chất: 100 mẻ giảm phơi nhiễm cá nhân 5→3 hoặc lọc 2→1. Nhiễm nguồn/ngưỡng dừng không đổi; cần chăm sóc sinh chất, không miễn nhiễm.':s.civilization?.anomalyBranch==='mystic'?'Đã cộng hưởng: 100 lượt +20% tiến độ tinh luyện/dệt/xay/nướng trong 4 ô tháp hoạt động/nguồn ổn định. Hết hoặc ngoài vùng dừng lợi ích; cần tinh chất chăm sóc.':'Hoàn tất hỗ trợ: 100 lượt công việc công nghiệp +15% tốc độ, sau đó cần bảo dưỡng. Giữ nghề/quan hệ/tính cách.';}}
// Only consume maintenance during real industrial progress with onsite inputs/output room; no free products or general combat/food bonus.
export function augmentationMultiplier(s:Island,n:NPC,b:Building):number{
 const r=RECIPES[b.type],a=n.adaptation;
 if(!a||a.charge<=0||s.civilization?.anomalyBranch!==a.kind||!r||!hasPower(s,b)||b.powerEnabled===false||b.productionQuota===0||outputRoom(s,b)<r.yield||Object.entries(r.inputs).some(([k,v])=>(b.buffer?.input[k as Commodity]??0)<v!))return 1;
 if(a.kind==='hightech')return ['component_factory','microchip_factory','prototype_workshop','steelworks','iron_smelter','sawmill','stonecutter'].includes(b.type)?1.15:1;
 if(a.kind!=='mystic')return 1;
 return ['spirit_refinery','weaver','mill','bakery'].includes(b.type)&&s.buildings.some(t=>resonanceOperating(s,t)&&Math.max(Math.abs(t.tileX-b.tileX),Math.abs(t.tileY-b.tileY))<=4)?1.2:1;
}
export function useAugmentation(s:Island,n:NPC,b:Building):number{const m=augmentationMultiplier(s,n,b);if(m>1)n.adaptation!.charge--;return m;}
