import type {Island,Building,NPC} from './types';
import {hasPower} from './PowerManager';
import {addOutput,outputRoom} from './logistics';
export function relicSite(s:Island){return s.surveys?.sites.find(p=>p.kind==='eldritch'&&p.foundationComplete&&p.decision==='research');}
export function initializeEldritch(s:Island):void{const site=relicSite(s);if(site&&s.civilization?.unlocks.includes('relic_handling')&&!s.eldritchSource)s.eldritchSource={version:1,siteId:site.id,charge:24,contamination:0,clockTicks:0};}
export function setRelicExtraction(s:Island,id:string,enabled:boolean):string|null{const b=s.buildings.find(b=>b.id===id&&b.type==='relic_extractor'&&b.complete);if(!b||typeof enabled!=='boolean')return 'Trạm thu di tích không hợp lệ.';b.relicEnabled=enabled;b.productionAlert=enabled?'Chờ thợ tới nguồn và kiểm tra ngưỡng nhiễm.':'Di tích nghỉ · giữ mẫu';b.workMessage=enabled?'Đã cho phép thu, vẫn cần nguồn an toàn/người tại chỗ.':'Đã cho di tích nghỉ.';return null;}
export function setRelicSafety(s:Island,id:string,enabled:boolean):string|null{const b=s.buildings.find(b=>b.id===id&&b.type==='relic_extractor'&&b.complete);if(!b||typeof enabled!=='boolean'||s.civilization?.anomalyBranch!=='eldritch'||!s.civilization.unlocks.includes('bio_containment'))return 'Cần chốt Quỷ Dị và trạm đã xây/kiểm soát sinh chất.';b.relicSafety=enabled;b.workMessage=enabled?'Lọc mẫu: chờ1sinh chất tại trạm cho5mẻ, nhiễm4/phơi nhiễm2 mỗi mẻ.':'Đã tắt lọc mẫu; giữ nhiên liệu còn lại, mẻ thường tăng8nhiễm/5phơi nhiễm.';return null;}
export function harvestRelic(s:Island,b:Building,n:NPC):void{const v=s.eldritchSource,site=relicSite(s);if(!v||!site||Math.max(Math.abs(b.tileX-site.x),Math.abs(b.tileY-site.y))>2){b.workMessage='Cần di tích nền tảng trong2ô';return;}if(b.relicEnabled===false){b.workMessage='Đang cho di tích nghỉ';return;}if(v.charge<1||v.contamination>=60||(n.exposure??0)>=30){b.workMessage='Dừng an toàn: nguồn cạn/nhiễm60 hoặc thợ phơi nhiễm30. Cho nghỉ, rút người khỏi3ô hoặc vận hành khu cách ly.';return;}if(outputRoom(s,b)<3){b.workMessage='Thành phẩm đầy · cần vận chuyển';return;}const safe=b.relicSafety===true&&s.civilization?.anomalyBranch==='eldritch';if(safe){if((b.relicSafetyBatches??0)<=0){if((b.buffer?.input.biomatter??0)<1){b.workMessage='Chờ giao1sinh chất tới trạm để lọc5mẻ · giữ nguồn';return;}b.buffer!.input.biomatter!--;b.relicSafetyBatches=5;}b.relicSafetyBatches!--;}v.charge--;v.contamination+=safe?4:8;const adapted=s.civilization?.anomalyBranch==='eldritch'&&n.adaptation?.kind==='eldritch'&&n.adaptation.charge>0;const exposureGain=adapted?(safe?1:3):(safe?2:5);n.exposure=Math.min(30,(n.exposure??0)+exposureGain);if(adapted)n.adaptation!.charge--;addOutput(s,b,'relicBone',2);addOutput(s,b,'bloodstone',1);b.productionBatches=(b.productionBatches??0)+1;b.workMessage=adapted?`Thích nghi thu2xương1huyết thạch · +${safe?4:8}nhiễm/+${exposureGain}phơi nhiễm · còn${n.adaptation!.charge}mẻ hỗ trợ`:safe?'Lọc mẫu thu2xương1huyết thạch · +4nhiễm/+2phơi nhiễm, tiêu sinh chất theo mẻ':'Thu2xương cốt1huyết thạch · +8nhiễm nguồn/+5phơi nhiễm người thu';}
export function containmentOperating(s:Island,b:Building):boolean{return b.type==='quarantine'&&b.complete&&!b.upgrade&&b.powerEnabled!==false&&hasPower(s,b)&&((b.quarantineFuelTicks??0)>0||(b.buffer?.input.biomatter??0)>=1)&&b.workers.some(id=>s.npcs.some(n=>n.id===id&&n.isAlive&&n.age>=18&&n.position&&!n.survivalBlocked&&!n.cargo&&!n.freight&&!n.actionTarget&&n.status==='working'&&n.laborMessage==='Kiểm soát phơi nhiễm tại khu cách ly'&&Math.max(Math.abs(n.position.tileX-b.tileX),Math.abs(n.position.tileY-b.tileY))<=1));}
export function tickEldritch(s:Island):void{initializeEldritch(s);const v=s.eldritchSource,site=relicSite(s);if(!v||!site)return;v.clockTicks++;if(v.clockTicks%10===0){v.charge=Math.min(24,v.charge+1);v.contamination=Math.max(0,v.contamination-1);}if(v.clockTicks%5===0)for(const n of s.npcs)if(n.isAlive&&n.position&&Math.max(Math.abs(n.position.tileX-site.x),Math.abs(n.position.tileY-site.y))>3)n.exposure=Math.max(0,(n.exposure??0)-1);
 for(const b of s.buildings){if(!containmentOperating(s,b))continue;const local=s.npcs.filter(n=>n.isAlive&&n.position&&(n.exposure??0)>0&&Math.max(Math.abs(n.position.tileX-b.tileX),Math.abs(n.position.tileY-b.tileY))<=4),sourceNear=Math.max(Math.abs(site.x-b.tileX),Math.abs(site.y-b.tileY))<=3&&v.contamination>0;if(!local.length&&!sourceNear){b.workMessage='Không có phơi nhiễm trong vùng · giữ sinh chất';continue;}if((b.quarantineFuelTicks??0)<=0){b.buffer!.input.biomatter!--;b.quarantineFuelTicks=10;}b.quarantineFuelTicks!--;if(sourceNear)v.contamination=Math.max(0,v.contamination-2);for(const n of local)n.exposure=Math.max(0,(n.exposure??0)-2);b.quarantineCareTicks=(b.quarantineCareTicks??0)+1;b.workMessage='Giảm nhiễm nguồn trong3ô/phơi nhiễm cư dân trong4ô · tiêu sinh chất theo nhịp có tác dụng';}}
