import type {Island,Building} from './types';
export const GENERATOR_POWER=4,WORKSHOP_POWER=2,FUEL_TICKS=10;
export const generatorCapacity=(b:Building)=>GENERATOR_POWER+2*(Math.max(1,Math.min(3,b.level??1))-1);
export const isPowerBuilding=(b:Building)=>['steam_generator','prototype_workshop','component_factory','measurement_lab','microchip_factory','control_center','spirit_refinery','resonance_tower','apothecary','clinic','biomatter_workshop','quarantine'].includes(b.type);
export function initializePower(s:Island):void{s.power??={version:1,clockTicks:0,supply:0,demand:0,supplied:[],steadyTicks:0};}
export function hasPower(s:Island,b:Building):boolean{return !['prototype_workshop','component_factory','measurement_lab','microchip_factory','control_center','spirit_refinery','resonance_tower','apothecary','clinic','biomatter_workshop','quarantine'].includes(b.type)||!!s.power?.supplied.includes(b.id);}
export function refreshPower(s:Island):void{const p=s.power;if(!p)return;const generators=s.buildings.filter(b=>b.type==='steam_generator'&&b.complete&&!b.upgrade&&b.powerEnabled!==false&&((b.powerFuelTicks??0)>0||(b.buffer?.input.coal??0)>=1));const consumers=s.buildings.filter(b=>['prototype_workshop','component_factory','measurement_lab','microchip_factory','control_center','spirit_refinery','resonance_tower','apothecary','clinic','biomatter_workshop','quarantine'].includes(b.type)&&b.complete&&!b.upgrade&&b.powerEnabled!==false).sort((a,b)=>(b.powerPriority??1)-(a.powerPriority??1)||a.id.localeCompare(b.id));p.supply=generators.reduce((sum,b)=>sum+generatorCapacity(b),0);p.demand=consumers.length*WORKSHOP_POWER;let available=p.supply;p.supplied=[];for(const b of consumers)if(available>=WORKSHOP_POWER){available-=WORKSHOP_POWER;p.supplied.push(b.id);}}
function proof(s:Island,b:Building):boolean{return !!s.power?.supplied.includes(b.id)&&!b.upgrade&&(b.type==='measurement_lab'||(b.productionBatches??0)>0)&&b.workers.some(w=>s.npcs.some(n=>n.id===w&&n.isAlive&&n.position));}
function updateProof(s:Island,advance:boolean):void{const p=s.power;if(!p)return;for(const b of s.buildings)if(b.type==='prototype_workshop')b.poweredTicks=proof(s,b)?(b.poweredTicks??0)+(advance?1:0):0;for(const b of s.buildings)if(b.type==='measurement_lab')b.labPoweredTicks=proof(s,b)?(b.labPoweredTicks??0)+(advance?1:0):0;p.steadyTicks=Math.max(0,...s.buildings.filter(b=>b.type==='prototype_workshop').map(b=>b.poweredTicks??0));}
export function synchronizePower(s:Island):void{refreshPower(s);updateProof(s,false);}
export function setPower(s:Island,id:string,enabled:boolean,priority:number):string|null{const b=s.buildings.find(b=>b.id===id);if(!s.power||!b||!isPowerBuilding(b)||!b.complete||typeof enabled!=='boolean'||!Number.isInteger(priority)||priority<0||priority>2)return 'Cấu hình điện không hợp lệ.';b.powerEnabled=enabled;b.powerPriority=priority;refreshPower(s);updateProof(s,false);return null;}
// Coal must arrive in the generator buffer. Electricity is capacity, never a warehouse item.
export function tickPower(s:Island):void{if(!s.power)return;for(const b of s.buildings){if(b.type!=='steam_generator'||!b.complete||b.upgrade||b.powerEnabled===false)continue;b.buffer??={input:{},output:{}};if((b.powerFuelTicks??0)>0)b.powerFuelTicks!--;if((b.powerFuelTicks??0)<=0&&(b.buffer.input.coal??0)>=1){b.buffer.input.coal!-=1;b.powerFuelTicks=FUEL_TICKS;}}refreshPower(s);}
export function trackPower(s:Island):void{if(!s.power)return;s.power.clockTicks++;updateProof(s,true);}
export function powerStatus(s:Island,b:Building):string{if(!b.complete)return 'Đang xây';if(b.upgrade)return 'Đang nâng cấp · tạm dừng máy';if(b.powerEnabled===false)return 'Đã tắt máy';if(b.type==='steam_generator')return (b.powerFuelTicks??0)>0||(b.buffer?.input.coal??0)>=1?`Máy phát ${generatorCapacity(b)} công suất · 1 than/ngày`:'Thiếu than tại máy phát · cần vận chuyển';if(b.type==='quarantine')return hasPower(s,b)?'Đủ 2 công suất · cần thợ/sinh chất/phơi nhiễm tại vùng':'Thiếu điện · dừng kiểm soát nhiễm';if(b.type==='clinic')return hasPower(s,b)?'Đủ 2 công suất · cần người chữa/thuốc/bệnh nhân tại chỗ':'Thiếu điện · giữ liệu trình';if(b.type==='control_center')return hasPower(s,b)?'Đủ 2 công suất cho trung tâm':'Thiếu điện · ngừng điều phối';if(b.type==='measurement_lab')return hasPower(s,b)?'Đủ 2 công suất cho cơ sở':'Thiếu điện · giữ tiến độ phân tích';return hasPower(s,b)?'Đủ 2 công suất · xưởng vẫn cần thợ/nguyên liệu':'Thiếu điện · mẻ đang làm được giữ lại';}
