import {mkdir,writeFile} from 'node:fs/promises';
import {characterSVG,type CharacterLook,type CharacterEra,type CharacterPose,type CharacterDirection} from '../src/renderer/CharacterTextures';
const eras:CharacterEra[]=['stone','bronze','iron','modern','anomaly'],poses:CharacterPose[]=['idle','walk','work','sleep','fight'],directions:CharacterDirection[]=['south','north','east','west'];
const labels=['Cư dân','Trẻ em','Người lớn tuổi','Người nghiên cứu','Người bảo vệ','Người vận chuyển'];
const looks:CharacterLook[]=Array.from({length:6},(_,variant)=>({variant,child:variant===1,elder:variant===2,role:variant===3?'researcher':variant===4?'guard':'villager',tool:variant===0?'axe':'',bag:variant===5}));
async function main(){await mkdir('web/assets/characters',{recursive:true});let count=0;
 for(const era of eras)for(const look of looks)for(const pose of poses)for(const direction of directions)for(let frame=0;frame<2;frame++){await writeFile(`web/assets/characters/${era}-${look.variant}-${direction}-${pose}-${frame}.svg`,characterSVG(look,era,direction,pose,frame));count++;}
 const cards=eras.map(era=>`<section><h2>${({stone:'Đồ Đá',bronze:'Đồ Đồng',iron:'Đồ Sắt',modern:'Hiện Đại · hình mẫu, gameplay đang phát triển',anomaly:'Dị Tượng · hình mẫu, chưa mở nhánh'} as Record<string,string>)[era]}</h2><div class="group">${looks.map(look=>`<article><div class="scene"><img data-era="${era}" data-variant="${look.variant}" src="assets/characters/${era}-${look.variant}-south-idle-0.svg" width="64" height="96"></div><strong>${labels[look.variant]}</strong><small>Biến thể ${look.variant+1} · Dáng chibi mềm</small></article>`).join('')}</div></section>`).join('');
 await writeFile('web/character-gallery.html',`<!doctype html><html lang="vi"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cư dân Thiên Nguyên</title><style>*{box-sizing:border-box}body{margin:0;background:#eee4cb;color:#503e2c;font:16px Georgia,serif}header{padding:28px;background:#344e5c;color:#f1dfb8}h1{margin:0 0 10px}p{line-height:1.6;max-width:880px}a{color:inherit}main{max-width:1180px;margin:auto;padding:20px}section{margin-bottom:28px}.group{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:12px}article{padding:14px;border:1px solid #ac9467;border-radius:8px;background:#f8f0db;text-align:center}.scene{background:linear-gradient(#789b78,#b4aa76);border:3px solid #6b6e4c;border-radius:6px;height:120px;display:grid;place-items:center;margin-bottom:12px}img{image-rendering:auto}small{display:block;margin-top:6px;font-size:12px;color:#7d674b}.controls{display:flex;gap:12px;flex-wrap:wrap}select{padding:9px;background:#f3e8cb;color:#4c3b2b;border:1px solid #b29762;border-radius:6px}</style><header><h1>Đảo Thiên Nguyên · Cư dân riêng</h1><p>Trang phục, tóc, mặt, trẻ em và người lớn tuổi; bộ hình theo kỷ nguyên. Công cụ trên mẫu chỉ minh họa trang bị. Trong game chỉ hiện dụng cụ thực sự đã lấy. Hiện Đại và Dị Tượng ở đây là hình mẫu, không xác nhận đã mở gameplay.</p><div class="controls"><label>Dáng <select id="pose"><option value="idle">Đứng</option><option value="walk">Đi</option><option value="work">Làm việc</option><option value="sleep">Ngủ</option><option value="fight">Giao chiến</option></select></label><label>Hướng <select id="direction"><option value="south">Trước</option><option value="north">Sau</option><option value="east">Phải</option><option value="west">Trái</option></select></label><a href="/">Về đảo →</a></div></header><main>${cards}</main><script>let frame=0;const refresh=()=>document.querySelectorAll('[data-era]').forEach(i=>i.src='assets/characters/'+i.dataset.era+'-'+i.dataset.variant+'-'+document.querySelector('#direction').value+'-'+document.querySelector('#pose').value+'-'+frame+'.svg');document.querySelectorAll('select').forEach(s=>s.onchange=refresh);setInterval(()=>{frame=1-frame;refresh()},450);</script></html>`);
 console.log(`Generated ${count} original character views/frames; 30 gallery samples.`);
}
void main();
