import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {createIsland,reserveEntityIds} from '../src/core/factory';
import {generateWorldMap} from '../src/renderer/WorldMap';
import {spawnResources} from '../src/renderer/ResourceSpawner';
import {createCivilization} from '../src/core/civilization';
import {enableSettlement} from '../src/core/settlement';
import {initializeWorkforce} from '../src/core/workforce';
import {initializeEquipment} from '../src/core/equipment';
import {initializeLogistics} from '../src/core/logistics';
import {initializeFaith} from '../src/core/FaithManager';
import {initializeWeather} from '../src/core/WeatherManager';
import {initializeRaids} from '../src/core/RaidManager';
import {initializePower} from '../src/core/PowerManager';
import {initializeExploration,refreshVisibility,startExploration,tickExploration,chooseTorch,tickTorches,sightRadius,craftTorch,cancelTorch} from '../src/core/ExplorationManager';
import {SimulationSession,type PlayerCommand} from '../src/core/SimulationSession';
import {encodeSave,decodeSave} from '../src/core/SaveSystem';
import {findPath} from '../src/core/pathfinding';
const config={seed:20810,shape:'circle' as const,size:'small' as const,startPop:8,mode:'local' as const},map=generateWorldMap(50,35,config.seed,config.shape),s=createIsland('Hành trình khám phá',8);s.resources=spawnResources(map,config.seed);s.civilization=createCivilization();s.dailyLife={campfire:null};enableSettlement(s);initializeWorkforce(s,true);initializeEquipment(s);initializeLogistics(s);initializeFaith(s);initializeWeather(s,config.seed);initializeRaids(s);initializePower(s);s.sharedFood=40;s.wood=0;s.stone=0;initializeExploration(s,map);const sim=new SimulationSession(s,map);let sequence=0;const send=(command:PlayerCommand)=>{const r=sim.submit({playerId:'exploration-play',sequence:++sequence,command});assert(r.accepted,JSON.stringify({command,r}));};
const score=(p:{x:number;y:number})=>[...s.resources].reduce((sum,[key,r])=>{const [x,y]=key.split(',').map(Number);return sum+(Math.max(Math.abs(x-p.x),Math.abs(y-p.y))<=3?(r.type==='herb_patch'?6:r.type==='wood_tree'?3:r.type==='stone_deposit'?2:0):0);},0);
const home=[...map.landTiles].sort((a,b)=>score(b)-score(a))[0],sites=map.landTiles.filter(p=>Math.max(Math.abs(p.x-home.x),Math.abs(p.y-home.y))<=2&&findPath(map,home.x,home.y,p.x,p.y)!==null);assert(sites.length>=8);
s.npcs.forEach((n,i)=>send({type:'place_npc',npcId:n.id,tileX:sites[i].x,tileY:sites[i].y}));const adults=s.npcs.filter(n=>n.age>=18&&n.occupation!=='child');assert(adults.length>=4);adults.forEach((n,i)=>send({type:'assign_labor',npcId:n.id,role:i===adults.length-1?'stone':i===adults.length-2?'wood':'food'}));
let steps=0;while(s.wood<1&&steps++<60)sim.advanceTicks(1);assert(s.wood>=1,'wood must be harvested and delivered');let actor=adults.find(n=>!n.cargo&&!n.freight&&!n.haulTask&&n.needs.hunger<80&&n.needs.rest<80)!;assert(actor);send({type:'assign_labor',npcId:actor.id,role:'idle'});writeFileSync('artifacts/exploration-precraft-save.json',encodeSave(s,map,config));const woodBefore=s.wood;send({type:'craft_torch',npcId:actor.id});assert.equal(s.wood,woodBefore-1);while(s.exploration!.torchOrder&&steps++<120)sim.advanceTicks(1);assert.equal(s.exploration!.torchCrafted,1);send({type:'choose_torch',npcId:actor.id,equip:true});while(!actor.torch&&steps++<160)sim.advanceTicks(1);assert(actor.torch);while(s.tick%10!==0&&steps++<180)sim.advanceTicks(1);assert.equal(s.npcs.filter(n=>n.isAlive).length,8);refreshVisibility(s,map);
const camp=s.dailyLife!.campfire!,distance=(p:{x:number;y:number})=>Math.max(Math.abs(p.x-camp.tileX),Math.abs(p.y-camp.tileY));const targets=map.landTiles.filter(p=>distance(p)>=7&&distance(p)<=12&&!s.exploration!.discovered.has(`${p.x},${p.y}`)&&[...s.resources].some(([k,r])=>{const [x,y]=k.split(',').map(Number);return ['herb_patch','fish_spot'].includes(r.type)&&r.amount>0&&Math.hypot(x-p.x,y-p.y)<=4&&Math.max(Math.abs(x-camp.tileX),Math.abs(y-camp.tileY))>=6;})).map(p=>({p,path:findPath(map,actor.position!.tileX,actor.position!.tileY,p.x,p.y)})).filter(p=>p.path&&p.path.length<=14).sort((a,b)=>a.path!.length-b.path!.length);assert(targets.length,'reachable unknown food region');const target=targets[0].p;writeFileSync('artifacts/exploration-ready-save.json',encodeSave(s,map,config));writeFileSync('artifacts/exploration-route.json',JSON.stringify({npcId:actor.id,target,home:{x:camp.tileX,y:camp.tileY},preparationSteps:steps,woodEarned:true,torchCrafted:1,alive:8,food:s.sharedFood},null,2));
// Controlled edge cases, separate from the earned playthrough.
const fixture=()=>{const d=decodeSave(readFileSync('artifacts/exploration-ready-save.json','utf8'));reserveEntityIds(d.island);return {d,n:d.island.npcs.find(n=>n.id===actor.id)!};};
{const {d,n}=fixture();n.torch!.fuel=9;n.position={tileX:camp.tileX,tileY:camp.tileY};n.survivalBlocked=false;assert.equal(chooseTorch(d.island,n.id,false),null);tickTorches(d.island,d.map);assert(!n.torch);assert.equal(d.island.exploration!.torchStock[0],9);n.survivalBlocked=false;assert.equal(chooseTorch(d.island,n.id,true),null);tickTorches(d.island,d.map);assert.equal(n.torch!.fuel,9);decodeSave(encodeSave(d.island,d.map,d.config));}
{const {d,n}=fixture();assert.equal(startExploration(d.island,d.map,n.id,target.x,target.y),null);n.survivalBlocked=false;tickExploration(d.island,d.map);n.survivalBlocked=false;n.needs.hunger=80;tickExploration(d.island,d.map);assert.equal(d.island.exploration!.active?.stage,'returning');assert.equal(n.laborRole,'idle');assert.equal(d.island.exploration!.mission.food,false);const raw=encodeSave(d.island,d.map,d.config);const loaded=decodeSave(raw);assert(loaded.island.exploration!.discovered instanceof Set);const bad=JSON.parse(raw);bad.island.npcs.find((x:any)=>x.id===n.id).torch.fuel=31;assert.throws(()=>decodeSave(JSON.stringify(bad)));}
{const {d,n}=fixture();n.torch=undefined;d.island.exploration!.torchStock=[30];d.island.tick=9;assert.equal(sightRadius(d.island,n),2);n.torch={fuel:1};d.island.exploration!.torchStock=[];assert.equal(sightRadius(d.island,n),6);const hiddenBefore=d.island.exploration!.discovered.size;tickExploration(d.island,d.map);assert.equal(n.torch.fuel,0);assert(d.island.exploration!.discovered.size>=hiddenBefore);assert(startExploration(d.island,d.map,n.id,target.x,target.y));}
{const {d,n}=fixture();assert.equal(startExploration(d.island,d.map,n.id,target.x,target.y),null);n.survivalBlocked=false;tickExploration(d.island,d.map);const p=n.position!;for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1],[1,1],[1,-1],[-1,1],[-1,-1]])d.map.tiles[p.tileY+dy][p.tileX+dx]='deep_water';n.survivalBlocked=false;tickExploration(d.island,d.map);assert.equal(d.island.exploration!.active!.stage,'returning');assert.match(d.island.exploration!.message,/Đường bị chặn/);assert.deepEqual(n.position,p);}
{const {d,n}=fixture();d.island.wood=2;assert.equal(craftTorch(d.island,d.map,n.id),null);assert.equal(d.island.wood,1);assert(craftTorch(d.island,d.map,n.id));const reloaded=decodeSave(encodeSave(d.island,d.map,d.config));assert.equal(reloaded.island.wood,1);assert.equal(cancelTorch(reloaded.island),null);assert.equal(reloaded.island.wood,2);assert(cancelTorch(reloaded.island));assert.equal(reloaded.island.wood,2);}
{const {d,n}=fixture();const source=[...d.island.resources].find(([,r])=>r.type==='wood_tree')![0].split(',').map(Number);n.actionTarget={type:'chop_wood',x:source[0],y:source[1]};n.laborTask={workTicks:3,totalTicks:5};assert.equal(startExploration(d.island,d.map,n.id,target.x,target.y),null);n.survivalBlocked=false;tickExploration(d.island,d.map);assert.equal(n.laborTask.workTicks,3);assert.equal(n.actionTarget.type,'chop_wood');decodeSave(encodeSave(d.island,d.map,d.config));}
{const {d,n}=fixture();d.island.wood=1;assert.equal(craftTorch(d.island,d.map,n.id),null);n.isAlive=false;const saved=decodeSave(encodeSave(d.island,d.map,d.config));assert.equal(cancelTorch(saved.island),null);assert.equal(saved.island.wood,1);}
console.log('PASS earned preparation: zero wood/stone, real harvest-delivery,1wood paid/1torch crafted/taken,8alive; separate fixtures fuel conservation/day-night/interrupt/blocked-path/save corruption.');
