import assert from 'node:assert/strict';
import {createIsland} from '../src/core/factory';
import {createCivilization} from '../src/core/civilization';
import {enableSettlement,tickCargo,openingMilestones} from '../src/core/settlement';
import {placeBuilding,assignWorker,tickBuildings,buildingSiteLock} from '../src/renderer/BuildingManager';
import {SimulationSession} from '../src/core/SimulationSession';
import {encodeSave,decodeSave} from '../src/core/SaveSystem';
import type {WorldMap} from '../src/renderer/WorldMap';
const map:WorldMap={width:20,height:12,tiles:Array.from({length:12},()=>Array(20).fill('grass')),landTiles:[]};
for(let y=0;y<12;y++)for(let x=0;x<20;x++)map.landTiles.push({x,y});
const island=createIsland('Khởi nguyên',5);island.civilization=createCivilization();enableSettlement(island);
island.dailyLife!.campfire={tileX:2,tileY:2,fuel:12,graceUntil:30,lit:true};
island.wood=100;island.stone=100;island.sharedFood=100;
island.npcs.forEach((n,i)=>{n.age=25;n.occupation='gatherer';n.position={tileX:2+i,tileY:2};n.laborRole='idle';n.needs={hunger:0,rest:0,safety:0,social:0};});
island.resources.set('4,5',{type:'fish_spot',amount:50,maxAmount:50,regenRate:0});map.tiles[5][4]='shallow_water';
assert(buildingSiteLock(island,'fishing_dock',12,8));const wood=island.wood;
assert.equal(placeBuilding(island,'fishing_dock',12,8),null);assert.equal(island.wood,wood);
const dock=placeBuilding(island,'fishing_dock',4,4)!;assert(dock);dock.complete=true;dock.progress=100;
const n=island.npcs[0];n.position={tileX:4,tileY:4};assert(assignWorker(island,dock.id,n.id));
const food=island.sharedFood;
for(let i=0;i<5;i++)tickBuildings(island,island.resources,map);
assert.equal(island.sharedFood,food,'No remote stock credit');assert.equal(n.cargo!.food,24);assert.equal(island.resources.get('4,5')!.amount,26);
tickBuildings(island,island.resources,map);assert.equal(island.resources.get('4,5')!.amount,26,'Carrier cannot fish twice');
const saved=decodeSave(encodeSave(island,map,{seed:42,shape:'circle',size:'small',startPop:5,mode:'local'},0));assert.equal(saved.island.npcs[0].cargo!.food,24);
n.survivalBlocked=false;tickCargo(island,map);assert.equal(island.sharedFood,food);n.survivalBlocked=false;tickCargo(island,map);assert.equal(island.sharedFood,food+24);assert.equal(n.cargo,undefined);
island.sharedFood=300;n.position={tileX:4,tileY:4};n.survivalBlocked=false;n.buildingWork={buildingId:dock.id,ticks:0};n.path=[];
for(let i=0;i<5;i++)tickBuildings(island,island.resources,map);assert.equal(island.resources.get('4,5')!.amount,26,'Full stock preserves source');assert.equal(n.cargo,undefined);
const session=new SimulationSession(island,map);let seq=0;const submit=(command:any)=>session.submit({playerId:'test',sequence:++seq,command});
assert(!submit({type:'start_research',techId:'fire'}).accepted);
const table=placeBuilding(island,'study_table',17,2)!;table.complete=true;table.progress=100;
assert(submit({type:'start_research',techId:'fire'}).accepted);const research=island.civilization!.research!,r=island.npcs.find(n=>n.id===research.researcherId)!;
r.position={tileX:2,tileY:2};session.advanceTicks(1);assert.equal(research.workTicks,0);assert(r.position.tileX>2,'Researcher physically walks');
for(let y=1;y<=3;y++)for(let x=16;x<=18;x++)if(x!==17||y!==2)map.tiles[y][x]='deep_water';
session.advanceTicks(1);assert.equal(research.workTicks,0,'Blocked table does not create remote knowledge');
assert.match(r.laborMessage!,/Không có đường/);
const researchSave=decodeSave(encodeSave(island,map,{seed:42,shape:'circle',size:'small',startPop:5,mode:'local'}));assert.equal(researchSave.island.civilization!.research!.workTicks,0);
for(let y=1;y<=3;y++)for(let x=16;x<=18;x++)map.tiles[y][x]='grass';
researchSave.island.buildings=researchSave.island.buildings.filter(b=>b.type!=='study_table');
new SimulationSession(researchSave.island,map).advanceTicks(1);
assert((researchSave.island.civilization!.research!.workTicks??0)>0,'Already active legacy project continues without a table');
for(let i=0;i<200&&!island.civilization!.unlocks.includes('fire');i++)session.advanceTicks(1);
assert(island.civilization!.unlocks.includes('fire'));assert(island.npcs.every(n=>n.isAlive));
assert.equal(openingMilestones(island).find(m=>m.label==='Bàn nghiên cứu và Lửa')!.met,true);
console.log('PASS: shore validation, source/cargo/stock conservation, full stock, save mid-delivery, table prerequisite, physical research and survival interruptions.');
