import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {decodeSave,encodeSave} from '../src/core/SaveSystem';
import {reserveEntityIds} from '../src/core/factory';
import {SimulationSession,type PlayerCommand} from '../src/core/SimulationSession';
import {findPath} from '../src/core/pathfinding';
import {canAfford,BUILD_COSTS} from '../src/renderer/BuildingManager';
const d=decodeSave(readFileSync('artifacts/modern-supply-played-save.json','utf8')),s=d.island,c=s.civilization!;reserveEntityIds(s);const sim=new SimulationSession(s,d.map);let seq=0;const start=s.tick,initialProduction=c.produced.components,initialCloth=c.produced.cloth,initialComponents=c.inventory.components;
const send=(command:PlayerCommand)=>{const r=sim.submit({playerId:'dispatch',sequence:++seq,command});assert(r.accepted,JSON.stringify({command,r}));};
const step=()=>{sim.advanceTicks(1);assert.equal(s.npcs.filter(n=>n.isAlive).length,50);};
const until=(ok:()=>boolean,max=3500)=>{for(let i=0;i<max&&!ok();i++)step();if(!ok())writeFileSync('artifacts/modern-dispatch-waiting-save.json',encodeSave(s,d.map,d.config));assert(ok(),JSON.stringify({tick:s.tick,food:s.sharedFood,goods:c.inventory,power:s.power,b:s.buildings.filter(b=>b.workers.length||b.type==='steam_generator').map(b=>[b.type,b.id,b.workMessage,b.buffer])}));};
const factory=s.buildings.find(b=>b.type==='component_factory')!,gen=s.buildings.find(b=>b.type==='steam_generator')!,proto=s.buildings.find(b=>b.type==='prototype_workshop')!,post=s.buildings.find(b=>b.type==='tradepost')!,iron=s.buildings.find(b=>b.type==='iron_smelter')!,steel=s.buildings.find(b=>b.type==='steelworks')!,flax=s.buildings.find(b=>b.type==='flax_field')!,weaver=s.buildings.find(b=>b.type==='weaver')!;
for(const b of [factory,gen,proto])send({type:'set_power',buildingId:b.id,enabled:false,priority:1});
const crew=s.npcs.filter(n=>n.isAlive&&n.age>=18&&n.occupation!=='child'&&!n.guardDuty&&n.laborRole==='food'&&!s.buildings.some(b=>b.workers.includes(n.id))).slice(-8);assert.equal(crew.length,8);for(const n of crew)send({type:'assign_labor',npcId:n.id,role:'idle'});const [builder,miner,smith,trader,op1,op2,op3,tailor]=crew;
send({type:'assign_worker',buildingId:post.id,npcId:trader.id});send({type:'assign_worker',buildingId:iron.id,npcId:miner.id});send({type:'assign_worker',buildingId:steel.id,npcId:smith.id});send({type:'assign_worker',buildingId:flax.id,npcId:builder.id});send({type:'assign_worker',buildingId:weaver.id,npcId:tailor.id});
const trip=(offerId:string)=>{until(()=>!trader.actionTarget&&!trader.cargo&&!trader.freight&&!trader.haulTask);send({type:'start_trade',buildingId:post.id,offerId});until(()=>!post.shipment);};
for(let i=0;i<4;i++){trip('cloth_for_coal');trip('cloth_for_ore');}until(()=>c.inventory.steel>=8);send({type:'remove_worker',buildingId:flax.id,npcId:builder.id});
const plants=[factory];for(let count=0;count<2;count++){
 until(()=>canAfford(s,BUILD_COSTS.component_factory));const t=d.map.landTiles.find(t=>t.x>=4&&t.x<=23&&t.y>=10&&t.y<=21&&['grass','sand'].includes(d.map.tiles[t.y][t.x])&&!s.buildings.some(b=>b.tileX===t.x&&b.tileY===t.y)&&!s.npcs.some(n=>n.position?.tileX===t.x&&n.position?.tileY===t.y)&&!s.animals.some(a=>a.tileX===t.x&&a.tileY===t.y)&&findPath(d.map,builder.position!.tileX,builder.position!.tileY,t.x,t.y)!==null)!;assert(t);send({type:'build',buildingType:'component_factory',tileX:t.x,tileY:t.y});const b=s.buildings.at(-1)!;send({type:'assign_worker',buildingId:b.id,npcId:builder.id});until(()=>b.complete);send({type:'set_power',buildingId:b.id,enabled:false,priority:1});send({type:'remove_worker',buildingId:b.id,npcId:builder.id});plants.push(b);
}
// Replenish all industrial inputs through paid contracts. Keep generation off while waiting.
for(let i=0;i<7;i++){trip('cloth_for_coal');if(i<7)trip('cloth_for_ore');if(i<3)trip('cloth_for_copper');}
until(()=>c.inventory.steel>=18);for(const [b,n] of [[iron,miner],[steel,smith]] as const)send({type:'remove_worker',buildingId:b.id,npcId:n.id});send({type:'remove_worker',buildingId:weaver.id,npcId:tailor.id});send({type:'assign_labor',npcId:builder.id,role:'food'});send({type:'assign_labor',npcId:tailor.id,role:'food'});send({type:'assign_labor',npcId:miner.id,role:'food'});send({type:'assign_labor',npcId:smith.id,role:'food'});for(let i=0;i<3;i++)send({type:'assign_worker',buildingId:plants[i].id,npcId:[op1,op2,op3][i].id});
while(c.inventory.coal<40)trip('cloth_for_coal');send({type:'remove_worker',buildingId:post.id,npcId:trader.id});send({type:'assign_labor',npcId:builder.id,role:'haul'});send({type:'assign_labor',npcId:trader.id,role:'haul'});for(const b of plants)send({type:'set_power',buildingId:b.id,enabled:true,priority:1});send({type:'set_power',buildingId:proto.id,enabled:true,priority:0});until(()=>plants.every(b=>(b.buffer?.input.steel??0)>=4&&(b.buffer?.input.copper??0)>=4)&&c.inventory.coal+(gen.buffer?.input.coal??0)>=35);send({type:'set_power',buildingId:gen.id,enabled:true,priority:1});until(()=>s.power!.supply===6);assert.equal(s.power!.supply,6);assert.equal(s.power!.demand,8);assert(!s.power!.supplied.includes(proto.id));for(const b of plants)assert(s.power!.supplied.includes(b.id));
writeFileSync('artifacts/modern-dispatch-ready-save.json',encodeSave(s,d.map,d.config));const blocked=plants[2];const buffer=structuredClone(blocked.buffer),production=blocked.productionBatches??0;send({type:'set_power',buildingId:blocked.id,enabled:true,priority:0});send({type:'set_power',buildingId:proto.id,enabled:true,priority:2});assert(s.power!.supplied.includes(proto.id));assert(!s.power!.supplied.includes(blocked.id));assert.deepEqual(blocked.buffer,buffer);const parts=c.produced.machineParts;
for(let i=0;i<20;i++)step();assert.equal(blocked.productionBatches??0,production);assert(c.produced.machineParts>parts);send({type:'set_power',buildingId:blocked.id,enabled:true,priority:2});send({type:'set_power',buildingId:proto.id,enabled:true,priority:0});assert(s.power!.supplied.includes(blocked.id));assert(!s.power!.supplied.includes(proto.id));
// A 30-day powered campaign, with real fuel deliveries and no simulated time while paused.
let powered=0;for(let i=0;i<300;i++){step();if(s.power!.supply===6&&plants.every(b=>s.power!.supplied.includes(b.id)))powered++;if(i%50===0)decodeSave(encodeSave(s,d.map,d.config));}
assert.equal(powered,300);until(()=>c.inventory.components>=initialComponents+27);assert(plants.every(b=>(b.productionBatches??0)>=2));assert(c.produced.components>=initialProduction+18);assert(c.produced.cloth>initialCloth);assert.equal(s.npcs.filter(n=>n.isAlive).length,50);const final=encodeSave(s,d.map,d.config);assert.deepEqual(decodeSave(final).island.civilization,JSON.parse(JSON.stringify(c)));writeFileSync('artifacts/modern-dispatch-played-save.json',final);console.log(`PASS earned dispatch: two paid/built factories, 6 supply/8 demand, swapped priority holds unpowered batch and runs prototype, all three factories make products, 30 powered days/300 ticks, 27 new components delivered, produced +${c.produced.components-initialProduction} components/+${c.produced.cloth-initialCloth} cloth, 50 alive/Food ${s.sharedFood.toFixed(1)}, ${s.tick-start} campaign steps.`);
