import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {decodeSave,encodeSave} from '../src/core/SaveSystem';
import {reserveEntityIds} from '../src/core/factory';
import {SimulationSession,type PlayerCommand} from '../src/core/SimulationSession';
import {tickCare,craftDefense,startTreatment,chooseDefense,cancelDefense} from '../src/core/CareManager';
import {castIncite,incited} from '../src/core/FaithManager';
import {materialCapacity} from '../src/renderer/BuildingManager';
import {respondToRaid} from '../src/core/RaidManager';
const d=decodeSave(readFileSync('artifacts/mystic-played-save.json','utf8')),s=d.island,c=s.civilization!;reserveEntityIds(s);const sim=new SimulationSession(s,d.map);let seq=0;const initial=s.tick;
const send=(command:PlayerCommand)=>{const r=sim.submit({playerId:'care-earned',sequence:++seq,command});assert(r.accepted,JSON.stringify({command,r}));};
const until=(ok:()=>boolean,max=1200)=>{for(let i=0;i<max&&!ok();i++){sim.advanceTicks(1);assert.equal(s.npcs.filter(n=>n.isAlive).length,50);}if(!ok())writeFileSync('artifacts/care-waiting-save.json',encodeSave(s,d.map,d.config));assert(ok(),JSON.stringify({food:s.sharedFood,health:guard.health,position:guard.position,herbs:s.herbs,treatment:guard.treatment,raids:s.raids,defense:s.defense}));};
const guard=s.npcs.find(n=>n.id==='npc_15')!,lab=s.buildings.find(b=>b.type==='measurement_lab')!;for(const b of s.buildings.filter(b=>['measurement_lab','steam_generator'].includes(b.type)))send({type:'set_power',buildingId:b.id,enabled:false,priority:1});send({type:'remove_worker',buildingId:lab.id,npcId:guard.id});const collector=s.npcs.find(n=>n.isAlive&&n.age>=18&&n.position&&!n.guardDuty&&!s.buildings.some(b=>b.workers.includes(n.id))&&n.id!==guard.id)!;send({type:'assign_labor',npcId:collector.id,role:'stone'});until(()=>s.stone>=30);send({type:'assign_labor',npcId:collector.id,role:'food'});const learn=(id:string)=>{if(c.unlocks.includes(id))return;send({type:'start_research',techId:id});send({type:'assign_researcher',npcId:guard.id});until(()=>c.unlocks.includes(id));};learn('nature_observation');learn('herbalism');send({type:'set_guard',npcId:guard.id,enabled:true});for(const kind of ['spear','padded_vest'] as const){const before={wood:s.wood,stone:s.stone,cloth:c.inventory.cloth};send({type:'craft_defense',kind});if(kind==='spear'){assert.equal(s.wood,before.wood-6);assert.equal(s.stone,before.stone-4);}else assert.equal(c.inventory.cloth,before.cloth-4);until(()=>!s.defense!.order);send({type:'choose_defense',npcId:guard.id,kind,equip:true});until(()=>!guard.defenseChoice);assert.equal(kind==='spear'?guard.weapon:guard.armor,kind);}
const fee=s.faith!.amount;const env={playerId:'care-earned',sequence:++seq,command:{type:'cast_incite' as const}};assert(sim.submit(env).accepted);assert(sim.submit(env).duplicate);assert.equal(s.faith!.amount,fee-30);assert(incited(s,guard));assert(!sim.submit({playerId:'care-earned',sequence:++seq,command:env.command}).accepted);writeFileSync('artifacts/care-equipped-earned-save.json',encodeSave(s,d.map,d.config));const raw=encodeSave(s,d.map,d.config);decodeSave(raw);for(const kind of ['spear','padded_vest'] as const){send({type:'choose_defense',npcId:guard.id,kind,equip:false});until(()=>!guard.defenseChoice);assert.equal(s.defense!.stock[kind],1);send({type:'choose_defense',npcId:guard.id,kind,equip:true});until(()=>!guard.defenseChoice);}writeFileSync('artifacts/care-played-save.json',encodeSave(s,d.map,d.config));console.log(JSON.stringify({passed:true,earned:true,steps:s.tick-initial,alive:50,food:s.sharedFood,weapon:guard.weapon,armor:guard.armor,defense:s.defense,faith:s.faith!.amount,incite:s.faith!.incite}));
// Fixtures isolate exact effects, source fees, blocked access and data validation.
const f=decodeSave(raw).island,n=f.npcs.find(n=>n.id===guard.id)!,camp=f.dailyLife!.campfire!;n.position={tileX:camp.tileX,tileY:camp.tileY};n.needs.hunger=0;n.needs.rest=0;n.survival=undefined;n.status='idle';n.survivalBlocked=false;n.treatment=undefined;n.health=60;writeFileSync('artifacts/care-injured-fixture-save.json',encodeSave(f,d.map,d.config));const herbs=f.herbs;assert.equal(startTreatment(f,n.id),null);tickCare(f,d.map);assert.equal(f.herbs,herbs-2);assert.equal(n.health,65);assert.equal(n.treatment!.workTicks,1);n.survivalBlocked=false;const midway=encodeSave(f,d.map,d.config);decodeSave(midway);for(let i=0;i<3;i++){n.survivalBlocked=false;tickCare(f,d.map);}assert.equal(n.health,80);assert.equal(f.herbs,herbs-2);assert(!n.treatment);n.health=60;n.position={tileX:0,tileY:0};assert.equal(startTreatment(f,n.id),null);const wall={...d.map,tiles:d.map.tiles.map(row=>[...row])};for(let y=0;y<wall.height;y++)wall.tiles[y][1]='deep_water';const h=f.herbs;n.survivalBlocked=false;tickCare(f,wall);assert.equal(n.treatment!.workTicks,0);assert.equal(f.herbs,h);
const fight=decodeSave(raw).island,a=fight.npcs.find(n=>n.id===guard.id)!;a.position={tileX:4,tileY:4};a.needs.hunger=0;a.health=100;a.survivalBlocked=false;fight.raids!.phase='active';fight.raids!.target={x:4,y:4};fight.raids!.enemies=[{id:'fixture',x:4,y:4,health:36}];respondToRaid(fight,d.map);const damage=36-fight.raids!.enemies[0].health;assert(damage>=9.6);assert.equal(a.health,98);a.survivalBlocked=false;fight.faith!.clockMs=fight.faith!.incite!.untilMs;fight.raids!.enemies[0].health=36;respondToRaid(fight,d.map);assert(36-fight.raids!.enemies[0].health<damage);const invalid=JSON.parse(raw);invalid.island.defense.stock.spear=1;assert.throws(()=>decodeSave(JSON.stringify(invalid)),/phòng vệ/);const bad=JSON.parse(midway);bad.island.npcs.find((x:any)=>x.id===guard.id).treatment.workTicks=4;assert.throws(()=>decodeSave(JSON.stringify(bad)),/Liệu trình/);console.log('PASS care fixtures: exact2herbs/4steps/+20HP, partial save and blocked route preserve fee, armor3→2 damage, spear/incite actual damage then expiry, malformed gear duplication/treatment saves rejected.');

const refund=decodeSave(raw).island;assert.equal(craftDefense(refund,'spear'),null);refund.wood=materialCapacity(refund);assert.match(cancelDefense(refund)!,/Kho đầy/);assert(refund.defense!.order);refund.wood-=6;assert.equal(cancelDefense(refund),null);assert(!refund.defense!.order);assert.notEqual(cancelDefense(refund),null);const previous=refund.faith!.amount;for(const p of refund.npcs)p.guardDuty=false;assert.notEqual(castIncite(refund),null);assert.equal(refund.faith!.amount,previous);console.log('PASS refund/full warehouse and no-guard Incite: pending order preserved until refund space exists, refund only once, rejected cast does not spend.');
