import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE??'playwright');const root=path.resolve('web');
const server=createServer(async(req,res)=>{const file=path.resolve(root,'.'+new URL(req.url??'/','http://localhost').pathname.replace(/\/$/,'/index.html'));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{res.setHeader('content-type',({'.html':'text/html','.css':'text/css','.js':'text/javascript','.svg':'image/svg+xml','.png':'image/png'} as Record<string,string>)[path.extname(file)]??'application/octet-stream');res.end(await readFile(file));}catch{res.writeHead(404).end();}});
async function main(){
 await mkdir('artifacts',{recursive:true});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors:string[]=[],failed:string[]=[];page.on('pageerror',(e:Error)=>errors.push(e.message));page.on('response',(r:any)=>{if(r.status()>=400)failed.push(r.url());});const url=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
 const close=async()=>{if(await page.locator('#panel-overlay').evaluate((e:HTMLElement)=>e.classList.contains('open')))await page.locator('#panel-close').click();await page.waitForTimeout(350);};
 const pause=async(on:boolean)=>{await close();if((await page.locator('#btn-pause').evaluate((e:HTMLElement)=>e.classList.contains('active')))!==on)await page.locator('#btn-pause').click();};
 const save=async()=>{await close();await page.locator('#btn-save-local').click();return page.evaluate(()=>JSON.parse(localStorage.getItem('dao_thien_nguyen_v2')!));};
 const load=async(raw:string)=>{await page.goto(url);await page.evaluate((raw:string)=>localStorage.setItem('dao_thien_nguyen_v2',raw),raw);await page.reload();await page.locator('#btn-resume-game').click();await page.locator('.era-roadmap').waitFor();await pause(true);};
 const inspect=async()=>{await close();await page.locator('#btn-build').click();await page.locator('[data-inspect-building]').filter({hasText:'Lò luyện đồng'}).click();await page.locator('#bi-auto-staff').waitFor();await page.waitForTimeout(350);};
 try{
  // Real Bronze playthrough: all old assignments survive migration; user explicitly hands adults back to auto using controls.
  const raw=await readFile('artifacts/bronze-playable-save.json','utf8');await load(raw);let initial=await save();const original=JSON.parse(raw);assert.deepEqual(initial.island.buildings.map((b:any)=>b.workers),original.island.buildings.map((b:any)=>b.workers));await page.locator('#sb-population').click();const modes=page.locator('.labor-mode-select');for(let i=0;i<await modes.count();i++)await modes.nth(i).selectOption('auto');await close();const configured=await save();assert(configured.island.buildings.some((b:any)=>b.autoWorkers?.length));await page.locator('#sb-population').click();await page.locator('#auto-claim-toggle').check();await close();
  const day=Number(await page.locator('#stat-day').innerText());await page.locator('.speed-btn[data-speed="2"]').click();await pause(false);await page.waitForFunction((day:number)=>Number(document.querySelector('#stat-day')?.textContent)>=day,day+15,{timeout:55000});await pause(true);let state=await save();assert.equal(state.island.npcs.filter((n:any)=>n.isAlive).length,12);assert(state.island.sharedFood>0);assert(state.island.buildings.some((b:any)=>b.autoWorkers?.length));
  await inspect();assert.match(await page.locator('#bi-auto-staff').innerText(),/Tắt/);await page.locator('#bi-auto-staff').click();assert.match(await page.locator('#bi-auto-staff').innerText(),/Bật/);await page.locator('#bi-close').click();state=await save();const smelter=state.island.buildings.find((b:any)=>b.type==='smelter');assert.equal(smelter.autoStaff,false);await load(JSON.stringify(state));assert.equal((await save()).island.buildings.find((b:any)=>b.id===smelter.id).autoStaff,false);
  const day2=Number(await page.locator('#stat-day').innerText());await page.locator('.speed-btn[data-speed="2"]').click();await pause(false);await page.waitForFunction((day:number)=>Number(document.querySelector('#stat-day')?.textContent)>=day,day2+6,{timeout:28000});await pause(true);state=await save();assert.equal(state.island.buildings.find((b:any)=>b.id===smelter.id).autoWorkers?.length??0,0,'Off releases automated staff after batch/travel boundary');
  await inspect();const selected=await page.locator('#bi-select-npc option').evaluateAll((opts:HTMLOptionElement[])=>opts.find(o=>o.value)?.value);assert(selected);await page.locator('#bi-select-npc').selectOption(selected);await page.locator('#bi-btn-assign').click();assert.match(await page.locator('.bi-worker-row').innerText(),/Bạn phân công/);await page.locator('#bi-auto-staff').click();assert.match(await page.locator('#bi-auto-staff').innerText(),/Tắt/);await page.locator('.bi-production-alert').scrollIntoViewIfNeeded();await page.waitForTimeout(350);await page.screenshot({path:'artifacts/production-factory-desktop.png'});await page.locator('#bi-close').click();state=await save();assert(state.island.buildings.find((b:any)=>b.id===smelter.id).workers.includes(selected));assert.equal(state.island.npcs.find((n:any)=>n.id===selected).laborMode,'manual');await load(JSON.stringify(state));const after=await save();assert.deepEqual(after.island.buildings.map((b:any)=>b.autoWorkers),state.island.buildings.map((b:any)=>b.autoWorkers));
  const day3=Number(await page.locator('#stat-day').innerText());await page.locator('.speed-btn[data-speed="2"]').click();await pause(false);await page.waitForFunction((day:number)=>Number(document.querySelector('#stat-day')?.textContent)>=day,day3+6,{timeout:28000});await pause(true);state=await save();assert(state.island.buildings.find((b:any)=>b.id===smelter.id).workers.includes(selected));assert.equal(state.island.npcs.filter((n:any)=>n.isAlive).length,12);assert(state.island.sharedFood>0);
  await page.locator('#sb-population').click();await page.locator('#logistics-overview').scrollIntoViewIfNeeded();assert(await page.locator('.production-alert').count()>0);await page.waitForTimeout(350);await page.screenshot({path:'artifacts/production-overview-desktop.png'});await page.setViewportSize({width:390,height:844});await page.locator('#logistics-overview').scrollIntoViewIfNeeded();await page.waitForTimeout(350);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'artifacts/production-overview-mobile.png'});await close();await page.setViewportSize({width:1440,height:1000});await inspect();await page.setViewportSize({width:390,height:844});await page.locator('#bi-auto-staff').scrollIntoViewIfNeeded();await page.waitForTimeout(350);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);const uncovered=await page.locator('#building-inspector').evaluate((e:HTMLElement)=>{const r=e.getBoundingClientRect(),el=document.elementFromPoint(r.right-30,r.top+160);return e.contains(el);});assert(uncovered,'Factory inspector must cover floating Faith HUD');await page.screenshot({path:'artifacts/production-factory-mobile.png'});await page.locator('#bi-close').click();await writeFile('artifacts/production-browser-save.json',JSON.stringify(await save()));assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);console.log(`PASS: real Bronze save preserves old manual assignments; controls opt into auto, per-factory off/release/reload, manual assignment retained under auto, 27 days / 12 alive / Food ${state.island.sharedFood.toFixed(1)}, alerts, desktop/mobile and no errors.`);
 }catch(e){await page.screenshot({path:'artifacts/production-ui-failure.png'});throw e;}finally{await browser.close();await new Promise<void>(r=>server.close(()=>r()));}
}
void main().catch(e=>{console.error(e);server.close();process.exitCode=1;});
