import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE??'playwright');const root=path.resolve('web');
const server=createServer(async(req,res)=>{const file=path.resolve(root,'.'+new URL(req.url??'/','http://localhost').pathname.replace(/\/$/,'/index.html'));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{res.setHeader('content-type',({'.html':'text/html','.css':'text/css','.js':'text/javascript','.svg':'image/svg+xml','.png':'image/png'} as Record<string,string>)[path.extname(file)]??'application/octet-stream');res.end(await readFile(file));}catch{res.writeHead(404).end();}});
async function main(){
 await mkdir('artifacts',{recursive:true});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors:string[]=[],failed:string[]=[];page.on('pageerror',(e:Error)=>errors.push(e.message));page.on('response',(r:any)=>{if(r.status()>=400)failed.push(r.url());});
 const url=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
 const close=async()=>{if(await page.locator('#panel-overlay').evaluate((e:HTMLElement)=>e.classList.contains('open')))await page.locator('#panel-close').click();await page.waitForTimeout(350);};
 const pause=async(on:boolean)=>{await close();if((await page.locator('#btn-pause').evaluate((e:HTMLElement)=>e.classList.contains('active')))!==on)await page.locator('#btn-pause').click();};
 const save=async()=>{await close();await page.locator('#btn-save-local').click();return page.evaluate(()=>JSON.parse(localStorage.getItem('dao_thien_nguyen_v2')!));};
 const load=async(raw:string)=>{await page.goto(url);await page.evaluate((raw:string)=>localStorage.setItem('dao_thien_nguyen_v2',raw),raw);await page.reload();await page.locator('#btn-resume-game').click();await page.locator('.era-roadmap').waitFor();await pause(true);};
 try{
  await page.goto(url+'/character-gallery.html');await page.waitForFunction(()=>[...document.images].every(i=>i.complete&&i.naturalWidth>0));assert.equal(await page.locator('[data-era]').count(),30);await page.screenshot({path:'artifacts/characters-gallery-desktop.png'});for(const pose of ['walk','work','sleep','fight']){await page.locator('#pose').selectOption(pose);for(const direction of ['south','north','east','west']){await page.locator('#direction').selectOption(direction);await page.waitForFunction(()=>[...document.images].every(i=>i.complete&&i.naturalWidth>0));}}await page.locator('#pose').selectOption('idle');await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'artifacts/characters-gallery-mobile.png'});
  await page.setViewportSize({width:1440,height:1000});
  for(const [file,era] of [['faith-played-save.json','stone'],['management-targets-save.json','bronze'],['logistics-iron-save.json','iron']]){const prior=JSON.parse(await readFile('artifacts/'+file,'utf8'));await load(JSON.stringify(prior));await page.locator('#sb-population').click();await page.waitForTimeout(500);await page.waitForFunction(()=>[...document.querySelectorAll<HTMLImageElement>('.character-portrait')].every(i=>i.complete&&i.naturalWidth>0));const portraits=await page.locator('.pop-row .character-portrait').evaluateAll((images:HTMLImageElement[])=>images.map(i=>i.src));assert.equal(portraits.length,prior.island.npcs.filter((n:any)=>n.isAlive).length);assert(new Set(portraits).size>1);await page.screenshot({path:`artifacts/characters-${era}-people.png`});const initial=await save();assert.equal(initial.island.sharedFood,prior.island.sharedFood);assert.equal(initial.island.wood,prior.island.wood);if(prior.island.equipment)assert.deepEqual(initial.island.equipment,prior.island.equipment);else{assert(Object.values(initial.island.equipment.stock).every(v=>v===0));assert(Object.values(initial.island.equipment.crafted).every(v=>v===0));}
   await page.locator('#btn-zoom-in').click();await page.locator('#btn-zoom-in').click();await page.waitForTimeout(700);const first=await page.locator('#game-canvas').evaluate((c:HTMLCanvasElement)=>c.toDataURL());await page.waitForTimeout(700);assert.equal(await page.locator('#game-canvas').evaluate((c:HTMLCanvasElement)=>c.toDataURL()),first,'Paused character animation is frozen');await page.screenshot({path:`artifacts/characters-${era}-island.png`});await load(JSON.stringify(initial));await page.locator('#sb-population').click();await page.waitForTimeout(500);assert.deepEqual(await page.locator('.pop-row .character-portrait').evaluateAll((images:HTMLImageElement[])=>images.map(i=>i.src)),portraits,'Appearance survives save/reload');await close();
  }
  await page.setViewportSize({width:390,height:844});await page.locator('#sb-population').click();await page.waitForTimeout(500);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'artifacts/characters-people-mobile.png'});await close();await page.locator('.speed-btn[data-speed="2"]').click();await pause(false);await page.waitForTimeout(4000);await pause(true);const played=await save();assert.equal(played.island.npcs.filter((n:any)=>n.isAlive).length,25);await writeFile('artifacts/characters-played-save.json',JSON.stringify(played));assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);console.log('PASS character browser: 30 samples/poses/directions, stone/bronze/iron actual saves, custom portraits stable after reload, no resource/equipment mutation, pause freezes canvas, live simulation /25 alive, desktop/mobile no overflow/errors.');
 }catch(e){await page.screenshot({path:'artifacts/characters-ui-failure.png'});throw e;}finally{await browser.close();await new Promise<void>(r=>server.close(()=>r()));}
}
void main().catch(e=>{console.error(e);server.close();process.exitCode=1;});
