import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE??'playwright');const root=path.resolve('web');
const server=createServer(async(req,res)=>{const file=path.resolve(root,'.'+new URL(req.url??'/','http://localhost').pathname.replace(/\/$/,'/index.html'));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{res.setHeader('content-type',({'.html':'text/html','.css':'text/css','.js':'text/javascript','.svg':'image/svg+xml','.png':'image/png'} as Record<string,string>)[path.extname(file)]??'application/octet-stream');res.end(await readFile(file));}catch{res.writeHead(404).end();}});
async function main(){
 await mkdir('artifacts',{recursive:true});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors:string[]=[],failed:string[]=[];page.on('pageerror',(e:Error)=>errors.push(e.message));page.on('response',(r:any)=>{if(r.status()>=400)failed.push(r.url());});const url=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
 const close=async()=>{if(await page.locator('#building-inspector').isVisible())await page.locator('#bi-close').click();if(await page.locator('#panel-overlay').evaluate((e:HTMLElement)=>e.classList.contains('open')))await page.locator('#panel-close').click();};
 const pause=async(on:boolean)=>{await close();if((await page.locator('#btn-pause').evaluate((e:HTMLElement)=>e.classList.contains('active')))!==on)await page.locator('#btn-pause').click();};
 const save=async()=>{await close();await page.locator('#btn-save-local').click();return page.evaluate(()=>JSON.parse(localStorage.getItem('dao_thien_nguyen_v2')!));};
 const load=async(raw:string)=>{await page.goto(url);await page.evaluate((raw:string)=>localStorage.setItem('dao_thien_nguyen_v2',raw),raw);await page.reload();await page.locator('#btn-resume-game').click();await page.locator('.era-roadmap').waitFor();await pause(true);};
 const open=async()=>{await close();await page.locator('#sb-quests').click();await page.locator('.era-roadmap').waitFor();await page.waitForTimeout(300);};
 const inspect=async(id:string)=>{await close();await page.locator('#btn-build').click();await page.locator(`[data-inspect-building="${id}"]`).click();await page.locator('#building-inspector').waitFor({state:'visible'});await page.waitForTimeout(300);};
 try{
 const locked=JSON.parse(await readFile('artifacts/modern-factory-upgraded-save.json','utf8')),post=locked.island.buildings.find((b:any)=>b.type==='tradepost');await load(JSON.stringify(locked));await inspect(post.id);assert(await page.locator('[data-trade-offer="cloth_for_coal"]').isDisabled());assert.match(await page.locator('.bi-trade').innerText(),/Hợp đồng cung ứng/);
 const raw=await readFile('artifacts/modern-supply-contract-save.json','utf8');await load(raw);await open();assert.match(await page.locator('.modern-supply-goal').innerText(),/Đã ký hợp đồng/);await page.locator('.modern-supply-goal').scrollIntoViewIfNeeded();await page.screenshot({path:'artifacts/modern-supply-goal-desktop.png'});
 const before=await save();await inspect(post.id);assert(await page.locator('[data-trade-offer="cloth_for_coal"]').isEnabled());await page.locator('[data-trade-offer="cloth_for_coal"]').click();const mid=await save();assert.equal(mid.island.civilization.inventory.cloth,before.island.civilization.inventory.cloth-8);assert.equal(mid.island.civilization.inventory.coal,before.island.civilization.inventory.coal);assert.equal(mid.island.buildings.find((b:any)=>b.id===post.id).shipment.offerId,'cloth_for_coal');await load(JSON.stringify(mid));await inspect(post.id);await page.screenshot({path:'artifacts/modern-supply-shipment-desktop.png'});await page.locator('#bi-cancel-trade').click();const refunded=await save();assert.equal(refunded.island.civilization.inventory.cloth,before.island.civilization.inventory.cloth);assert.equal(refunded.island.civilization.inventory.coal,before.island.civilization.inventory.coal);
 await load(raw);const start=await save();await inspect(post.id);await page.locator('[data-trade-offer="cloth_for_coal"]').click();await pause(false);await page.locator('.speed-btn[data-speed="2"]').click();await inspect(post.id);await page.locator('#bi-cancel-trade').waitFor({state:'hidden',timeout:120000});await pause(true);const landed=await save();assert.equal(landed.island.civilization.completedTrades,start.island.civilization.completedTrades+1);assert.equal(landed.island.civilization.produced.coal,start.island.civilization.produced.coal);const total=(state:any)=>state.island.civilization.inventory.coal+state.island.buildings.reduce((v:number,b:any)=>v+(b.buffer?.input.coal??0)+(b.buffer?.output.coal??0),0)+state.island.npcs.reduce((v:number,n:any)=>v+(n.freight?.good==='coal'?n.freight.amount:0),0);assert.equal(total(landed),total(start)+10);assert.equal(landed.island.npcs.filter((n:any)=>n.isAlive).length,50);await inspect(post.id);await page.screenshot({path:'artifacts/modern-supply-landed-desktop.png'});
 await page.setViewportSize({width:390,height:844});await load(raw);await inspect(post.id);await page.locator('.bi-trade').scrollIntoViewIfNeeded();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'artifacts/modern-supply-trade-mobile.png'});await page.locator('[data-trade-offer="cloth_for_copper"]').click();const copper=await save();assert.equal(copper.island.civilization.inventory.cloth,JSON.parse(raw).island.civilization.inventory.cloth-12);assert.equal(copper.island.buildings.find((b:any)=>b.id===post.id).shipment.offerId,'cloth_for_copper');await load(JSON.stringify(copper));await inspect(post.id);assert.match(await page.locator('.bi-trade').innerText(),/12 Vải.*6 Đồng/);await page.locator('#bi-cancel-trade').click();assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);console.log('PASS browser supply: locked research, earned contract/goal, paid8 cloth with no instant coal, midship reload and full refund, physical +10 coal return/unchanged production/50 alive, mobile paid copper/reload/cancel, no errors/overflow.');
 }catch(e){await page.screenshot({path:'artifacts/modern-supply-ui-failure.png'});throw e;}finally{await browser.close();server.close();}
}
main().catch(e=>{console.error(e);process.exitCode=1;});
