import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE??'playwright');const root=path.resolve('web');
const server=createServer(async(req,res)=>{const file=path.resolve(root,'.'+new URL(req.url??'/','http://localhost').pathname.replace(/\/$/,'/index.html'));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{res.setHeader('content-type',({'.html':'text/html','.css':'text/css','.js':'text/javascript','.svg':'image/svg+xml','.png':'image/png'} as Record<string,string>)[path.extname(file)]??'application/octet-stream');res.end(await readFile(file));}catch{res.writeHead(404).end();}});
async function main(){
 await mkdir('artifacts',{recursive:true});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors:string[]=[],failed:string[]=[];page.on('pageerror',(e:Error)=>errors.push(e.message));page.on('response',(r:any)=>{if(r.status()>=400)failed.push(r.url());});const url=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
 const close=async()=>{if(await page.locator('#building-inspector').isVisible())await page.locator('#bi-close').click();if(await page.locator('#panel-overlay').evaluate((e:HTMLElement)=>e.classList.contains('open')))await page.locator('#panel-close').click();};
 const pause=async(on:boolean)=>{await close();if((await page.locator('#btn-pause').evaluate((e:HTMLElement)=>e.classList.contains('active')))!==on)await page.locator('#btn-pause').click();};
 const save=async()=>{await close();await page.locator('#btn-save-local').click();return page.evaluate(()=>JSON.parse(localStorage.getItem('dao_thien_nguyen_v2')!));};
 const load=async(raw:string)=>{await page.goto(url);await page.evaluate((raw:string)=>localStorage.setItem('dao_thien_nguyen_v2',raw),raw);await page.reload();await page.locator('#btn-resume-game').click();await page.locator('.era-roadmap').waitFor();await pause(true);};
 const open=async()=>{await close();await page.locator('#sb-quests').click();await page.locator('.era-roadmap').waitFor();await page.waitForTimeout(300);};
 const inspect=async(id:string)=>{await close();await page.locator('#btn-build').click();await page.locator(`[data-inspect-building="${id}"]`).click();await page.locator('#building-inspector').waitFor({state:'visible'});await page.waitForTimeout(300);};
 try{
 const raw=await readFile('artifacts/surveys-ready-save.json','utf8'),ready=JSON.parse(raw),outing=JSON.parse(await readFile('artifacts/surveys-outbound-save.json','utf8')),npcId=outing.island.surveys.active.npcId,site=ready.island.surveys.sites[0];await load(raw);const before=await save();await open();await page.locator('.survey-panel').scrollIntoViewIfNeeded();await page.locator('#survey-worker').selectOption(npcId);await page.screenshot({path:'artifacts/surveys-ready-desktop.png'});await page.locator(`[data-start-survey="${site.id}"]`).click();const paid=await save();assert.equal(paid.island.civilization.inventory.components,before.island.civilization.inventory.components-2);assert.equal(paid.island.civilization.inventory.cloth,before.island.civilization.inventory.cloth-2);assert.equal(paid.island.surveys.active.workTicks,0);await load(JSON.stringify(paid));await open();await page.locator('.survey-panel').scrollIntoViewIfNeeded();assert.match(await page.locator('.survey-panel').innerText(),/Đang đi/);await page.screenshot({path:'artifacts/surveys-outbound-desktop.png'});await page.locator('#cancel-survey').click();const refund=await save();assert.equal(refund.island.civilization.inventory.components,before.island.civilization.inventory.components);assert.equal(refund.island.civilization.inventory.cloth,before.island.civilization.inventory.cloth);
 await load(raw);await open();await page.locator('#survey-worker').selectOption(npcId);await page.locator(`[data-start-survey="${site.id}"]`).click();await pause(false);await page.locator('.speed-btn[data-speed="2"]').click();await open();await page.waitForFunction(()=>document.querySelector('.survey-panel')?.textContent?.includes('1/3 hồ sơ'),undefined,{timeout:120000});await pause(true);const done=await save();assert.equal(done.island.surveys.sites.filter((p:any)=>p.surveyed).length,1);assert.equal(done.island.npcs.filter((n:any)=>n.isAlive).length,50);assert(!done.island.surveys.active);await close();await page.locator('#btn-zoom-in').click();await page.screenshot({path:'artifacts/surveys-island.png'});await open();await page.locator('.survey-panel').scrollIntoViewIfNeeded();await page.screenshot({path:'artifacts/surveys-returned-desktop.png'});
 await page.setViewportSize({width:390,height:844});await load(JSON.stringify(done));await open();await page.locator('.survey-panel').scrollIntoViewIfNeeded();assert.match(await page.locator('.survey-panel').innerText(),/1\/3 hồ sơ/);await page.screenshot({path:'artifacts/surveys-mobile.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);console.log('PASS browser earned surveys: public choose/start paid2+2, paused progress/goods, midtrip reload/cancel exact refund, live field journey/returned1 file/50 alive, reload/mobile/no errors/overflow and chibi island image.');
 }catch(e){await page.screenshot({path:'artifacts/surveys-ui-failure.png'});throw e;}finally{await browser.close();server.close();}
}
main().catch(e=>{console.error(e);server.close();process.exitCode=1;});
