import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {decodeSave,encodeSave} from '../src/core/SaveSystem';
import {reserveEntityIds} from '../src/core/factory';
import {SimulationSession,type PlayerCommand} from '../src/core/SimulationSession';
import {ERAS} from '../src/core/civilization';
const d=decodeSave(readFileSync('artifacts/decisions-played-save.json','utf8')),s=d.island,c=s.civilization!;reserveEntityIds(s);const sim=new SimulationSession(s,d.map);let seq=0,trips=0,assembly=false;const initial=s.tick,produced=structuredClone(c.produced);
const send=(command:PlayerCommand)=>{const r=sim.submit({playerId:'technology-preparation',sequence:++seq,command});assert(r.accepted,JSON.stringify({command,r}));};
const until=(ok:()=>boolean,max=4000)=>{for(let i=0;i<max&&!ok();i++){sim.advanceTicks(1);if(assembly){if(c.produced.machineParts-produced.machineParts>=6&&proto.powerEnabled!==false)send({type:'set_power',buildingId:proto.id,enabled:false,priority:1});if(c.produced.components-produced.components>=30&&factory.powerEnabled!==false)send({type:'set_power',buildingId:factory.id,enabled:false,priority:2});}if(s.npcs.filter(n=>n.isAlive).length!==50){writeFileSync('artifacts/technology-survival-failure-save.json',encodeSave(s,d.map,d.config));throw new Error(JSON.stringify({food:s.sharedFood,tick:s.tick,dead:s.npcs.filter(n=>!n.isAlive).map(n=>({id:n.id,name:n.name,health:n.health,hunger:n.needs.hunger,message:n.laborMessage,position:n.position,rest:n.needs.rest})),buffers:s.buildings.filter(b=>b.buffer?.output.food).map(b=>({id:b.id,food:b.buffer?.output.food}))}));}}if(!ok())writeFileSync('artifacts/technology-preparation-waiting-save.json',encodeSave(s,d.map,d.config));assert(ok(),JSON.stringify({tick:s.tick,inventory:c.inventory,buildings:s.buildings.filter(b=>b.workers.length).map(b=>({id:b.id,type:b.type,buffer:b.buffer,message:b.workMessage}))}));};
const gen=s.buildings.find(b=>b.type==='steam_generator')!,lab=s.buildings.find(b=>b.type==='measurement_lab')!,factory=s.buildings.find(b=>b.type==='component_factory')!,proto=s.buildings.find(b=>b.type==='prototype_workshop')!,post=s.buildings.find(b=>b.type==='tradepost')!,iron=s.buildings.find(b=>b.type==='iron_smelter')!,steel=s.buildings.find(b=>b.type==='steelworks')!,flax=s.buildings.find(b=>b.type==='flax_field')!,weaver=s.buildings.find(b=>b.type==='weaver')!;
for(const b of [gen,lab,factory,proto])send({type:'set_power',buildingId:b.id,enabled:false,priority:1});assert.equal(lab.labPoweredTicks,0);
const crew=s.npcs.filter(n=>n.isAlive&&n.age>=18&&n.laborRole==='food'&&!n.guardDuty&&!s.buildings.some(b=>b.workers.includes(n.id))).slice(-5);assert.equal(crew.length,5);for(const n of crew)send({type:'assign_labor',npcId:n.id,role:'idle'});const [trader,miner,smith,farmer,tailor]=crew;
for(const [b,n] of [[post,trader],[iron,miner],[steel,smith],[flax,farmer],[weaver,tailor]] as const)send({type:'assign_worker',buildingId:b.id,npcId:n.id});
const trip=(offerId:string,fee:number,importGood:'coal'|'ironOre'|'copper')=>{until(()=>!trader.actionTarget&&!trader.cargo&&!trader.freight&&!trader.haulTask);const cloth=c.inventory.cloth,p=c.produced[importGood];send({type:'start_trade',buildingId:post.id,offerId});assert.equal(c.inventory.cloth,cloth-fee);until(()=>!post.shipment);assert.equal(c.produced[importGood],p);trips++;};
for(let i=0;i<22;i++){trip('cloth_for_ore',4,'ironOre');if(i<20)trip('cloth_for_coal',8,'coal');if(i<4)trip('cloth_for_copper',12,'copper');if(i===3)for(const [b,n] of [[flax,farmer],[weaver,tailor]] as const){send({type:'remove_worker',buildingId:b.id,npcId:n.id});send({type:'assign_labor',npcId:n.id,role:'food'});}}
until(()=>c.inventory.steel>=52);
// Preserve a real metal reserve by ending smelting before opening powered assembly.
for(const [b,n] of [[iron,miner],[steel,smith]] as const){send({type:'remove_worker',buildingId:b.id,npcId:n.id});send({type:'assign_labor',npcId:n.id,role:'haul'});}
while(c.inventory.coal<30)trip('cloth_for_coal',8,'coal');
for(const [b,n] of [[post,trader]] as const){send({type:'remove_worker',buildingId:b.id,npcId:n.id});send({type:'assign_labor',npcId:n.id,role:'food'});}
writeFileSync('artifacts/technology-materials-ready-save.json',encodeSave(s,d.map,d.config));
assembly=true;
send({type:'set_power',buildingId:factory.id,enabled:true,priority:2});send({type:'set_power',buildingId:proto.id,enabled:true,priority:1});send({type:'set_power',buildingId:gen.id,enabled:true,priority:1});
until(()=>c.inventory.components>=30&&c.inventory.machineParts>=6);
for(const b of [factory,proto,gen])send({type:'set_power',buildingId:b.id,enabled:false,priority:1});
assert(c.inventory.steel>=8);assert(c.produced.components-produced.components>=30);assert(c.produced.machineParts-produced.machineParts>=6);assert(c.produced.cloth>produced.cloth);assert(s.surveys!.sites[0].foundationComplete);assert.equal(c.era,'modern');assert.equal(c.anomalyBranch,undefined);assert.equal(lab.labPoweredTicks,0);const raw=encodeSave(s,d.map,d.config);assert.deepEqual(decodeSave(raw).island.civilization,c);writeFileSync('artifacts/technology-prepared-save.json',raw);
console.log(JSON.stringify({passed:true,kind:'earned technology prerequisites, no new branch goods or era unlock',ticks:s.tick-initial,paidTrips:trips,alive:s.npcs.filter(n=>n.isAlive).length,food:s.sharedFood,inventory:c.inventory,producedComponents:c.produced.components-produced.components,producedParts:c.produced.machineParts-produced.machineParts,producedCloth:c.produced.cloth-produced.cloth,labProof:lab.labPoweredTicks}));
