import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE??'playwright');const root=path.resolve('web');
const server=createServer(async(req,res)=>{const file=path.resolve(root,'.'+new URL(req.url??'/','http://localhost').pathname.replace(/\/$/,'/index.html'));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{res.setHeader('content-type',({'.html':'text/html','.css':'text/css','.js':'text/javascript','.svg':'image/svg+xml','.png':'image/png'} as Record<string,string>)[path.extname(file)]??'application/octet-stream');res.end(await readFile(file));}catch{res.writeHead(404).end();}});
async function main(){
 await mkdir('artifacts',{recursive:true});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors:string[]=[],failed:string[]=[];page.on('pageerror',(e:Error)=>errors.push(e.message));page.on('response',(r:any)=>{if(r.status()>=400)failed.push(r.url());});const url=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
 const close=async()=>{if(await page.locator('#building-inspector').isVisible())await page.locator('#bi-close').click();if(await page.locator('#panel-overlay').evaluate((e:HTMLElement)=>e.classList.contains('open')))await page.locator('#panel-close').click();};
 const pause=async(on:boolean)=>{await close();if((await page.locator('#btn-pause').evaluate((e:HTMLElement)=>e.classList.contains('active')))!==on)await page.locator('#btn-pause').click();};
 const save=async()=>{await close();await page.locator('#btn-save-local').click();return page.evaluate(()=>JSON.parse(localStorage.getItem('dao_thien_nguyen_v2')!));};
 const load=async(raw:string)=>{await page.goto(url);await page.evaluate((raw:string)=>localStorage.setItem('dao_thien_nguyen_v2',raw),raw);await page.reload();await page.locator('#btn-resume-game').click();await page.locator('.era-roadmap').waitFor();await pause(true);};
 const open=async()=>{await close();await page.locator('#sb-quests').click();await page.locator('.era-roadmap').waitFor();await page.waitForTimeout(300);};
 const inspect=async(id:string)=>{await close();await page.locator('#btn-build').click();await page.locator(`[data-inspect-building="${id}"]`).click();await page.locator('#building-inspector').waitFor({state:'visible'});await page.waitForTimeout(300);};
 try{
 const ready=JSON.parse(await readFile('artifacts/modern-ready-save.json','utf8'));await load(JSON.stringify(ready));const initial=await save();await open();assert(await page.locator('#btn-develop-era').isEnabled());await page.locator('#btn-develop-era').click();assert.match(await page.locator('#era-transition-status').innerText(),/0\/50/);const paid=await save();for(const [g,a] of Object.entries({steel:30,cutStone:40,cloth:20}))assert.equal(paid.island.civilization.inventory[g],initial.island.civilization.inventory[g]-a);assert.equal(paid.island.sharedFood,initial.island.sharedFood);await open();await page.locator('.modern-preparation').scrollIntoViewIfNeeded();await page.screenshot({path:'artifacts/modern-public-investment.png'});for(const b of paid.island.buildings.filter((b:any)=>['prototype_workshop','steam_generator'].includes(b.type)))await page.locator(`[data-power-toggle="${b.id}"]`).click();await pause(false);await page.locator('.speed-btn[data-speed="2"]').click();await open();await page.locator('.modern-industry-goal').waitFor({timeout:60000});await pause(true);const transitioned=await save();assert.equal(transitioned.island.civilization.era,'modern');assert.equal(transitioned.island.npcs.filter((n:any)=>n.isAlive).length,50);await open();await page.locator('.modern-industry-goal').scrollIntoViewIfNeeded();await page.screenshot({path:'artifacts/modern-public-era.png'});
 const played=JSON.parse(await readFile('artifacts/modern-factory-played-save.json','utf8')),plant=played.island.buildings.find((b:any)=>b.type==='component_factory'),builder=played.island.npcs.find((n:any)=>n.isAlive&&n.age>=18&&n.laborRole==='idle'&&!n.guardDuty&&!played.island.buildings.some((b:any)=>b.workers.includes(n.id)));assert(builder);await load(JSON.stringify(played));await open();await page.locator(`[data-power-building="${plant.id}"]`).scrollIntoViewIfNeeded();await page.waitForFunction(()=>[...document.querySelectorAll<HTMLImageElement>('.power-building img')].every(i=>i.complete&&i.naturalWidth>0));await page.screenshot({path:'artifacts/modern-factory-power-desktop.png'});await page.locator(`[data-power-priority="${plant.id}"]`).selectOption('0');const priority=await save();assert.equal(priority.island.buildings.find((b:any)=>b.id===plant.id).powerPriority,0);assert.deepEqual(priority.island.civilization.inventory,played.island.civilization.inventory);
 await inspect(plant.id);assert.match(await page.locator('.bi-level').innerText(),/Hiện Đại/);assert.match(await page.locator('#building-inspector').innerText(),/Linh kiện|linh kiện/);await page.locator('#bi-upgrade').click();const upgrade=await save();assert.equal(upgrade.island.civilization.inventory.components,played.island.civilization.inventory.components-6);assert.equal(upgrade.island.buildings.find((b:any)=>b.id===plant.id).upgrade.targetLevel,2);await writeFile('artifacts/modern-factory-browser-mid-save.json',JSON.stringify(upgrade));await load(JSON.stringify(upgrade));await inspect(plant.id);await page.locator('#bi-select-npc').selectOption(builder.id);await page.locator('#bi-btn-assign').click();await pause(false);await inspect(plant.id);await page.waitForFunction(()=>document.querySelector('#building-inspector')?.textContent?.includes('Cấp 2 / 3'),undefined,{timeout:60000});await pause(true);const upgraded=await save();assert.equal(upgraded.island.buildings.find((b:any)=>b.id===plant.id).level,2);assert.equal(upgraded.island.npcs.filter((n:any)=>n.isAlive).length,50);await inspect(plant.id);await page.screenshot({path:'artifacts/modern-factory-upgrade-desktop.png'});await close();await page.locator('#btn-zoom-in').click();await page.screenshot({path:'artifacts/modern-factory-island.png'});
 await page.setViewportSize({width:390,height:844});await open();await page.locator('.modern-industry-goal').scrollIntoViewIfNeeded();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'artifacts/modern-factory-mobile.png'});await page.locator(`[data-power-toggle="${plant.id}"]`).click();const off=await save();assert.equal(off.island.buildings.find((b:any)=>b.id===plant.id).powerEnabled,false);await load(JSON.stringify(off));await open();assert.match(await page.locator(`[data-power-building="${plant.id}"]`).innerText(),/Đã tắt/);assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);console.log('PASS browser public chain: actual ready village/button/paid fee/50 live steps/Modern; earned factory textures, paused priorities/no costs, paid6-component upgrade/reload/physical builder/level2, 50 alive, mobile off/reload and no errors/overflow.');
 }catch(e){await page.screenshot({path:'artifacts/modern-chain-ui-failure.png'});throw e;}finally{await browser.close();server.close();}
}
main().catch(e=>{console.error(e);process.exitCode=1;});
