import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE??'playwright');const root=path.resolve('web');
const server=createServer(async(req,res)=>{const file=path.resolve(root,'.'+new URL(req.url??'/','http://localhost').pathname.replace(/\/$/,'/index.html'));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{res.setHeader('content-type',({'.html':'text/html','.css':'text/css','.js':'text/javascript','.svg':'image/svg+xml','.png':'image/png'} as Record<string,string>)[path.extname(file)]??'application/octet-stream');res.end(await readFile(file));}catch{res.writeHead(404).end();}});
async function main(){
 await mkdir('artifacts',{recursive:true});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors:string[]=[],failed:string[]=[];page.on('pageerror',(e:Error)=>errors.push(e.message));page.on('response',(r:any)=>{if(r.status()>=400)failed.push(r.url());});const url=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
 const close=async()=>{if(await page.locator('#building-inspector').isVisible())await page.locator('#bi-close').click();if(await page.locator('#panel-overlay').evaluate((e:HTMLElement)=>e.classList.contains('open')))await page.locator('#panel-close').click();};
 const pause=async(on:boolean)=>{await close();if((await page.locator('#btn-pause').evaluate((e:HTMLElement)=>e.classList.contains('active')))!==on)await page.locator('#btn-pause').click();};
 const save=async()=>{await close();await page.locator('#btn-save-local').click();return page.evaluate(()=>JSON.parse(localStorage.getItem('dao_thien_nguyen_v2')!));};
 const load=async(raw:string)=>{await page.goto(url);await page.evaluate((raw:string)=>localStorage.setItem('dao_thien_nguyen_v2',raw),raw);await page.reload();await page.locator('#btn-resume-game').click();await page.locator('.era-roadmap').waitFor();await pause(true);};
 const open=async()=>{await close();await page.locator('#sb-quests').click();await page.locator('.era-roadmap').waitFor();await page.waitForTimeout(300);};
 const inspect=async(id:string)=>{await close();await page.locator('#btn-build').click();await page.locator(`[data-inspect-building="${id}"]`).click();await page.locator('#building-inspector').waitFor({state:'visible'});await page.waitForTimeout(300);};


 try{
 const raw=await readFile('artifacts/eldritch-adaptation-ready-save.json','utf8'),ready=JSON.parse(raw),lab=ready.island.buildings.find((b:any)=>b.type==='measurement_lab'),gen=ready.island.buildings.find((b:any)=>b.type==='steam_generator'),person=JSON.parse(await readFile('artifacts/eldritch-adaptation-equipped-save.json','utf8')).island.npcs.find((n:any)=>n.adaptation),mentor=lab.workers[0];await load(raw);const initial=await save();await open();await page.locator(`[data-adapt-manage="${lab.id}"]`).click();await page.locator(`[data-remove-worker="${mentor}"]`).click();await close();await open();assert.match(await page.locator('[data-adapt-staff]').innerText(),/ch\u01b0a c\u00f3 th\u1ee3/);await page.locator(`[data-adapt-person="${person.id}"] summary`).click();assert(await page.locator(`[data-adapt-start="${person.id}"][data-adapt-mode="apply"]`).isDisabled());const noStaff=await save();assert.equal(noStaff.island.civilization.inventory.biomatter,initial.island.civilization.inventory.biomatter);await open();await page.locator(`[data-adapt-manage="${lab.id}"]`).click();await page.locator('#bi-select-npc').selectOption(mentor);await page.locator('#bi-btn-assign').click();await close();await open();await page.locator('#adapt-lab-toggle').click();await page.locator('#adapt-generator-toggle').click();assert.match(await page.locator('[data-adapt-power]').innerText(),/\u0110\u1ee7 2/);await page.locator('.adaptation-readiness').scrollIntoViewIfNeeded();await page.screenshot({path:'artifacts/adaptation-preparation-desktop.png'});await page.locator(`[data-adapt-person="${person.id}"] summary`).click();await page.locator(`[data-adapt-start="${person.id}"][data-adapt-mode="apply"]`).click();const paid=await save();assert.equal(paid.island.civilization.inventory.biomatter,initial.island.civilization.inventory.biomatter-2);await open();assert(await page.locator('#adapt-lab').isDisabled());await page.locator(`[data-adapt-manage="${lab.id}"]`).click();assert.equal(await page.locator(`#bi-select-npc option[value="${person.id}"]`).count(),0);await close();await open();await page.locator('#cancel-adaptation').click();const refund=await save();assert.equal(refund.island.civilization.inventory.biomatter,initial.island.civilization.inventory.biomatter);await load(await readFile('artifacts/augmentation-played-save.json','utf8'));await open();assert.match(await page.locator('[data-adapt-stock]').innerText(),/0\/1/);const apply=page.locator('[data-adapt-mode="apply"]');assert((await apply.count())>0);for(let i=0;i<await apply.count();i++)assert(await apply.nth(i).isDisabled());assert(await page.locator('[data-decision-key="adapt-not-ready"]').isVisible());assert.equal(await page.locator('[data-decision-key="adapt-not-ready"]').evaluate((e:HTMLDetailsElement)=>e.open),false);
 await load(await readFile('artifacts/augmentation-empty-save.json','utf8'));await open();assert.equal(await page.locator('[data-adapt-upkeep]').count(),1);
 await page.setViewportSize({width:390,height:844});await load(await readFile('artifacts/eldritch-adaptation-played-save.json','utf8'));await open();await page.locator('.adaptation-readiness').scrollIntoViewIfNeeded();await page.screenshot({path:'artifacts/adaptation-preparation-mobile.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.locator('[data-decision-key="adapt-not-ready"] summary').click();assert((await page.locator('[data-decision-key="adapt-not-ready"] p').count())>0);assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);console.log('PASS browser readiness: no staff/stock disabled before fee, public manage/assign/power, exact apply/cancel, active lab locked/actor excluded from assignment, missing materials/no debit, collapsed not-ready reasons/mobile/no errors.');
 }catch(e){console.error(e);try{await page.screenshot({path:'artifacts/adaptation-readiness-failure.png'});}catch{}throw e;}finally{await browser.close();server.close();}
}
main().catch(e=>{console.error(e);server.close();process.exitCode=1;});
