import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE??'playwright');const root=path.resolve('web');
const server=createServer(async(req,res)=>{const file=path.resolve(root,'.'+new URL(req.url??'/','http://localhost').pathname.replace(/\/$/,'/index.html'));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{res.setHeader('content-type',({'.html':'text/html','.css':'text/css','.js':'text/javascript','.svg':'image/svg+xml','.png':'image/png'} as Record<string,string>)[path.extname(file)]??'application/octet-stream');res.end(await readFile(file));}catch{res.writeHead(404).end();}});
async function main(){
 await mkdir('artifacts',{recursive:true});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors:string[]=[],failed:string[]=[];page.on('pageerror',(e:Error)=>errors.push(e.message));page.on('response',(r:any)=>{if(r.status()>=400)failed.push(r.url());});const url=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
 const close=async()=>{if(await page.locator('#building-inspector').isVisible())await page.locator('#bi-close').click();if(await page.locator('#panel-overlay').evaluate((e:HTMLElement)=>e.classList.contains('open')))await page.locator('#panel-close').click();};
 const pause=async(on:boolean)=>{await close();if((await page.locator('#btn-pause').evaluate((e:HTMLElement)=>e.classList.contains('active')))!==on)await page.locator('#btn-pause').click();};
 const save=async()=>{await close();await page.locator('#btn-save-local').click();return page.evaluate(()=>JSON.parse(localStorage.getItem('dao_thien_nguyen_v2')!));};
 const load=async(raw:string)=>{await page.goto(url);await page.evaluate((raw:string)=>localStorage.setItem('dao_thien_nguyen_v2',raw),raw);await page.reload();await page.locator('#btn-resume-game').click();await page.locator('.era-roadmap').waitFor();await pause(true);};
 const open=async()=>{await close();await page.locator('#sb-quests').click();await page.locator('.era-roadmap').waitFor();await page.waitForTimeout(300);};
 const inspect=async(id:string)=>{await close();await page.locator('#btn-build').click();await page.locator(`[data-inspect-building="${id}"]`).click();await page.locator('#building-inspector').waitFor({state:'visible'});await page.waitForTimeout(300);};
 try{
 const raw=await readFile('artifacts/relic-channel-played-save.json','utf8'),ready=JSON.parse(raw),extractor=ready.island.buildings.find((b:any)=>b.type==='relic_extractor');await load(raw);await inspect(extractor.id);assert.match(await page.locator('.bi-level').innerText(),/Cấp 1 \/ 1.*mẫu Quỷ Dị/);await page.waitForFunction(()=>[...document.querySelectorAll<HTMLImageElement>('.bi-texture')].every(i=>i.complete&&i.naturalWidth>0));await page.screenshot({path:'artifacts/relic-extractor-desktop.png'});await page.locator('#bi-relic-toggle').click();const enabled=await save();assert.equal(enabled.island.buildings.find((b:any)=>b.id===extractor.id).relicEnabled,true);await load(JSON.stringify(enabled));await pause(false);await page.locator('.speed-btn[data-speed="2"]').click();await page.waitForTimeout(16000);await pause(true);const harvested=await save();assert(harvested.island.civilization.produced.relicBone>ready.island.civilization.produced.relicBone);assert(harvested.island.civilization.produced.bloodstone>ready.island.civilization.produced.bloodstone);assert.equal(harvested.island.npcs.filter((n:any)=>n.isAlive).length,50);
 const workshopRaw=await readFile('artifacts/biomatter-ready-save.json','utf8'),workshopState=JSON.parse(workshopRaw),workshop=workshopState.island.buildings.find((b:any)=>b.type==='biomatter_workshop');await load(workshopRaw);await inspect(workshop.id);assert.match(await page.locator('.bi-state').innerText(),/Đủ 2 công suất/);await page.screenshot({path:'artifacts/biomatter-workshop-desktop.png'});await pause(false);await page.locator('.speed-btn[data-speed="2"]').click();await page.waitForTimeout(16000);await pause(true);const made=await save();assert(made.island.civilization.produced.biomatter>workshopState.island.civilization.produced.biomatter);
 const qRaw=await readFile('artifacts/quarantine-ready-save.json','utf8'),qState=JSON.parse(qRaw),q=qState.island.buildings.find((b:any)=>b.type==='quarantine');await load(qRaw);await inspect(q.id);await page.screenshot({path:'artifacts/quarantine-desktop.png'});await open();await page.locator(`[data-power-toggle="${q.id}"]`).click();const off=await save();await load(JSON.stringify(off));await pause(false);await page.locator('.speed-btn[data-speed="2"]').click();await page.waitForTimeout(8000);await pause(true);const held=await save();assert.equal(held.island.buildings.find((b:any)=>b.id===q.id).quarantineCareTicks??0,q.quarantineCareTicks??0);assert.equal(held.island.buildings.find((b:any)=>b.id===q.id).quarantineFuelTicks??0,q.quarantineFuelTicks??0);await open();await page.locator(`[data-power-toggle="${q.id}"]`).click();await pause(false);await page.waitForTimeout(16000);await pause(true);const cared=await save();assert((cared.island.buildings.find((b:any)=>b.id===q.id).quarantineCareTicks??0)>(q.quarantineCareTicks??0));assert.equal(cared.island.npcs.filter((n:any)=>n.isAlive).length,50);assert.equal(cared.island.civilization.era,'modern');assert.equal(cared.island.civilization.anomalyBranch,undefined);
 await page.setViewportSize({width:390,height:844});await load(await readFile('artifacts/eldritch-played-save.json','utf8'));await open();await page.locator('.eldritch-panel h3').scrollIntoViewIfNeeded();assert.match(await page.locator('.eldritch-panel').innerText(),/chưa chốt nhánh/);await page.screenshot({path:'artifacts/eldritch-mobile.png'});await inspect(q.id);await page.screenshot({path:'artifacts/quarantine-mobile.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);console.log('PASS browser alternate earned eldritch: extraction own texture/public pause-resume-save/live2outputs, live biomatter, quarantine outage hold/save/resume/livecare,50alive/mobile/noerrors/branch locked.');
 }catch(e){console.error(e);try{await page.screenshot({path:'artifacts/eldritch-ui-failure.png'});}catch{}throw e;}finally{await browser.close();server.close();}
}
main().catch(e=>{console.error(e);server.close();process.exitCode=1;});
