import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE??'playwright');const root=path.resolve('web');
const server=createServer(async(req,res)=>{const file=path.resolve(root,'.'+new URL(req.url??'/','http://localhost').pathname.replace(/\/$/,'/index.html'));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{res.setHeader('content-type',({'.html':'text/html','.css':'text/css','.js':'text/javascript','.svg':'image/svg+xml','.png':'image/png'} as Record<string,string>)[path.extname(file)]??'application/octet-stream');res.end(await readFile(file));}catch{res.writeHead(404).end();}});
async function main(){
 await mkdir('artifacts',{recursive:true});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors:string[]=[],failed:string[]=[];page.on('pageerror',(e:Error)=>errors.push(e.message));page.on('response',(r:any)=>{if(r.status()>=400)failed.push(r.url());});const url=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
 const close=async()=>{if(await page.locator('#building-inspector').isVisible())await page.locator('#bi-close').click();if(await page.locator('#panel-overlay').evaluate((e:HTMLElement)=>e.classList.contains('open')))await page.locator('#panel-close').click();};
 const pause=async(on:boolean)=>{await close();if((await page.locator('#btn-pause').evaluate((e:HTMLElement)=>e.classList.contains('active')))!==on)await page.locator('#btn-pause').click();};
 const save=async()=>{await close();await page.locator('#btn-save-local').click();return page.evaluate(()=>JSON.parse(localStorage.getItem('dao_thien_nguyen_v2')!));};
 const load=async(raw:string)=>{await page.goto(url);await page.evaluate((raw:string)=>localStorage.setItem('dao_thien_nguyen_v2',raw),raw);await page.reload();await page.locator('#btn-resume-game').click();await page.locator('.era-roadmap').waitFor();await pause(true);};
 const open=async()=>{await close();await page.locator('#sb-quests').click();await page.locator('.era-roadmap').waitFor();await page.waitForTimeout(300);};
 const inspect=async(id:string)=>{await close();await page.locator('#btn-build').click();await page.locator(`[data-inspect-building="${id}"]`).click();await page.locator('#building-inspector').waitFor({state:'visible'});await page.waitForTimeout(300);};




 try{
 const route=JSON.parse(await readFile('artifacts/exploration-route.json','utf8')),id=route.npcId;
 await load(await readFile('artifacts/exploration-precraft-save.json','utf8'));await open();await page.locator('#explorer-choice').selectOption(id);const before=await save();await open();await page.locator('#craft-exploration-torch').click();const paid=await save();assert.equal(paid.island.wood,before.island.wood-1);assert.equal(paid.island.exploration.torchOrder.npcId,id);
 await pause(false);await open();await page.waitForFunction(()=>document.querySelector('.exploration-torch')?.textContent?.includes('Kho: 1 đuốc'),{},{timeout:30000});await pause(true);await open();await page.locator('#take-exploration-torch').click();await pause(false);await open();await page.waitForFunction(()=>document.querySelector('.exploration-torch')?.textContent?.includes('Đang cầm:'),{},{timeout:30000});await pause(true);const took=await save();assert.equal(took.island.exploration.torchCrafted,1);assert.equal(took.island.exploration.torchStock.length,0);assert(took.island.npcs.find((n:any)=>n.id===id).torch.fuel>0);
 if(took.island.tick%10!==0){await pause(false);await page.waitForFunction(()=>document.querySelector('#world-time')?.textContent?.includes('06:00'),{},{timeout:30000});await pause(true);}
 const ready=await save();await writeFile('artifacts/exploration-browser-ready-save.json',JSON.stringify(ready));await open();await page.locator('#explorer-choice').selectOption(id);await page.screenshot({path:'artifacts/exploration-preparation-desktop.png'});await page.locator('#place-explore-marker').click();
 const box=await page.locator('#game-canvas').boundingBox();assert(box);const z=Math.min(box.width/(ready.map.width*16),box.height/(ready.map.height*16))*.88;await page.locator('#game-canvas').click({position:{x:box.width/2+(route.target.x-ready.map.width/2+.5)*16*z,y:box.height/2+(route.target.y-ready.map.height/2+.5)*16*z}});await page.locator('#recall-explorer').waitFor();const started=await save();assert(started.island.exploration.active);assert.deepEqual(started.island.exploration.active.target,route.target);const fogBefore=started.island.exploration.discovered.values.length;
 await pause(false);await open();await page.waitForFunction(()=>/đang khám phá|đang về lửa trại/.test(document.querySelector('[data-explore-message]')?.textContent??''),{},{timeout:20000});await pause(true);const midway=await save();assert(midway.island.exploration.active,'save while physically travelling');assert.notDeepEqual(midway.island.npcs.find((n:any)=>n.id===id).position,ready.island.npcs.find((n:any)=>n.id===id).position);await writeFile('artifacts/exploration-midtrip-save.json',JSON.stringify(midway));await page.screenshot({path:'artifacts/exploration-midtrip-world.png'});
 await load(JSON.stringify(midway));const restored=await save();assert.deepEqual(restored.island.exploration.active,midway.island.exploration.active);assert.equal(restored.island.exploration.discovered.values.length,midway.island.exploration.discovered.values.length);await pause(false);await open();await page.waitForFunction(()=>document.querySelector('[data-explore-done]')?.getAttribute('data-explore-done')==='3',{},{timeout:30000});await pause(true);const finished=await save();assert(!finished.island.exploration.active);assert.equal(finished.island.exploration.completed,1);assert(finished.island.exploration.discovered.values.length>fogBefore);assert.equal(finished.island.npcs.filter((n:any)=>n.isAlive).length,8);assert.equal(finished.island.npcs.find((n:any)=>n.id===id).laborRole,ready.island.npcs.find((n:any)=>n.id===id).laborRole);await writeFile('artifacts/exploration-played-save.json',JSON.stringify(finished));await open();await page.screenshot({path:'artifacts/exploration-complete-desktop.png'});
 const fuel=finished.island.npcs.find((n:any)=>n.id===id).torch.fuel;await pause(false);await open();await page.waitForFunction((fuel:number)=>{const text=document.querySelector('.exploration-torch')?.textContent??'',m=text.match(/Đang cầm: (\d+)\/30/);return m&&Number(m[1])<fuel;},fuel,{timeout:30000});await pause(true);const night=await save();assert(night.island.npcs.find((n:any)=>n.id===id).torch.fuel<fuel);assert.equal(night.island.exploration.torchCrafted,1);await page.screenshot({path:'artifacts/exploration-night-world.png'});
 await page.setViewportSize({width:390,height:844});await open();await page.locator('.exploration-panel').scrollIntoViewIfNeeded();await page.screenshot({path:'artifacts/exploration-mobile.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);await writeFile('artifacts/exploration-browser-result.json',JSON.stringify({alive:8,completed:1,mission:finished.island.exploration.mission,discoveredBefore:fogBefore,discoveredAfter:finished.island.exploration.discovered.values.length,torchCrafted:1,woodPaid:1,fuelBeforeNight:fuel,fuelAfterNight:night.island.npcs.find((n:any)=>n.id===id).torch.fuel,food:finished.island.sharedFood,midtripReload:true,mobile:true,errors},null,2));console.log('PASS one browser earned playthrough: public1wood craft/physical take/map marker/actual walking/fog/food discovery/return/3mission steps, midtrip save-reload, night torch fuel,8alive/mobile/no errors.');
 }catch(error){try{await page.screenshot({path:'artifacts/exploration-ui-failure.png'});await page.locator('#btn-save-local').click();const raw=await page.evaluate(()=>localStorage.getItem('dao_thien_nguyen_v2'));if(raw)await writeFile('artifacts/exploration-ui-failure-save.json',raw);}catch{}throw error;}finally{await browser.close();server.close();}
}
main().catch(e=>{console.error(e);server.close();process.exitCode=1;});
