import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {decodeSave,encodeSave} from '../src/core/SaveSystem';
import {SimulationSession,type PlayerCommand} from '../src/core/SimulationSession';
const d=decodeSave(readFileSync('artifacts/care-played-save.json','utf8')),s=d.island,c=s.civilization!,sim=new SimulationSession(s,d.map);let seq=0;const initial=s.tick,foodStart=s.sharedFood,goodsStart=c.inventory.components,production=c.produced.components;
const send=(command:PlayerCommand)=>assert(sim.submit({playerId:'care-industry',sequence:++seq,command}).accepted,JSON.stringify(command));
const until=(ok:()=>boolean,max=500)=>{for(let i=0;i<max&&!ok();i++){sim.advanceTicks(1);assert.equal(s.npcs.filter(n=>n.isAlive).length,50);}assert(ok(),JSON.stringify({food:s.sharedFood,power:s.power,inventory:c.inventory}));};
const factory=s.buildings.find(b=>b.type==='component_factory')!,gen=s.buildings.find(b=>b.type==='steam_generator')!,worker=s.npcs.find(n=>n.isAlive&&n.position&&n.age>=18&&!n.guardDuty&&!n.researching&&!s.buildings.some(b=>b.workers.includes(n.id)))!;
send({type:'assign_worker',buildingId:factory.id,npcId:worker.id});send({type:'set_power',buildingId:factory.id,enabled:true,priority:2});send({type:'set_power',buildingId:gen.id,enabled:true,priority:1});until(()=>c.produced.components>=production+6);send({type:'set_power',buildingId:factory.id,enabled:false,priority:2});until(()=>c.inventory.components>=goodsStart+6);send({type:'remove_worker',buildingId:factory.id,npcId:worker.id});send({type:'assign_labor',npcId:worker.id,role:'food'});send({type:'set_power',buildingId:gen.id,enabled:false,priority:1});let minimum=s.sharedFood;for(let i=0;i<300;i++){sim.advanceTicks(1);minimum=Math.min(minimum,s.sharedFood);assert.equal(s.npcs.filter(n=>n.isAlive).length,50);assert(s.sharedFood>100);}
assert.equal(c.produced.components,production+6);const raw=encodeSave(s,d.map,d.config);decodeSave(raw);writeFileSync('artifacts/care-industry-stable-save.json',raw);console.log(JSON.stringify({passed:true,earned:true,steps:s.tick-initial,alive:50,actualNewComponents:6,deliveredNewComponents:c.inventory.components-goodsStart,foodStart,foodMinimum:minimum,foodEnd:s.sharedFood,maintenanceDays:30,continuousProductionClaim:false}));
