import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE??'playwright');const root=path.resolve('web');
const server=createServer(async(req,res)=>{const file=path.resolve(root,'.'+new URL(req.url??'/','http://localhost').pathname.replace(/\/$/,'/index.html'));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{res.setHeader('content-type',({'.html':'text/html','.css':'text/css','.js':'text/javascript','.svg':'image/svg+xml','.png':'image/png'} as Record<string,string>)[path.extname(file)]??'application/octet-stream');res.end(await readFile(file));}catch{res.writeHead(404).end();}});
async function main(){
 await mkdir('artifacts',{recursive:true});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors:string[]=[],failed:string[]=[];page.on('pageerror',(e:Error)=>errors.push(e.message));page.on('response',(r:any)=>{if(r.status()>=400)failed.push(r.url());});const url=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
 const close=async()=>{if(await page.locator('#building-inspector').isVisible())await page.locator('#bi-close').click();if(await page.locator('#panel-overlay').evaluate((e:HTMLElement)=>e.classList.contains('open')))await page.locator('#panel-close').click();};
 const pause=async(on:boolean)=>{await close();if((await page.locator('#btn-pause').evaluate((e:HTMLElement)=>e.classList.contains('active')))!==on)await page.locator('#btn-pause').click();};
 const save=async()=>{await close();await page.locator('#btn-save-local').click();return page.evaluate(()=>JSON.parse(localStorage.getItem('dao_thien_nguyen_v2')!));};
 const load=async(raw:string)=>{await page.goto(url);await page.evaluate((raw:string)=>localStorage.setItem('dao_thien_nguyen_v2',raw),raw);await page.reload();await page.locator('#btn-resume-game').click();await page.locator('.era-roadmap').waitFor();await pause(true);};
 const open=async()=>{await close();await page.locator('#sb-quests').click();await page.locator('.era-roadmap').waitFor();await page.waitForTimeout(300);};
 const inspect=async(id:string)=>{await close();await page.locator('#btn-build').click();await page.locator(`[data-inspect-building="${id}"]`).click();await page.locator('#building-inspector').waitFor({state:'visible'});await page.waitForTimeout(300);};
 try{
 const raw=await readFile('artifacts/technology-materials-ready-save.json','utf8'),ready=JSON.parse(raw),gen=ready.island.buildings.find((b:any)=>b.type==='steam_generator'),factory=ready.island.buildings.find((b:any)=>b.type==='component_factory'),proto=ready.island.buildings.find((b:any)=>b.type==='prototype_workshop');await load(raw);const before=await save();await open();await page.locator(`[data-power-toggle="${factory.id}"]`).click();await page.locator(`[data-power-toggle="${gen.id}"]`).click();assert.match(await page.locator('.analysis-panel').innerText(),/Dị Tượng vẫn khóa/);await pause(false);await page.locator('.speed-btn[data-speed="2"]').click();await page.waitForTimeout(16000);await pause(true);const made=await save();assert(made.island.civilization.produced.components>before.island.civilization.produced.components);assert.equal(made.island.npcs.filter((n:any)=>n.isAlive).length,50);assert.equal(made.island.buildings.find((b:any)=>b.id===proto.id).powerEnabled,false);await inspect(factory.id);await page.waitForFunction(()=>[...document.querySelectorAll<HTMLImageElement>('.bi-texture')].every(i=>i.complete&&i.naturalWidth>0));await page.screenshot({path:'artifacts/technology-preparation-factory.png'});
 await page.setViewportSize({width:390,height:844});await load(await readFile('artifacts/technology-prepared-save.json','utf8'));await open();await page.locator('.analysis-panel h3').scrollIntoViewIfNeeded();assert.match(await page.locator('.analysis-panel').innerText(),/Đã hoàn tất hồ sơ nền tảng/);assert.match(await page.locator('.analysis-panel').innerText(),/0.0\/5 ngày/);await page.screenshot({path:'artifacts/technology-preparation-mobile.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);console.log('PASS browser earned prerequisites: public factory/generator toggle/live components production/50 alive/prototype OFF, own factory texture, mobile funded foundation survives power-proof reset/Anomaly locked/no errors/overflow.');
 }catch(e){console.error(e);try{await page.screenshot({path:'artifacts/technology-preparation-ui-failure.png'});}catch{}throw e;}finally{await browser.close();server.close();}
}
main().catch(e=>{console.error(e);server.close();process.exitCode=1;});
