import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE??'playwright');const root=path.resolve('web');
const server=createServer(async(req,res)=>{const file=path.resolve(root,'.'+new URL(req.url??'/','http://localhost').pathname.replace(/\/$/,'/index.html'));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{res.setHeader('content-type',({'.html':'text/html','.css':'text/css','.js':'text/javascript','.svg':'image/svg+xml','.png':'image/png'} as Record<string,string>)[path.extname(file)]??'application/octet-stream');res.end(await readFile(file));}catch{res.writeHead(404).end();}});
async function main(){
 await mkdir('artifacts',{recursive:true});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors:string[]=[],failed:string[]=[];page.on('pageerror',(e:Error)=>errors.push(e.message));page.on('response',(r:any)=>{if(r.status()>=400)failed.push(r.url());});
 const url=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
 const close=async()=>{if(await page.locator('#panel-overlay').evaluate((e:HTMLElement)=>e.classList.contains('open')))await page.locator('#panel-close').click();await page.waitForTimeout(350);};
 const pause=async(on:boolean)=>{await close();if((await page.locator('#btn-pause').evaluate((e:HTMLElement)=>e.classList.contains('active')))!==on)await page.locator('#btn-pause').click();};
 const save=async()=>{await close();await page.locator('#btn-save-local').click();return page.evaluate(()=>JSON.parse(localStorage.getItem('dao_thien_nguyen_v2')!));};
 const load=async(raw:string)=>{await page.goto(url);await page.evaluate((raw:string)=>localStorage.setItem('dao_thien_nguyen_v2',raw),raw);await page.reload();await page.locator('#btn-resume-game').click();await page.locator('.era-roadmap').waitFor();await pause(true);};
 try{
  // Earned Faith from the real earlier playthrough. Only the weather incident is staged for a repeatable fire test.
  const prior=JSON.parse(await readFile('artifacts/faith-played-save.json','utf8'));await load(JSON.stringify(prior));const migrated=await save();assert.equal(migrated.island.weather.clockMs,0);assert.equal(migrated.island.faith.amount,prior.island.faith.amount);assert.equal(migrated.island.wood,prior.island.wood);
  const entries=migrated.island.resources.entries as [string,any][],key=entries.find(([k,n])=>n.type==='wood_tree'&&n.amount>0&&!migrated.island.buildings.some((b:any)=>`${b.tileX},${b.tileY}`===k))![0];
  migrated.island.weather.kind='drought';migrated.island.weather.dryFireChecked=true;migrated.island.weather.fires=[{key,life:20,heat:3}];migrated.island.weather.burned=[key];migrated.island.weather.incidentCount=1;
  await load(JSON.stringify(migrated));await page.screenshot({path:'artifacts/weather-fire-desktop.png'});await page.locator('#faith-hud').click();await page.waitForTimeout(350);assert.match(await page.locator('#rain-weather').innerText(),/đang cháy/);assert(!(await page.locator('#cast-rainfall').isDisabled()));await page.locator('#cast-rainfall').click();assert(await page.locator('#cast-rainfall').isDisabled());const cast=await save();assert.equal(cast.island.faith.amount,migrated.island.faith.amount-40);assert.equal(cast.island.weather.fires.length,0);assert.equal(cast.island.weather.rainUntilMs,45000);assert.equal(cast.island.wood,migrated.island.wood);assert.equal(cast.island.sharedFood,migrated.island.sharedFood);await writeFile('artifacts/weather-rain-save.json',JSON.stringify(cast));
  await page.locator('#faith-hud').click();await page.locator('#cast-rainfall').scrollIntoViewIfNeeded();await page.waitForTimeout(350);await page.screenshot({path:'artifacts/weather-rain-desktop.png'});await close();await page.screenshot({path:'artifacts/weather-rain-island.png'});await page.waitForTimeout(1000);assert.deepEqual((await save()).island.weather,cast.island.weather);
  await load(JSON.stringify(cast));assert.deepEqual((await save()).island.weather,cast.island.weather);await page.setViewportSize({width:390,height:844});await page.locator('#faith-hud').click();await page.locator('#cast-rainfall').scrollIntoViewIfNeeded();await page.waitForTimeout(350);assert(await page.locator('#cast-rainfall').isDisabled());assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'artifacts/weather-rain-mobile.png'});await close();const weather=await page.locator('#settlement-status').boundingBox(),hud=await page.locator('#faith-hud').boundingBox();assert(weather.y+weather.height<=hud.y||weather.x+weather.width<=hud.x,'Weather and Faith HUD must not overlap');await page.screenshot({path:'artifacts/weather-hud-mobile.png'});
  await page.locator('.speed-btn[data-speed="2"]').click();await pause(false);await page.locator('#faith-hud').click();await page.waitForFunction(()=>!document.querySelector('#rain-weather')?.textContent?.includes('ruộng +30%'),undefined,{timeout:28000});await pause(true);const expired=await save();assert(expired.island.weather.clockMs>=45000);assert(expired.island.weather.clockMs<60000);await page.locator('#faith-hud').click();assert(await page.locator('#cast-rainfall').isDisabled());await pause(false);await page.locator('#faith-hud').click();await page.locator('#cast-rainfall:enabled').waitFor({timeout:16000});await pause(true);const recovered=await save();assert(recovered.island.weather.clockMs>=60000);assert.equal(recovered.island.npcs.filter((n:any)=>n.isAlive).length,5);assert(recovered.island.sharedFood>0);await writeFile('artifacts/weather-played-save.json',JSON.stringify(recovered));assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);console.log(`PASS: old save migration, staged fire extinguished by paid Rain from earned Faith, no resource gift; paused/reloaded timers, ×2 45s bonus / 60s cooldown; desktop/mobile no overlap/errors; 5 alive, Food ${recovered.island.sharedFood.toFixed(1)}.`);
 }catch(e){await page.screenshot({path:'artifacts/weather-ui-failure.png'});throw e;}finally{await browser.close();await new Promise<void>(r=>server.close(()=>r()));}
}
void main().catch(e=>{console.error(e);server.close();process.exitCode=1;});
