import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {decodeSave,encodeSave} from '../src/core/SaveSystem';
import {reserveEntityIds} from '../src/core/factory';
import {SimulationSession,type PlayerCommand} from '../src/core/SimulationSession';
import {controlOperating,controlMultiplier} from '../src/core/ControlManager';
import {findPath} from '../src/core/pathfinding';
import {tickBuildings} from '../src/renderer/BuildingManager';
import {ERAS} from '../src/core/civilization';
const raw=readFileSync('artifacts/technology-prepared-save.json','utf8'),d=decodeSave(raw),s=d.island,c=s.civilization!;reserveEntityIds(s);const sim=new SimulationSession(s,d.map);let seq=0;const initial=s.tick,initialComponents=c.inventory.components;
const send=(command:PlayerCommand)=>{const r=sim.submit({playerId:'microchips',sequence:++seq,command});assert(r.accepted,JSON.stringify({command,r}));};
const until=(ok:()=>boolean,max=1600)=>{for(let i=0;i<max&&!ok();i++){sim.advanceTicks(1);assert.equal(s.npcs.filter(n=>n.isAlive).length,50);}if(!ok())writeFileSync('artifacts/microchips-waiting-save.json',encodeSave(s,d.map,d.config));assert(ok(),JSON.stringify({tick:s.tick,goods:c.inventory,power:s.power,b:s.buildings.filter(b=>b.type==='microchip_factory'||b.type==='control_center').map(b=>[b.id,b.workMessage,b.workers,b.buffer])}));};
const lab=s.buildings.find(b=>b.type==='measurement_lab')!,scientist=s.npcs.find(n=>lab.workers.includes(n.id))!,miner=s.npcs.find(n=>n.isAlive&&n.laborRole==='wood'&&!s.buildings.some(b=>b.workers.includes(n.id)))!,builder=s.npcs.find(n=>n.isAlive&&n.age>=18&&n.laborRole==='food'&&!n.cargo&&!n.freight&&!n.actionTarget&&!s.buildings.some(b=>b.workers.includes(n.id)))!;
assert(miner&&builder);send({type:'assign_labor',npcId:miner.id,role:'stone'});until(()=>s.stone>=40);send({type:'assign_labor',npcId:miner.id,role:'food'});until(()=>!miner.cargo&&!miner.actionTarget);send({type:'remove_worker',buildingId:lab.id,npcId:scientist.id});
const gate=decodeSave(raw),g=new SimulationSession(gate.island,gate.map);gate.island.surveys!.sites[0].foundationComplete=false;assert(!g.submit({playerId:'gate',sequence:1,command:{type:'start_research',techId:'advanced_semiconductors'}}).accepted);assert.equal(gate.island.civilization!.inventory.components,initialComponents);
const fee=c.inventory.components,parts=c.inventory.machineParts;const env={playerId:'microchips',sequence:++seq,command:{type:'start_research' as const,techId:'advanced_semiconductors'}};assert(sim.submit(env).accepted);assert(sim.submit(env).duplicate);assert.equal(c.inventory.components,fee-8);assert.equal(c.inventory.machineParts,parts-2);send({type:'assign_researcher',npcId:scientist.id});until(()=>c.unlocks.includes('advanced_semiconductors'));
const ref=s.buildings.find(b=>b.type==='component_factory')!;
const tile=(near:{tileX:number;tileY:number},other?:{tileX:number;tileY:number})=>d.map.landTiles.find(t=>Math.max(Math.abs(t.x-near.tileX),Math.abs(t.y-near.tileY))<=4&&(!other||Math.max(Math.abs(t.x-other.tileX),Math.abs(t.y-other.tileY))<=6)&&['grass','sand'].includes(d.map.tiles[t.y][t.x])&&!s.buildings.some(b=>b.tileX===t.x&&b.tileY===t.y)&&!s.npcs.some(n=>n.position?.tileX===t.x&&n.position?.tileY===t.y)&&!s.animals.some(a=>a.tileX===t.x&&a.tileY===t.y)&&findPath(d.map,builder.position!.tileX,builder.position!.tileY,t.x,t.y)!==null)!;
const pos=tile(ref);assert(pos);send({type:'build',buildingType:'microchip_factory',tileX:pos.x,tileY:pos.y});assert.equal(c.inventory.components,fee-14);const chip=s.buildings.at(-1)!;send({type:'assign_labor',npcId:builder.id,role:'idle'});send({type:'assign_worker',buildingId:chip.id,npcId:builder.id});until(()=>chip.complete);assert(!sim.submit({playerId:'microchips',sequence:++seq,command:{type:'upgrade_building',buildingId:chip.id}}).accepted);
const gen=s.buildings.find(b=>b.type==='steam_generator')!,post=s.buildings.find(b=>b.type==='tradepost')!;send({type:'assign_worker',buildingId:post.id,npcId:miner.id});for(let i=0;i<2;i++){until(()=>!miner.cargo&&!miner.freight&&!miner.actionTarget&&!miner.haulTask);const cloth=c.inventory.cloth;send({type:'start_trade',buildingId:post.id,offerId:'cloth_for_coal'});assert.equal(c.inventory.cloth,cloth-8);until(()=>!post.shipment);}send({type:'remove_worker',buildingId:post.id,npcId:miner.id});send({type:'assign_labor',npcId:miner.id,role:'food'});
send({type:'set_power',buildingId:chip.id,enabled:true,priority:2});send({type:'set_power',buildingId:gen.id,enabled:true,priority:1});until(()=>!!s.power?.supplied.includes(chip.id)&&(chip.buffer?.input.components??0)>=2);writeFileSync('artifacts/microchips-ready-save.json',encodeSave(s,d.map,d.config));until(()=>c.produced.microchips>=1);send({type:'set_power',buildingId:chip.id,enabled:false,priority:2});const batch=c.produced.microchips,buffer=structuredClone(chip.buffer);sim.advanceTicks(6);assert.equal(c.produced.microchips,batch);assert.deepEqual(chip.buffer!.input,buffer!.input);writeFileSync('artifacts/microchips-paused-save.json',encodeSave(s,d.map,d.config));assert.deepEqual(decodeSave(encodeSave(s,d.map,d.config)).island.civilization,JSON.parse(JSON.stringify(c)));send({type:'set_power',buildingId:chip.id,enabled:true,priority:2});until(()=>c.produced.microchips>=6);send({type:'set_power',buildingId:chip.id,enabled:false,priority:2});until(()=>c.inventory.microchips>=6);assert.equal(c.produced.microchips,6);assert.equal(c.inventory.microchips,6);send({type:'set_power',buildingId:gen.id,enabled:false,priority:1});writeFileSync('artifacts/microchips-produced-save.json',encodeSave(s,d.map,d.config));
const before=c.inventory.microchips;send({type:'start_research',techId:'industrial_control'});assert.equal(c.inventory.microchips,before-4);send({type:'assign_researcher',npcId:scientist.id});until(()=>c.unlocks.includes('industrial_control'));send({type:'remove_worker',buildingId:chip.id,npcId:builder.id});const centerPos=tile(chip,ref);assert(centerPos);const beforeParts=c.inventory.machineParts;send({type:'build',buildingType:'control_center',tileX:centerPos.x,tileY:centerPos.y});assert.equal(c.inventory.microchips,0);assert.equal(c.inventory.machineParts,beforeParts-2);const center=s.buildings.at(-1)!;send({type:'assign_worker',buildingId:center.id,npcId:builder.id});until(()=>center.complete);send({type:'set_power',buildingId:center.id,enabled:true,priority:2});send({type:'set_power',buildingId:gen.id,enabled:true,priority:1});until(()=>controlOperating(s,center));assert.equal(controlMultiplier(s,chip),1.25);assert.equal(controlMultiplier(s,ref),1.25);writeFileSync('artifacts/control-center-ready-save.json',encodeSave(s,d.map,d.config));send({type:'set_power',buildingId:center.id,enabled:false,priority:2});assert.equal(controlMultiplier(s,chip),1);send({type:'set_power',buildingId:center.id,enabled:true,priority:2});until(()=>controlOperating(s,center));send({type:'remove_worker',buildingId:center.id,npcId:builder.id});assert.equal(controlMultiplier(s,chip),1);send({type:'assign_worker',buildingId:center.id,npcId:builder.id});until(()=>controlOperating(s,center));// The factory has only one old copper batch left. Refill through paid shipments.
send({type:'set_power',buildingId:gen.id,enabled:false,priority:1});send({type:'assign_labor',npcId:miner.id,role:'idle'});until(()=>!miner.cargo&&!miner.freight&&!miner.actionTarget&&!miner.haulTask);send({type:'assign_worker',buildingId:post.id,npcId:miner.id});for(const [offer,fee] of [['cloth_for_coal',8],['cloth_for_copper',12]] as const){until(()=>!miner.cargo&&!miner.freight&&!miner.actionTarget&&!miner.haulTask);const cloth=c.inventory.cloth;send({type:'start_trade',buildingId:post.id,offerId:offer});assert.equal(c.inventory.cloth,cloth-fee);until(()=>!post.shipment);}send({type:'remove_worker',buildingId:post.id,npcId:miner.id});send({type:'assign_labor',npcId:miner.id,role:'food'});send({type:'set_power',buildingId:gen.id,enabled:true,priority:1});until(()=>controlOperating(s,center));
const componentStart=c.produced.components;send({type:'set_power',buildingId:ref.id,enabled:true,priority:1});until(()=>c.produced.components>=componentStart+9);send({type:'set_power',buildingId:ref.id,enabled:false,priority:1});until(()=>c.inventory.components>=9);assert(c.produced.components>=componentStart+9);
assert.equal(c.era,'modern');assert.equal(c.anomalyBranch,undefined);assert.equal(s.npcs.filter(n=>n.isAlive).length,50);const final=encodeSave(s,d.map,d.config);assert.deepEqual(decodeSave(final).island.civilization,JSON.parse(JSON.stringify(c)));writeFileSync('artifacts/microchips-played-save.json',final);console.log(JSON.stringify({passed:true,earned:true,steps:s.tick-initial,alive:50,food:s.sharedFood,producedChips:c.produced.microchips,paidChipsResearch:4,paidChipsCenter:2,inventory:c.inventory,control:[center.tileX,center.tileY],factory:[chip.tileX,chip.tileY]}));
// Separate fixture checks the physical effect rather than just its displayed label.
const x=decodeSave(final).island,cc=x.buildings.find(b=>b.type==='control_center')!,target=x.buildings.find(b=>b.type==='microchip_factory')!,operator=x.npcs.find(n=>cc.workers.includes(n.id))!;operator.status='working';operator.laborMessage='Điều phối tại trung tâm';operator.survivalBlocked=false;operator.position={tileX:cc.tileX,tileY:cc.tileY};assert.equal(controlMultiplier(x,target),1.25);operator.status='sleeping';assert.equal(controlMultiplier(x,target),1);operator.status='working';operator.position={tileX:cc.tileX+3,tileY:cc.tileY};assert.equal(controlMultiplier(x,target),1);operator.position={tileX:cc.tileX,tileY:cc.tileY};const duplicate=structuredClone(cc);duplicate.id='fixture-second-center';x.buildings.push(duplicate);x.power!.supplied.push(duplicate.id);assert.equal(controlMultiplier(x,target),1.25);const bad=JSON.parse(final);bad.island.civilization.inventory.microchips=-1;assert.throws(()=>decodeSave(JSON.stringify(bad)),/Kho hàng/);console.log('PASS fixtures: no sleeping/absent operator bonus, no stacking, negative chips rejected.');

const compare=(enabled:boolean)=>{const unit=decodeSave(final).island,ct=unit.buildings.find(b=>b.type==='control_center')!,cf=unit.buildings.find(b=>b.type==='microchip_factory')!,op=unit.npcs.find(n=>ct.workers.includes(n.id))!,worker=unit.npcs.find(n=>n.id===scientist.id)!;unit.buildings=[ct,cf];ct.powerEnabled=enabled;cf.powerEnabled=true;unit.power!.supplied=enabled?[ct.id,cf.id]:[cf.id];cf.workers=[worker.id];cf.buffer={input:{components:40,copper:20},output:{}};cf.productionBatches=0;
 for(const [n,b] of [[op,ct],[worker,cf]] as const){n.status='working';n.survivalBlocked=false;n.cargo=undefined;n.freight=undefined;n.actionTarget=undefined;n.path=undefined;n.position={tileX:b.tileX,tileY:b.tileY};n.needs.hunger=0;n.buildingWork={buildingId:b.id,ticks:0};}op.laborMessage='Điều phối tại trung tâm';
 for(let i=0;i<20;i++)tickBuildings(unit,unit.resources,d.map);return {batches:cf.productionBatches,components:cf.buffer.input.components,copper:cf.buffer.input.copper};};const normal=compare(false),controlled=compare(true);assert.equal(normal.batches,4);assert.equal(controlled.batches,5);assert.equal(normal.components,32);assert.equal(controlled.components,30);assert.equal(controlled.copper,15);console.log('PASS production fixture: same20 onsite work steps yield4 ordinary vs5 controlled batches (+25%), exact recipe inputs consumed; no free outputs.');
