import {readFileSync,writeFileSync} from 'node:fs';
import assert from 'node:assert/strict';
import {createIsland} from '../src/core/factory';
import {createCivilization} from '../src/core/civilization';
import {enableSettlement} from '../src/core/settlement';
import {initializeWorkforce,planWorkforce,attributeBonus} from '../src/core/workforce';
import {SimulationSession,type PlayerCommand} from '../src/core/SimulationSession';
import {encodeSave,decodeSave} from '../src/core/SaveSystem';
import {initializeLogistics} from '../src/core/logistics';
import {productionAlert,releaseAutoStaff,haulTarget} from '../src/core/productionWorkforce';
import {assignWorker} from '../src/renderer/BuildingManager';
import type {WorldMap} from '../src/renderer/WorldMap';
function fixture(pop=5){
 const map:WorldMap={width:16,height:12,tiles:Array.from({length:12},()=>Array(16).fill('grass')),landTiles:[]};
 for(let y=0;y<12;y++)for(let x=0;x<16;x++)map.landTiles.push({x,y});
 const island=createIsland('Tự nhận việc',pop);island.civilization=createCivilization();enableSettlement(island);initializeWorkforce(island,true);
 island.dailyLife!.campfire={tileX:3,tileY:5,fuel:12,graceUntil:30,lit:true};island.wood=0;island.stone=0;island.sharedFood=pop*5;
 island.npcs.forEach(n=>{n.age=25;n.occupation='gatherer';n.position={tileX:3,tileY:5};n.privateFood=0;n.needs={hunger:0,rest:0,safety:0,social:0};});
 for(let y=2;y<10;y++)for(let x=1;x<12;x++)island.resources.set(`${x},${y}`,{type:'herb_patch',amount:100,maxAmount:100,regenRate:2});
 island.resources.set('5,5',{type:'wood_tree',amount:10000,maxAmount:10000,regenRate:1});island.resources.set('6,5',{type:'stone_deposit',amount:10000,maxAmount:10000,regenRate:0});
 const session=new SimulationSession(island,map);let seq=0;return {island,map,session,submit:(command:PlayerCommand)=>session.submit({playerId:'test',sequence:++seq,command})};
}

function shops(pop:number){const f=fixture(pop),s=f.island;initializeLogistics(s);s.wood=200;s.stone=100;s.sharedFood=pop*12;s.civilization!.era='bronze';
 const specs=[['farm',2,5],['lumbercamp',5,5],['mine',6,5],['copper_mine',8,5],['smelter',9,5],['sawmill',10,5],['wheat_field',3,7],['bakery',4,7]] as const;
 for(const [type,tileX,tileY] of specs)s.buildings.push({id:type,type,tileX,tileY,complete:true,progress:100,workers:[],level:1});s.resources.set('8,6',{type:'copper_vein',amount:10000,maxAmount:10000,regenRate:0});initializeLogistics(s);return f;}
for(const pop of [5,15,25]){const {island,map,session}=shops(pop);const before=island.civilization!.produced.copper;let assigned=false,carriers=0;for(let i=0;i<600;i++){session.advanceTicks(1);assigned ||= island.buildings.some(b=>b.autoWorkers?.length);carriers=Math.max(carriers,island.npcs.filter(n=>n.laborRole==='haul').length);for(const b of island.buildings){assert((b.autoWorkers??[]).every(id=>b.workers.includes(id)));for(const stock of [b.buffer?.input??{},b.buffer?.output??{}])assert(Object.values(stock).reduce((s,n)=>s+(n??0),0)<=60.0000001);}assert(island.npcs.every(n=>!n.freight||n.freight.amount<=30));}
 assert(assigned);assert.equal(island.npcs.filter(n=>n.isAlive).length,pop);assert(island.sharedFood>0);assert(carriers>0);if(pop>=15)assert(island.civilization!.produced.copper>before,'Copper chain operates without manual staffing');const saved=encodeSave(island,map,{seed:42,shape:'circle',size:'small',startPop:pop,mode:'local'});assert.deepEqual(decodeSave(saved).island.buildings.map(b=>b.autoWorkers),island.buildings.map(b=>b.autoWorkers));writeFileSync(`artifacts/production-auto-${pop}-save.json`,saved);console.log(`PASS: ${pop} people / 60 days, ${pop} alive, Food ${island.sharedFood.toFixed(1)}, copper ${island.civilization!.produced.copper}, max carriers ${carriers}, no hand staffing or resource gifts.`);}
{
 const {island,map,submit}=shops(15),b=island.buildings.find(b=>b.type==='smelter')!,n=island.npcs[0];assert(submit({type:'assign_worker',buildingId:b.id,npcId:n.id}).accepted);assert.equal(n.laborMode,'manual');for(let i=0;i<20;i++)planWorkforce(island,map);assert(b.workers.includes(n.id));assert(!b.autoWorkers?.includes(n.id));
 const auto=island.npcs[1];auto.position={tileX:9,tileY:5};assert(assignWorker(island,b.id,auto.id,true));auto.buildingWork={buildingId:b.id,ticks:2};b.autoStaff=false;releaseAutoStaff(island,map);assert(b.workers.includes(auto.id),'Preserve partial batch');auto.buildingWork.ticks=0;auto.freight={good:'copper',amount:2,target:'@warehouse'};releaseAutoStaff(island,map);assert(b.workers.includes(auto.id));auto.freight=undefined;releaseAutoStaff(island,map);assert(!b.workers.includes(auto.id));assert(b.workers.includes(n.id));assert.equal(auto.laborMode,'auto');assert(assignWorker(island,b.id,auto.id,true));auto.buildingWork={buildingId:b.id,ticks:.5,cycleBoundary:true};releaseAutoStaff(island,map);assert(!b.workers.includes(auto.id));assert.equal(auto.autoWorkProgress![b.id],.5);const partial=decodeSave(encodeSave(island,map,{seed:42,shape:'circle',size:'small',startPop:15,mode:'local'}));assert.equal(partial.island.npcs.find(x=>x.id===auto.id)!.autoWorkProgress![b.id],.5);assert(assignWorker(island,b.id,auto.id,true));assert.equal(auto.buildingWork!.ticks,.5);assert.equal(auto.autoWorkProgress![b.id],undefined);auto.buildingWork={buildingId:b.id,ticks:0};releaseAutoStaff(island,map);assert(submit({type:'set_labor_mode',npcId:n.id,mode:'auto'}).accepted);assert(b.autoWorkers?.includes(n.id));assert(submit({type:'set_labor_mode',npcId:n.id,mode:'manual'}).accepted);assert(!b.autoWorkers?.includes(n.id));
 assert.match(productionAlert(island,b,map),/Thiếu đầu vào/);b.buffer!.input={copperOre:4,wood:2};b.buffer!.output={copper:60};assert.match(productionAlert(island,b,map),/Kho thành phẩm đầy/);b.buffer!.output={};assert.match(productionAlert(island,island.buildings.find(b=>b.type==='copper_mine')!,map),/Thiếu công nhân|Sẵn sàng/);island.resources.get('8,6')!.amount=0;assert.match(productionAlert(island,island.buildings.find(b=>b.type==='copper_mine')!,map),/đã cạn/);
 const water={...map,tiles:map.tiles.map(r=>[...r])};for(let y=0;y<12;y++)water.tiles[y][7]='deep_water';for(const person of island.npcs)person.position={tileX:3,tileY:5};assert.match(productionAlert(island,b,water),/Không có đường/);b.buffer!.output={copper:5};island.npcs[0].position={tileX:9,tileY:5};assert.match(productionAlert(island,b,water),/Không có đường vận chuyển/);b.buffer!.output={};b.buffer!.input={};island.civilization!.inventory.copperOre=4;assert.match(productionAlert(island,b,water),/không có đường vận chuyển đến xưởng/);
 const config={seed:42,shape:'circle' as const,size:'small' as const,startPop:15,mode:'local' as const};const bad=JSON.parse(encodeSave(island,map,config));bad.island.buildings[0].autoWorkers=['missing'];assert.throws(()=>decodeSave(JSON.stringify(bad)),/Nhân công tự động/);const amount=island.wood;assert(submit({type:'set_building_auto',buildingId:b.id,enabled:false}).accepted);assert.equal(island.wood,amount);const old=JSON.parse(encodeSave(island,map,config));for(const building of old.island.buildings){delete building.autoWorkers;delete building.autoStaff;}const legacy=decodeSave(JSON.stringify(old));initializeWorkforce(legacy.island);planWorkforce(legacy.island,map);assert(legacy.island.buildings.find(x=>x.id===b.id)!.workers.includes(n.id),'Old manually assigned staff stays protected');
 const oldTarget=haulTarget(island,15);island.buildings.forEach(x=>{x.buffer!.output={};});island.buildings.slice(0,5).forEach(x=>x.buffer!.output={food:60});assert(haulTarget(island,15)>oldTarget);console.log('PASS: manual ownership, partial work/cargo protection, per-building off, alerts for missing inputs/full/source/route, saved ownership and conservative old save migration, adaptive haul target.');
}

for(const file of ['artifacts/bronze-playable-save.json','artifacts/logistics-iron-save.json']){
 const saved=decodeSave(readFileSync(file,'utf8')),s=saved.island;initializeWorkforce(s);initializeLogistics(s);const session=new SimulationSession(s,saved.map);let sequence=0;session.submit({playerId:'auto',sequence:++sequence,command:{type:'set_auto_claim',enabled:true}});for(const n of s.npcs.filter(n=>n.isAlive&&n.position&&n.age>=18))assert(session.submit({playerId:'auto',sequence:++sequence,command:{type:'set_labor_mode',npcId:n.id,mode:'auto'}}).accepted);const alive=s.npcs.filter(n=>n.isAlive).length;
 for(let i=0;i<400;i++)session.advanceTicks(1);assert.equal(s.npcs.filter(n=>n.isAlive).length,alive);assert(s.sharedFood>0);decodeSave(encodeSave(s,saved.map,saved.config));console.log(`PASS: actual ${s.civilization!.era} save handed to auto through commands, 40 days, ${alive} alive, Food ${s.sharedFood.toFixed(1)}, saved staff/progress valid.`);
}
