import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE??'playwright');const root=path.resolve('web');
const server=createServer(async(req,res)=>{const file=path.resolve(root,'.'+new URL(req.url??'/','http://localhost').pathname.replace(/\/$/,'/index.html'));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{res.setHeader('content-type',({'.html':'text/html','.css':'text/css','.js':'text/javascript','.svg':'image/svg+xml','.png':'image/png'} as Record<string,string>)[path.extname(file)]??'application/octet-stream');res.end(await readFile(file));}catch{res.writeHead(404).end();}});
async function main(){
 await mkdir('artifacts',{recursive:true});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors:string[]=[],failed:string[]=[];page.on('pageerror',(e:Error)=>errors.push(e.message));page.on('response',(r:any)=>{if(r.status()>=400)failed.push(r.url());});const url=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
 const close=async()=>{if(await page.locator('#panel-overlay').evaluate((e:HTMLElement)=>e.classList.contains('open')))await page.locator('#panel-close').click();};
 const pause=async(on:boolean)=>{await close();if((await page.locator('#btn-pause').evaluate((e:HTMLElement)=>e.classList.contains('active')))!==on)await page.locator('#btn-pause').click();};
 const save=async()=>{await close();await page.locator('#btn-save-local').click();return page.evaluate(()=>JSON.parse(localStorage.getItem('dao_thien_nguyen_v2')!));};
 const load=async(raw:string)=>{await page.goto(url);await page.evaluate((raw:string)=>localStorage.setItem('dao_thien_nguyen_v2',raw),raw);await page.reload();await page.locator('#btn-resume-game').click();await page.locator('.era-roadmap').waitFor();await pause(true);};
 const open=async()=>{await close();await page.locator('#sb-quests').click();await page.locator('.modern-preparation').waitFor();await page.waitForTimeout(300);};
 try{
 const raw=await readFile('artifacts/modern-ready-save.json','utf8'),prior=JSON.parse(raw),gen=prior.island.buildings.find((b:any)=>b.type==='steam_generator');await load(raw);await open();assert.equal(await page.locator('[data-modern-requirement].met').count(),10);assert.equal(await page.locator('[data-modern-fee].met').count(),3);await page.waitForFunction(()=>[...document.querySelectorAll<HTMLImageElement>('[data-modern-fee] img')].every(i=>i.complete&&i.naturalWidth>0));assert(await page.locator('#btn-develop-era').isEnabled());await page.locator('.modern-preparation').scrollIntoViewIfNeeded();await page.screenshot({path:'artifacts/modern-ready-desktop.png'});await page.locator('[data-modern-fee=steel]').scrollIntoViewIfNeeded();await page.screenshot({path:'artifacts/modern-ready-fees-desktop.png'});await page.setViewportSize({width:390,height:844});await page.locator('.modern-preparation').scrollIntoViewIfNeeded();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'artifacts/modern-ready-mobile.png'});await page.locator('[data-modern-fee=steel]').scrollIntoViewIfNeeded();await page.screenshot({path:'artifacts/modern-ready-fees-mobile.png'});
 await page.locator(`[data-power-toggle="${gen.id}"]`).click();assert(!(await page.locator('[data-modern-requirement="6"]').evaluate((e:HTMLElement)=>e.classList.contains('met'))));const off=await save();assert.equal(off.island.power.steadyTicks,0);assert.deepEqual(off.island.civilization.inventory,{components:0,...prior.island.civilization.inventory});assert.equal(off.island.tick,prior.island.tick);assert.equal(off.island.npcs.filter((n:any)=>n.isAlive).length,50);await load(JSON.stringify(off));await open();assert.match(await page.locator('[data-modern-requirement="6"]').innerText(),/0.0\/3/);await page.locator('.modern-preparation').scrollIntoViewIfNeeded();await page.screenshot({path:'artifacts/modern-ready-power-reset.png'});await page.setViewportSize({width:1440,height:1000});await load(raw);await page.locator('#btn-zoom-in').click();await page.waitForTimeout(300);await page.screenshot({path:'artifacts/modern-ready-island.png'});assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);console.log('PASS browser earned readiness: ten requirements met /50 living/real fee stock, Modern investment enabled, paused toggle breaks continuous proof without costs, exact reload, desktop/mobile no errors or overflow, character/building textures in game.');
 }catch(e){await page.screenshot({path:'artifacts/modern-readiness-ui-failure.png'});throw e;}finally{await browser.close();server.close();}
}
main().catch(e=>{console.error(e);process.exitCode=1;});
