import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {decodeSave,encodeSave} from '../src/core/SaveSystem';
import {reserveEntityIds} from '../src/core/factory';
import {SimulationSession,type PlayerCommand} from '../src/core/SimulationSession';
import {ERAS} from '../src/core/civilization';
const raw=readFileSync('artifacts/analysis-played-save.json','utf8');let d=decodeSave(raw),s=d.island,c=s.civilization!;reserveEntityIds(s);let sim=new SimulationSession(s,d.map),seq=0;const initial=s.tick;
const send=(command:PlayerCommand)=>{const r=sim.submit({playerId:'decisions',sequence:++seq,command});assert(r.accepted,JSON.stringify({command,r}));};
const until=(ok:()=>boolean,max=1200)=>{for(let i=0;i<max&&!ok();i++){sim.advanceTicks(1);assert.equal(s.npcs.filter(n=>n.isAlive).length,50);}if(!ok())writeFileSync('artifacts/decisions-waiting-save.json',encodeSave(s,d.map,d.config));assert(ok(),JSON.stringify({analysis:s.analysis,power:s.power}));};
const lab=s.buildings.find(b=>b.type==='measurement_lab')!,id=lab.id,site=s.surveys!.sites[0],comp=c.inventory.components;
// Refill through two paid physical shipments; the source has no coal in warehouse.
const post=s.buildings.find(b=>b.type==='tradepost')!,trader=s.npcs.find(n=>n.isAlive&&n.age>=18&&!n.guardDuty&&n.laborRole==='food'&&!s.buildings.some(b=>b.workers.includes(n.id)))!;assert(trader);send({type:'assign_labor',npcId:trader.id,role:'idle'});send({type:'assign_worker',buildingId:post.id,npcId:trader.id});for(let i=0;i<2;i++){until(()=>!trader.actionTarget&&!trader.cargo&&!trader.freight&&!trader.haulTask);const cloth=c.inventory.cloth;send({type:'start_trade',buildingId:post.id,offerId:'cloth_for_coal'});assert.equal(c.inventory.cloth,cloth-8);until(()=>!post.shipment);}send({type:'remove_worker',buildingId:post.id,npcId:trader.id});send({type:'assign_labor',npcId:trader.id,role:'food'});writeFileSync('artifacts/decisions-ready-save.json',encodeSave(s,d.map,d.config));
const command:PlayerCommand={type:'decide_site',siteId:site.id,decision:'research',labId:id},env={playerId:'decisions',sequence:++seq,command};assert(sim.submit(env).accepted);assert(sim.submit(env).duplicate);assert.equal(c.inventory.components,comp-4);
assert(!sim.submit({playerId:'decisions',sequence:++seq,command}).accepted);assert.equal(c.inventory.components,comp-4);
until(()=>s.analysis!.foundation!.workTicks>=5);const held=s.analysis!.foundation!.workTicks;send({type:'set_power',buildingId:id,enabled:false,priority:2});sim.advanceTicks(4);assert.equal(s.analysis!.foundation!.workTicks,held);assert.equal(lab.labPoweredTicks,0);const paused=encodeSave(s,d.map,d.config);writeFileSync('artifacts/decisions-paused-save.json',paused);assert.deepEqual(decodeSave(paused).island.analysis,s.analysis);
send({type:'cancel_foundation'});assert.equal(c.inventory.components,comp);assert.equal(site.decision,undefined);assert(!sim.submit({playerId:'decisions',sequence:++seq,command:{type:'cancel_foundation'}}).accepted);
send(command);assert.equal(s.analysis!.foundation!.workTicks,0);send({type:'set_power',buildingId:id,enabled:true,priority:2});
// Resume in a fresh simulation through the public save path, without supplying goods.
d=decodeSave(encodeSave(s,d.map,d.config));s=d.island;c=s.civilization!;sim=new SimulationSession(s,d.map);seq=0;
until(()=>!!s.surveys!.sites[0].foundationComplete);assert.equal(c.inventory.components,comp-4);assert(!s.analysis!.foundation);assert(!sim.submit({playerId:'decisions',sequence:++seq,command}).accepted);
const second=s.surveys!.sites[1],cloth=c.inventory.cloth,stone=c.inventory.cutStone;send({type:'decide_site',siteId:second.id,decision:'contain'});assert.equal(c.inventory.cloth,cloth-4);assert.equal(c.inventory.cutStone,stone-2);assert(!sim.submit({playerId:'decisions',sequence:++seq,command:{type:'decide_site',siteId:second.id,decision:'research',labId:id}}).accepted);
send({type:'decide_site',siteId:s.surveys!.sites[2].id,decision:'ignore'});assert.equal(c.inventory.components,0);assert.equal(c.era,'modern');assert.equal(c.anomalyBranch,undefined);assert.equal(s.npcs.filter(n=>n.isAlive).length,50);const complete=encodeSave(s,d.map,d.config);assert.deepEqual(decodeSave(complete).island.surveys,s.surveys);writeFileSync('artifacts/decisions-played-save.json',complete);
const bad=JSON.parse(paused);bad.island.analysis.foundation.workTicks=60;assert.throws(()=>decodeSave(JSON.stringify(bad)),/nền tảng/);const wrong=JSON.parse(complete);wrong.island.surveys.sites[1].foundationComplete=true;assert.throws(()=>decodeSave(JSON.stringify(wrong)),/Quyết định/);
// Separate behavior fixture: a temporarily ignored record can be reconsidered, not a contained one.
const f=decodeSave(raw),fs=new SimulationSession(f.island,f.map);assert(fs.submit({playerId:'fixture',sequence:1,command:{type:'decide_site',siteId:'site-1',decision:'ignore'}}).accepted);assert(fs.submit({playerId:'fixture',sequence:2,command:{type:'decide_site',siteId:'site-1',decision:'research',labId:id}}).accepted);assert.equal(f.island.civilization!.inventory.components,0);
console.log(`PASS earned decisions: paid4/replay/reject duplicate/outage holds/save/reload/cancel once/reset progress/60 onsite steps, containment paid4cloth2stone/immutable, ignore/reconsider fixture, invalid saves rejected, 50 alive/Food ${s.sharedFood.toFixed(1)}, ${s.tick-initial} ticks, Modern preserved/Anomaly locked.`);
