import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE??'playwright');const root=path.resolve('web');
const server=createServer(async(req,res)=>{const file=path.resolve(root,'.'+new URL(req.url??'/','http://localhost').pathname.replace(/\/$/,'/index.html'));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{res.setHeader('content-type',({'.html':'text/html','.css':'text/css','.js':'text/javascript','.svg':'image/svg+xml','.png':'image/png'} as Record<string,string>)[path.extname(file)]??'application/octet-stream');res.end(await readFile(file));}catch{res.writeHead(404).end();}});
async function main(){
 await mkdir('artifacts',{recursive:true});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors:string[]=[],failed:string[]=[];page.on('pageerror',(e:Error)=>errors.push(e.message));page.on('response',(r:any)=>{if(r.status()>=400)failed.push(r.url());});const url=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
 const close=async()=>{if(await page.locator('#building-inspector').isVisible())await page.locator('#bi-close').click();if(await page.locator('#panel-overlay').evaluate((e:HTMLElement)=>e.classList.contains('open')))await page.locator('#panel-close').click();};
 const pause=async(on:boolean)=>{await close();if((await page.locator('#btn-pause').evaluate((e:HTMLElement)=>e.classList.contains('active')))!==on)await page.locator('#btn-pause').click();};
 const save=async()=>{await close();await page.locator('#btn-save-local').click();return page.evaluate(()=>JSON.parse(localStorage.getItem('dao_thien_nguyen_v2')!));};
 const load=async(raw:string)=>{await page.goto(url);await page.evaluate((raw:string)=>localStorage.setItem('dao_thien_nguyen_v2',raw),raw);await page.reload();await page.locator('#btn-resume-game').click();await page.locator('.era-roadmap').waitFor();await pause(true);};
 const open=async()=>{await close();await page.locator('#sb-quests').click();await page.locator('.era-roadmap').waitFor();await page.waitForTimeout(300);};
 const inspect=async(id:string)=>{await close();await page.locator('#btn-build').click();await page.locator(`[data-inspect-building="${id}"]`).click();await page.locator('#building-inspector').waitFor({state:'visible'});await page.waitForTimeout(300);};
 try{
 const raw=await readFile('artifacts/analysis-ready-save.json','utf8'),ready=JSON.parse(raw),lab=ready.island.buildings.find((b:any)=>b.type==='measurement_lab'),site=ready.island.surveys.sites[0];await load(raw);const before=await save();await inspect(lab.id);assert.match(await page.locator('.bi-state').innerText(),/Đủ 2 công suất/);assert.match(await page.locator('.bi-level').innerText(),/Cấp 1 \/ 1.*Hiện Đại/);assert.match(await page.locator('#building-inspector').innerText(),/2 công suất/);await page.waitForFunction(()=>[...document.querySelectorAll<HTMLImageElement>('.bi-texture')].every(i=>i.complete&&i.naturalWidth>0));await page.screenshot({path:'artifacts/analysis-lab-desktop.png'});await open();await page.locator('.analysis-panel').scrollIntoViewIfNeeded();await page.screenshot({path:'artifacts/analysis-ready-desktop.png'});await page.locator('#analysis-lab').selectOption(lab.id);await page.locator(`[data-start-analysis="${site.id}"]`).click();const paid=await save();assert.equal(paid.island.civilization.inventory.components,before.island.civilization.inventory.components-2);assert.equal(paid.island.analysis.active.workTicks,0);await load(JSON.stringify(paid));await open();assert.match(await page.locator('.analysis-panel').innerText(),/0\/40/);await page.locator('#cancel-analysis').click();const refund=await save();assert.equal(refund.island.civilization.inventory.components,before.island.civilization.inventory.components);
 const heldRaw=await readFile('artifacts/analysis-paused-save.json','utf8'),held=JSON.parse(heldRaw);await load(heldRaw);await open();await page.locator('.analysis-panel').scrollIntoViewIfNeeded();assert.match(await page.locator('.analysis-panel').innerText(),new RegExp(`${held.island.analysis.active.workTicks}/40`));assert.equal(held.island.buildings.find((b:any)=>b.id===lab.id).labPoweredTicks,0);await page.screenshot({path:'artifacts/analysis-outage-desktop.png'});await page.locator(`[data-power-toggle="${lab.id}"]`).click();assert.match(await page.locator('.analysis-status').innerText(),/Đủ điện/);await pause(false);await page.locator('.speed-btn[data-speed="2"]').click();await open();await page.waitForFunction(()=>document.querySelector('.analysis-panel')?.textContent?.includes('1/3 hồ sơ'),undefined,{timeout:120000});await pause(true);const completed=await save();assert.equal(completed.island.surveys.sites.filter((p:any)=>p.analyzed).length,1);assert.equal(completed.island.npcs.filter((n:any)=>n.isAlive).length,50);await close();await page.locator('#btn-zoom-in').click();await page.screenshot({path:'artifacts/analysis-island.png'});
 await page.setViewportSize({width:390,height:844});await load(await readFile('artifacts/analysis-played-save.json','utf8'));await open();await page.locator('.analysis-panel h3').scrollIntoViewIfNeeded();assert.match(await page.locator('.analysis-panel').innerText(),/3\/3 hồ sơ/);await page.screenshot({path:'artifacts/analysis-mobile.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);console.log('PASS browser earned analysis: own lab texture/Modern/level1, paid2 project/pause/reload/cancel refund, outage snapshot/own proof0/resume physical work/1 processed/50 alive, mobile earned3 files, no errors/overflow and island texture.');
 }catch(e){await page.screenshot({path:'artifacts/analysis-ui-failure.png'});throw e;}finally{await browser.close();server.close();}
}
main().catch(e=>{console.error(e);server.close();process.exitCode=1;});
