import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE??'playwright');const root=path.resolve('web');
const server=createServer(async(req,res)=>{const file=path.resolve(root,'.'+new URL(req.url??'/','http://localhost').pathname.replace(/\/$/,'/index.html'));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{res.setHeader('content-type',({'.html':'text/html','.css':'text/css','.js':'text/javascript','.svg':'image/svg+xml','.png':'image/png'} as Record<string,string>)[path.extname(file)]??'application/octet-stream');res.end(await readFile(file));}catch{res.writeHead(404).end();}});
async function main(){
 await mkdir('artifacts',{recursive:true});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors:string[]=[],failed:string[]=[];page.on('pageerror',(e:Error)=>errors.push(e.message));page.on('response',(r:any)=>{if(r.status()>=400)failed.push(r.url());});const url=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
 const close=async()=>{if(await page.locator('#panel-overlay').evaluate((e:HTMLElement)=>e.classList.contains('open')))await page.locator('#panel-close').click();await page.waitForTimeout(350);};const pause=async(on:boolean)=>{await close();if((await page.locator('#btn-pause').evaluate((e:HTMLElement)=>e.classList.contains('active')))!==on)await page.locator('#btn-pause').click();};const save=async()=>{await close();await page.locator('#btn-save-local').click();return page.evaluate(()=>JSON.parse(localStorage.getItem('dao_thien_nguyen_v2')!));};const load=async(raw:string)=>{await page.goto(url);await page.evaluate((raw:string)=>localStorage.setItem('dao_thien_nguyen_v2',raw),raw);await page.reload();await page.locator('#btn-resume-game').click();await page.locator('.era-roadmap').waitFor();await pause(true);};const open=async()=>{await page.locator('#sb-resources').click();await page.locator('#manage-apply').waitFor();await page.waitForTimeout(350);};
 try{
  await load(await readFile('artifacts/production-browser-save.json','utf8'));const initial=await save();assert.equal(initial.island.reserves,undefined);const manual=initial.island.buildings.flatMap((b:any)=>b.workers.filter((id:string)=>!b.autoWorkers?.includes(id)).map((id:string)=>({id,b:b.id})));
  await open();await page.locator('#reserve-wood').fill('-1');await page.locator('#manage-apply').click();assert.match(await page.locator('#management-feedback').innerText(),/số nguyên/);assert.equal((await save()).island.reserves,undefined);
  await open();await page.locator('#reserve-food').fill('120');await page.locator('#reserve-wood').fill('180');await page.locator('#reserve-stone').fill('90');await page.locator('#reserve-copper').fill('40');await page.locator('#manage-apply').click();assert.match(await page.locator('#management-feedback').innerText(),/Đã áp dụng/);let state=await save();assert.equal(state.island.reserves.targets.wood,180);assert.equal(state.island.reserves.targets.copper,40);assert.equal(state.island.sharedFood,initial.island.sharedFood);assert.equal(state.island.wood,initial.island.wood);assert.deepEqual(state.island.civilization.produced,initial.island.civilization.produced);await writeFile('artifacts/management-targets-save.json',JSON.stringify(state));await load(JSON.stringify(state));assert.deepEqual((await save()).island.reserves,state.island.reserves);
  await open();assert.match(await page.locator('#management-mode').innerText(),/đang bật/);assert.equal(await page.locator('#reserve-wood').inputValue(),'180');await page.screenshot({path:'artifacts/management-desktop.png'});await close();await pause(false);await open();await page.locator('#reserve-wood').fill('123');await page.waitForTimeout(1600);assert.equal(await page.locator('#reserve-wood').inputValue(),'123','Live updates must not replace an editing input');await pause(true);
  await open();await page.locator('#management-warnings').scrollIntoViewIfNeeded();const warning=page.locator('[data-manage-building]').first();assert(await warning.count());const id=await warning.getAttribute('data-manage-building');await warning.click();await page.locator('#building-inspector').waitFor({state:'visible'});const b=state.island.buildings.find((b:any)=>b.id===id);assert.match(await page.locator('.bi-location').innerText(),new RegExp(`\(${b.tileX}, ${b.tileY}\)`));await page.waitForTimeout(500);await page.screenshot({path:'artifacts/management-alert-building.png'});await page.locator('#bi-close').click();
  const day=Number(await page.locator('#stat-day').innerText());await page.locator('.speed-btn[data-speed="2"]').click();await pause(false);await page.waitForFunction((day:number)=>Number(document.querySelector('#stat-day')?.textContent)>=day,day+15,{timeout:55000});await pause(true);state=await save();assert.equal(state.island.npcs.filter((n:any)=>n.isAlive).length,12);assert(state.island.sharedFood>0);assert(state.island.npcs.filter((n:any)=>n.isAlive).every((n:any)=>(n.health??100)>=90&&n.needs.hunger<80));for(const pair of manual)assert(state.island.buildings.find((b:any)=>b.id===pair.b).workers.includes(pair.id),'Manual assignments survive target changes');assert.equal(state.island.reserves.targets.wood,180);
  await open();await page.setViewportSize({width:390,height:844});await page.waitForTimeout(350);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'artifacts/management-mobile.png'});await page.locator('#management-warnings').scrollIntoViewIfNeeded();await page.waitForTimeout(350);await page.screenshot({path:'artifacts/management-alerts-mobile.png'});await page.locator('#manage-reset').scrollIntoViewIfNeeded();await page.locator('#manage-reset').click();assert.match(await page.locator('#management-feedback').innerText(),/mặc định/);state=await save();assert.equal(state.island.reserves,undefined);await writeFile('artifacts/management-browser-save.json',JSON.stringify(state));assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);console.log(`PASS: real village target edit/reject without gifts, exact save/reload, live input retained, actionable alert opens correct building, 15 days / 12 alive / Food ${state.island.sharedFood.toFixed(1)}, manual staff held, default reset, desktop/mobile no overflow/errors.`);
 }catch(e){await page.screenshot({path:'artifacts/management-ui-failure.png'});throw e;}finally{await browser.close();await new Promise<void>(r=>server.close(()=>r()));}
}
void main().catch(e=>{console.error(e);server.close();process.exitCode=1;});
