import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {decodeSave,encodeSave} from '../src/core/SaveSystem';
import {reserveEntityIds} from '../src/core/factory';
import {SimulationSession,type PlayerCommand} from '../src/core/SimulationSession';
import {startTrade,cancelTrade,tickTrades,TRADE_OFFERS} from '../src/core/trade';
import {goodsCapacity} from '../src/core/civilization';
const raw=readFileSync('artifacts/modern-factory-upgraded-save.json','utf8');
// Deliberately modified fixtures test rejected/blocked/canceled shipments, not earned play.
const fixture=decodeSave(raw),u=fixture.island,uc=u.civilization!,post=u.buildings.find(b=>b.type==='tradepost')!,adult=u.npcs.find(n=>n.isAlive&&n.age>=18&&n.position)!;post.workers=[adult.id];adult.actionTarget=undefined;adult.researching=false;adult.cargo=undefined;adult.freight=undefined;adult.haulTask=undefined;
const stock=uc.inventory.cloth;assert.match(startTrade(u,fixture.map,post.id,'cloth_for_coal')!,/Hợp đồng/);assert.equal(uc.inventory.cloth,stock);uc.unlocks.push('industrial_supply');uc.era='iron';assert.match(startTrade(u,fixture.map,post.id,'cloth_for_coal')!,/Hiện Đại/);uc.era='modern';uc.inventory.coal=goodsCapacity(u);assert.match(startTrade(u,fixture.map,post.id,'cloth_for_coal')!,/Kho/);uc.inventory.coal=0;assert.equal(startTrade(u,fixture.map,post.id,'cloth_for_coal'),null);assert.equal(uc.inventory.cloth,stock-8);assert.equal(uc.inventory.coal,0);const dest=post.shipment!.destination,terrain=fixture.map.tiles[dest.y][dest.x];fixture.map.tiles[dest.y][dest.x]='deep_water';const held=JSON.stringify(post.shipment);tickTrades(u,fixture.map);assert.equal(JSON.stringify(post.shipment),held);fixture.map.tiles[dest.y][dest.x]=terrain;assert.equal(cancelTrade(u,post),null);assert.equal(uc.inventory.cloth,stock);assert.equal(uc.inventory.coal,0);assert(cancelTrade(u,post));assert.equal(uc.inventory.cloth,stock);assert(startTrade(u,fixture.map,post.id,'__proto__'));console.log('PASS supply fixtures: research/era lock, atomic fee, full warehouse, no instant imports, blocked destination holds escrow, cancellation refunds exactly once, unknown offers rejected.');
const d=decodeSave(raw),s=d.island,c=s.civilization!;reserveEntityIds(s);let sim=new SimulationSession(s,d.map),seq=0;const begin=s.tick;
const send=(command:PlayerCommand)=>{const r=sim.submit({playerId:'modern-supply',sequence:++seq,command});assert(r.accepted,JSON.stringify({command,r}));};
const step=()=>{sim.advanceTicks(1);assert.equal(s.npcs.filter(n=>n.isAlive).length,50);};
const until=(ok:()=>boolean,max=2500)=>{for(let i=0;i<max&&!ok();i++)step();if(!ok())writeFileSync('artifacts/modern-supply-waiting-save.json',encodeSave(s,d.map,d.config));assert(ok(),JSON.stringify({tick:s.tick,food:s.sharedFood,goods:c.inventory,research:c.research,b:s.buildings.filter(b=>b.workers.length||b.type==='steam_generator').map(b=>[b.type,b.workers,b.workMessage,b.buffer])}));};
const factory=s.buildings.find(b=>b.type==='component_factory')!,gen=s.buildings.find(b=>b.type==='steam_generator')!,trade=s.buildings.find(b=>b.type==='tradepost')!,iron=s.buildings.find(b=>b.type==='iron_smelter')!,steel=s.buildings.find(b=>b.type==='steelworks')!;
const [operator,smithId,researchId]=factory.workers;for(const id of [smithId,researchId])send({type:'remove_worker',buildingId:factory.id,npcId:id});
const free=s.npcs.filter(n=>n.isAlive&&n.age>=18&&!n.guardDuty&&n.laborRole==='food'&&!s.buildings.some(b=>b.workers.includes(n.id))).slice(-2);assert.equal(free.length,2);const [miner,trader]=free;for(const n of free)send({type:'assign_labor',npcId:n.id,role:'idle'});
send({type:'set_power',buildingId:factory.id,enabled:false,priority:2});send({type:'set_power',buildingId:gen.id,enabled:false,priority:1});send({type:'assign_worker',buildingId:trade.id,npcId:trader.id});
const trip=(id:string)=>{until(()=>!trader.actionTarget&&!trader.cargo&&!trader.freight&&!trader.haulTask);const o=TRADE_OFFERS[id],before=c.inventory[o.give],produced=c.produced[o.receive],completed=c.completedTrades??0;const envelope={playerId:'modern-supply',sequence:++seq,command:{type:'start_trade' as const,buildingId:trade.id,offerId:id}};assert(sim.submit(envelope).accepted);assert.equal(c.inventory[o.give],before-o.giveAmount);assert(sim.submit(envelope).duplicate);assert.equal(c.inventory[o.give],before-o.giveAmount);const mid=decodeSave(encodeSave(s,d.map,d.config));assert.equal(mid.island.buildings.find(b=>b.id===trade.id)!.shipment!.offerId,id);until(()=>!trade.shipment);assert.equal(c.completedTrades,completed+1);assert.equal(c.produced[o.receive],produced);};
trip('copper_for_coal');trip('cloth_for_ore');send({type:'assign_worker',buildingId:iron.id,npcId:miner.id});send({type:'assign_worker',buildingId:steel.id,npcId:smithId});until(()=>c.inventory.steel+(factory.buffer?.input.steel??0)>=4);for(const [b,id] of [[iron,miner.id],[steel,smithId]] as const)send({type:'remove_worker',buildingId:b.id,npcId:id});send({type:'assign_labor',npcId:miner.id,role:'food'});send({type:'assign_labor',npcId:smithId,role:'food'});
trip('copper_for_coal');send({type:'set_power',buildingId:factory.id,enabled:true,priority:2});until(()=>(factory.buffer?.input.steel??0)>=2);send({type:'set_power',buildingId:gen.id,enabled:true,priority:1});until(()=>c.inventory.components>=3);send({type:'set_power',buildingId:factory.id,enabled:false,priority:2});send({type:'set_power',buildingId:gen.id,enabled:false,priority:1});const components=c.inventory.components,parts=c.inventory.machineParts;send({type:'start_research',techId:'industrial_supply'});assert.equal(c.inventory.components,components-3);assert.equal(c.inventory.machineParts,parts-2);send({type:'assign_researcher',npcId:researchId});until(()=>c.unlocks.includes('industrial_supply'));
writeFileSync('artifacts/modern-supply-contract-save.json',encodeSave(s,d.map,d.config));
// These imports replace finite mines; no new miners or sources are granted.
trip('cloth_for_coal');trip('cloth_for_copper');const fiber=s.buildings.find(b=>b.type==='flax_field')!,weaver=s.buildings.find(b=>b.type==='weaver')!;const beforeCloth=c.produced.cloth;send({type:'assign_labor',npcId:miner.id,role:'idle'});send({type:'assign_labor',npcId:smithId,role:'idle'});send({type:'assign_worker',buildingId:fiber.id,npcId:miner.id});send({type:'assign_worker',buildingId:weaver.id,npcId:smithId});until(()=>c.produced.cloth>=beforeCloth+12);trip('cloth_for_ore');trip('cloth_for_ore');trip('cloth_for_coal');send({type:'remove_worker',buildingId:fiber.id,npcId:miner.id});send({type:'remove_worker',buildingId:weaver.id,npcId:smithId});send({type:'assign_worker',buildingId:iron.id,npcId:miner.id});send({type:'assign_worker',buildingId:steel.id,npcId:smithId});until(()=>c.inventory.steel+(factory.buffer?.input.steel??0)>=4);send({type:'remove_worker',buildingId:iron.id,npcId:miner.id});send({type:'remove_worker',buildingId:steel.id,npcId:smithId});for(const id of [miner.id,smithId,researchId])send({type:'assign_labor',npcId:id,role:'food'});
const previousComponents=c.produced.components;send({type:'set_power',buildingId:factory.id,enabled:true,priority:2});until(()=>(factory.buffer?.input.steel??0)>=4);send({type:'set_power',buildingId:gen.id,enabled:true,priority:1});until(()=>c.produced.components>=previousComponents+6&&c.inventory.components>=6);send({type:'set_power',buildingId:factory.id,enabled:false,priority:2});send({type:'set_power',buildingId:gen.id,enabled:false,priority:1});send({type:'remove_worker',buildingId:factory.id,npcId:operator});send({type:'assign_labor',npcId:operator,role:'food'});send({type:'remove_worker',buildingId:trade.id,npcId:trader.id});send({type:'assign_labor',npcId:trader.id,role:'food'});for(let i=0;i<300;i++)step();
const final=encodeSave(s,d.map,d.config);assert.deepEqual(decodeSave(final).island.civilization,JSON.parse(JSON.stringify(c)));writeFileSync('artifacts/modern-supply-played-save.json',final);console.log(`PASS earned supply: paid old routes bootstrap 3 components/research, new cloth->coal/copper physical paid trips and replay/load, real flax/weaving +${c.produced.cloth-beforeCloth} cloth, new metal->6 more components, +30 days resting economy, 50 alive/Food ${s.sharedFood.toFixed(1)}, ${s.tick-begin} steps.`);
