import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {beginModernDevelopment,ERAS} from '../src/core/civilization';
import {modernRequirements,MODERN_FEE} from '../src/core/ModernPreparation';
import {decodeSave,encodeSave} from '../src/core/SaveSystem';
import {SimulationSession} from '../src/core/SimulationSession';
import {setPower} from '../src/core/PowerManager';
const total=(s:import('../src/core/types').Island,g:keyof typeof MODERN_FEE)=>s.civilization!.inventory[g]+s.buildings.reduce((sum,b)=>sum+(b.buffer?.input[g]??0)+(b.buffer?.output[g]??0),0)+s.npcs.filter(n=>n.isAlive).reduce((sum,n)=>sum+(n.freight?.good===g?n.freight.amount:0),0);
const raw=readFileSync('artifacts/modern-ready-save.json','utf8');
for(const missing of ['steel','cutStone','cloth'] as const){const d=decodeSave(raw),c=d.island.civilization!;c.inventory[missing]=MODERN_FEE[missing]-1;const before=structuredClone(c.inventory);assert(beginModernDevelopment(d.island));assert.deepEqual(c.inventory,before);assert(!c.transition);}
const poor=decodeSave(raw);poor.island.sharedFood=0;const before=structuredClone(poor.island.civilization!.inventory);assert(beginModernDevelopment(poor.island));assert.deepEqual(poor.island.civilization!.inventory,before);
const data=decodeSave(raw),s=data.island,c=s.civilization!,initial=structuredClone(c.inventory),food=s.sharedFood,totals={steel:total(s,'steel'),cutStone:total(s,'cutStone'),cloth:total(s,'cloth')};assert(modernRequirements(s).every(r=>r.met));assert.equal(beginModernDevelopment(s),null);for(const [g,a] of Object.entries(MODERN_FEE))assert.equal(c.inventory[g as keyof typeof MODERN_FEE],initial[g as keyof typeof MODERN_FEE]-a);assert.equal(s.sharedFood,food);assert.equal(c.transition!.ticksNeeded,50);const paid=structuredClone(c.inventory);assert(beginModernDevelopment(s));assert.deepEqual(c.inventory,paid,'Repeated investment does not charge twice');
// The player can stop the prototype after the investment to retain new-era materials.
for(const b of s.buildings.filter(b=>['steam_generator','prototype_workshop'].includes(b.type)))assert.equal(setPower(s,b.id,false,1),null);let sim=new SimulationSession(s,data.map);for(let i=0;i<15;i++)sim.advanceTicks(1);assert.equal(c.era,'iron');assert.equal(c.transition!.workTicks,15);const stage=encodeSave(s,data.map,data.config);writeFileSync('artifacts/modern-investment-stage-save.json',stage);const restored=decodeSave(stage);assert.deepEqual(restored.island.civilization,c);sim=new SimulationSession(restored.island,restored.map);for(let i=0;i<34;i++)sim.advanceTicks(1);assert.equal(restored.island.civilization!.era,'iron');assert.equal(restored.island.civilization!.transition!.workTicks,49);sim.advanceTicks(1);assert.equal(restored.island.civilization!.era,'modern');assert(!restored.island.civilization!.transition);for(const [g,a] of Object.entries(MODERN_FEE))assert.equal(total(restored.island,g as keyof typeof MODERN_FEE),totals[g as keyof typeof MODERN_FEE]-a);assert.equal(restored.island.npcs.filter(n=>n.isAlive).length,50);
for(const corrupt of [{target:'modern',workTicks:15,ticksNeeded:49},{target:'modern',workTicks:51,ticksNeeded:50},{target:'modern',workTicks:-1,ticksNeeded:50}]){const bad=JSON.parse(stage);bad.island.civilization.transition=corrupt;assert.throws(()=>decodeSave(JSON.stringify(bad)),/Tiến độ phát triển/);}const wrong=JSON.parse(stage);wrong.island.civilization.era='bronze';assert.throws(()=>decodeSave(JSON.stringify(wrong)),/Tiến độ phát triển/);
const live=decodeSave(raw),session=new SimulationSession(live.island,live.map);assert(session.submit({playerId:'release',sequence:1,command:{type:'develop_era'}}).accepted);assert.equal(live.island.civilization!.inventory.steel,initial.steel-30);console.log('PASS staged investment: earned 50-person town, atomic actual 30 steel/40 stone/20 cloth fees, no Food debit/double fee, 15-step exact reload/49-before-50 completion, 50 alive, invalid timers/source eras rejected. Public Modern investment enabled after factory gameplay verification.');
