import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {decodeSave,encodeSave} from '../src/core/SaveSystem';
import {reserveEntityIds} from '../src/core/factory';
import {SimulationSession,type PlayerCommand} from '../src/core/SimulationSession';
const d=decodeSave(readFileSync('artifacts/eldritch-played-save.json','utf8')),s=d.island,c=s.civilization!;reserveEntityIds(s);const sim=new SimulationSession(s,d.map);let seq=0,trips=0,assembly=false;const initial=s.tick,startProduction=c.produced.components;
const send=(command:PlayerCommand)=>{const r=sim.submit({playerId:'eldritch-preparation',sequence:++seq,command});assert(r.accepted,JSON.stringify({command,r}));};
const until=(ok:()=>boolean,max=4000)=>{for(let i=0;i<max&&!ok();i++){sim.advanceTicks(1);assert.equal(s.npcs.filter(n=>n.isAlive).length,50);if(assembly&&c.produced.components-startProduction>=51&&factory.powerEnabled!==false)send({type:'set_power',buildingId:factory.id,enabled:false,priority:2});}if(!ok())writeFileSync('artifacts/eldritch-preparation-waiting-save.json',encodeSave(s,d.map,d.config));assert(ok(),JSON.stringify({tick:s.tick,food:s.sharedFood,goods:c.inventory,buildings:s.buildings.filter(b=>b.workers.length).map(b=>({id:b.id,type:b.type,buffer:b.buffer,message:b.workMessage}))}));};
const gen=s.buildings.find(b=>b.type==='steam_generator')!,lab=s.buildings.find(b=>b.type==='measurement_lab')!,factory=s.buildings.find(b=>b.type==='component_factory')!,post=s.buildings.find(b=>b.type==='tradepost')!,iron=s.buildings.find(b=>b.type==='iron_smelter')!,steel=s.buildings.find(b=>b.type==='steelworks')!,tower=s.buildings.find(b=>b.type==='quarantine')!;
for(const b of s.buildings.filter(b=>['steam_generator','measurement_lab','component_factory','prototype_workshop','biomatter_workshop','quarantine'].includes(b.type)))send({type:'set_power',buildingId:b.id,enabled:false,priority:1});
for(const b of s.buildings.filter(b=>['component_factory','prototype_workshop','relic_extractor','biomatter_workshop','quarantine','coal_mine'].includes(b.type)))for(const id of [...b.workers]){send({type:'remove_worker',buildingId:b.id,npcId:id});send({type:'assign_labor',npcId:id,role:'food'});}
const crew=s.npcs.filter(n=>n.isAlive&&n.age>=18&&n.laborRole==='food'&&!n.guardDuty&&!s.buildings.some(b=>b.workers.includes(n.id))).slice(-3);assert.equal(crew.length,3);const [trader,miner,smith]=crew;for(const n of crew)send({type:'assign_labor',npcId:n.id,role:'idle'});for(const [b,n] of [[post,trader],[iron,miner],[steel,smith]] as const)send({type:'assign_worker',buildingId:b.id,npcId:n.id});
const trip=(offerId:string,fee:number)=>{until(()=>!trader.cargo&&!trader.freight&&!trader.actionTarget&&!trader.haulTask);const cloth=c.inventory.cloth;send({type:'start_trade',buildingId:post.id,offerId});assert.equal(c.inventory.cloth,cloth-fee);until(()=>!post.shipment);trips++;};
for(let i=0;i<24;i++){trip('cloth_for_ore',4);if(i<20)trip('cloth_for_coal',8);if(i<5)trip('cloth_for_copper',12);}
until(()=>c.inventory.steel>=60);for(const [b,n] of [[iron,miner],[steel,smith],[post,trader]] as const){send({type:'remove_worker',buildingId:b.id,npcId:n.id});send({type:'assign_labor',npcId:n.id,role:'food'});}writeFileSync('artifacts/eldritch-metals-earned-save.json',encodeSave(s,d.map,d.config));
send({type:'assign_worker',buildingId:factory.id,npcId:smith.id});assembly=true;send({type:'set_power',buildingId:factory.id,enabled:true,priority:2});send({type:'set_power',buildingId:gen.id,enabled:true,priority:1});until(()=>c.inventory.components>=51);send({type:'set_power',buildingId:factory.id,enabled:false,priority:2});send({type:'set_power',buildingId:gen.id,enabled:false,priority:1});send({type:'remove_worker',buildingId:factory.id,npcId:smith.id});send({type:'assign_labor',npcId:smith.id,role:'food'});assert(c.inventory.steel>=20);assert.equal(c.produced.components-startProduction,51);assert.equal(c.era,'modern');assert.equal(c.anomalyBranch,undefined);assert.equal(lab.labPoweredTicks,0);assert.equal(tower.quarantineCareTicks,20);assert(s.surveys!.sites.find(p=>p.kind==='eldritch')!.foundationComplete);const raw=encodeSave(s,d.map,d.config);decodeSave(raw);writeFileSync('artifacts/eldritch-prepared-save.json',raw);console.log(JSON.stringify({passed:true,alternateEarned:true,steps:s.tick-initial,trips,alive:50,food:s.sharedFood,inventory:c.inventory,newComponents:c.produced.components-startProduction,labProof:lab.labPoweredTicks}));
