import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE??'playwright');const root=path.resolve('web');
const server=createServer(async(req,res)=>{const file=path.resolve(root,'.'+new URL(req.url??'/','http://localhost').pathname.replace(/\/$/,'/index.html'));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{res.setHeader('content-type',({'.html':'text/html','.css':'text/css','.js':'text/javascript','.svg':'image/svg+xml','.png':'image/png'} as Record<string,string>)[path.extname(file)]??'application/octet-stream');res.end(await readFile(file));}catch{res.writeHead(404).end();}});
async function main(){
 await mkdir('artifacts',{recursive:true});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors:string[]=[],failed:string[]=[];page.on('pageerror',(e:Error)=>errors.push(e.message));page.on('response',(r:any)=>{if(r.status()>=400)failed.push(r.url());});const url=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
 const close=async()=>{if(await page.locator('#panel-overlay').evaluate((e:HTMLElement)=>e.classList.contains('open')))await page.locator('#panel-close').click();};
 const pause=async(on:boolean)=>{await close();if((await page.locator('#btn-pause').evaluate((e:HTMLElement)=>e.classList.contains('active')))!==on)await page.locator('#btn-pause').click();};
 const save=async()=>{await close();await page.locator('#btn-save-local').click();return page.evaluate(()=>JSON.parse(localStorage.getItem('dao_thien_nguyen_v2')!));};
 const load=async(raw:string)=>{await page.goto(url);await page.evaluate((raw:string)=>localStorage.setItem('dao_thien_nguyen_v2',raw),raw);await page.reload();await page.locator('#btn-resume-game').click();await page.locator('.era-roadmap').waitFor();await pause(true);};
 const open=async()=>{await close();await page.locator('#sb-quests').click();await page.locator('.modern-preparation').waitFor();};
 try{
 const raw=await readFile('artifacts/industry-upgraded-save.json','utf8'),prior=JSON.parse(raw);await load(raw);const initial=await save();await open();assert.equal(await page.locator('[data-modern-requirement]').count(),10);assert.match(await page.locator('[data-modern-requirement="0"]').innerText(),/25\/50/);assert.match(await page.locator('[data-modern-requirement="1"]').innerText(),/15\/25/);assert(await page.locator('#btn-develop-era').isDisabled());await page.locator('.modern-preparation').scrollIntoViewIfNeeded();await page.waitForTimeout(300);await page.screenshot({path:'artifacts/modern-preparation-desktop.png'});
 await page.locator('[data-modern-requirement="1"] button').click();await page.locator('[data-build="house"]').waitFor();await open();await page.locator('[data-modern-requirement="9"] button').click();assert(!await page.locator('.modern-preparation').count());const unchanged=await save();assert.deepEqual(unchanged.island.civilization.inventory,initial.island.civilization.inventory);assert.equal(unchanged.island.sharedFood,initial.island.sharedFood);assert.equal(unchanged.island.tick,initial.island.tick);assert.equal(unchanged.island.civilization.era,'iron');
 await page.setViewportSize({width:390,height:844});await open();await page.locator('.modern-preparation').scrollIntoViewIfNeeded();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.waitForTimeout(300);await page.screenshot({path:'artifacts/modern-preparation-mobile.png'});
 const town=await readFile('artifacts/modern-50-stable-save.json','utf8');await page.setViewportSize({width:1440,height:1000});await load(town);await open();assert.match(await page.locator('[data-modern-requirement="0"]').innerText(),/50\/50/);assert.match(await page.locator('[data-modern-requirement="1"]').innerText(),/50\/50/);assert(await page.locator('[data-modern-requirement="9"]').evaluate((e:HTMLElement)=>e.classList.contains('met')));assert(await page.locator('#btn-develop-era').isDisabled());await page.locator('.modern-preparation').scrollIntoViewIfNeeded();await page.waitForTimeout(300);await page.screenshot({path:'artifacts/modern-50-preparation-desktop.png'});await close();await page.locator('#btn-zoom-in').click();await page.waitForTimeout(300);await page.screenshot({path:'artifacts/modern-50-island.png'});
 // Isolated scarcity fixture only: verify actual browser steps go to onsite food and recover.
 const emergency=structuredClone(prior),n=emergency.island.npcs[0],farm=emergency.island.buildings.find((b:any)=>b.type==='farm');emergency.island.sharedFood=0;for(const other of emergency.island.npcs){other.privateFood=20;other.needs.hunger=20;}n.privateFood=0;n.needs.hunger=90;n.health=100;n.guardDuty=false;n.position={tileX:farm.tileX-2,tileY:farm.tileY};farm.buffer.output.food=30;await page.setViewportSize({width:1440,height:1000});await load(JSON.stringify(emergency));await pause(false);await page.locator('.speed-btn[data-speed="2"]').click();await page.waitForTimeout(4200);await pause(true);const after=await save(),fed=after.island.npcs.find((other:any)=>other.id===n.id);assert(fed.isAlive);assert(fed.needs.hunger<80,JSON.stringify(fed));assert.equal(after.island.civilization.era,'iron');await page.waitForTimeout(300);await page.screenshot({path:'artifacts/emergency-meal-browser-fixture.png'});await writeFile('artifacts/emergency-meal-browser-fixture-save.json',JSON.stringify(after));assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);console.log('PASS browser: ten real preparation requirements, 25/50 settlers and 15/25 actual beds, locked Modern/no fees deducted, earned 50-person town/50 beds/seven-day food shown, navigation, desktop/mobile no overflow/errors; isolated scarcity fixture physically eats onsite food and survives actual ticks.');
 }catch(e){await page.waitForTimeout(300);await page.screenshot({path:'artifacts/modern-preparation-ui-failure.png'});throw e;}finally{await browser.close();server.close();}
}
main().catch(e=>{console.error(e);process.exitCode=1;});
