import assert from 'node:assert/strict';
import { createIsland } from '../src/core/factory';
import { SimulationSession } from '../src/core/SimulationSession';
import { settlerCapacity, SETTLER_COST } from '../src/core/settlers';
import { generateWorldMap } from '../src/renderer/WorldMap';
import { CreaturesPanel } from '../src/ui/CreaturesPanel';
import { ResearchPanel } from '../src/ui/ResearchPanel';
import { createGameState, type IslandStats } from '../src/game/GameState';
import { TECH_TREE, startResearch, tickResearch } from '../src/core/research';
import { feedAnimal } from '../src/core/AnimalSystem';
import { createAnimal } from '../src/core/factory';

const map = generateWorldMap(50, 35, 321);
const island = createIsland('Creature test', 3);
const session = new SimulationSession(island, map);
let sequence = 0;
const submit = (command: Parameters<SimulationSession['submit']>[0]['command']) => session.submit({ playerId: 'test', sequence: ++sequence, command });
island.sharedFood = 1000;
island.wood = 1000;
assert.equal(submit({ type: 'invite_settler', tileX: map.landTiles[4].x, tileY: map.landTiles[4].y }).accepted, false, 'Unplaced founders must be placed first');
for (const [i, npc] of island.npcs.entries()) {
  const tile = map.landTiles[i];
  assert(submit({ type: 'place_npc', npcId: npc.id, tileX: tile.x, tileY: tile.y }).accepted);
}
const before = { food: island.sharedFood, wood: island.wood, pop: island.npcs.length };
assert(!submit({ type: 'invite_settler', tileX: 0, tileY: 0 }).accepted);
assert(!submit({ type: 'invite_settler', tileX: map.landTiles[0].x, tileY: map.landTiles[0].y }).accepted);
assert.equal(island.sharedFood, before.food, 'Invalid placement must not spend food');
assert.equal(island.wood, before.wood);
const tile = map.landTiles[4];
const envelope = { playerId: 'test', sequence: ++sequence, command: { type: 'invite_settler' as const, tileX: tile.x, tileY: tile.y } };
assert(session.submit(envelope).accepted);
assert(session.submit(envelope).duplicate);
assert.equal(island.npcs.length, before.pop + 1, 'Retry must not duplicate a settler');
assert.equal(island.sharedFood, before.food - SETTLER_COST.food);
assert.equal(island.wood, before.wood - SETTLER_COST.wood);
assert.deepEqual(island.npcs.at(-1)?.position, { tileX: tile.x, tileY: tile.y });
island.sharedFood = 0;
assert(!submit({ type: 'invite_settler', tileX: map.landTiles[5].x, tileY: map.landTiles[5].y }).accepted);
island.sharedFood = 10000;
island.wood = 10000;
for (let i = 5; island.npcs.length < 15; i++) assert(submit({ type: 'invite_settler', tileX: map.landTiles[i].x, tileY: map.landTiles[i].y }).accepted);
assert(!submit({ type: 'invite_settler', tileX: map.landTiles[30].x, tileY: map.landTiles[30].y }).accepted);
island.buildings.push({ id: 'house', type: 'house', tileX: 1, tileY: 1, workers: [], progress: 99, complete: false });
assert.equal(settlerCapacity(island), 15);
island.buildings[0].complete = true;
assert.equal(settlerCapacity(island), 20);
assert(submit({ type: 'invite_settler', tileX: map.landTiles[30].x, tileY: map.landTiles[30].y }).accepted);

const gs = createGameState();
const creatures = new CreaturesPanel();
assert.match(creatures.renderHTML(island, gs, false), /Cần nghiên cứu Thuần Hóa Bò/);
gs.unlocks.add('domesticate_cattle');
assert.match(creatures.renderHTML(island, gs, false), /data-creature="cattle" >Đặt bò/);
assert.match(creatures.renderHTML(island, gs, true), /data-creature="cattle" disabled/);
const cow = createAnimal('cattle', tile.x, tile.y);
island.animals.push(cow);
for (let i = 0; i < 4; i++) feedAnimal(island, cow.id, 10);
assert.equal(cow.status, 'domesticated');

const stats: IslandStats = { population: 16, sharedFood: 1000, wood: 1000, stone: 1000, herbs: 100, buildingCount: 1, completedBuildingCount: 1, elderCount: 0, daysPassed: 1, maxGeneration: 0, maxAdultGeneration: 0, domesticatedSpecies: 0 };
const panel = new ResearchPanel();
let html = panel.renderHTML(island, gs, stats, null);
assert.equal((html.match(/<section class="tech-group">/g) ?? []).length, new Set(TECH_TREE.map(t => `${t.needEra}:${t.category}`)).size);
assert.equal((html.match(/data-tech="[^"]+">/g) ?? []).length >= TECH_TREE.length, true);
const fire = TECH_TREE.find(t => t.id === 'fire')!;
island.stone = 1000;
const progress = startResearch(fire, island, gs, stats, 1)!;
assert(progress);
html = panel.renderHTML(island, gs, stats, progress);
assert.match(html, /tc-active/);
assert.match(html, /Đang nghiên cứu/);
assert.equal(tickResearch(progress, gs, island, 1 + progress.daysNeeded), null);
assert(gs.unlocks.has('fire'));
assert.match(panel.renderHTML(island, gs, stats, null), /tc-done/);
// Two clients cannot spend the same immigration budget twice.
island.sharedFood = SETTLER_COST.food;
island.wood = SETTLER_COST.wood;
const popBeforeRace = island.npcs.length;
assert(session.submit({ playerId: 'client-a', sequence: 1, command: { type: 'invite_settler', tileX: map.landTiles[31].x, tileY: map.landTiles[31].y } }).accepted);
assert(!session.submit({ playerId: 'client-b', sequence: 1, command: { type: 'invite_settler', tileX: map.landTiles[32].x, tileY: map.landTiles[32].y } }).accepted);
assert.equal(island.npcs.length, popBeforeRace + 1);
assert.equal(island.sharedFood, 0);
assert.equal(island.wood, 0);
// Research bonuses remain applied when local commands use the session.
const harvestIsland = createIsland('Tools', 1);
const treeTile = map.landTiles.find(t => map.tiles[t.y][t.x] === 'forest')!;
harvestIsland.npcs[0].position = { tileX: treeTile.x, tileY: treeTile.y };
harvestIsland.resources.set(`${treeTile.x},${treeTile.y}`, { type: 'wood_tree', amount: 10, maxAmount: 10, regenRate: 0 });
harvestIsland.wood = 0;
const harvestSession = new SimulationSession(harvestIsland, map, () => 1.5);
assert(harvestSession.submit({ playerId: 'local', sequence: 1, command: { type: 'manual_action', npcId: harvestIsland.npcs[0].id, action: 'chop_wood' } }).accepted);
assert.equal(harvestIsland.wood, 4.5);
assert.equal(harvestIsland.resources.get(`${treeTile.x},${treeTile.y}`)?.amount, 5.5);
harvestIsland.resources.set(`${treeTile.x},${treeTile.y}`, { type: 'herb_patch', amount: 40, maxAmount: 40, regenRate: 0 });
assert(harvestSession.submit({ playerId: 'local', sequence: 2, command: { type: 'manual_action', npcId: harvestIsland.npcs[0].id, action: 'gather_food' } }).accepted);
assert(harvestIsland.herbs > 0, 'Foraging must provide herbs needed by animal research');
console.log('PASS: settler costs, invalid tiles, occupied tiles, replay, capacity, housing, animal unlocks/feeding, and research groups/progress/completion.');
