import {tickSurveys,cancelSurvey} from '../src/core/SurveyManager';
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {decodeSave,encodeSave} from '../src/core/SaveSystem';
import {reserveEntityIds} from '../src/core/factory';
import {SimulationSession,type PlayerCommand} from '../src/core/SimulationSession';
import {ERAS} from '../src/core/civilization';
const d=decodeSave(readFileSync('artifacts/modern-dispatch-played-save.json','utf8')),s=d.island,c=s.civilization!;reserveEntityIds(s);const sim=new SimulationSession(s,d.map);let seq=0;const start=s.tick;
const send=(command:PlayerCommand)=>{const r=sim.submit({playerId:'survey',sequence:++seq,command});assert(r.accepted,JSON.stringify({command,r}));};
const until=(ok:()=>boolean,max=1500)=>{for(let i=0;i<max&&!ok();i++){sim.advanceTicks(1);assert.equal(s.npcs.filter(n=>n.isAlive).length,50);}if(!ok())writeFileSync('artifacts/surveys-waiting-save.json',encodeSave(s,d.map,d.config));assert(ok(),JSON.stringify({tick:s.tick,state:s.surveys,n:s.npcs.find(n=>n.id===s.surveys?.active?.npcId)}));};
for(const b of s.buildings.filter(b=>['steam_generator','prototype_workshop','component_factory'].includes(b.type)))send({type:'set_power',buildingId:b.id,enabled:false,priority:1});
const n=s.npcs.find(n=>n.isAlive&&n.age>=18&&n.occupation!=='child'&&!n.guardDuty&&!s.buildings.some(b=>b.workers.includes(n.id))&&!n.researching&&!n.cargo&&!n.freight&&!n.haulTask&&!n.actionTarget)!;assert(n);send({type:'assign_labor',npcId:n.id,role:'idle'});const comps=c.inventory.components,parts=c.inventory.machineParts;send({type:'start_research',techId:'field_surveys'});assert.equal(c.inventory.components,comps-6);assert.equal(c.inventory.machineParts,parts-1);send({type:'assign_researcher',npcId:n.id});until(()=>c.unlocks.includes('field_surveys'));assert.equal(s.surveys!.sites.length,3);writeFileSync('artifacts/surveys-ready-save.json',encodeSave(s,d.map,d.config));
const clothTotal=()=>c.inventory.cloth+s.buildings.reduce((v,b)=>v+(b.buffer?.input.cloth??0)+(b.buffer?.output.cloth??0),0)+s.npcs.reduce((v,n)=>v+(n.freight?.good==='cloth'?n.freight.amount:0),0);const clothMass=clothTotal(),clothProduction=c.produced.cloth;
const site=s.surveys!.sites[0],before=structuredClone(c.inventory),envelope={playerId:'survey',sequence:++seq,command:{type:'start_survey' as const,siteId:site.id,npcId:n.id}};assert(sim.submit(envelope).accepted);assert(sim.submit(envelope).duplicate);assert.equal(c.inventory.components,before.components-2);assert.equal(c.inventory.cloth,before.cloth-2);assert(!sim.submit({playerId:'survey',sequence:++seq,command:{type:'assign_labor',npcId:n.id,role:'food'}}).accepted);assert(!sim.submit({playerId:'survey',sequence:++seq,command:{type:'assign_worker',buildingId:s.buildings[0].id,npcId:n.id}}).accepted);const pos=structuredClone(n.position);sim.advanceTicks(1);assert.notDeepEqual(n.position,pos);assert(!site.surveyed);const mid=encodeSave(s,d.map,d.config);assert.deepEqual(decodeSave(mid).island.surveys,s.surveys);writeFileSync('artifacts/surveys-outbound-save.json',mid);send({type:'cancel_survey'});assert.equal(c.inventory.components,before.components);assert.equal(c.inventory.cloth,before.cloth);assert(!sim.submit({playerId:'survey',sequence:++seq,command:{type:'cancel_survey'}}).accepted);
for(const site of s.surveys!.sites){until(()=>!n.researching&&!n.cargo&&!n.freight&&!n.haulTask&&!n.actionTarget);send({type:'start_survey',siteId:site.id,npcId:n.id});until(()=>s.surveys!.active?.stage==='observing');assert.deepEqual(n.position,{tileX:site.x,tileY:site.y});assert(!site.surveyed);assert.deepEqual(decodeSave(encodeSave(s,d.map,d.config)).island.surveys,s.surveys);until(()=>s.surveys!.active?.stage==='returning');assert(!site.surveyed);until(()=>site.surveyed);assert(!s.surveys!.active);const home=s.buildings.find(b=>b.type==='study_table')!;assert.deepEqual(n.position,{tileX:home.tileX,tileY:home.tileY});}
assert.equal(s.surveys!.sites.filter(p=>p.surveyed).length,3);assert.equal(c.inventory.components,before.components-6);assert.equal(clothTotal(),clothMass+c.produced.cloth-clothProduction-6);assert.equal(c.anomalyBranch,undefined);writeFileSync('artifacts/surveys-played-save.json',encodeSave(s,d.map,d.config));console.log(`PASS earned field surveys: paid research/dispatch/replay/cancel/refund, exclusive NPC, physical move/10 onsite work/return-before-record, exact phase saves, 3 returned files, 50 alive/Food ${s.sharedFood.toFixed(1)}, ${s.tick-start} steps; no analysis/Anomaly unlock.`);
for(const mutate of [(v:any)=>v.island.surveys.active.workTicks=11,(v:any)=>v.island.surveys.active.npcId='missing']){const v=JSON.parse(mid);mutate(v);assert.throws(()=>decodeSave(JSON.stringify(v)),/khảo sát/);}console.log('PASS corrupt survey timer/owner rejected.');

const blocked=decodeSave(mid),u=blocked.island,a=u.surveys!.active!,point=u.surveys!.sites.find(p=>p.id===a.siteId)!;blocked.map.tiles[point.y][point.x]='deep_water';const kept=JSON.stringify(a);tickSurveys(u,blocked.map);assert.equal(JSON.stringify(u.surveys!.active),kept);assert.match(u.surveys!.message,/chặn/);const paid=u.civilization!.inventory.components;assert.equal(cancelSurvey(u),null);assert.equal(u.civilization!.inventory.components,paid+2);console.log('PASS blocked-path fixture holds field progress and refunds once without a file.');
