import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE??'playwright');const root=path.resolve('web');
const server=createServer(async(req,res)=>{const file=path.resolve(root,'.'+new URL(req.url??'/','http://localhost').pathname.replace(/\/$/,'/index.html'));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{res.setHeader('content-type',({'.html':'text/html','.css':'text/css','.js':'text/javascript','.svg':'image/svg+xml','.png':'image/png'} as Record<string,string>)[path.extname(file)]??'application/octet-stream');res.end(await readFile(file));}catch{res.writeHead(404).end();}});
async function main(){
 await mkdir('artifacts',{recursive:true});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors:string[]=[],failed:string[]=[];page.on('pageerror',(e:Error)=>errors.push(e.message));page.on('response',(r:any)=>{if(r.status()>=400)failed.push(r.url());});const url=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
 const close=async()=>{if(await page.locator('#building-inspector').isVisible())await page.locator('#bi-close').click();if(await page.locator('#panel-overlay').evaluate((e:HTMLElement)=>e.classList.contains('open')))await page.locator('#panel-close').click();};
 const pause=async(on:boolean)=>{await close();if((await page.locator('#btn-pause').evaluate((e:HTMLElement)=>e.classList.contains('active')))!==on)await page.locator('#btn-pause').click();};
 const save=async()=>{await close();await page.locator('#btn-save-local').click();return page.evaluate(()=>JSON.parse(localStorage.getItem('dao_thien_nguyen_v2')!));};
 const load=async(raw:string)=>{await page.goto(url);await page.evaluate((raw:string)=>localStorage.setItem('dao_thien_nguyen_v2',raw),raw);await page.reload();await page.locator('#btn-resume-game').click();await page.locator('.era-roadmap').waitFor();await pause(true);};
 const open=async()=>{await close();await page.locator('#sb-quests').click();await page.locator('.era-roadmap').waitFor();await page.waitForTimeout(300);};
 const inspect=async(id:string)=>{await close();await page.locator('#btn-build').click();await page.locator(`[data-inspect-building="${id}"]`).click();await page.locator('#building-inspector').waitFor({state:'visible'});await page.waitForTimeout(300);};
 try{
 const raw=await readFile('artifacts/modern-dispatch-ready-save.json','utf8'),ready=JSON.parse(raw),plants=ready.island.buildings.filter((b:any)=>b.type==='component_factory'),proto=ready.island.buildings.find((b:any)=>b.type==='prototype_workshop'),blocked=plants[2];await load(raw);const before=await save();await open();assert.match(await page.locator('.power-summary').innerText(),/Cung 6 \/ nhu cầu 8/);assert.match(await page.locator('.power-shortfall').innerText(),/Thiếu 2 công suất/);await page.locator(`[data-power-building="${proto.id}"]`).scrollIntoViewIfNeeded();await page.screenshot({path:'artifacts/modern-dispatch-desktop.png'});
 await page.locator(`[data-power-priority="${blocked.id}"]`).selectOption('0');await page.locator(`[data-power-priority="${proto.id}"]`).selectOption('2');assert.equal(await page.locator(`[data-power-building="${proto.id}"]`).getAttribute('data-power-fed'),'true');assert.equal(await page.locator(`[data-power-building="${blocked.id}"]`).getAttribute('data-power-fed'),'false');const swap=await save();assert.deepEqual(swap.island.civilization.inventory,before.island.civilization.inventory);assert.equal(swap.island.tick,before.island.tick);assert.deepEqual(swap.island.buildings.find((b:any)=>b.id===blocked.id).buffer,before.island.buildings.find((b:any)=>b.id===blocked.id).buffer);await load(JSON.stringify(swap));await open();assert.equal(await page.locator(`[data-power-priority="${proto.id}"]`).inputValue(),'2');await page.locator(`[data-power-building="${blocked.id}"]`).scrollIntoViewIfNeeded();await page.screenshot({path:'artifacts/modern-dispatch-swapped.png'});
 await pause(false);await page.locator('.speed-btn[data-speed="2"]').click();await inspect(proto.id);await page.waitForFunction((n:number)=>{const m=document.querySelector('#building-inspector')?.textContent?.match(/Đã sản xuất (\d+) mẻ/);return !!m&&Number(m[1])>n;},proto.productionBatches??0,{timeout:60000});await pause(true);const ran=await save();assert.equal(ran.island.buildings.find((b:any)=>b.id===blocked.id).productionBatches??0,blocked.productionBatches??0);assert(ran.island.civilization.produced.machineParts>ready.island.civilization.produced.machineParts);assert.equal(ran.island.npcs.filter((n:any)=>n.isAlive).length,50);
 await page.setViewportSize({width:390,height:844});await open();await page.locator(`[data-power-priority="${blocked.id}"]`).selectOption('2');await page.locator(`[data-power-priority="${proto.id}"]`).selectOption('0');assert.equal(await page.locator(`[data-power-building="${blocked.id}"]`).getAttribute('data-power-fed'),'true');await page.locator(`[data-power-building="${proto.id}"]`).scrollIntoViewIfNeeded();await page.screenshot({path:'artifacts/modern-dispatch-mobile.png'});await page.locator(`[data-power-toggle="${proto.id}"]`).click();assert.match(await page.locator('.power-shortfall').innerText(),/Đủ công suất/);const off=await save();assert.equal(off.island.power.demand,6);await load(JSON.stringify(off));await open();assert.equal(off.island.power.supplied.length,3);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);console.log('PASS browser earned 3-factory dispatch: 6/8 deficit2, pause priority swap protects goods/buffer/tick, reload, live prototype production with blocked factory held/50 alive, mobile restore/toggle removes shortage/3 powered consumers, no errors/overflow.');
 }catch(e){await page.screenshot({path:'artifacts/modern-dispatch-ui-failure.png'});throw e;}finally{await browser.close();server.close();}
}
main().catch(e=>{console.error(e);server.close();process.exitCode=1;});
