import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE??'playwright');const root=path.resolve('web');
const server=createServer(async(req,res)=>{const file=path.resolve(root,'.'+new URL(req.url??'/','http://localhost').pathname.replace(/\/$/,'/index.html'));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{res.setHeader('content-type',({'.html':'text/html','.css':'text/css','.js':'text/javascript','.svg':'image/svg+xml','.png':'image/png'} as Record<string,string>)[path.extname(file)]??'application/octet-stream');res.end(await readFile(file));}catch{res.writeHead(404).end();}});
async function main(){
 await mkdir('artifacts',{recursive:true});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors:string[]=[],failed:string[]=[];page.on('pageerror',(e:Error)=>errors.push(e.message));page.on('response',(r:any)=>{if(r.status()>=400)failed.push(r.url());});const url=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
 const close=async()=>{if(await page.locator('#building-inspector').isVisible())await page.locator('#bi-close').click();if(await page.locator('#panel-overlay').evaluate((e:HTMLElement)=>e.classList.contains('open')))await page.locator('#panel-close').click();};
 const pause=async(on:boolean)=>{await close();if((await page.locator('#btn-pause').evaluate((e:HTMLElement)=>e.classList.contains('active')))!==on)await page.locator('#btn-pause').click();};
 const save=async()=>{await close();await page.locator('#btn-save-local').click();return page.evaluate(()=>JSON.parse(localStorage.getItem('dao_thien_nguyen_v2')!));};
 const load=async(raw:string)=>{await page.goto(url);await page.evaluate((raw:string)=>localStorage.setItem('dao_thien_nguyen_v2',raw),raw);await page.reload();await page.locator('#btn-resume-game').click();await page.locator('.era-roadmap').waitFor();await pause(true);};
 const open=async()=>{await close();await page.locator('#sb-quests').click();await page.locator('.era-roadmap').waitFor();await page.waitForTimeout(300);};
 const inspect=async(id:string)=>{await close();await page.locator('#btn-build').click();await page.locator(`[data-inspect-building="${id}"]`).click();await page.locator('#building-inspector').waitFor({state:'visible'});await page.waitForTimeout(300);};
 try{
 const production=await readFile('artifacts/clinic-production-ready-save.json','utf8'),pbase=JSON.parse(production),pharmacy=pbase.island.buildings.find((b:any)=>b.type==='apothecary'),clinic=pbase.island.buildings.find((b:any)=>b.type==='clinic');await load(production);await inspect(pharmacy.id);await page.screenshot({path:'artifacts/clinic-production-desktop.png'});await pause(false);await page.locator('.speed-btn[data-speed="2"]').click();await page.waitForTimeout(16000);await pause(true);const produced=await save();assert(produced.island.civilization.produced.medicine>pbase.island.civilization.produced.medicine);assert.equal(produced.island.npcs.filter((n:any)=>n.isAlive).length,50);await inspect(clinic.id);await page.screenshot({path:'artifacts/clinic-building-desktop.png'});
 const fixture=await readFile('artifacts/clinic-child-fixture-save.json','utf8'),base=JSON.parse(fixture),patient=base.island.npcs.find((n:any)=>n.clinicalCare),initialDoses=base.island.buildings.find((b:any)=>b.type==='clinic').clinicalDoses??0;await load(fixture);await page.locator('#btn-military').click();await page.locator(`[data-clinic-request="${patient.id}"]`).click();let cancelled=await save();assert.equal(cancelled.island.npcs.find((n:any)=>n.id===patient.id).clinicalCare,undefined);await page.locator('#btn-military').click();await page.locator('#clinic-choice').selectOption(clinic.id);await page.locator(`[data-clinic-request="${patient.id}"]`).click();let queued=await save();assert.equal(queued.island.npcs.find((n:any)=>n.id===patient.id).clinicalCare.paid,false);await load(JSON.stringify(queued));await page.locator('#btn-military').click();await page.locator(`[data-clinic-patient="${patient.id}"]`).scrollIntoViewIfNeeded();await page.screenshot({path:'artifacts/clinic-child-care-desktop.png'});await pause(false);await page.locator('.speed-btn[data-speed="2"]').click();await page.waitForTimeout(20000);await pause(true);const healed=await save(),child=healed.island.npcs.find((n:any)=>n.id===patient.id),treated=healed.island.buildings.find((b:any)=>b.type==='clinic');assert.equal(child.health,100);assert.equal(child.clinicalCare,undefined);assert.equal(treated.clinicalDoses,initialDoses+1);assert.equal(treated.completedCare,1);assert.equal(healed.island.npcs.filter((n:any)=>n.isAlive).length,50);
 const partial=await readFile('artifacts/clinic-partial-fixture-save.json','utf8');await load(partial);await open();await page.locator(`[data-power-toggle="${clinic.id}"]`).click();const off=await save();assert.equal(off.island.buildings.find((b:any)=>b.id===clinic.id).powerEnabled,false);await load(JSON.stringify(off));await pause(false);await page.locator('.speed-btn[data-speed="2"]').click();await page.waitForTimeout(5000);await pause(true);const held=await save();assert.equal(held.island.npcs.find((n:any)=>n.id===patient.id).clinicalCare.workTicks,1);assert.equal(held.island.buildings.find((b:any)=>b.id===clinic.id).clinicalDoses,1);await open();await page.locator(`[data-power-toggle="${clinic.id}"]`).click();await pause(false);await page.waitForTimeout(18000);await pause(true);const resumed=await save();assert.equal(resumed.island.npcs.find((n:any)=>n.id===patient.id).clinicalCare,undefined);assert.equal(resumed.island.buildings.find((b:any)=>b.id===clinic.id).clinicalDoses,1);
 await page.setViewportSize({width:390,height:844});await load(fixture);await page.locator('#btn-military').click();await page.locator(`[data-clinic-patient="${patient.id}"]`).scrollIntoViewIfNeeded();await page.screenshot({path:'artifacts/clinic-mobile.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);console.log('PASS clinic browser: earned live medicine/50alive/textures, public cancel/request/pause/reload, controlled child treatment1dose5steps, outage holds/reload/resume no double charge, mobile/no errors.');
 }catch(e){console.error(e);try{await page.screenshot({path:'artifacts/clinic-ui-failure.png'});}catch{}throw e;}finally{await browser.close();server.close();}
}
main().catch(e=>{console.error(e);server.close();process.exitCode=1;});
