import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE??'playwright');const root=path.resolve('web');
const server=createServer(async(req,res)=>{const file=path.resolve(root,'.'+new URL(req.url??'/','http://localhost').pathname.replace(/\/$/,'/index.html'));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{res.setHeader('content-type',({'.html':'text/html','.css':'text/css','.js':'text/javascript','.svg':'image/svg+xml','.png':'image/png'} as Record<string,string>)[path.extname(file)]??'application/octet-stream');res.end(await readFile(file));}catch{res.writeHead(404).end();}});
async function main(){
 await mkdir('artifacts',{recursive:true});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors:string[]=[],failed:string[]=[];page.on('pageerror',(e:Error)=>errors.push(e.message));page.on('response',(r:any)=>{if(r.status()>=400)failed.push(r.url());});const url=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
 const close=async()=>{if(await page.locator('#building-inspector').isVisible())await page.locator('#bi-close').click();if(await page.locator('#panel-overlay').evaluate((e:HTMLElement)=>e.classList.contains('open')))await page.locator('#panel-close').click();};
 const pause=async(on:boolean)=>{await close();if((await page.locator('#btn-pause').evaluate((e:HTMLElement)=>e.classList.contains('active')))!==on)await page.locator('#btn-pause').click();};
 const save=async()=>{await close();await page.locator('#btn-save-local').click();return page.evaluate(()=>JSON.parse(localStorage.getItem('dao_thien_nguyen_v2')!));};
 const load=async(raw:string)=>{await page.goto(url);await page.evaluate((raw:string)=>localStorage.setItem('dao_thien_nguyen_v2',raw),raw);await page.reload();await page.locator('#btn-resume-game').click();await page.locator('.era-roadmap').waitFor();await pause(true);};
 const open=async()=>{await close();await page.locator('#sb-quests').click();await page.locator('.era-roadmap').waitFor();await page.waitForTimeout(300);};
 const inspect=async(id:string)=>{await close();await page.locator('#btn-build').click();await page.locator(`[data-inspect-building="${id}"]`).click();await page.locator('#building-inspector').waitFor({state:'visible'});await page.waitForTimeout(300);};
 try{
 const raw=await readFile('artifacts/microchips-ready-save.json','utf8'),ready=JSON.parse(raw),chip=ready.island.buildings.find((b:any)=>b.type==='microchip_factory');await load(raw);await inspect(chip.id);assert.doesNotMatch(await page.locator('.bi-state').innerText(),/Thiếu điện/);assert.match(await page.locator('.bi-level').innerText(),/Cấp 1 \/ 1.*Hiện Đại/);assert.match(await page.locator('#building-inspector').innerText(),/2 linh kiện.*1 đồng/);await page.waitForFunction(()=>[...document.querySelectorAll<HTMLImageElement>('.bi-texture')].every(i=>i.complete&&i.naturalWidth>0));await page.screenshot({path:'artifacts/microchips-factory-desktop.png'});await load(await readFile('artifacts/microchips-paused-save.json','utf8'));await open();await page.locator(`[data-power-toggle="${chip.id}"]`).click();await pause(false);await page.locator('.speed-btn[data-speed="2"]').click();await page.waitForTimeout(16000);await pause(true);const live=await save();assert(live.island.civilization.produced.microchips>1);assert.equal(live.island.npcs.filter((n:any)=>n.isAlive).length,50);
 await load(await readFile('artifacts/microchips-produced-save.json','utf8'));const before=await save();await close();await page.locator('#btn-research').click();const card=page.locator('.tech-card[data-tech="industrial_control"]');await card.scrollIntoViewIfNeeded();assert.match(await card.innerText(),/4 Vi mạch|4 vi mạch|Vi mạch.*4/);await page.screenshot({path:'artifacts/microchips-research-desktop.png'});await page.locator('.tc-research-btn[data-tech="industrial_control"]').click();const paid=await save();assert.equal(paid.island.civilization.inventory.microchips,before.island.civilization.inventory.microchips-4);assert.equal(paid.island.civilization.research.techId,'industrial_control');await load(JSON.stringify(paid));const restored=await save();assert.equal(restored.island.civilization.research.techId,'industrial_control');assert.equal(restored.island.civilization.inventory.microchips,paid.island.civilization.inventory.microchips);
 const controlled=await readFile('artifacts/control-center-ready-save.json','utf8'),center=JSON.parse(controlled).island.buildings.find((b:any)=>b.type==='control_center');await load(controlled);await inspect(center.id);assert.match(await page.locator('.bi-state').innerText(),/Đang điều phối/);await page.screenshot({path:'artifacts/control-center-desktop.png'});await open();await page.locator(`[data-power-toggle="${center.id}"]`).click();await inspect(center.id);assert.match(await page.locator('.bi-state').innerText(),/chưa tăng tốc/);await open();await page.locator(`[data-power-toggle="${center.id}"]`).click();await inspect(center.id);assert.match(await page.locator('.bi-state').innerText(),/Đang điều phối/);
 await page.setViewportSize({width:390,height:844});await load(await readFile('artifacts/microchips-played-save.json','utf8'));await inspect(center.id);await page.screenshot({path:'artifacts/control-center-mobile.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await open();await page.locator('.analysis-panel h3').scrollIntoViewIfNeeded();assert.match(await page.locator('.analysis-panel').innerText(),/Dị Tượng vẫn khóa/);assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);console.log('PASS browser earned microchips: texture/level1/Modern, public outage toggle/live chip production/50 alive, public4chips research cost/pause/reload, control active/off/on feedback, mobile/no overflow/errors/Anomaly locked.');
 }catch(e){console.error(e);try{await page.screenshot({path:'artifacts/microchips-ui-failure.png'});}catch{}throw e;}finally{await browser.close();server.close();}
}
main().catch(e=>{console.error(e);server.close();process.exitCode=1;});
