import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE??'playwright');const root=path.resolve('web');
const server=createServer(async(req,res)=>{const file=path.resolve(root,'.'+new URL(req.url??'/','http://localhost').pathname.replace(/\/$/,'/index.html'));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{res.setHeader('content-type',({'.html':'text/html','.css':'text/css','.js':'text/javascript','.svg':'image/svg+xml','.png':'image/png'} as Record<string,string>)[path.extname(file)]??'application/octet-stream');res.end(await readFile(file));}catch{res.writeHead(404).end();}});
async function main(){
 await mkdir('artifacts',{recursive:true});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors:string[]=[],failed:string[]=[];page.on('pageerror',(e:Error)=>errors.push(e.message));page.on('response',(r:any)=>{if(r.status()>=400)failed.push(r.url());});const url=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
 const close=async()=>{if(await page.locator('#building-inspector').isVisible())await page.locator('#bi-close').click();if(await page.locator('#panel-overlay').evaluate((e:HTMLElement)=>e.classList.contains('open')))await page.locator('#panel-close').click();};
 const pause=async(on:boolean)=>{await close();if((await page.locator('#btn-pause').evaluate((e:HTMLElement)=>e.classList.contains('active')))!==on)await page.locator('#btn-pause').click();};
 const save=async()=>{await close();await page.locator('#btn-save-local').click();return page.evaluate(()=>JSON.parse(localStorage.getItem('dao_thien_nguyen_v2')!));};
 const load=async(raw:string)=>{await page.goto(url);await page.evaluate((raw:string)=>localStorage.setItem('dao_thien_nguyen_v2',raw),raw);await page.reload();await page.locator('#btn-resume-game').click();await page.locator('.era-roadmap').waitFor();await pause(true);};
 const open=async()=>{await close();await page.locator('#sb-quests').click();await page.locator('.era-roadmap').waitFor();await page.waitForTimeout(300);};
 const inspect=async(id:string)=>{await close();await page.locator('#btn-build').click();await page.locator(`[data-inspect-building="${id}"]`).click();await page.locator('#building-inspector').waitFor({state:'visible'});await page.waitForTimeout(300);};




 try{
 const raw=await readFile('artifacts/patrol-ready-save.json','utf8'),initial=JSON.parse(raw),id=initial.island.npcs.find((n:any)=>n.torch).id;
 await load(raw);await open();await page.locator('#explorer-choice').selectOption(id);await page.locator('#toggle-patrol').click();const on=await save();assert(on.island.exploration.patrol.enabled);assert.equal(on.island.exploration.patrol.npcId,id);await open();assert(await page.locator('#explorer-choice').isDisabled());assert(await page.locator('#craft-exploration-torch').isDisabled());await page.screenshot({path:'artifacts/patrol-start-desktop.png'});
 await pause(false);await open();await page.waitForFunction(()=>document.querySelector('.discovery-list')?.textContent?.includes('Đã xử lý'),{},{timeout:60000});await pause(true);const mid=await save();assert(mid.island.exploration.points.some((p:any)=>p.claimed));await writeFile('artifacts/patrol-browser-midtrip-save.json',JSON.stringify(mid));await load(JSON.stringify(mid));const loaded=await save();assert.deepEqual(loaded.island.exploration.points,mid.island.exploration.points);assert.deepEqual(loaded.island.exploration.active,mid.island.exploration.active);
 await pause(false);await open();await page.waitForFunction(()=>document.querySelectorAll('[data-discovery]').length===3&&[...document.querySelectorAll('[data-discovery]')].every(p=>p.textContent?.includes('Đã xử lý')),{},{timeout:60000});await pause(true);await open();await page.screenshot({path:'artifacts/patrol-discoveries-desktop.png'});await page.locator('#toggle-patrol').click();const stopped=await save();assert(!stopped.island.exploration.patrol.enabled);
 await pause(false);await open();await page.waitForFunction(()=>!document.querySelector('#recall-explorer'),{},{timeout:30000});await page.waitForTimeout(1600);await pause(true);const finished=await save();const actor=finished.island.npcs.find((n:any)=>n.id===id);assert(!finished.island.exploration.active&&!actor.cargo);assert.equal(finished.island.npcs.filter((n:any)=>n.isAlive).length,8);assert.equal(actor.attributes.int,Math.min(10,initial.island.npcs.find((n:any)=>n.id===id).attributes.int+1));assert.equal(actor.laborRole,'idle');assert.equal(finished.island.exploration.points.filter((p:any)=>p.claimed).length,3);assert(!await page.locator('[data-visit-discovery]').count());await writeFile('artifacts/patrol-browser-played-save.json',JSON.stringify(finished));await page.screenshot({path:'artifacts/patrol-world.png'});
 await load(JSON.stringify(finished));const again=await save();assert.deepEqual(again.island.exploration.points,finished.island.exploration.points);assert.equal(again.island.npcs.find((n:any)=>n.id===id).attributes.int,actor.attributes.int);await open();await page.setViewportSize({width:390,height:844});await page.locator('.exploration-panel').scrollIntoViewIfNeeded();await page.screenshot({path:'artifacts/patrol-mobile.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.setViewportSize({width:1440,height:1000});await load(await readFile('artifacts/patrol-warning-fixture-save.json','utf8'));await pause(false);await open();await page.waitForFunction(()=>document.querySelector('.exploration-warning')?.textContent?.includes('Đuốc còn'),{},{timeout:20000});await pause(true);await open();await page.screenshot({path:'artifacts/patrol-return-warning-fixture.png'});
 assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);await writeFile('artifacts/patrol-browser-result.json',JSON.stringify({earned:{alive:8,food:finished.island.sharedFood,points:finished.island.exploration.points,automaticTrips:finished.island.exploration.patrol.trips,intBefore:initial.island.npcs.find((n:any)=>n.id===id).attributes.int,intAfter:actor.attributes.int,midtripReload:true,returnedCargo:true,stop:true,mobile:true},separateFixture:{lowTorchWarning:true},errors,failed},null,2));console.log('PASS browser earned public patrol/3finite discoveries/physical cargo/stop/return/save-load/one-time INT/mobile; separate low-torch fixture/no errors.');
 }catch(error){try{await page.screenshot({path:'artifacts/patrol-ui-failure.png'});}catch{}throw error;}finally{await browser.close();server.close();}
}
main().catch(e=>{console.error(e);server.close();process.exitCode=1;});
