import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {decodeSave,encodeSave} from '../src/core/SaveSystem';
import {SimulationSession} from '../src/core/SimulationSession';
import {anomalyRequirements,branchName} from '../src/core/AnomalyManager';
for(const name of ['anomaly-ready','anomaly-paused','anomaly-entered','anomaly-quota-ready','anomaly-played','mystic-ready','mystic-paused','mystic-played','eldritch-ready','eldritch-paused','eldritch-entered','eldritch-safety-ready','eldritch-transition-played']){const raw=readFileSync(`artifacts/${name}-save.json`,'utf8'),d=decodeSave(raw);assert.equal(d.island.npcs.filter(n=>n.isAlive).length,50);assert.deepEqual(decodeSave(encodeSave(d.island,d.map,d.config)).island.civilization,JSON.parse(JSON.stringify(d.island.civilization)));}
for(const [name,branch] of [['anomaly-ready','hightech'],['mystic-ready','mystic'],['eldritch-ready','eldritch']] as const){const d=decodeSave(readFileSync(`artifacts/${name}-save.json`,'utf8')),s=d.island,c=s.civilization!,lab=s.buildings.find(b=>b.type==='measurement_lab')!;assert(anomalyRequirements(s,lab.id,branch).every(r=>r.met));const before={...c.inventory},sim=new SimulationSession(s,d.map);assert(sim.submit({playerId:'readonly-regression',sequence:1,command:{type:'start_branch',branch,labId:lab.id}}).accepted);assert.equal(c.inventory.components,before.components-50);assert.equal(c.inventory.steel,before.steel-20);assert(sim.submit({playerId:'readonly-regression',sequence:2,command:{type:'cancel_branch'}}).accepted);assert.deepEqual(c.inventory,before);assert(!sim.submit({playerId:'readonly-regression',sequence:3,command:{type:'cancel_branch'}}).accepted);}
assert.equal(branchName('eldritch'),'Quỷ Dị');const base=JSON.parse(readFileSync('artifacts/eldritch-transition-played-save.json','utf8'));for(const defect of ['foundation','bio','care']){const bad=JSON.parse(JSON.stringify(base));if(defect==='foundation')bad.island.surveys.sites.find((p:any)=>p.kind==='eldritch').foundationComplete=false;if(defect==='bio')bad.island.civilization.produced.biomatter=8;if(defect==='care')bad.island.buildings.find((b:any)=>b.type==='quarantine').quarantineCareTicks=19;assert.throws(()=>decodeSave(JSON.stringify(bad)),/nền tảng|Di tích/);}
console.log('PASS three branches:13 earned checkpoints read-only load/roundtrip/50alive, each ready branch pays50+20/cancel refunds once, missing eldritch foundation/9bio/20care corrupt saves rejected. Main Hightech/Mystic saves untouched.');

const modern=decodeSave(readFileSync('artifacts/eldritch-ready-save.json','utf8')),ms=modern.island,ex=ms.buildings.find(b=>b.type==='relic_extractor')!,stock=JSON.stringify(ms.civilization!.inventory);assert(!new SimulationSession(ms,modern.map).submit({playerId:'early-filter',sequence:1,command:{type:'set_relic_safety',buildingId:ex.id,enabled:true}}).accepted);assert.equal(ex.relicSafety,undefined);assert.equal(JSON.stringify(ms.civilization!.inventory),stock);console.log('PASS safety is locked before choosing Eldritch; no material debit or mode flag.');
