import {setPower,tickPower,trackPower,synchronizePower} from '../src/core/PowerManager';
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {decodeSave,encodeSave} from '../src/core/SaveSystem';
import {reserveEntityIds} from '../src/core/factory';
import {SimulationSession,type PlayerCommand} from '../src/core/SimulationSession';
import {findPath} from '../src/core/pathfinding';
import {ERAS} from '../src/core/civilization';
const d=decodeSave(readFileSync('artifacts/surveys-played-save.json','utf8')),s=d.island,c=s.civilization!;reserveEntityIds(s);const sim=new SimulationSession(s,d.map);let seq=0;const initial=s.tick;
const send=(command:PlayerCommand)=>{const r=sim.submit({playerId:'analysis',sequence:++seq,command});assert(r.accepted,JSON.stringify({command,r}));};
const until=(ok:()=>boolean,max=1500)=>{for(let i=0;i<max&&!ok();i++){sim.advanceTicks(1);assert.equal(s.npcs.filter(n=>n.isAlive).length,50);}if(!ok())writeFileSync('artifacts/analysis-waiting-save.json',encodeSave(s,d.map,d.config));assert(ok(),JSON.stringify({tick:s.tick,analysis:s.analysis,power:s.power,goods:c.inventory,b:s.buildings.filter(b=>b.type==='measurement_lab'),n:s.npcs.filter(n=>s.buildings.some(b=>b.type==='measurement_lab'&&b.workers.includes(n.id)))}));};
const scientist=s.npcs.find(n=>n.isAlive&&n.age>=18&&n.laborRole==='idle'&&!n.researching&&!n.actionTarget&&!n.cargo&&!n.freight&&!n.haulTask&&!s.buildings.some(b=>b.workers.includes(n.id)))!;assert(scientist);const comp=c.inventory.components,parts=c.inventory.machineParts;send({type:'start_research',techId:'measurement_science'});assert.equal(c.inventory.components,comp-6);assert.equal(c.inventory.machineParts,parts-1);send({type:'assign_researcher',npcId:scientist.id});until(()=>c.unlocks.includes('measurement_science'));send({type:'assign_labor',npcId:scientist.id,role:'stone'});until(()=>s.stone>=20);send({type:'assign_labor',npcId:scientist.id,role:'idle'});until(()=>!scientist.cargo&&!scientist.freight&&!scientist.actionTarget);
const t=d.map.landTiles.find(t=>t.x>=5&&t.x<=23&&t.y>=10&&t.y<=21&&['grass','sand'].includes(d.map.tiles[t.y][t.x])&&!s.buildings.some(b=>b.tileX===t.x&&b.tileY===t.y)&&!s.npcs.some(n=>n.position?.tileX===t.x&&n.position?.tileY===t.y)&&!s.animals.some(a=>a.tileX===t.x&&a.tileY===t.y)&&findPath(d.map,scientist.position!.tileX,scientist.position!.tileY,t.x,t.y)!==null)!;assert(t);const prior=c.inventory.components;send({type:'build',buildingType:'measurement_lab',tileX:t.x,tileY:t.y});assert.equal(c.inventory.components,prior-8);const lab=s.buildings.at(-1)!;send({type:'assign_worker',buildingId:lab.id,npcId:scientist.id});until(()=>lab.complete);assert(!sim.submit({playerId:'analysis',sequence:++seq,command:{type:'upgrade_building',buildingId:lab.id}}).accepted);
const post=s.buildings.find(b=>b.type==='tradepost')!,trader=s.npcs.find(n=>n.isAlive&&n.age>=18&&!n.guardDuty&&n.laborRole==='food'&&!s.buildings.some(b=>b.workers.includes(n.id)))!;assert(trader);send({type:'assign_labor',npcId:trader.id,role:'idle'});send({type:'assign_worker',buildingId:post.id,npcId:trader.id});for(let i=0;i<2;i++){until(()=>!trader.actionTarget&&!trader.cargo&&!trader.freight&&!trader.haulTask);const cloth=c.inventory.cloth;send({type:'start_trade',buildingId:post.id,offerId:'cloth_for_coal'});assert.equal(c.inventory.cloth,cloth-8);until(()=>!post.shipment);}send({type:'remove_worker',buildingId:post.id,npcId:trader.id});send({type:'assign_labor',npcId:trader.id,role:'food'});
const gen=s.buildings.find(b=>b.type==='steam_generator')!;send({type:'set_power',buildingId:lab.id,enabled:true,priority:2});send({type:'set_power',buildingId:gen.id,enabled:true,priority:1});until(()=>s.power!.supplied.includes(lab.id));writeFileSync('artifacts/analysis-ready-save.json',encodeSave(s,d.map,d.config));const site=s.surveys!.sites[0],fee=c.inventory.components,env={playerId:'analysis',sequence:++seq,command:{type:'start_analysis' as const,siteId:site.id,labId:lab.id}};assert(sim.submit(env).accepted);assert(sim.submit(env).duplicate);assert.equal(c.inventory.components,fee-2);until(()=>s.analysis!.active!.workTicks>=8);const held=s.analysis!.active!.workTicks;send({type:'set_power',buildingId:lab.id,enabled:false,priority:2});assert.equal(lab.labPoweredTicks,0);for(let i=0;i<5;i++)sim.advanceTicks(1);assert.equal(s.analysis!.active!.workTicks,held);const mid=encodeSave(s,d.map,d.config);assert.deepEqual(decodeSave(mid).island.analysis,s.analysis);writeFileSync('artifacts/analysis-paused-save.json',mid);send({type:'cancel_analysis'});assert.equal(c.inventory.components,fee);assert(!sim.submit({playerId:'analysis',sequence:++seq,command:{type:'cancel_analysis'}}).accepted);
send({type:'set_power',buildingId:lab.id,enabled:true,priority:2});for(const site of s.surveys!.sites){send({type:'start_analysis',siteId:site.id,labId:lab.id});until(()=>!!site.analyzed);assert(!s.analysis!.active);}until(()=>(lab.labPoweredTicks??0)>=50);assert.equal(s.surveys!.sites.filter(p=>p.analyzed).length,3);assert.equal(lab.productionBatches,3);assert.equal(c.inventory.components,fee-6);assert.equal(s.power!.steadyTicks,0);assert.equal(c.anomalyBranch,undefined);writeFileSync('artifacts/analysis-played-save.json',encodeSave(s,d.map,d.config));console.log(`PASS earned analysis: paid research/build/2 coal trips, onsite staffed 2-power lab, paid2 projects/replay/outage holds/reset/cancel/refund/save, 3 analyzed records/own >=50 ticks/5 days(no borrowed proof), 50 alive/Food ${s.sharedFood.toFixed(1)}, ${s.tick-initial} steps, Anomaly locked.`);
const broken=JSON.parse(mid);broken.island.analysis.active.workTicks=40;assert.throws(()=>decodeSave(JSON.stringify(broken)),/Phân tích/);console.log('PASS corrupted analysis time rejected.');

// Separate counter fixture: sequential connections cannot add up across two facilities.
const unit=decodeSave(readFileSync('artifacts/analysis-ready-save.json','utf8')).island,first=unit.buildings.find(b=>b.type==='measurement_lab')!,second={...structuredClone(first),id:'fixture-second-lab',labPoweredTicks:0,powerEnabled:false,workers:[unit.npcs.find(n=>n.isAlive&&n.age>=18&&!unit.buildings.some(b=>b.workers.includes(n.id)))!.id]};unit.buildings.push(second);first.labPoweredTicks=0;for(let i=0;i<25;i++){tickPower(unit);trackPower(unit);}assert.equal(first.labPoweredTicks,25);setPower(unit,first.id,false,2);setPower(unit,second.id,true,2);for(let i=0;i<25;i++){tickPower(unit);trackPower(unit);}assert.equal(first.labPoweredTicks,0);assert.equal(second.labPoweredTicks,25);assert.equal(Math.max(first.labPoweredTicks!,second.labPoweredTicks!),25);second.workers=[];synchronizePower(unit);assert.equal(second.labPoweredTicks,0);console.log('PASS electrical fixture: two sequential 25-tick facilities do not become50; remove assigned staff resets only its own proof.');
const invalid=JSON.parse(mid);invalid.island.buildings.find((b:any)=>b.type==='measurement_lab').labPoweredTicks=99999999;assert.throws(()=>decodeSave(JSON.stringify(invalid)),/Điện của cơ sở/);
