import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE??'playwright');const root=path.resolve('web');
const server=createServer(async(req,res)=>{const file=path.resolve(root,'.'+new URL(req.url??'/','http://localhost').pathname.replace(/\/$/,'/index.html'));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{res.setHeader('content-type',({'.html':'text/html','.css':'text/css','.js':'text/javascript','.svg':'image/svg+xml','.png':'image/png'} as Record<string,string>)[path.extname(file)]??'application/octet-stream');res.end(await readFile(file));}catch{res.writeHead(404).end();}});
async function main(){
 await mkdir('artifacts',{recursive:true});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors:string[]=[],failed:string[]=[];page.on('pageerror',(e:Error)=>errors.push(e.message));page.on('response',(r:any)=>{if(r.status()>=400)failed.push(r.url());});const url=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
 const close=async()=>{if(await page.locator('#building-inspector').isVisible())await page.locator('#bi-close').click();if(await page.locator('#panel-overlay').evaluate((e:HTMLElement)=>e.classList.contains('open')))await page.locator('#panel-close').click();};
 const pause=async(on:boolean)=>{await close();if((await page.locator('#btn-pause').evaluate((e:HTMLElement)=>e.classList.contains('active')))!==on)await page.locator('#btn-pause').click();};
 const save=async()=>{await close();await page.locator('#btn-save-local').click();return page.evaluate(()=>JSON.parse(localStorage.getItem('dao_thien_nguyen_v2')!));};
 const load=async(raw:string)=>{await page.goto(url);await page.evaluate((raw:string)=>localStorage.setItem('dao_thien_nguyen_v2',raw),raw);await page.reload();await page.locator('#btn-resume-game').click();await page.locator('.era-roadmap').waitFor();await pause(true);};
 const open=async()=>{await close();await page.locator('#sb-quests').click();await page.locator('.era-roadmap').waitFor();await page.waitForTimeout(300);};
 const inspect=async(id:string)=>{await close();await page.locator('#btn-build').click();await page.locator(`[data-inspect-building="${id}"]`).click();await page.locator('#building-inspector').waitFor({state:'visible'});await page.waitForTimeout(300);};
 try{
 const raw=await readFile('artifacts/anomaly-ready-save.json','utf8'),ready=JSON.parse(raw),lab=ready.island.buildings.find((b:any)=>b.type==='measurement_lab');await load(raw);const before=await save();await open();await page.locator('.anomaly-panel h3').scrollIntoViewIfNeeded();await page.locator('[data-decision-key="branch-hightech"] summary').click();assert.match(await page.locator('.anomaly-panel').innerText(),/50 nhịp/);assert.match(await page.locator('.anomaly-panel').innerText(),/không biến đổi dân/);await page.screenshot({path:'artifacts/anomaly-investment-preview.png'});await page.locator('[data-start-branch="hightech"]').click();const paid=await save();assert.equal(paid.island.civilization.inventory.components,before.island.civilization.inventory.components-50);assert.equal(paid.island.civilization.inventory.steel,before.island.civilization.inventory.steel-20);assert.equal(paid.island.civilization.branchDevelopment.workTicks,0);await load(JSON.stringify(paid));await open();assert.match(await page.locator('.anomaly-panel').innerText(),/0\/50/);await page.locator('#cancel-branch').click();const refund=await save();assert.equal(refund.island.civilization.inventory.components,before.island.civilization.inventory.components);assert.equal(refund.island.civilization.inventory.steel,before.island.civilization.inventory.steel);
 await load(await readFile('artifacts/anomaly-paused-save.json','utf8'));await open();await page.locator(`[data-power-toggle="${lab.id}"]`).click();await pause(false);await page.locator('.speed-btn[data-speed="2"]').click();await open();await page.waitForFunction(()=>document.querySelector('.anomaly-panel h3')?.textContent?.includes('Dị Tượng · Công Nghệ Cao'),undefined,{timeout:180000});await pause(true);const entered=await save();assert.equal(entered.island.civilization.era,'anomaly');assert.equal(entered.island.civilization.anomalyBranch,'hightech');assert.equal(entered.island.npcs.filter((n:any)=>n.isAlive).length,50);await open();await page.locator('.anomaly-panel').scrollIntoViewIfNeeded();await page.screenshot({path:'artifacts/anomaly-entered-desktop.png'});
 const quota=await readFile('artifacts/anomaly-quota-ready-save.json','utf8'),q=JSON.parse(quota),factory=q.island.buildings.find((b:any)=>b.type==='component_factory');await load(quota);await inspect(factory.id);assert.match(await page.locator('.bi-level').innerText(),/Công Nghệ Cao/);await page.locator('[data-quota="3"]').click();const programmed=await save();assert.equal(programmed.island.buildings.find((b:any)=>b.id===factory.id).productionQuota,3);await load(JSON.stringify(programmed));await inspect(factory.id);await page.locator('.production-quota').scrollIntoViewIfNeeded();await page.screenshot({path:'artifacts/anomaly-quota-programmed.png'});await pause(false);await page.locator('.speed-btn[data-speed="2"]').click();await inspect(factory.id);await page.waitForFunction(()=>document.querySelector('.production-quota')?.textContent?.includes('Đã đủ định mức'),undefined,{timeout:120000});await pause(true);const done=await save(),finished=done.island.buildings.find((b:any)=>b.id===factory.id);assert.equal(finished.productionQuota,0);assert.equal(finished.powerEnabled,false);assert.equal(finished.productionBatches,factory.productionBatches+3);assert.equal(done.island.civilization.produced.components,q.island.civilization.produced.components+9);assert.equal(done.island.npcs.filter((n:any)=>n.isAlive).length,50);await load(JSON.stringify(done));await inspect(factory.id);assert.match(await page.locator('.production-quota').innerText(),/Đã đủ định mức/);await page.locator('#bi-clear-quota').click();const cleared=await save();assert.equal(cleared.island.buildings.find((b:any)=>b.id===factory.id).productionQuota,undefined);
 await page.setViewportSize({width:390,height:844});await load(await readFile('artifacts/anomaly-played-save.json','utf8'));await inspect(factory.id);await page.locator('.production-quota').scrollIntoViewIfNeeded();await page.screenshot({path:'artifacts/anomaly-quota-mobile.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);console.log('PASS browser earned anomaly: preview/public50components20steel fee/pause/reload/cancel/refund, own lab proof recovery/live50work steps/50alive/hightech, public quota3/persist/live exactly3batches+9components/autoOFF/clear, mobile/no errors/overflow.');
 }catch(e){console.error(e);try{await page.screenshot({path:'artifacts/anomaly-ui-failure.png'});}catch{}throw e;}finally{await browser.close();server.close();}
}
main().catch(e=>{console.error(e);server.close();process.exitCode=1;});
