import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE??'playwright');const root=path.resolve('web');
const server=createServer(async(req,res)=>{const file=path.resolve(root,'.'+new URL(req.url??'/','http://localhost').pathname.replace(/\/$/,'/index.html'));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{res.setHeader('content-type',({'.html':'text/html','.css':'text/css','.js':'text/javascript','.svg':'image/svg+xml','.png':'image/png'} as Record<string,string>)[path.extname(file)]??'application/octet-stream');res.end(await readFile(file));}catch{res.writeHead(404).end();}});
async function main(){
 await mkdir('artifacts',{recursive:true});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors:string[]=[],failed:string[]=[];page.on('pageerror',(e:Error)=>errors.push(e.message));page.on('response',(r:any)=>{if(r.status()>=400)failed.push(r.url());});const url=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
 const close=async()=>{if(await page.locator('#building-inspector').isVisible())await page.locator('#bi-close').click();if(await page.locator('#panel-overlay').evaluate((e:HTMLElement)=>e.classList.contains('open')))await page.locator('#panel-close').click();};
 const pause=async(on:boolean)=>{await close();if((await page.locator('#btn-pause').evaluate((e:HTMLElement)=>e.classList.contains('active')))!==on)await page.locator('#btn-pause').click();};
 const save=async()=>{await close();await page.locator('#btn-save-local').click();return page.evaluate(()=>JSON.parse(localStorage.getItem('dao_thien_nguyen_v2')!));};
 const load=async(raw:string)=>{await page.goto(url);await page.evaluate((raw:string)=>localStorage.setItem('dao_thien_nguyen_v2',raw),raw);await page.reload();await page.locator('#btn-resume-game').click();await page.locator('.era-roadmap').waitFor();await pause(true);};
 const open=async()=>{await close();await page.locator('#sb-quests').click();await page.locator('.era-roadmap').waitFor();await page.waitForTimeout(300);};
 const inspect=async(id:string)=>{await close();await page.locator('#btn-build').click();await page.locator(`[data-inspect-building="${id}"]`).click();await page.locator('#building-inspector').waitFor({state:'visible'});await page.waitForTimeout(300);};
 try{
 const raw=await readFile('artifacts/care-equipped-earned-save.json','utf8'),base=JSON.parse(raw),guard=base.island.npcs.find((n:any)=>n.id==='npc_15');await load(raw);await close();await page.locator('#btn-military').click();await page.locator('.defense-controls').scrollIntoViewIfNeeded();const before=await save();await page.locator('#btn-military').click();await page.locator('[data-craft-defense="spear"]').click();const paid=await save();assert.equal(paid.island.wood,before.island.wood-6);assert.equal(paid.island.stone,before.island.stone-4);await load(JSON.stringify(paid));await page.locator('#btn-military').click();await page.locator('#cancel-defense').click();const refund=await save();assert.equal(refund.island.wood,before.island.wood);assert.equal(refund.island.stone,before.island.stone);
 await page.locator('#btn-military').click();await page.locator('[data-craft-defense="spear"]').click();await pause(false);await page.locator('.speed-btn[data-speed="2"]').click();await page.locator('#btn-military').click();await page.waitForFunction(()=>document.querySelector('#defense-craft-state')?.textContent?.includes('Kho: 1 giáo'),undefined,{timeout:120000});await pause(true);const crafted=await save();assert.equal(crafted.island.defense.crafted.spear,2);await page.locator('#btn-military').click();await page.locator(`[data-gear-npc="${guard.id}"][data-defense-kind="padded_vest"]`).click();await pause(false);await page.waitForTimeout(12000);await pause(true);const returned=await save();assert.equal(returned.island.npcs.find((n:any)=>n.id===guard.id).armor,undefined);assert.equal(returned.island.defense.stock.padded_vest,1);await page.locator('#btn-military').click();await page.locator(`[data-gear-npc="${guard.id}"][data-defense-kind="padded_vest"]`).click();await pause(false);await page.waitForTimeout(12000);await pause(true);const equipped=await save();assert.equal(equipped.island.npcs.find((n:any)=>n.id===guard.id).armor,'padded_vest');assert.equal(equipped.island.npcs.filter((n:any)=>n.isAlive).length,50);await page.locator('#btn-military').click();await page.locator(`[data-care-person="${guard.id}"]`).scrollIntoViewIfNeeded();await page.screenshot({path:'artifacts/care-equipment-desktop.png'});
 await load(await readFile('artifacts/care-injured-fixture-save.json','utf8'));await page.locator('#btn-military').click();await page.locator(`[data-treat="${guard.id}"]`).click();const queued=await save();assert.equal(queued.island.npcs.find((n:any)=>n.id===guard.id).treatment.paid,false);await load(JSON.stringify(queued));await pause(false);await page.locator('.speed-btn[data-speed="2"]').click();await page.waitForTimeout(8000);await pause(true);const healed=await save(),patient=healed.island.npcs.find((n:any)=>n.id===guard.id);assert.equal(patient.herbalDoses,1);assert(patient.health>=80);assert.equal(patient.treatment,undefined);assert.equal(healed.island.npcs.filter((n:any)=>n.isAlive).length,50);await page.locator('#btn-military').click();await page.locator(`[data-care-person="${guard.id}"]`).scrollIntoViewIfNeeded();await page.screenshot({path:'artifacts/care-herbal-desktop.png'});
 const inciteBase=JSON.parse(raw);await load(raw);await close();await page.locator('#faith-hud').click();const button=page.locator('#cast-incite');assert(await button.isDisabled());await pause(false);await page.locator('.speed-btn[data-speed="2"]').click();await page.waitForTimeout(20000);await pause(true);const matured=await save();await page.locator('#faith-hud').click();await page.locator('#cast-incite').click();const inc=await save();assert.equal(inc.island.faith.amount,matured.island.faith.amount-60);assert(inc.island.faith.incite.targets.includes(guard.id));await load(JSON.stringify(inc));await page.locator('#faith-hud').click();assert(await page.locator('#cast-incite').isDisabled());await page.locator('#cast-incite').scrollIntoViewIfNeeded();await page.screenshot({path:'artifacts/care-incite-desktop.png'});
 await page.setViewportSize({width:390,height:844});await load(JSON.stringify(healed));await page.locator('#btn-military').click();await page.locator(`[data-care-person="${guard.id}"]`).scrollIntoViewIfNeeded();await page.screenshot({path:'artifacts/care-mobile.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await load(await readFile('artifacts/mystic-prepared-save.json','utf8'));assert(await page.locator('#food-reserve-warning').isVisible());await page.screenshot({path:'artifacts/care-food-warning-mobile.png'});assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);console.log('PASS care browser: earned craft fee/cancel/reload/live craft, physical return/equip armor, fixture paid herbal treatment/reload/live healing, incite cooldown/escalated60fee/reload, 50alive/mobile/lowFood HUD/no errors.');
 }catch(e){console.error(e);try{await page.screenshot({path:'artifacts/care-ui-failure.png'});}catch{}throw e;}finally{await browser.close();server.close();}
}
main().catch(e=>{console.error(e);server.close();process.exitCode=1;});
