import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createIsland} from '../src/core/factory';
import {createCivilization} from '../src/core/civilization';
import {initializeFaith} from '../src/core/FaithManager';
import {initializeRaids,tickRaids,respondToRaid,castShield} from '../src/core/RaidManager';
import {SimulationSession} from '../src/core/SimulationSession';
import {encodeSave,decodeSave} from '../src/core/SaveSystem';
import type {WorldMap} from '../src/renderer/WorldMap';
const map:WorldMap={width:30,height:20,tiles:Array.from({length:20},()=>Array(30).fill('grass')),landTiles:[]};for(let y=0;y<20;y++)for(let x=0;x<30;x++)map.landTiles.push({x,y});
const config={mode:'local' as const,seed:321,size:'small' as const,width:30,height:20,population:5};
function world(){const s=createIsland('Phòng vệ',5);s.civilization=createCivilization();s.sharedFood=200;s.wood=100;s.stone=100;s.dailyLife={campfire:{tileX:10,tileY:10}};s.buildings=[{id:'home',type:'house',tileX:11,tileY:10,complete:true,progress:100,workers:[],level:1}];for(const n of s.npcs){n.age=25;n.occupation='gatherer';n.position={tileX:10,tileY:10};n.needs={hunger:0,rest:0,safety:0,social:0};n.health=100;}initializeFaith(s);initializeRaids(s);return s;}
const s=world();s.raids!.untilMs=600;tickRaids(s,map);assert.equal(s.raids!.phase,'warning');assert.equal(s.raids!.enemies.length,0);const warning=decodeSave(encodeSave(s,map,config));assert.deepEqual(warning.island.raids,s.raids);for(let i=0;i<34;i++)tickRaids(s,map);assert.equal(s.raids!.phase,'active');assert.equal(s.raids!.enemies.length,2);assert.deepEqual(decodeSave(encodeSave(s,map,config)).island.raids,s.raids);
for(let i=0;i<55;i++)tickRaids(s,map);assert.equal(s.raids!.phase,'peace');assert.equal(s.raids!.stolen,40);assert.equal(s.sharedFood,160);
const shield=world();shield.faith!.amount=150;shield.raids!.phase='active';shield.raids!.target={x:10,y:10};shield.raids!.untilMs=30000;shield.raids!.budget=40;shield.raids!.enemies=[{id:'a',x:10,y:9,health:36},{id:'b',x:11,y:10,health:36}];const session=new SimulationSession(shield,map),env={playerId:'x',sequence:1,command:{type:'cast_shield' as const}};assert(session.submit(env).accepted);assert(session.submit(env).duplicate);assert.equal(shield.faith!.amount,80);assert(castShield(shield));tickRaids(shield,map);assert.equal(shield.sharedFood,200);assert.equal(shield.raids!.stolen,0);assert.deepEqual(decodeSave(encodeSave(shield,map,config)).island.raids,shield.raids);for(let i=0;i<149;i++)tickRaids(shield,map);assert.equal(castShield(shield),null);
const combat=world(),guard=combat.npcs[0],civilian=combat.npcs[1];guard.guardDuty=true;guard.laborMode='manual';guard.buildingWork={buildingId:'home',ticks:2.5};guard.cargo={wood:10,food:0,stone:0,herbs:0};guard.actionTarget={type:'chop_wood',x:15,y:10};guard.laborTask={workTicks:3,totalTicks:5};combat.raids!.phase='active';combat.raids!.target={x:10,y:10};combat.raids!.untilMs=30000;combat.raids!.budget=40;combat.raids!.enemies=[{id:'a',x:10,y:9,health:36}];respondToRaid(combat,map);assert.equal(guard.raidResponse,'guarding');assert.equal(civilian.raidResponse,'fleeing');assert.equal(guard.cargo.wood,10);assert.equal(guard.buildingWork.ticks,2.5);assert.equal(guard.laborTask.workTicks,3);assert.equal(guard.laborMode,'manual');assert(guard.survivalBlocked);assert(guard.health!>=20);for(let i=0;i<8;i++){for(const n of combat.npcs)n.survivalBlocked=false;respondToRaid(combat,map);}assert.equal(combat.raids!.phase,'peace');assert.equal(combat.sharedFood,200);
const blocked=world();blocked.raids!.phase='active';blocked.raids!.target={x:10,y:10};blocked.raids!.untilMs=30000;blocked.raids!.enemies=[{id:'a',x:0,y:0,health:36}];const wall={...map,tiles:map.tiles.map(row=>row.map(()=> 'deep_water' as const))};tickRaids(blocked,wall);assert.equal(blocked.raids!.phase,'peace');assert.equal(blocked.sharedFood,200);
const poor=world();poor.sharedFood=10;poor.raids!.untilMs=600;tickRaids(poor,map);assert.equal(poor.raids!.phase,'peace');const bad=JSON.parse(encodeSave(s,map,config));bad.island.raids.enemies=[{id:'bad',x:999,y:0,health:36}];assert.throws(()=>decodeSave(JSON.stringify(bad)),/Đột kích/);
// Continue actual economies for 60 days with natural raid timing and two guards.
for(const file of ['management-targets-save.json','logistics-iron-save.json']){const saved=decodeSave(readFileSync('artifacts/'+file,'utf8')),w=saved.island;initializeFaith(w);initializeRaids(w);const adults=w.npcs.filter(n=>n.isAlive&&n.position&&n.age>=18);for(const n of adults.slice(0,2))n.guardDuty=true;const alive=w.npcs.filter(n=>n.isAlive).length,sim=new SimulationSession(w,saved.map);for(let i=0;i<600;i++)sim.advanceTicks(1);assert.equal(w.npcs.filter(n=>n.isAlive).length,alive);assert(w.sharedFood>0);assert(w.raids!.stolen<=40);console.log(`PASS economy ${file}: ${alive} alive, Food ${w.sharedFood.toFixed(1)}, raids ${w.raids!.count}`);}
console.log('PASS: warning/spawn/physical theft cap, paid idempotent Shield/90s, guard/civilian physical responses, cargo/work progress held, blocked routes, weak settlements protected, exact saves and corrupt data rejected.');

// Full session consumes guard response once, without advancing harvest/cargo/work in the same interval.
const full=world();full.dailyLife=undefined;full.raids!.phase='active';full.raids!.untilMs=30000;full.raids!.target={x:10,y:10};full.raids!.budget=40;full.raids!.enemies=[{id:'a',x:10,y:9,health:36}];const g=full.npcs[0];g.guardDuty=true;g.laborMode='manual';g.actionTarget={type:'chop_wood',x:10,y:10};g.laborTask={workTicks:5,totalTicks:5};g.path=[];full.resources.set('10,10',{type:'wood_tree',amount:100,maxAmount:100,regenRate:0});const fs=new SimulationSession(full,map);fs.advanceTicks(1);assert.equal(g.laborTask!.workTicks,5);assert.equal(full.resources.get('10,10')!.amount,100);assert(g.survivalBlocked);assert.equal(g.health,97);assert.equal(g.raidResponse,'guarding');assert.equal(full.npcs[1].health,100);
full.raids!.enemies=[];full.raids!.phase='peace';full.raids!.untilMs=full.raids!.clockMs+180000;fs.advanceTicks(1);assert.equal(g.raidResponse,undefined);assert.equal(g.laborTask!.workTicks,4,'Original work resumes from preserved progress');
console.log('PASS: authoritative session blocks a second labor action during defense and resumes original harvest afterward.');

// Refuge destinations and the first actual step must be safe against both attackers.
const escape=world(),c=escape.npcs[0];c.position={tileX:10,tileY:10};escape.raids!.phase='active';escape.raids!.untilMs=30000;escape.raids!.target={x:10,y:10};escape.raids!.enemies=[{id:'left',x:9,y:10,health:36},{id:'right',x:12,y:10,health:36}];const beforeDistance=Math.min(...escape.raids!.enemies.map(e=>Math.abs(e.x-10)+Math.abs(e.y-10)));respondToRaid(escape,map);assert.equal(c.raidResponse,'fleeing');assert(Math.min(...escape.raids!.enemies.map(e=>Math.abs(e.x-c.position!.tileX)+Math.abs(e.y-c.position!.tileY)))>=beforeDistance);assert.notEqual(c.position.tileY,10,'Move away from the two-sided threat instead of toward the other enemy');
console.log('PASS: first physical refuge step considers both attackers, without moving onto unwalkable shelter tiles.');
