import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE??'playwright');const root=path.resolve('web');
const server=createServer(async(req,res)=>{const file=path.resolve(root,'.'+new URL(req.url??'/','http://localhost').pathname.replace(/\/$/,'/index.html'));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{res.setHeader('content-type',({'.html':'text/html','.css':'text/css','.js':'text/javascript','.svg':'image/svg+xml','.png':'image/png'} as Record<string,string>)[path.extname(file)]??'application/octet-stream');res.end(await readFile(file));}catch{res.writeHead(404).end();}});
async function main(){
 await mkdir('artifacts',{recursive:true});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors:string[]=[],failed:string[]=[];page.on('pageerror',(e:Error)=>errors.push(e.message));page.on('response',(r:any)=>{if(r.status()>=400)failed.push(r.url());});const url=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
 const close=async()=>{if(await page.locator('#building-inspector').isVisible())await page.locator('#bi-close').click();if(await page.locator('#panel-overlay').evaluate((e:HTMLElement)=>e.classList.contains('open')))await page.locator('#panel-close').click();};
 const pause=async(on:boolean)=>{await close();if((await page.locator('#btn-pause').evaluate((e:HTMLElement)=>e.classList.contains('active')))!==on)await page.locator('#btn-pause').click();};
 const save=async()=>{await close();await page.locator('#btn-save-local').click();return page.evaluate(()=>JSON.parse(localStorage.getItem('dao_thien_nguyen_v2')!));};
 const load=async(raw:string)=>{await page.goto(url);await page.evaluate((raw:string)=>localStorage.setItem('dao_thien_nguyen_v2',raw),raw);await page.reload();await page.locator('#btn-resume-game').click();await page.locator('.era-roadmap').waitFor();await pause(true);};
 const open=async()=>{await close();await page.locator('#sb-quests').click();await page.locator('.era-roadmap').waitFor();await page.waitForTimeout(300);};
 const inspect=async(id:string)=>{await close();await page.locator('#btn-build').click();await page.locator(`[data-inspect-building="${id}"]`).click();await page.locator('#building-inspector').waitFor({state:'visible'});await page.waitForTimeout(300);};

 try{
 const readyRaw=await readFile('artifacts/mystic-adaptation-ready-save.json','utf8'),equippedRaw=await readFile('artifacts/mystic-adaptation-equipped-save.json','utf8'),equipped=JSON.parse(equippedRaw),person=equipped.island.npcs.find((n:any)=>n.adaptation),lab=equipped.island.buildings.find((b:any)=>b.type==='measurement_lab'),gen=equipped.island.buildings.find((b:any)=>b.type==='steam_generator');const details=`[data-adapt-person="${person.id}"]`;
 const personOpen=async()=>{await open();await page.locator(details+' summary').click();await page.locator(details).scrollIntoViewIfNeeded();};
 await load(readyRaw);const before=await save();await personOpen();assert(await page.locator(`[data-adapt-start="${person.id}"][data-adapt-mode="apply"]`).isEnabled());await page.screenshot({path:'artifacts/mystic-adaptation-preview-desktop.png'});await page.locator(`[data-adapt-start="${person.id}"][data-adapt-mode="apply"]`).click();const paid=await save();assert.equal(paid.island.civilization.inventory.spiritEssence,before.island.civilization.inventory.spiritEssence-2);assert.equal(paid.island.civilization.inventory.cloth,before.island.civilization.inventory.cloth-1);assert.equal(paid.island.adaptationProcess.workTicks,0);await load(JSON.stringify(paid));await open();await page.locator('#cancel-adaptation').click();const refund=await save();assert.equal(refund.island.civilization.inventory.cloth,before.island.civilization.inventory.cloth);assert.equal(refund.island.civilization.inventory.spiritEssence,before.island.civilization.inventory.spiritEssence);
 await load(await readFile('artifacts/mystic-adaptation-paused-save.json','utf8'));await open();await page.locator(`[data-power-toggle="${lab.id}"]`).click();await pause(false);await page.locator('.speed-btn[data-speed="2"]').click();await open();await page.waitForFunction((id:string)=>document.querySelector(`[data-adapt-person="${id}"] summary`)?.textContent?.includes('100/100'),person.id,{timeout:120000});await pause(true);const installed=await save();assert.equal(installed.island.npcs.filter((n:any)=>n.adaptation).length,1);assert.equal(installed.island.npcs.find((n:any)=>n.id===person.id).adaptation.charge,100);assert.equal(installed.island.npcs.filter((n:any)=>n.isAlive).length,50);await personOpen();await page.screenshot({path:'artifacts/mystic-adaptation-equipped-desktop.png'});
 await close();await page.locator('#sb-population').click();await page.locator('#open-adaptation').click();await page.locator('.adaptation-panel').waitFor();
 await load(await readFile('artifacts/mystic-adaptation-care-ready-save.json','utf8'));const careBefore=await save();await pause(false);await page.locator('.speed-btn[data-speed="2"]').click();await page.waitForTimeout(30000);await pause(true);const worked=await save();assert(worked.island.npcs.find((n:any)=>n.id===person.id).adaptation.charge<100);assert(worked.island.civilization.produced.spiritEssence>careBefore.island.civilization.produced.spiritEssence);await personOpen();await page.screenshot({path:'artifacts/mystic-adaptation-working-desktop.png'});await close();await page.screenshot({path:'artifacts/mystic-adaptation-world-desktop.png'});
 await load(await readFile('artifacts/mystic-adaptation-cared-save.json','utf8'));await open();await page.locator(`[data-power-toggle="${lab.id}"]`).click();const empty=await save();await personOpen();await page.locator(`[data-adapt-start="${person.id}"][data-adapt-mode="service"]`).click();const service=await save();assert.equal(service.island.civilization.inventory.spiritEssence,empty.island.civilization.inventory.spiritEssence-1);await load(JSON.stringify(service));await pause(false);await page.locator('.speed-btn[data-speed="2"]').click();await open();await page.waitForFunction((id:string)=>document.querySelector(`[data-adapt-person="${id}"] summary`)?.textContent?.includes('100/100'),person.id,{timeout:120000});await pause(true);await personOpen();await page.locator(`[data-adapt-start="${person.id}"][data-adapt-mode="remove"]`).click();const removal=await save();await load(JSON.stringify(removal));await pause(false);await page.locator('.speed-btn[data-speed="2"]').click();await open();await page.waitForFunction((id:string)=>document.querySelector(`[data-adapt-start="${id}"][data-adapt-mode="apply"]`),person.id,{timeout:120000});await pause(true);const removed=await save();assert(!removed.island.npcs.some((n:any)=>n.adaptation));assert.equal(removed.island.civilization.inventory.cloth,service.island.civilization.inventory.cloth);
 await page.setViewportSize({width:390,height:844});await load(await readFile('artifacts/mystic-adaptation-played-save.json','utf8'));await personOpen();await page.screenshot({path:'artifacts/mystic-adaptation-mobile.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await load(await readFile('artifacts/mystic-adaptation-cared-save.json','utf8'));await personOpen();await page.screenshot({path:'artifacts/mystic-adaptation-empty-mobile.png'});assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);console.log('PASS browser earned Mystic variant: public preview/apply fee/refund/reload/outage/live installation/one consenting adult, population navigation, actual spirit refining/zone maintenance use, public essence care/remove/reload/live, chibi/world/mobile/no errors.');
 }catch(e){console.error(e);try{await page.screenshot({path:'artifacts/mystic-adaptation-ui-failure.png'});}catch{}throw e;}finally{await browser.close();server.close();}
}
main().catch(e=>{console.error(e);server.close();process.exitCode=1;});
