import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE??'playwright');const root=path.resolve('web');
const server=createServer(async(req,res)=>{const file=path.resolve(root,'.'+new URL(req.url??'/','http://localhost').pathname.replace(/\/$/,'/index.html'));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{res.setHeader('content-type',({'.html':'text/html','.css':'text/css','.js':'text/javascript','.svg':'image/svg+xml','.png':'image/png'} as Record<string,string>)[path.extname(file)]??'application/octet-stream');res.end(await readFile(file));}catch{res.writeHead(404).end();}});
async function main(){
 await mkdir('artifacts',{recursive:true});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors:string[]=[],failed:string[]=[];
 page.on('pageerror',(e:Error)=>errors.push(e.message));page.on('response',(r:any)=>{if(r.status()>=400)failed.push(r.url());});
 const close=async()=>{if(await page.locator('#panel-overlay').evaluate((e:HTMLElement)=>e.classList.contains('open')))await page.locator('#panel-close').click();};const pause=async(on:boolean)=>{await close();if((await page.locator('#btn-pause').evaluate((e:HTMLElement)=>e.classList.contains('active')))!==on)await page.locator('#btn-pause').click();};const save=async()=>{await close();await page.locator('#btn-save-local').click();return page.evaluate(()=>JSON.parse(localStorage.getItem('dao_thien_nguyen_v2')!));};
 try{
  const raw=await readFile('artifacts/workforce-played-save.json','utf8');await page.goto(`http://127.0.0.1:${(server.address() as {port:number}).port}`);await page.evaluate((raw:string)=>localStorage.setItem('dao_thien_nguyen_v2',raw),raw);await page.reload();await page.locator('#btn-resume-game').click();await page.locator('.era-roadmap').waitFor();await pause(true);let state=await save();assert.equal(state.island.faith.amount,0);assert.equal(state.island.faith.clockMs,0);
  await page.locator('#faith-hud').click();assert(await page.locator('#cast-blessing').isDisabled());assert.match(await page.locator('.faith-backlash').innerText(),/60 giây/);await close();await page.locator('.speed-btn[data-speed="2"]').click();await pause(false);await page.locator('#faith-hud').click();await page.locator('#cast-blessing:enabled').waitFor({timeout:70000});await pause(true);const before=await save();assert(before.island.faith.amount>=50);
  await page.locator('#faith-hud').click();await page.locator('#cast-blessing').click();assert(await page.locator('#cast-blessing').isDisabled());state=await save();await writeFile('artifacts/faith-blessing-save.json',JSON.stringify(state));assert(Math.abs(state.island.faith.amount-(before.island.faith.amount-50))<1e-8);assert.equal(state.island.faith.casts.length,1);assert(state.island.npcs.filter((n:any)=>n.isAlive&&n.position&&n.age>=18).every((n:any)=>n.divineState==='blessed'));
  await page.locator('#faith-hud').click();await page.waitForTimeout(350);await page.screenshot({path:'artifacts/faith-blessing-desktop.png'});await close();await page.waitForTimeout(350);await page.screenshot({path:'artifacts/faith-halo-desktop.png'});await page.waitForTimeout(1100);const paused=await save();assert.deepEqual(paused.island.faith,state.island.faith,'Pause freezes points, buff and cooldown');
  await page.reload();await page.locator('#btn-resume-game').click();await page.locator('.era-roadmap').waitFor();await pause(true);const reloaded=await save();assert.deepEqual(reloaded.island.faith,state.island.faith,'Reload grants no points, duration or refund');await page.locator('.speed-btn[data-speed="2"]').click();await pause(false);await page.locator('#faith-hud').click();await page.waitForFunction(()=>document.querySelector('#blessing-status')?.textContent?.includes('Kiệt sức'),undefined,{timeout:22000});await pause(true);state=await save();await writeFile('artifacts/faith-exhaustion-save.json',JSON.stringify(state));assert(state.island.faith.blessing.exhaustApplied);assert(state.island.npcs.some((n:any)=>n.divineState==='exhausted'));
  await page.locator('#faith-hud').click();assert(await page.locator('#cast-blessing').isDisabled());await page.setViewportSize({width:390,height:844});await page.waitForTimeout(350);await page.screenshot({path:'artifacts/faith-exhaustion-mobile.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await close();await page.waitForTimeout(350);await page.screenshot({path:'artifacts/faith-hud-mobile.png'});
  await page.reload();await page.locator('#btn-resume-game').click();await page.locator('.era-roadmap').waitFor();await pause(true);const exhaustedReload=await save();assert.deepEqual(exhaustedReload.island.faith,state.island.faith);await page.locator('.speed-btn[data-speed="2"]').click();await pause(false);await page.locator('#faith-hud').click();await page.waitForFunction(()=>document.querySelector('#blessing-status')?.textContent?.includes('bình thường'),undefined,{timeout:38000});await pause(true);state=await save();assert.equal(state.island.faith.blessing,undefined);assert.equal(state.island.npcs.filter((n:any)=>n.isAlive).length,5);assert(state.island.sharedFood>0);await page.locator('#faith-hud').click();assert.match(await page.locator('#cast-blessing').innerText(),/100 Niềm tin/);
  await page.setViewportSize({width:1440,height:1000});await page.waitForTimeout(350);await page.screenshot({path:'artifacts/faith-recovered-desktop.png'});await writeFile('artifacts/faith-played-save.json',JSON.stringify(state));assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);console.log(`PASS: browser earned Faith without grants, paid global Blessing, pause/×2, reload in buff/exhaustion, no spam, recovery/escalated price, 5 alive Food ${state.island.sharedFood.toFixed(1)}, desktop/mobile and no runtime/asset errors.`);
 }catch(e){await page.waitForTimeout(350);await page.screenshot({path:'artifacts/faith-ui-failure.png'});throw e;}finally{await browser.close();await new Promise<void>(r=>server.close(()=>r()));}
}
void main().catch(e=>{console.error(e);server.close();process.exitCode=1;});
