import {generateWorldMap,regionAt} from '../src/renderer/WorldMap';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE??'playwright');const root=path.resolve('web');
const server=createServer(async(req,res)=>{const file=path.resolve(root,'.'+new URL(req.url??'/','http://localhost').pathname.replace(/\/$/,'/index.html'));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{res.setHeader('content-type',({'.html':'text/html','.css':'text/css','.js':'text/javascript','.svg':'image/svg+xml','.png':'image/png'} as Record<string,string>)[path.extname(file)]??'application/octet-stream');res.end(await readFile(file));}catch{res.writeHead(404).end();}});
async function main(){
 await mkdir('artifacts',{recursive:true});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors:string[]=[],failed:string[]=[];page.on('pageerror',(e:Error)=>errors.push(e.message));page.on('response',(r:any)=>{if(r.status()>=400)failed.push(r.url());});const url=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
 const close=async()=>{if(await page.locator('#building-inspector').isVisible())await page.locator('#bi-close').click();if(await page.locator('#panel-overlay').evaluate((e:HTMLElement)=>e.classList.contains('open')))await page.locator('#panel-close').click();};
 const pause=async(on:boolean)=>{await close();if((await page.locator('#btn-pause').evaluate((e:HTMLElement)=>e.classList.contains('active')))!==on)await page.locator('#btn-pause').click();};
 const save=async()=>{await close();await page.locator('#btn-save-local').click();return page.evaluate(()=>JSON.parse(localStorage.getItem('dao_thien_nguyen_v2')!));};
 const load=async(raw:string)=>{await page.goto(url);await page.evaluate((raw:string)=>localStorage.setItem('dao_thien_nguyen_v2',raw),raw);await page.reload();await page.locator('#btn-resume-game').click();await page.locator('.era-roadmap').waitFor();await pause(true);};
 const open=async()=>{await close();await page.locator('#sb-quests').click();await page.locator('.era-roadmap').waitFor();await page.waitForTimeout(300);};
 const inspect=async(id:string)=>{await close();await page.locator('#btn-build').click();await page.locator(`[data-inspect-building="${id}"]`).click();await page.locator('#building-inspector').waitFor({state:'visible'});await page.waitForTimeout(300);};




 try{
 await page.goto(url);await page.locator('[data-shape="three-islands"]').click();await page.locator('[data-size="small"]').click();await page.locator('#start-seed').fill('20810');await page.locator('#start-pop-slider').fill('8');assert(await page.locator('#archipelago-start-note').isVisible());await page.locator('#start-preview').scrollIntoViewIfNeeded();await page.screenshot({path:'artifacts/three-islands-create-desktop.png'});await page.locator('#start-preview').screenshot({path:'artifacts/three-islands-preview.png'});
 const map=generateWorldMap(50,35,20810,'three-islands'),regions=map.archipelago!.islands,home=regions[0].landing;
 await page.locator('#btn-start-game').click();await page.locator('[data-creature="founder"]').click();await page.waitForTimeout(250);const box=await page.locator('#game-canvas').boundingBox();assert(box);const zoom=Math.min(box.width/(map.width*16),box.height/(map.height*16))*.88,point=(x:number,y:number)=>({x:box.x+box.width/2+(x-map.width/2+.5)*16*zoom,y:box.y+box.height/2+(y-map.height/2+.5)*16*zoom});await page.screenshot({path:'artifacts/three-islands-overview-world.png'});
 const foreign=point(regions[1].landing.x,regions[1].landing.y);await page.mouse.click(foreign.x,foreign.y);await page.waitForFunction(()=>document.querySelector('#manual-badge')?.textContent?.includes('chưa có đường vượt biển'));assert.equal(await page.locator('#food-reserve-warning').isVisible(),false);const rejected=await save();assert.equal(rejected.island.npcs.filter((n:any)=>n.position).length,0);assert.equal(rejected.island.wood,0);assert.equal(rejected.island.stone,0);assert.equal(rejected.island.sharedFood,40);assert.deepEqual(rejected.map.tiles,map.tiles);assert.equal(rejected.map.archipelago.islands.length,3);
 const positions=map.landTiles.filter(p=>regionAt(map,p.x,p.y)?.id==='thien-nguyen'&&Math.max(Math.abs(p.x-home.x),Math.abs(p.y-home.y))<=2).sort((a,b)=>Math.hypot(a.x-home.x,a.y-home.y)-Math.hypot(b.x-home.x,b.y-home.y)).slice(0,8);for(const p of positions){const click=point(p.x,p.y);await page.mouse.click(click.x,click.y);}await page.locator('#mc-fraction').filter({hasText:'Bước 1'}).waitFor();await pause(true);const placed=await save();assert.equal(placed.island.npcs.filter((n:any)=>n.position).length,8);assert(placed.island.npcs.every((n:any)=>regionAt(map,n.position.tileX,n.position.tileY)?.id==='thien-nguyen'));await writeFile('artifacts/three-islands-browser-placed-save.json',JSON.stringify(placed));
 await page.locator('#sb-population').click();const choices=page.locator('.labor-role-select:enabled');const count=await choices.count();assert(count>=4);for(let i=0;i<count;i++)await choices.nth(i).selectOption(i===count-1?'stone':i===count-2?'wood':'food');await close();await pause(false);const startTime=Date.now();let earned:any;while(Date.now()-startTime<60000){await page.waitForTimeout(1700);earned=await save();if(earned.island.stone>0&&(earned.island.wood>0||(earned.island.dailyLife.campfire.fuel??0)>0))break;}await pause(true);earned=await save();assert(earned.island.stone>0);assert(earned.island.wood>0||(earned.island.dailyLife.campfire.fuel??0)>0);assert.equal(earned.island.npcs.filter((n:any)=>n.isAlive).length,8);assert(earned.island.sharedFood>0);await writeFile('artifacts/three-islands-browser-played-save.json',JSON.stringify(earned));
 await load(JSON.stringify(earned));const restored=await save();assert.deepEqual(restored.map.archipelago,earned.map.archipelago);assert.deepEqual(restored.map.tiles,earned.map.tiles);assert.deepEqual(restored.island.resources,earned.island.resources);await open();assert.equal(await page.locator('[data-island-region]').count(),3);await page.screenshot({path:'artifacts/three-islands-panel-desktop.png'});await page.locator('[data-region-focus="primary"]').click();await page.waitForTimeout(450);await page.screenshot({path:'artifacts/three-islands-mainland-world.png'});await open();await page.setViewportSize({width:390,height:844});await page.locator('.archipelago-panel').scrollIntoViewIfNeeded();await page.screenshot({path:'artifacts/three-islands-mobile.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 const oldRaw=await readFile('artifacts/exploration-played-save.json','utf8'),old=JSON.parse(oldRaw);await page.setViewportSize({width:1440,height:1000});await load(oldRaw);const legacy=await save();assert(!legacy.map.archipelago);assert.deepEqual(legacy.map.tiles,old.map.tiles);assert.deepEqual(legacy.island.resources,old.island.resources);await open();assert.equal(await page.locator('.archipelago-panel').count(),0);
 // The new layout is local only; the existing server choices remain unchanged.
 await page.evaluate(()=>localStorage.clear());await page.reload();await page.locator('[data-mode="server-dev"]').click();assert.equal(await page.locator('[data-shape="three-islands"]').count(),0);assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);await writeFile('artifacts/three-islands-browser-result.json',JSON.stringify({publicCreation:true,seed:20810,dimensions:[map.width,map.height],identities:regions.map(r=>({id:r.id,name:r.name,landing:r.landing})),rejectOverseasWithoutFee:true,mainlandPlaced:8,earned:{alive:8,tick:earned.island.tick,food:earned.island.sharedFood,wood:earned.island.wood,stone:earned.island.stone},saveLoad:true,legacyPreserved:true,localOnly:true,mobile:true,errors,failed},null,2));console.log('PASS public browser three-island creation/preview/labels/no overseas placement/8founders/real harvest/save reload/mainland camera/mobile/old map unchanged/local-only/no errors.');
 }catch(error){try{await page.screenshot({path:'artifacts/three-islands-ui-failure.png'});await close();await page.locator('#btn-save-local').click();const raw=await page.evaluate(()=>localStorage.getItem('dao_thien_nguyen_v2'));if(raw)await writeFile('artifacts/three-islands-ui-failure-save.json',raw);}catch{}throw error;}finally{await browser.close();server.close();}
}
main().catch(e=>{console.error(e);server.close();process.exitCode=1;});
