import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {decodeSave,encodeSave} from '../src/core/SaveSystem';
import {reserveEntityIds} from '../src/core/factory';
import {SimulationSession,type PlayerCommand} from '../src/core/SimulationSession';
import {anomalyRequirements} from '../src/core/AnomalyManager';
import {controlOperating} from '../src/core/ControlManager';
let d=decodeSave(readFileSync('artifacts/microchips-played-save.json','utf8')),s=d.island,c=s.civilization!;reserveEntityIds(s);let sim=new SimulationSession(s,d.map),seq=0,trips=0;const initial=s.tick,production=c.produced.components;
const send=(command:PlayerCommand)=>{const r=sim.submit({playerId:'anomaly',sequence:++seq,command});assert(r.accepted,JSON.stringify({command,r}));};
const until=(ok:()=>boolean,max=3000)=>{for(let i=0;i<max&&!ok();i++){sim.advanceTicks(1);assert.equal(s.npcs.filter(n=>n.isAlive).length,50);}if(!ok())writeFileSync('artifacts/anomaly-waiting-save.json',encodeSave(s,d.map,d.config));assert(ok(),JSON.stringify({tick:s.tick,food:s.sharedFood,goods:c.inventory,power:s.power,project:c.branchDevelopment,message:c.branchMessage}));};
let gen=s.buildings.find(b=>b.type==='steam_generator')!,lab=s.buildings.find(b=>b.type==='measurement_lab')!,center=s.buildings.find(b=>b.type==='control_center')!,factory=s.buildings.find(b=>b.type==='component_factory')!;const post=s.buildings.find(b=>b.type==='tradepost')!,iron=s.buildings.find(b=>b.type==='iron_smelter')!,steel=s.buildings.find(b=>b.type==='steelworks')!;
for(const b of [gen,lab,center,factory])send({type:'set_power',buildingId:b.id,enabled:false,priority:1});
const crew=s.npcs.filter(n=>n.isAlive&&n.age>=18&&n.laborRole==='food'&&!n.guardDuty&&!s.buildings.some(b=>b.workers.includes(n.id))).slice(-3);assert.equal(crew.length,3);const [trader,miner,smith]=crew;for(const n of crew)send({type:'assign_labor',npcId:n.id,role:'idle'});for(const [b,n] of [[post,trader],[iron,miner],[steel,smith]] as const)send({type:'assign_worker',buildingId:b.id,npcId:n.id});
const trip=(offerId:string,fee:number)=>{until(()=>!trader.cargo&&!trader.freight&&!trader.actionTarget&&!trader.haulTask);const cloth=c.inventory.cloth;send({type:'start_trade',buildingId:post.id,offerId});assert.equal(c.inventory.cloth,cloth-fee);until(()=>!post.shipment);trips++;};
for(let i=0;i<20;i++){if(i<14)trip('cloth_for_ore',4);trip('cloth_for_coal',8);if(i<6)trip('cloth_for_copper',12);}
until(()=>c.inventory.steel>=50);for(const [b,n] of [[iron,miner],[steel,smith],[post,trader]] as const){send({type:'remove_worker',buildingId:b.id,npcId:n.id});send({type:'assign_labor',npcId:n.id,role:'food'});}
const scientist=s.npcs.find(n=>n.id==='npc_15')!;send({type:'assign_worker',buildingId:lab.id,npcId:scientist.id});for(const b of [gen,lab,center,factory])send({type:'set_power',buildingId:b.id,enabled:true,priority:b===factory?1:2});until(()=>c.produced.components>=production+42);send({type:'set_power',buildingId:factory.id,enabled:false,priority:1});until(()=>c.inventory.components>=50&&anomalyRequirements(s,lab.id).every(r=>r.met));const beforeComponents=c.inventory.components,beforeSteel=c.inventory.steel;
writeFileSync('artifacts/anomaly-ready-save.json',encodeSave(s,d.map,d.config));const env={playerId:'anomaly',sequence:++seq,command:{type:'start_branch' as const,branch:'hightech',labId:lab.id}};assert(sim.submit(env).accepted);assert(sim.submit(env).duplicate);assert.equal(c.inventory.components,beforeComponents-50);assert.equal(c.inventory.steel,beforeSteel-20);assert(!sim.submit({playerId:'anomaly',sequence:++seq,command:env.command}).accepted);assert(!sim.submit({playerId:'anomaly',sequence:++seq,command:{type:'start_research',techId:'industrial_control'}}).accepted);until(()=>c.branchDevelopment!.workTicks>=5);const held=c.branchDevelopment!.workTicks;send({type:'set_power',buildingId:lab.id,enabled:false,priority:2});sim.advanceTicks(5);assert.equal(c.branchDevelopment!.workTicks,held);assert.equal(lab.labPoweredTicks,0);const paused=encodeSave(s,d.map,d.config);writeFileSync('artifacts/anomaly-paused-save.json',paused);assert.equal(decodeSave(paused).island.civilization!.branchDevelopment!.workTicks,held);send({type:'cancel_branch'});assert.equal(c.inventory.components,beforeComponents);assert.equal(c.inventory.steel,beforeSteel);assert(!sim.submit({playerId:'anomaly',sequence:++seq,command:{type:'cancel_branch'}}).accepted);
send({type:'set_power',buildingId:lab.id,enabled:true,priority:2});until(()=>anomalyRequirements(s,lab.id).every(r=>r.met));send(env.command);d=decodeSave(encodeSave(s,d.map,d.config));s=d.island;c=s.civilization!;sim=new SimulationSession(s,d.map);seq=0;gen=s.buildings.find(b=>b.type==='steam_generator')!;lab=s.buildings.find(b=>b.type==='measurement_lab')!;center=s.buildings.find(b=>b.type==='control_center')!;factory=s.buildings.find(b=>b.type==='component_factory')!;until(()=>c.era==='anomaly');assert.equal(c.anomalyBranch,'hightech');assert(!c.branchDevelopment);assert.equal(c.inventory.components,beforeComponents-50);assert.equal(c.inventory.steel,beforeSteel-20);assert(!sim.submit({playerId:'anomaly',sequence:++seq,command:env.command}).accepted);assert(!sim.submit({playerId:'anomaly',sequence:++seq,command:{type:'cancel_branch'}}).accepted);writeFileSync('artifacts/anomaly-entered-save.json',encodeSave(s,d.map,d.config));
until(()=>controlOperating(s,center));const base=factory.productionBatches??0,componentCount=c.produced.components;writeFileSync('artifacts/anomaly-quota-ready-save.json',encodeSave(s,d.map,d.config));send({type:'set_production_quota',buildingId:factory.id,batches:3});assert.equal(factory.productionQuota,3);until(()=>factory.productionQuota===0);assert.equal(factory.productionBatches,base+3);assert.equal(c.produced.components,componentCount+9);assert.equal(factory.powerEnabled,false);const inputs=structuredClone(factory.buffer!.input);sim.advanceTicks(10);sim.advanceTicks(10);assert.equal(factory.productionBatches,base+3);assert.deepEqual(factory.buffer!.input,inputs);until(()=>c.inventory.components>=beforeComponents-50+9);assert.equal(s.npcs.filter(n=>n.isAlive).length,50);const final=encodeSave(s,d.map,d.config);assert.equal(decodeSave(final).island.buildings.find(b=>b.id===factory.id)!.productionQuota,0);writeFileSync('artifacts/anomaly-played-save.json',final);console.log(JSON.stringify({passed:true,earned:true,ticks:s.tick-initial,paidTrips:trips,alive:50,food:s.sharedFood,inventory:c.inventory,branch:c.anomalyBranch,quotaBatches:3,quotaNewComponents:9,labProof:lab.labPoweredTicks}));
const invalid=JSON.parse(paused);invalid.island.civilization.branchDevelopment.workTicks=50;assert.throws(()=>decodeSave(JSON.stringify(invalid)),/chuyển nhánh/);const wrong=JSON.parse(final);wrong.island.buildings.find((b:any)=>b.id===factory.id).productionQuota=-1;assert.throws(()=>decodeSave(JSON.stringify(wrong)),/Định mức/);
// Separate negative fixtures; no grants are used in the earned route above.
const fixture=decodeSave(readFileSync('artifacts/anomaly-ready-save.json','utf8')),f=new SimulationSession(fixture.island,fixture.map);const fee=fixture.island.civilization!.inventory.components;assert(!f.submit({playerId:'fixture',sequence:1,command:{type:'start_branch',branch:'mystic',labId:lab.id}}).accepted);assert.equal(fixture.island.civilization!.inventory.components,fee);fixture.island.buildings.find(b=>b.id===lab.id)!.labPoweredTicks=49;assert(!f.submit({playerId:'fixture',sequence:2,command:{type:'start_branch',branch:'hightech',labId:lab.id}}).accepted);assert(!f.submit({playerId:'fixture',sequence:3,command:{type:'set_production_quota',buildingId:factory.id,batches:3}}).accepted);console.log('PASS negative fixtures: unfinished branch/proof49/Modern quota rejected without charge; corrupt project/quota saves rejected.');
