import {readFileSync,writeFileSync} from 'node:fs';
import assert from 'node:assert/strict';
import {createIsland} from '../src/core/factory';
import {createCivilization} from '../src/core/civilization';
import {initializeFaith,tickFaith,castBlessing} from '../src/core/FaithManager';
import {initializeWeather,tickWeather,igniteForest,fightForestFire,castRainfall,agricultureMultiplier,FIRE_LIMIT} from '../src/core/WeatherManager';
import {SimulationSession} from '../src/core/SimulationSession';
import {encodeSave,decodeSave} from '../src/core/SaveSystem';
import {tickBuildings} from '../src/renderer/BuildingManager';
import type {WorldMap} from '../src/renderer/WorldMap';
const map:WorldMap={width:18,height:12,tiles:Array.from({length:12},()=>Array(18).fill('grass')),landTiles:[]};for(let y=0;y<12;y++)for(let x=0;x<18;x++)map.landTiles.push({x,y});
const config={mode:'local' as const,seed:321,size:'small' as const,width:18,height:12,population:1};
function world(){const s=createIsland('Mưa và rừng',1);s.civilization=createCivilization();const n=s.npcs[0];n.age=25;n.occupation='gatherer';n.laborRole='idle';n.position={tileX:2,tileY:2};n.needs={hunger:0,rest:0,safety:0,social:0};initializeFaith(s);initializeWeather(s,321);for(let y=2;y<7;y++)for(let x=2;x<7;x++)s.resources.set(`${x},${y}`,{type:'wood_tree',amount:100,maxAmount:100,regenRate:.5});return s;}
const s=world(),session=new SimulationSession(s,map);s.faith!.amount=39;assert(castRainfall(s));s.faith!.amount=200;igniteForest(s,'2,2');const before=s.wood,env={playerId:'rain',sequence:1,command:{type:'cast_rainfall' as const}};assert(session.submit(env).accepted);assert.equal(s.faith!.amount,160);assert.equal(s.weather!.fires.length,0);assert.equal(s.wood,before);assert(session.submit(env).duplicate);assert.equal(s.faith!.amount,160);assert(castRainfall(s));assert.equal(agricultureMultiplier(s),1.3);assert.deepEqual(decodeSave(encodeSave(s,map,config)).island.weather,s.weather);
const frozen=JSON.stringify(s.weather);session.snapshot();assert.equal(JSON.stringify(s.weather),frozen);
for(let i=0;i<74;i++){tickWeather(s);tickFaith(s);}assert.equal(agricultureMultiplier(s),1.3);tickWeather(s);tickFaith(s);assert.equal(s.weather!.clockMs,45000);assert.equal(agricultureMultiplier(s),1);assert(castRainfall(s));for(let i=0;i<25;i++){tickWeather(s);tickFaith(s);}assert.equal(castRainfall(s),null);
// Rain has independent cooldown, no Blessing exhaustion or escalating cost.
const both=world();both.faith!.amount=200;castBlessing(both);for(let i=0;i<50;i++)tickFaith(both);assert.equal(castRainfall(both),null);assert.equal(both.faith!.amount>100,true);
const fire=world();assert(igniteForest(fire,'2,2'));for(let i=0;i<100;i++)tickWeather(fire);assert.equal(fire.weather!.fires.length,0);assert(fire.weather!.burned.length<=FIRE_LIMIT);assert(fire.resources.get('2,2')!.amount<100);assert.equal(fire.wood,world().wood,'Burned wood is not village stock');assert.deepEqual(decodeSave(encodeSave(fire,map,config)).island.weather,fire.weather);
const rescued=world(),n=rescued.npcs[0];n.position={tileX:1,tileY:2};igniteForest(rescued,'2,2');for(let i=0;i<3;i++){n.survivalBlocked=false;fightForestFire(rescued,map);}assert.equal(rescued.weather!.fires.length,0);assert(n.survivalBlocked);assert.match(n.laborMessage!,/dập/);assert.equal(rescued.resources.get('2,2')!.amount,100);
// No remote rescue across water; carriers and children do not abandon cargo.
const blocked=world();blocked.npcs[0].position={tileX:0,tileY:0};const water={...map,tiles:map.tiles.map(r=>[...r])};for(let x=0;x<18;x++)water.tiles[1][x]='deep_water';igniteForest(blocked,'2,2');fightForestFire(blocked,water);assert.equal(blocked.weather!.fires[0].heat,3);blocked.npcs[0].position={tileX:1,tileY:2};blocked.npcs[0].freight={good:'wood',amount:5,target:'@warehouse'};fightForestFire(blocked,map);assert.equal(blocked.weather!.fires[0].heat,3);
const deterministicA=world(),deterministicB=world();for(let i=0;i<2000;i++){tickWeather(deterministicA);tickWeather(deterministicB);}assert.deepEqual(deterministicA.weather,deterministicB.weather);
const resumed=decodeSave(encodeSave(deterministicA,map,config));for(let i=0;i<200;i++){tickWeather(deterministicA);tickWeather(resumed.island);}assert.deepEqual(resumed.island.weather,deterministicA.weather,'Weather RNG continues identically after reload');
// Actual completed farm batches are 20 / 16 / 26 with equal labor and storage limits.
function crop(mode:'clear'|'drought'|'prayer',type:'farm'|'wheat_field'|'flax_field'='farm'){const w=world();w.sharedFood=0;w.npcs[0].privateFood=0;w.weather!.kind=mode==='drought'?'drought':'clear';if(mode==='prayer'){w.faith!.amount=100;castRainfall(w);}w.buildings=[{id:'farm',type,tileX:2,tileY:2,complete:true,progress:100,workers:[w.npcs[0].id]}];for(let i=0;i<10;i++)tickBuildings(w,w.resources,map);return type==='farm'?w.sharedFood:w.civilization!.inventory[type==='wheat_field'?'wheat':'fiber'];}
assert.equal(crop('clear'),20);assert.equal(crop('drought'),16);assert.equal(crop('prayer'),26);for(const type of ['wheat_field','flax_field'] as const){assert.equal(crop('clear',type),12);assert(Math.abs(crop('drought',type)-9.6)<1e-8);assert(Math.abs(crop('prayer',type)-15.6)<1e-8);}
const bad=JSON.parse(encodeSave(s,map,config));bad.island.weather.fires=[{key:'999,2',life:20,heat:3}];assert.throws(()=>decodeSave(JSON.stringify(bad)),/Thời tiết/);
console.log('PASS: paid/idempotent Rain, 45s bonus / 60s cooldown / no offline or pause change; actual crops 20/16/26, bounded fire and physical rescue, cargo protection, deterministic weather and save continuation.');

const played=decodeSave(readFileSync('artifacts/faith-played-save.json','utf8'));initializeWeather(played.island,played.config.seed);const living=played.island.npcs.filter(n=>n.isAlive).length,liveSession=new SimulationSession(played.island,played.map),kinds=new Set<string>();for(let i=0;i<1800;i++){liveSession.advanceTicks(1);kinds.add(played.island.weather!.kind);decodeSave(encodeSave(played.island,played.map,played.config));}assert.equal(played.island.npcs.filter(n=>n.isAlive).length,living);assert(played.island.sharedFood>0);writeFileSync('artifacts/weather-simulation-save.json',encodeSave(played.island,played.map,played.config));console.log(`PASS: real 5-person village, 180 days with weather, ${[...kinds]}, ${played.island.weather!.incidentCount} natural fires, Food ${played.island.sharedFood.toFixed(1)}, all alive and every tick save valid.`);

assert(kinds.has('rain')&&kinds.has('drought'));const hazard=world();hazard.weather!.kind='drought';hazard.weather!.seed=0;for(let i=0;i<34;i++)tickWeather(hazard);assert.equal(hazard.weather!.incidentCount,1,'Natural dry-weather ignition uses saved RNG');assert(hazard.weather!.fires.length>0);console.log('PASS: natural drought ignition after 20 seconds with reproducible RNG.');
const natural=world();igniteForest(natural,'2,2');natural.weather!.kind='rain';tickWeather(natural);assert.equal(natural.weather!.fires.length,0);assert.equal(natural.resources.get('2,2')!.amount,100);assert.equal(agricultureMultiplier(natural),1,'Natural rain extinguishes but does not grant the paid agriculture bonus');
const walking=world();walking.npcs[0].position={tileX:0,tileY:2};igniteForest(walking,'4,2');fightForestFire(walking,map);assert.equal(walking.npcs[0].position!.tileX,1);assert.equal(walking.weather!.fires[0].heat,3,'Travel is not extinguishing work');
const full=world();full.logistics={version:1};full.faith!.amount=100;castRainfall(full);full.buildings=[{id:'farm',type:'farm',tileX:2,tileY:2,complete:true,progress:100,workers:[full.npcs[0].id],buffer:{input:{},output:{food:55}}}];for(let i=0;i<10;i++)tickBuildings(full,full.resources,map);assert.equal(full.buildings[0].buffer!.output.food,60);assert.equal(full.sharedFood,world().sharedFood,'Rain yield remains onsite until hauled');
console.log('PASS: natural rain extinguishes without agriculture gift, actual walking costs a step, rain harvest respects 60-unit onsite buffer.');
