import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE??'playwright');const root=path.resolve('web');
const server=createServer(async(req,res)=>{const file=path.resolve(root,'.'+new URL(req.url??'/','http://localhost').pathname.replace(/\/$/,'/index.html'));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{res.setHeader('content-type',({'.html':'text/html','.css':'text/css','.js':'text/javascript','.svg':'image/svg+xml','.png':'image/png'} as Record<string,string>)[path.extname(file)]??'application/octet-stream');res.end(await readFile(file));}catch{res.writeHead(404).end();}});
async function main(){
 await mkdir('artifacts',{recursive:true});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors:string[]=[],failed:string[]=[];page.on('pageerror',(e:Error)=>errors.push(e.message));page.on('response',(r:any)=>{if(r.status()>=400)failed.push(r.url());});const url=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
 const close=async()=>{if(await page.locator('#panel-overlay').evaluate((e:HTMLElement)=>e.classList.contains('open')))await page.locator('#panel-close').click();await page.waitForTimeout(150);};
 const pause=async(on:boolean)=>{await close();if((await page.locator('#btn-pause').evaluate((e:HTMLElement)=>e.classList.contains('active')))!==on)await page.locator('#btn-pause').click();};
 const save=async()=>{await close();await page.locator('#btn-save-local').click();return page.evaluate(()=>JSON.parse(localStorage.getItem('dao_thien_nguyen_v2')!));};
 const load=async(raw:string)=>{await page.goto(url);await page.evaluate((raw:string)=>localStorage.setItem('dao_thien_nguyen_v2',raw),raw);await page.reload();await page.locator('#btn-resume-game').click();await page.locator('.era-roadmap').waitFor();await pause(true);};
 const open=async()=>{await close();await page.locator('#sb-quests').click();await page.locator('.industry-panel').waitFor();};
 try{
 const prior=JSON.parse(await readFile('artifacts/industry-played-save.json','utf8')),gen=prior.island.buildings.find((b:any)=>b.type==='steam_generator'),shop=prior.island.buildings.find((b:any)=>b.type==='prototype_workshop');await load(JSON.stringify(prior));const initial=await save();assert.equal(initial.island.sharedFood,prior.island.sharedFood);assert.deepEqual(initial.island.civilization.inventory,{components:0,...prior.island.civilization.inventory});assert.deepEqual(initial.island.power,prior.island.power);
 await open();await page.locator('.industry-panel').scrollIntoViewIfNeeded();await page.waitForFunction(()=>[...document.querySelectorAll<HTMLImageElement>('.power-building img')].every(i=>i.complete&&i.naturalWidth>0));await page.screenshot({path:'artifacts/industry-desktop.png'});await page.locator(`[data-power-priority="${shop.id}"]`).selectOption('2');const priority=await save();assert.equal(priority.island.buildings.find((b:any)=>b.id===shop.id).powerPriority,2);assert.deepEqual(priority.island.civilization.inventory,initial.island.civilization.inventory);assert.equal(priority.island.power.clockTicks,initial.island.power.clockTicks);
 await open();await page.locator(`[data-power-toggle="${gen.id}"]`).click();assert.match(await page.locator('.power-summary').innerText(),/Cung 0/);const off=await save();assert.equal(off.island.power.steadyTicks,0);assert.deepEqual(off.island.civilization.inventory,initial.island.civilization.inventory);assert.equal(off.island.buildings.find((b:any)=>b.id===gen.id).powerFuelTicks,initial.island.buildings.find((b:any)=>b.id===gen.id).powerFuelTicks);
 await load(JSON.stringify(off));await open();assert.match(await page.locator(`[data-power-building="${shop.id}"]`).innerText(),/Thiếu điện/);await page.locator(`[data-power-building="${shop.id}"]`).scrollIntoViewIfNeeded();await page.screenshot({path:'artifacts/industry-outage.png'});await page.locator(`[data-power-toggle="${gen.id}"]`).click();await pause(false);await page.locator('.speed-btn[data-speed="2"]').click();await page.waitForTimeout(10000);await pause(true);const played=await save();assert.equal(played.island.npcs.filter((n:any)=>n.isAlive).length,25);assert(played.island.power.clockTicks>off.island.power.clockTicks);assert(played.island.power.steadyTicks>0);await writeFile('artifacts/industry-browser-save.json',JSON.stringify(played));await page.locator('#btn-zoom-in').click();await page.screenshot({path:'artifacts/industry-island.png'});
 // Explicit scarcity fixture: two extra completed workshops are for decision testing only, not earned gameplay.
 const scarcity=structuredClone(initial),extras=[0,1].map(i=>({...structuredClone(shop),id:'fixture-shop-'+i,tileX:17+i,tileY:11,workers:[],productionBatches:0,poweredTicks:0,powerPriority:1}));scarcity.island.buildings.push(...extras);await load(JSON.stringify(scarcity));await open();await page.locator('[data-power-priority="fixture-shop-1"]').selectOption('2');const scarce=await save();assert.equal(scarce.island.power.supply,4);assert.equal(scarce.island.power.demand,6);assert(scarce.island.power.supplied.includes('fixture-shop-1'));assert.equal(scarce.island.power.supplied.length,2);await open();await page.locator('[data-power-building="fixture-shop-1"]').scrollIntoViewIfNeeded();await page.screenshot({path:'artifacts/industry-priority-fixture.png'});
 await page.setViewportSize({width:390,height:844});await page.locator('.industry-panel').scrollIntoViewIfNeeded();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'artifacts/industry-mobile.png'});await page.locator('[data-power-priority="fixture-shop-0"]').selectOption('0');const mobile=await save();assert.equal(mobile.island.buildings.find((b:any)=>b.id==='fixture-shop-0').powerPriority,0);
 await close();await page.locator('#btn-build').click();assert.equal(await page.locator('[data-build="steelworks"]').count(),1);assert.equal(await page.locator('[data-build="steam_generator"]').count(),1);await page.screenshot({path:'artifacts/industry-build-mobile.png'});await page.setViewportSize({width:1440,height:1000});const upgraded=await readFile('artifacts/industry-upgraded-save.json','utf8');await load(upgraded);await open();assert.match(await page.locator('.power-summary').innerText(),/Cung 6/);await page.locator('.industry-panel').scrollIntoViewIfNeeded();await page.screenshot({path:'artifacts/industry-upgraded-desktop.png'});assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);console.log('PASS browser: real earned Iron industry save, original textures loaded, paid inputs untouched by pause/priority, toggle outage resets proof, exact reload, actual live power/recovery /25 alive, priority 4/6 fixture, desktop/mobile controls and no errors/overflow.');
 }catch(e){await page.screenshot({path:'artifacts/industry-ui-failure.png'});throw e;}finally{await browser.close();server.close();}
}
main().catch(e=>{console.error(e);server.close();process.exitCode=1;});
