import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE??'playwright');const root=path.resolve('web');
const server=createServer(async(req,res)=>{const file=path.resolve(root,'.'+new URL(req.url??'/','http://localhost').pathname.replace(/\/$/,'/index.html'));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{res.setHeader('content-type',({'.html':'text/html','.css':'text/css','.js':'text/javascript','.svg':'image/svg+xml','.png':'image/png'} as Record<string,string>)[path.extname(file)]??'application/octet-stream');res.end(await readFile(file));}catch{res.writeHead(404).end();}});
async function main(){
 await mkdir('artifacts',{recursive:true});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors:string[]=[],failed:string[]=[];page.on('pageerror',(e:Error)=>errors.push(e.message));page.on('response',(r:any)=>{if(r.status()>=400)failed.push(r.url());});const url=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
 const close=async()=>{if(await page.locator('#building-inspector').isVisible())await page.locator('#bi-close').click();if(await page.locator('#panel-overlay').evaluate((e:HTMLElement)=>e.classList.contains('open')))await page.locator('#panel-close').click();};
 const pause=async(on:boolean)=>{await close();if((await page.locator('#btn-pause').evaluate((e:HTMLElement)=>e.classList.contains('active')))!==on)await page.locator('#btn-pause').click();};
 const save=async()=>{await close();await page.locator('#btn-save-local').click();return page.evaluate(()=>JSON.parse(localStorage.getItem('dao_thien_nguyen_v2')!));};
 const load=async(raw:string)=>{await page.goto(url);await page.evaluate((raw:string)=>localStorage.setItem('dao_thien_nguyen_v2',raw),raw);await page.reload();await page.locator('#btn-resume-game').click();await page.locator('.era-roadmap').waitFor();await pause(true);};
 const open=async()=>{await close();await page.locator('#sb-quests').click();await page.locator('.era-roadmap').waitFor();await page.waitForTimeout(300);};
 const inspect=async(id:string)=>{await close();await page.locator('#btn-build').click();await page.locator(`[data-inspect-building="${id}"]`).click();await page.locator('#building-inspector').waitFor({state:'visible'});await page.waitForTimeout(300);};
 try{
 const raw=await readFile('artifacts/decisions-ready-save.json','utf8'),ready=JSON.parse(raw),lab=ready.island.buildings.find((b:any)=>b.type==='measurement_lab');await load(raw);const before=await save();await open();await page.locator('.analysis-panel h3').scrollIntoViewIfNeeded();const card=page.locator('.survey-site').filter({has:page.locator('[data-site="site-1"]')});await card.locator('summary').filter({hasText:'Nghiên cứu'}).click();assert.match(await card.innerText(),/60 nhịp/);assert.match(await card.innerText(),/Mất điện giữ tiến độ/);await page.screenshot({path:'artifacts/decisions-preview-desktop.png'});await pause(false);await open();await page.locator('[data-decision-key="site-1-research"] summary').click();await page.waitForTimeout(1800);assert(await page.locator('[data-decision-key="site-1-research"]').evaluate((e:HTMLDetailsElement)=>e.open));await pause(true);await open();await page.locator('[data-decision-key="site-1-research"] summary').click();await page.locator('[data-site="site-1"][data-site-decision="research"]').click();const paid=await save();assert.equal(paid.island.civilization.inventory.components,before.island.civilization.inventory.components-4);assert.equal(paid.island.analysis.foundation.workTicks,0);await load(JSON.stringify(paid));await open();assert.match(await page.locator('.analysis-panel').innerText(),/nền tảng 0\/60/);await page.locator('#cancel-foundation').click();const refund=await save();assert.equal(refund.island.civilization.inventory.components,before.island.civilization.inventory.components);
 await load(await readFile('artifacts/decisions-paused-save.json','utf8'));await open();assert.match(await page.locator('.analysis-status').innerText(),/Thiếu điện/);await page.locator(`[data-power-toggle="${lab.id}"]`).click();assert.match(await page.locator('.analysis-status').innerText(),/Đủ điện/);await pause(false);await page.locator('.speed-btn[data-speed="2"]').click();await open();await page.waitForFunction(()=>document.querySelector('.analysis-panel')?.textContent?.includes('Đã hoàn tất hồ sơ nền tảng'),undefined,{timeout:120000});await pause(true);const live=await save();assert(live.island.surveys.sites[0].foundationComplete);assert.equal(live.island.npcs.filter((n:any)=>n.isAlive).length,50);await page.screenshot({path:'artifacts/decisions-island.png'});
 await load(raw);await open();await page.locator('.survey-site').filter({has:page.locator('[data-site="site-2"]')}).locator('summary').filter({hasText:'Phong tỏa'}).click();await page.locator('[data-site="site-2"][data-site-decision="contain"]').click();const contained=await save();assert.equal(contained.island.civilization.inventory.cloth,before.island.civilization.inventory.cloth-4);assert.equal(contained.island.civilization.inventory.cutStone,before.island.civilization.inventory.cutStone-2);await load(JSON.stringify(contained));await open();await page.locator('.survey-site').filter({has:page.locator('[data-site="site-3"]')}).locator('summary').filter({hasText:'Bỏ qua'}).click();await page.locator('[data-site="site-3"][data-site-decision="ignore"]').click();const ignored=await save();assert.equal(ignored.island.surveys.sites[2].decision,'ignore');
 await page.setViewportSize({width:390,height:844});await load(await readFile('artifacts/decisions-played-save.json','utf8'));await open();await page.locator('.analysis-panel h3').scrollIntoViewIfNeeded();assert.match(await page.locator('.analysis-panel').innerText(),/Đã phong tỏa/);assert.match(await page.locator('.analysis-panel').innerText(),/Dị Tượng vẫn khóa/);await page.screenshot({path:'artifacts/decisions-mobile.png'});await page.locator('[data-decision-key="site-3-research"]').scrollIntoViewIfNeeded();await page.screenshot({path:'artifacts/decisions-choices-mobile.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);console.log('PASS browser decisions: preview/cost/public confirm/paid4/pause/reload/refund, outage immediate restore/live foundation/50 alive, containment/ignore persistence, mobile/no overflow/errors.');
 }catch(e){console.error(e);try{await page.screenshot({path:'artifacts/decisions-ui-failure.png'});}catch(imageError){console.error(imageError);}throw e;}finally{await browser.close();server.close();}
}
main().catch(e=>{console.error(e);server.close();process.exitCode=1;});
