import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {decodeSave,encodeSave} from '../src/core/SaveSystem';
import {reserveEntityIds} from '../src/core/factory';
import {SimulationSession,type PlayerCommand} from '../src/core/SimulationSession';
import {isPowerBuilding} from '../src/core/PowerManager';
const results=[];
for(const [name,branch] of [['augmentation','hightech'],['mystic-adaptation','mystic'],['eldritch-adaptation','eldritch']] as const){const d=decodeSave(readFileSync(`artifacts/${name}-played-save.json`,'utf8')),s=d.island,c=s.civilization!;reserveEntityIds(s);const sim=new SimulationSession(s,d.map);let sequence=0;const send=(command:PlayerCommand)=>{const r=sim.submit({playerId:'long-run-'+branch,sequence:++sequence,command});assert(r.accepted,JSON.stringify({command,r}));};const actor=s.npcs.find(n=>n.adaptation)!,initial={food:s.sharedFood,charge:actor.adaptation!.charge,produced:structuredClone(c.produced)};for(const b of s.buildings){if(isPowerBuilding(b))send({type:'set_power',buildingId:b.id,enabled:false,priority:b.powerPriority??1});if(b.type==='relic_extractor')send({type:'set_relic_extraction',buildingId:b.id,enabled:false});if(b.type==='spirit_extractor')send({type:'set_spirit_extraction',buildingId:b.id,enabled:false});if(['measurement_lab','component_factory','prototype_workshop','microchip_factory','control_center','spirit_refinery','resonance_tower','biomatter_workshop','quarantine','steelworks','iron_smelter','sawmill','stonecutter','relic_extractor','spirit_extractor'].includes(b.type))for(const id of [...b.workers]){send({type:'remove_worker',buildingId:b.id,npcId:id});send({type:'assign_labor',npcId:id,role:'food'});}}
let minFood=s.sharedFood;for(let i=0;i<300;i++){sim.advanceTicks(1);minFood=Math.min(minFood,s.sharedFood);assert.equal(s.npcs.filter(n=>n.isAlive).length,50);assert.equal(c.anomalyBranch,branch);assert(!s.adaptationProcess);}assert.equal(actor.adaptation!.charge,initial.charge);assert.equal(c.produced.components,initial.produced.components);assert.equal(c.produced.biomatter,initial.produced.biomatter);const raw=encodeSave(s,d.map,d.config);decodeSave(raw);writeFileSync(`artifacts/variants-${branch}-30day-save.json`,raw);results.push({branch,kind:'earned_idle_30_days',ticks:300,alive:50,foodStart:initial.food,foodMin:minFood,foodEnd:s.sharedFood,charge:actor.adaptation!.charge,continuousIndustrialProduction:false});}
// Additional paid safety operation on Eldritch continuation; not a fixture grant.
const d=decodeSave(readFileSync('artifacts/eldritch-adaptation-played-save.json','utf8')),s=d.island,c=s.civilization!,actor=s.npcs.find(n=>n.adaptation)!,station=s.buildings.find(b=>b.type==='relic_extractor')!;reserveEntityIds(s);const sim=new SimulationSession(s,d.map);let sequence=0;const send=(command:PlayerCommand)=>assert(sim.submit({playerId:'long-run-filtered',sequence:++sequence,command}).accepted,JSON.stringify(command));send({type:'assign_worker',buildingId:station.id,npcId:actor.id});send({type:'set_relic_safety',buildingId:station.id,enabled:true});send({type:'set_relic_extraction',buildingId:station.id,enabled:true});const before=station.productionBatches??0,wareBio=c.inventory.biomatter;assert.equal(wareBio,1);let minFood=s.sharedFood;for(let i=0;i<300;i++){sim.advanceTicks(1);minFood=Math.min(minFood,s.sharedFood);assert.equal(s.npcs.filter(n=>n.isAlive).length,50);}const batches=(station.productionBatches??0)-before;assert.equal(batches,5);assert.equal(station.relicSafetyBatches,0);assert.equal(actor.adaptation!.charge,95);assert.equal(c.inventory.biomatter,0);assert.equal(c.produced.relicBone,JSON.parse(readFileSync('artifacts/eldritch-adaptation-played-save.json','utf8')).island.civilization.produced.relicBone+10);assert((actor.exposure??0)<30);const raw=encodeSave(s,d.map,d.config);decodeSave(raw);writeFileSync('artifacts/variants-eldritch-filtered-30day-save.json',raw);results.push({branch:'eldritch',kind:'earned_filtered_30_days',ticks:300,alive:50,foodMin:minFood,foodEnd:s.sharedFood,paidBiomatter:wareBio-c.inventory.biomatter,actualFilteredHarvests:batches,charge:actor.adaptation!.charge,exposure:actor.exposure,stoppedWhenFuelEmpty:true,continuousIndustrialProduction:false});writeFileSync('artifacts/variants-long-run.json',JSON.stringify(results,null,2));console.log(JSON.stringify(results));console.log('PASS three branches30days safe-idle/no free industrial output, Eldritch additional1earned bio pays exactly5filtered harvests then stops,50alive/no grants/save intact.');
