import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE??'playwright');const root=path.resolve('web');
const server=createServer(async(req,res)=>{const file=path.resolve(root,'.'+new URL(req.url??'/','http://localhost').pathname.replace(/\/$/,'/index.html'));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{res.setHeader('content-type',({'.html':'text/html','.css':'text/css','.js':'text/javascript','.svg':'image/svg+xml','.png':'image/png'} as Record<string,string>)[path.extname(file)]??'application/octet-stream');res.end(await readFile(file));}catch{res.writeHead(404).end();}});
async function main(){
 await mkdir('artifacts',{recursive:true});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors:string[]=[],failed:string[]=[];page.on('pageerror',(e:Error)=>errors.push(e.message));page.on('response',(r:any)=>{if(r.status()>=400)failed.push(r.url());});const url=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
 const close=async()=>{if(await page.locator('#building-inspector').isVisible())await page.locator('#bi-close').click();if(await page.locator('#panel-overlay').evaluate((e:HTMLElement)=>e.classList.contains('open')))await page.locator('#panel-close').click();};
 const pause=async(on:boolean)=>{await close();if((await page.locator('#btn-pause').evaluate((e:HTMLElement)=>e.classList.contains('active')))!==on)await page.locator('#btn-pause').click();};
 const save=async()=>{await close();await page.locator('#btn-save-local').click();return page.evaluate(()=>JSON.parse(localStorage.getItem('dao_thien_nguyen_v2')!));};
 const load=async(raw:string)=>{await page.goto(url);await page.evaluate((raw:string)=>localStorage.setItem('dao_thien_nguyen_v2',raw),raw);await page.reload();await page.locator('#btn-resume-game').click();await page.locator('.era-roadmap').waitFor();await pause(true);};
 const open=async()=>{await close();await page.locator('#sb-quests').click();await page.locator('.era-roadmap').waitFor();await page.waitForTimeout(300);};
 const inspect=async(id:string)=>{await close();await page.locator('#btn-build').click();await page.locator(`[data-inspect-building="${id}"]`).click();await page.locator('#building-inspector').waitFor({state:'visible'});await page.waitForTimeout(300);};




 try{
 const raw=await readFile('artifacts/wildlife-ready-save.json','utf8'),initial=JSON.parse(raw),id=initial.island.npcs.find((n:any)=>n.torch).id,wolf=initial.island.wilderness.territories.find((t:any)=>t.species==='wolf');
 await load(raw);await open();await page.locator('#explorer-choice').selectOption(id);await page.locator('#place-explore-marker').click();const box=await page.locator('#game-canvas').boundingBox();assert(box);const z=Math.min(box.width/(initial.map.width*16),box.height/(initial.map.height*16))*.88;await page.locator('#game-canvas').click({position:{x:box.width/2+(wolf.x-initial.map.width/2+.5)*16*z,y:box.height/2+(wolf.y-initial.map.height/2+.5)*16*z}});await page.locator('#recall-explorer').waitFor();const started=await save();assert(started.island.exploration.active);
 await pause(false);await open();await page.waitForFunction(()=>document.querySelector('[data-wildlife-message]')?.textContent?.includes('xua sói'),{},{timeout:30000});await pause(true);const mid=await save();assert(mid.island.wilderness.repelled>=1);assert.equal(mid.island.npcs.find((n:any)=>n.id===id).health,100);await writeFile('artifacts/wildlife-browser-midtrip-save.json',JSON.stringify(mid));await open();await page.screenshot({path:'artifacts/wildlife-torch-desktop.png'});await close();await page.screenshot({path:'artifacts/wildlife-torch-world.png'});
 // Zoom toward the actual seen wolf to inspect the soft custom sprite in the game.
 const animal=mid.island.wilderness.territories.find((t:any)=>t.species==='wolf'),px=box.x+box.width/2+(animal.animalX-initial.map.width/2+.5)*16*z,py=box.y+box.height/2+(animal.animalY-initial.map.height/2+.5)*16*z;await page.mouse.move(px,py);for(let i=0;i<7;i++)await page.mouse.wheel(0,-100);await page.waitForTimeout(400);await page.screenshot({path:'artifacts/wildlife-wolf-closeup.png'});
 await load(JSON.stringify(mid));const restored=await save();assert.deepEqual(restored.island.wilderness,mid.island.wilderness);assert.deepEqual(restored.island.exploration.active,mid.island.exploration.active);await pause(false);await open();await page.waitForFunction(()=>!document.querySelector('#recall-explorer'),{},{timeout:30000});await pause(true);const earned=await save();assert.equal(earned.island.npcs.filter((n:any)=>n.isAlive).length,8);assert.equal(earned.island.npcs.find((n:any)=>n.id===id).health,100);assert(!earned.island.exploration.active);await writeFile('artifacts/wildlife-browser-played-save.json',JSON.stringify(earned));await open();await page.setViewportSize({width:390,height:844});await page.locator('.wildlife-panel').scrollIntoViewIfNeeded();await page.screenshot({path:'artifacts/wildlife-mobile.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 // Injury/healing use a separately labelled controlled fixture with herbalism enabled.
 await page.setViewportSize({width:1440,height:1000});await load(await readFile('artifacts/wildlife-injury-fixture-save.json','utf8'));await pause(false);await open();await page.waitForFunction(()=>document.querySelector('[data-wildlife-message]')?.textContent?.includes('mất 16'),{},{timeout:20000});await pause(true);const injured=await save();assert(injured.island.wilderness.injuries>=1);assert(!injured.island.exploration.patrol.enabled);assert(injured.island.npcs.find((n:any)=>n.id===id).health<90);await open();await page.screenshot({path:'artifacts/wildlife-injury-fixture.png'});await close();await page.screenshot({path:'artifacts/wildlife-boar-fixture-world.png'});
 await load(JSON.stringify(injured));assert.deepEqual((await save()).island.wilderness,injured.island.wilderness);await pause(false);await open();await page.waitForFunction(()=>!document.querySelector('#recall-explorer'),{},{timeout:30000});await pause(true);const returned=await save();assert(!returned.island.exploration.active);const patient=returned.island.npcs.find((n:any)=>n.id===id);assert(patient.health<90);await open();await page.locator('#wildlife-care').click();const treat=page.locator(`[data-treat="${id}"]`);assert(await treat.isEnabled());await treat.click();const request=await save();assert(request.island.npcs.find((n:any)=>n.id===id).treatment);await pause(false);await page.locator('#btn-military').click();await page.waitForFunction((id:string)=>document.querySelector(`[data-care-state="${id}"]`)?.textContent?.includes('Sức khỏe 100%'),id,{timeout:45000});await pause(true);const healed=await save();assert.equal(healed.island.npcs.find((n:any)=>n.id===id).health,100);assert.equal(healed.island.npcs.find((n:any)=>n.id===id).herbalDoses,(patient.herbalDoses??0)+1);assert.equal(healed.island.npcs.filter((n:any)=>n.isAlive).length,8);await page.locator('#btn-military').click();await page.screenshot({path:'artifacts/wildlife-healing-fixture.png'});
 assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);await writeFile('artifacts/wildlife-browser-result.json',JSON.stringify({earned:{alive:8,food:earned.island.sharedFood,repelled:earned.island.wilderness.repelled,health:100,midtripReload:true,physicalReturn:true,mobile:true},separateFixture:{injuries:injured.island.wilderness.injuries,injuryHP:injured.island.npcs.find((n:any)=>n.id===id).health,patrolStopped:true,returned:true,healedHP:100,herbalDosePaid:1},errors,failed},null,2));console.log('PASS browser earned torch/wolf/real map trip/save-return/mobile; separate boar injury/stop/return/paid herbal treatment fixture/no errors.');
 }catch(error){try{await page.screenshot({path:'artifacts/wildlife-ui-failure.png'});await close();await page.locator('#btn-save-local').click();const raw=await page.evaluate(()=>localStorage.getItem('dao_thien_nguyen_v2'));if(raw)await writeFile('artifacts/wildlife-ui-failure-save.json',raw);}catch{}throw error;}finally{await browser.close();server.close();}
}
main().catch(e=>{console.error(e);server.close();process.exitCode=1;});
