import {characterSVG,characterLook} from '../src/renderer/CharacterTextures';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE??'playwright');const root=path.resolve('web');
const server=createServer(async(req,res)=>{const file=path.resolve(root,'.'+new URL(req.url??'/','http://localhost').pathname.replace(/\/$/,'/index.html'));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{res.setHeader('content-type',({'.html':'text/html','.css':'text/css','.js':'text/javascript','.svg':'image/svg+xml','.png':'image/png'} as Record<string,string>)[path.extname(file)]??'application/octet-stream');res.end(await readFile(file));}catch{res.writeHead(404).end();}});
async function main(){
 await mkdir('artifacts',{recursive:true});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors:string[]=[],failed:string[]=[];page.on('pageerror',(e:Error)=>errors.push(e.message));page.on('response',(r:any)=>{if(r.status()>=400)failed.push(r.url());});
 const url=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
 const close=async()=>{if(await page.locator('#panel-overlay').evaluate((e:HTMLElement)=>e.classList.contains('open')))await page.locator('#panel-close').click();await page.waitForTimeout(350);};
 const pause=async(on:boolean)=>{await close();if((await page.locator('#btn-pause').evaluate((e:HTMLElement)=>e.classList.contains('active')))!==on)await page.locator('#btn-pause').click();};
 const save=async()=>{await close();await page.locator('#btn-save-local').click();return page.evaluate(()=>JSON.parse(localStorage.getItem('dao_thien_nguyen_v2')!));};
 const load=async(raw:string)=>{await page.goto(url);await page.evaluate((raw:string)=>localStorage.setItem('dao_thien_nguyen_v2',raw),raw);await page.reload();await page.locator('#btn-resume-game').click();await page.locator('.era-roadmap').waitFor();await pause(true);};
 try{
 await page.addInitScript(()=>{const original=CanvasRenderingContext2D.prototype.drawImage;const draws:Record<string,{x:number;y:number;w:number;h:number}>={};(window as any).characterDraws=draws;CanvasRenderingContext2D.prototype.drawImage=function(...args:any[]){const img=args[0] as HTMLImageElement;if(img?.src?.includes('viewBox%3D%220%200%2024%2036%22')&&args.length===5)draws[img.src]={x:args[1],y:args[2],w:args[3],h:args[4]};return (original as any).apply(this,args);};});
 const prior=JSON.parse(await readFile('artifacts/faith-played-save.json','utf8')),fixture=JSON.parse(JSON.stringify(prior)),n=fixture.island.npcs[0];for(const person of fixture.island.npcs)person.researching=false;n.researching=true;n.status='idle';const target=fixture.map.landTiles.filter((t:any)=>['grass','forest','sand'].includes(fixture.map.tiles[t.y][t.x])&&!fixture.island.buildings.some((b:any)=>b.tileX===t.x&&b.tileY===t.y)).sort((a:any,b:any)=>(Math.abs(a.x-fixture.map.width/2)+Math.abs(a.y-fixture.map.height/2))-(Math.abs(b.x-fixture.map.width/2)+Math.abs(b.y-fixture.map.height/2)))[0];n.position={tileX:target.x,tileY:target.y};await load(JSON.stringify(fixture));await page.locator('#sb-population').click();await page.waitForTimeout(400);const portrait=await page.locator('.pop-row .character-portrait').first().getAttribute('src');await close();for(let i=0;i<20;i++)await page.locator('#btn-zoom-in').click();await page.waitForTimeout(1000);const expected='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(characterSVG(characterLook(n),fixture.island.civilization.era,'south','work',0));const draw=await page.evaluate((src:string)=>(window as any).characterDraws[src],expected);assert(draw,'Actual custom sprite was drawn');const rect=await page.locator('#game-canvas').boundingBox();await page.mouse.click(rect.x+draw.x+draw.w/2,rect.y+draw.y+draw.h*10/36);await page.locator('#inspector-npc .character-portrait').waitFor({state:'visible'});assert.equal(await page.locator('.insp-name').innerText(),n.name.split('#')[0]);await page.waitForTimeout(500);await page.screenshot({path:'artifacts/characters-selected-desktop.png'});assert.equal(await page.locator('#inspector-npc .character-portrait').getAttribute('src'),portrait);await page.locator('#inspector-close').click();await page.goto(url+'/character-gallery.html');await page.waitForFunction(()=>[...document.images].every(i=>i.complete&&i.naturalWidth>0));await page.locator('section').first().screenshot({path:'artifacts/characters-cute-sample.png'});assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);console.log('PASS: actual sprite draw, high-zoom head click selects correct resident, original portrait shown, no browser errors. Fixture changes placement/research badge only, without resource gifts.');
 }finally{await browser.close();await new Promise<void>(r=>server.close(()=>r()));}}
void main().catch(e=>{console.error(e);server.close();process.exitCode=1;});
