import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE??'playwright');const root=path.resolve('web');
const server=createServer(async(req,res)=>{const file=path.resolve(root,'.'+new URL(req.url??'/','http://localhost').pathname.replace(/\/$/,'/index.html'));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{res.setHeader('content-type',({'.html':'text/html','.css':'text/css','.js':'text/javascript','.svg':'image/svg+xml','.png':'image/png'} as Record<string,string>)[path.extname(file)]??'application/octet-stream');res.end(await readFile(file));}catch{res.writeHead(404).end();}});
async function main(){
 await mkdir('artifacts',{recursive:true});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors:string[]=[],failed:string[]=[];page.on('pageerror',(e:Error)=>errors.push(e.message));page.on('response',(r:any)=>{if(r.status()>=400)failed.push(r.url());});const url=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
 const close=async()=>{if(await page.locator('#panel-overlay').evaluate((e:HTMLElement)=>e.classList.contains('open')))await page.locator('#panel-close').click();};
 const pause=async(on:boolean)=>{await close();if((await page.locator('#btn-pause').evaluate((e:HTMLElement)=>e.classList.contains('active')))!==on)await page.locator('#btn-pause').click();};
 const save=async()=>{await close();await page.locator('#btn-save-local').click();return page.evaluate(()=>JSON.parse(localStorage.getItem('dao_thien_nguyen_v2')!));};
 const load=async(raw:string)=>{await page.goto(url);await page.evaluate((raw:string)=>localStorage.setItem('dao_thien_nguyen_v2',raw),raw);await page.reload();await page.locator('#btn-resume-game').click();await page.locator('.era-roadmap').waitFor();await pause(true);};
 const open=async()=>{await close();await page.locator('#sb-quests').click();await page.locator('.modern-preparation').waitFor();await page.waitForTimeout(300);};
 try{
 // Core-paid staging world: public Modern start is enabled after verification of its factory chain.
 const raw=await readFile('artifacts/modern-investment-stage-save.json','utf8'),prior=JSON.parse(raw);await load(raw);await open();assert.match(await page.locator('#era-transition-status').innerText(),/15\/50/);assert(await page.locator('#btn-develop-era').isDisabled());assert.match(await page.locator('.modern-preparation').innerText(),/Phí đầu tư đã trả/);await page.locator('.modern-preparation').scrollIntoViewIfNeeded();await page.screenshot({path:'artifacts/modern-investment-staged-desktop.png'});const same=await save();assert.deepEqual(same.island.civilization.inventory,{components:0,...prior.island.civilization.inventory});assert.deepEqual(same.island.civilization.transition,prior.island.civilization.transition);
 await page.setViewportSize({width:390,height:844});await open();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'artifacts/modern-investment-staged-mobile.png'});await pause(false);await page.locator('.speed-btn[data-speed="2"]').click();await page.waitForTimeout(3500);await pause(true);const progress=await save();assert(progress.island.civilization.transition.workTicks>15);assert(progress.island.civilization.transition.workTicks<50);assert.equal(progress.island.civilization.era,'iron');assert.equal(progress.island.npcs.filter((n:any)=>n.isAlive).length,50);await load(JSON.stringify(progress));await open();assert.match(await page.locator('#era-transition-status').innerText(),new RegExp(`${progress.island.civilization.transition.workTicks}/50`));await page.screenshot({path:'artifacts/modern-investment-staged-resume.png'});
 await load(await readFile('artifacts/modern-ready-save.json','utf8'));await open();assert(await page.locator('#btn-develop-era').isEnabled());assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);console.log('PASS browser staged transition: paid core world /15 of 50 steps, pause preserves goods/progress, live ticks and exact reload, 50 alive, desktop/mobile no errors/overflow. Ready world exposes the enabled Modern investment button.');
 }catch(e){await page.screenshot({path:'artifacts/modern-investment-ui-failure.png'});throw e;}finally{await browser.close();server.close();}
}
main().catch(e=>{console.error(e);process.exitCode=1;});
