import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {createIsland,reserveEntityIds} from '../src/core/factory';
import {createCivilization,buildingLock} from '../src/core/civilization';
import {initializePower,tickPower,trackPower,setPower,refreshPower,generatorCapacity} from '../src/core/PowerManager';
import {initializeLogistics,tickLogistics,processLocalRecipe,sumStock,haulJobs} from '../src/core/logistics';
import {tickBuildings,upgradeCost,upgradeBuilding,BUILD_COSTS,canAfford} from '../src/renderer/BuildingManager';
import {SimulationSession,type PlayerCommand} from '../src/core/SimulationSession';
import {decodeSave,encodeSave} from '../src/core/SaveSystem';
import {TECH_TREE} from '../src/core/research';
import {findPath} from '../src/core/pathfinding';
import type {WorldMap} from '../src/renderer/WorldMap';
import type {Building,BuildingType} from '../src/core/types';
const map:WorldMap={width:24,height:12,tiles:Array.from({length:12},()=>Array(24).fill('grass')),landTiles:[]};for(let y=0;y<12;y++)for(let x=0;x<24;x++)map.landTiles.push({x,y});
const cfg={mode:'local' as const,seed:321,size:'small' as const,width:24,height:12,population:4};
function fixture(){const s=createIsland('Điện thử',4);s.civilization=createCivilization();s.civilization.era='iron';for(const n of s.npcs){n.age=25;n.occupation='gatherer';n.position={tileX:3,tileY:3};n.laborRole='idle';n.needs.hunger=0;n.needs.rest=0;}s.sharedFood=100;s.buildings=[{id:'gen',type:'steam_generator',tileX:15,tileY:3,complete:true,progress:100,workers:[],buffer:{input:{coal:1},output:{}}},...[0,1,2].map(i=>({id:'shop'+i,type:'prototype_workshop' as const,tileX:3+i,tileY:3,complete:true,progress:100,workers:[s.npcs[i].id],productionBatches:1,buffer:{input:{steel:6,lumber:6},output:{}}}))];initializePower(s);initializeLogistics(s);return s;}
const s=fixture();tickPower(s);assert.equal(s.power!.supply,4);assert.equal(s.power!.demand,6);assert.deepEqual(s.power!.supplied,['shop0','shop1']);assert.equal(s.buildings[0].buffer!.input.coal,0);for(let i=0;i<9;i++)tickPower(s);assert.equal(s.power!.supply,4);const snapshot=encodeSave(s,map,cfg),fuel=s.buildings[0].powerFuelTicks;for(let i=0;i<10;i++)setPower(s,'shop2',true,2);assert.equal(s.buildings[0].powerFuelTicks,fuel);assert.deepEqual(s.power!.supplied,['shop2','shop0']);tickPower(s);assert.equal(s.power!.supply,0);assert.equal(s.civilization!.inventory.coal,0);assert(!('electricity' in s.civilization!.inventory));
const p=fixture();tickPower(p);for(let i=0;i<20;i++)trackPower(p);assert.equal(p.buildings[1].poweredTicks,20);setPower(p,'shop0',true,0);setPower(p,'shop2',true,2);assert.equal(p.buildings[1].poweredTicks,0);assert.equal(p.buildings[3].poweredTicks,0,'No proof transferred to another factory');for(let i=0;i<10;i++)trackPower(p);assert.equal(p.buildings[3].poweredTicks,10);assert.equal(p.buildings[2].poweredTicks,30);setPower(p,'gen',false,1);assert.equal(p.power!.steadyTicks,0);const fuelBefore=p.buildings[0].powerFuelTicks;tickPower(p);assert.equal(p.buildings[0].powerFuelTicks,fuelBefore);setPower(p,'gen',true,1);assert.equal(p.power!.steadyTicks,0);assert.deepEqual(decodeSave(encodeSave(p,map,cfg)).island.power,p.power);
const bad=JSON.parse(encodeSave(p,map,cfg));bad.island.buildings[1].poweredTicks=999;assert.throws(()=>decodeSave(JSON.stringify(bad)),/điện/);const bad2=JSON.parse(snapshot);bad2.island.power.supplied=['gen'];assert.throws(()=>decodeSave(JSON.stringify(bad2)),/điện/);
// Missing fuel, inputs, power and full buffers never debit materials or erase partial work.
const r=fixture(),shop=r.buildings[1];r.power!.supplied=[];const before=JSON.stringify(shop.buffer);processLocalRecipe(r,shop);assert.equal(JSON.stringify(shop.buffer),before);r.npcs[0].buildingWork={buildingId:shop.id,ticks:3};tickBuildings(r,r.resources,map);assert.equal(r.npcs[0].buildingWork.ticks,3);tickPower(r);processLocalRecipe(r,shop);assert.equal(shop.buffer!.output.machineParts,2);shop.buffer!.output.machineParts=60;const input=JSON.stringify(shop.buffer!.input);processLocalRecipe(r,shop);assert.equal(JSON.stringify(shop.buffer!.input),input);shop.buffer!.output={};shop.buffer!.input.steel=0;processLocalRecipe(r,shop);assert.equal(sumStock(shop.buffer!.output),0);
const steel:Building={id:'steel',type:'steelworks',tileX:4,tileY:4,complete:true,progress:100,workers:[],buffer:{input:{iron:4,coal:2},output:{}}};processLocalRecipe(r,steel);assert.equal(steel.buffer!.output.steel,2);assert.equal(r.civilization!.produced.steel,2);const stone:Building={...steel,id:'stone',type:'stonecutter',buffer:{input:{stone:4},output:{}}};processLocalRecipe(r,stone);assert.equal(stone.buffer!.output.cutStone,3);
// A courier must physically carry the fuel; global coal cannot power a remote machine.
const haul=fixture();haul.buildings=haul.buildings.slice(0,1);haul.buildings.push({id:'store',type:'storehouse',tileX:3,tileY:3,complete:true,progress:100,workers:[]});haul.buildings[0].buffer!.input={};haul.civilization!.inventory.coal=9;const carrier=haul.npcs[3];carrier.laborRole='haul';carrier.position={tileX:3,tileY:3};tickPower(haul);assert.equal(haul.power!.supply,0);tickLogistics(haul,map);assert.equal(carrier.freight!.good,'coal');assert.equal(haul.power!.supply,0);assert.equal(haul.civilization!.inventory.coal,0);for(let i=0;i<20&&carrier.freight;i++){carrier.survivalBlocked=false;tickLogistics(haul,map);}assert.equal(haul.buildings[0].buffer!.input.coal,9);tickPower(haul);assert.equal(haul.power!.supply,4);
const cmd=new SimulationSession(haul,map),env={playerId:'test',sequence:1,command:{type:'set_power' as const,buildingId:'gen',enabled:false,priority:1}};const clock=haul.power!.clockTicks;assert(cmd.submit(env).accepted);assert(cmd.submit(env).duplicate);assert.equal(haul.power!.clockTicks,clock);assert(!cmd.submit({playerId:'test',sequence:2,command:{...env.command,priority:3}}).accepted);

const decision=fixture();decision.civilization!.inventory.coal=9;decision.buildings.push({id:'food-buffer',type:'farm',tileX:4,tileY:4,complete:true,progress:100,workers:[],buffer:{input:{},output:{food:30}}});assert.equal(haulJobs(decision)[0].target,'gen','Safe food stock allows fuel first');decision.sharedFood=0;for(const n of decision.npcs)n.privateFood=0;assert.equal(haulJobs(decision)[0].good,'food','Urgent food stays first');decision.civilization!.inventory.steel=10;setPower(decision,'shop0',false,1);decision.buildings[1].buffer!.input={};assert(!haulJobs(decision).some(j=>j.target==='shop0'),'Off workshop does not requisition more inputs');tickPower(decision);trackPower(decision);const ds=new SimulationSession(decision,map),active=decision.buildings[2];assert(active.poweredTicks!>0);assert(ds.submit({playerId:'d',sequence:1,command:{type:'remove_worker',buildingId:active.id,npcId:active.workers[0]}}).accepted);assert.equal(active.poweredTicks,0,'Removing a worker resets its proof while paused');
assert.equal(generatorCapacity({...haul.buildings[0],level:2}),6);assert.equal(generatorCapacity({...haul.buildings[0],level:3}),8);const cost=upgradeCost(haul.buildings[0],haul);assert.equal(cost.goods!.machineParts,4);assert(upgradeBuilding(haul,'gen'),'No free upgrade when missing machine parts');console.log('PASS: physical fuel /10 ticks, priority scarcity, per-factory continuous proof/reset, no electricity storage, recipes / blocked output, held work, paid upgrade sink, idempotent paused commands, exact saves/corruption.');
// Continue the real Iron playthrough: no injected inventory, technologies or completed new buildings.
const data=decodeSave(readFileSync('artifacts/logistics-iron-save.json','utf8')),w=data.island,c=w.civilization!;reserveEntityIds(w);initializePower(w);initializeLogistics(w);const startTick=w.tick;let sim=new SimulationSession(w,data.map),seq=0;const send=(command:PlayerCommand)=>{const result=sim.submit({playerId:'industry',sequence:++seq,command});assert(result.accepted,JSON.stringify({command,result}));};
let maxProof=0;const until=(ok:()=>boolean,max=4000)=>{for(let i=0;i<max&&!ok();i++){sim.advanceTicks(1);maxProof=Math.max(maxProof,w.power!.steadyTicks);if(w.npcs.filter(n=>n.isAlive).length!==25){writeFileSync('artifacts/industry-failed-save.json',encodeSave(w,data.map,data.config));console.log(JSON.stringify({tick:w.tick,food:w.sharedFood,goods:c.inventory,people:w.npcs.map(n=>({id:n.id,alive:n.isAlive,hunger:n.needs.hunger,age:n.age,role:n.laborRole,msg:n.laborMessage})),buildings:w.buildings.map(b=>({id:b.id,type:b.type,workers:b.workers,msg:b.workMessage,buffer:b.buffer}))}));}assert.equal(w.npcs.filter(n=>n.isAlive).length,25,'Keep real settlement alive');}assert(ok(),JSON.stringify({maxProof,tick:w.tick,food:w.sharedFood,wood:w.wood,stone:w.stone,goods:c.inventory,research:c.research,power:w.power,work:w.buildings.map(b=>[b.type,b.workers,b.workMessage,b.buffer])}));};
const researcher=w.npcs[22],builder=w.npcs[23],worker=w.npcs[24];send({type:'assign_labor',npcId:w.npcs[20].id,role:'wood'});
// Rebalance existing real labor before extending industry: grain and bread replace idle textile/trade work.
for(const [index,target] of [[3,'wheat_field'],[4,'bakery'],[12,'farm'],[0,'farm']] as const){const n=w.npcs[index];for(const b of w.buildings)if(b.workers.includes(n.id))send({type:'remove_worker',buildingId:b.id,npcId:n.id});const b=w.buildings.find(b=>b.type===target)!;send({type:'assign_worker',buildingId:b.id,npcId:n.id});}

for(const n of [researcher,builder,worker]){for(const b of w.buildings)if(b.workers.includes(n.id))send({type:'remove_worker',buildingId:b.id,npcId:n.id});send({type:'assign_labor',npcId:n.id,role:'idle'});}
function research(id:string){const tech=TECH_TREE.find(t=>t.id===id)!;until(()=>w.wood>=tech.costWood&&w.stone>=tech.costStone&&w.sharedFood>=tech.costFood&&Object.entries(tech.costGoods??{}).every(([g,a])=>c.inventory[g as keyof typeof c.inventory]>=a!));send({type:'start_research',techId:id});send({type:'assign_researcher',npcId:researcher.id});until(()=>c.unlocks.includes(id));}
function build(type:BuildingType){until(()=>canAfford(w,BUILD_COSTS[type]));assert.equal(buildingLock(w,type),null);const site=data.map.landTiles.find(t=>t.x>=4&&t.x<=18&&t.y>=10&&t.y<=18&&['grass','sand'].includes(data.map.tiles[t.y][t.x])&&!w.buildings.some(b=>b.tileX===t.x&&b.tileY===t.y)&&!w.npcs.some(n=>n.isAlive&&n.position?.tileX===t.x&&n.position?.tileY===t.y)&&!w.animals.some(n=>n.isAlive&&n.position?.tileX===t.x&&n.position?.tileY===t.y)&&findPath(data.map,builder.position!.tileX,builder.position!.tileY,t.x,t.y)!==null)!;assert(site);send({type:'build',buildingType:type,tileX:site.x,tileY:site.y});const b=w.buildings.at(-1)!;send({type:'assign_worker',buildingId:b.id,npcId:builder.id});until(()=>b.complete);if(type==='steam_generator')send({type:'set_power',buildingId:b.id,enabled:false,priority:1});if(b.workers.includes(builder.id))send({type:'remove_worker',buildingId:b.id,npcId:builder.id});return b;}
research('mechanics');research('steelmaking');
// The old local iron deposit is depleted; use the existing paid NPC trade route for ore.
const trader=w.npcs[21],post=w.buildings.find(b=>b.type==='tradepost')!;send({type:'assign_worker',buildingId:post.id,npcId:trader.id});until(()=>!trader.cargo&&!trader.freight&&!trader.actionTarget&&!trader.haulTask);for(let i=0;i<8;i++){send({type:'start_trade',buildingId:post.id,offerId:'cloth_for_ore'});until(()=>!post.shipment);}send({type:'remove_worker',buildingId:post.id,npcId:trader.id});
const furnace=build('steelworks');send({type:'assign_worker',buildingId:furnace.id,npcId:worker.id});until(()=>c.inventory.steel>=12&&c.produced.steel>=30);send({type:'remove_worker',buildingId:furnace.id,npcId:worker.id});send({type:'assign_labor',npcId:worker.id,role:'food'});research('electricity');const generator=build('steam_generator'),workshop=build('prototype_workshop'),cutter=build('stonecutter');send({type:'assign_worker',buildingId:post.id,npcId:trader.id});until(()=>!trader.cargo&&!trader.freight&&!trader.actionTarget&&!trader.haulTask);for(let i=0;i<3;i++){send({type:'start_trade',buildingId:post.id,offerId:'copper_for_coal'});until(()=>!post.shipment);}send({type:'remove_worker',buildingId:post.id,npcId:trader.id});send({type:'set_power',buildingId:generator.id,enabled:true,priority:1});send({type:'assign_worker',buildingId:workshop.id,npcId:builder.id});send({type:'assign_worker',buildingId:cutter.id,npcId:researcher.id});until(()=>c.inventory.machineParts>=4&&c.inventory.cutStone>=12&&w.power!.steadyTicks>=30);writeFileSync('artifacts/industry-played-save.json',encodeSave(w,data.map,data.config));console.log(`PASS real Iron chain: 25 alive /Food ${w.sharedFood.toFixed(1)}, steel produced ${c.produced.steel}, parts ${c.inventory.machineParts}, stone ${c.inventory.cutStone}, power ${w.power!.supply}/${w.power!.demand}, proof ${w.power!.steadyTicks}, ${w.tick-startTick} ticks`);
send({type:'remove_worker',buildingId:cutter.id,npcId:researcher.id});send({type:'assign_labor',npcId:researcher.id,role:'stone'});send({type:'set_power',buildingId:workshop.id,enabled:false,priority:1});send({type:'set_power',buildingId:generator.id,enabled:false,priority:1});
// Buy real fuel for the upgrade phase too; do not burn it in an idle generator.
send({type:'assign_worker',buildingId:post.id,npcId:trader.id});until(()=>!trader.cargo&&!trader.freight&&!trader.actionTarget&&!trader.haulTask);for(let i=0;i<2;i++){send({type:'start_trade',buildingId:post.id,offerId:'copper_for_coal'});until(()=>!post.shipment);}send({type:'remove_worker',buildingId:post.id,npcId:trader.id});send({type:'assign_worker',buildingId:furnace.id,npcId:worker.id});until(()=>c.inventory.steel>=4);send({type:'remove_worker',buildingId:furnace.id,npcId:worker.id});send({type:'assign_labor',npcId:worker.id,role:'food'});const upgrades=upgradeCost(generator,w);until(()=>canAfford(w,upgrades));const parts=c.inventory.machineParts,stones=c.inventory.cutStone;send({type:'upgrade_building',buildingId:generator.id});assert.equal(c.inventory.machineParts,parts-4);assert.equal(c.inventory.cutStone,stones-10);send({type:'remove_worker',buildingId:workshop.id,npcId:builder.id});send({type:'assign_worker',buildingId:generator.id,npcId:builder.id});until(()=>generator.level===2&&!generator.upgrade);if(generator.workers.includes(builder.id))send({type:'remove_worker',buildingId:generator.id,npcId:builder.id});send({type:'assign_worker',buildingId:workshop.id,npcId:builder.id});send({type:'set_power',buildingId:workshop.id,enabled:true,priority:1});send({type:'set_power',buildingId:generator.id,enabled:true,priority:1});until(()=>w.power!.supply===6&&w.power!.steadyTicks>=30);assert.equal(c.era,'iron');assert(!sim.submit({playerId:'industry',sequence:++seq,command:{type:'develop_era'}}).accepted);const final=encodeSave(w,data.map,data.config);assert.deepEqual(decodeSave(final).island.power,w.power);writeFileSync('artifacts/industry-upgraded-save.json',final);console.log('PASS real materials paid / upgraded 6 power / restored 3-day proof; Modern correctly locked.');
