import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {createIsland,reserveEntityIds} from '../src/core/factory';
import {createCivilization,ERAS,buildingLock} from '../src/core/civilization';
import {initializePower,refreshPower,setPower} from '../src/core/PowerManager';
import {initializeLogistics,processLocalRecipe,haulJobs} from '../src/core/logistics';
import {decodeSave,encodeSave} from '../src/core/SaveSystem';
import {SimulationSession,type PlayerCommand} from '../src/core/SimulationSession';
import {TECH_TREE} from '../src/core/research';
import {BUILD_COSTS,canAfford,upgradeCost,maxBuildingWorkers} from '../src/renderer/BuildingManager';
import {findPath} from '../src/core/pathfinding';
// The real campaign must use the public release flag without overriding it.
assert(ERAS.find(e=>e.id==='modern')!.implemented);
const unit=createIsland('Fixture điện nhà máy',2);unit.civilization=createCivilization();unit.civilization.era='modern';for(const n of unit.npcs){n.age=25;n.position={tileX:3,tileY:2};}unit.buildings=[{id:'gen',type:'steam_generator',tileX:2,tileY:2,workers:[],complete:true,progress:100,buffer:{input:{coal:3},output:{}},powerFuelTicks:10},{id:'plant',type:'component_factory',tileX:3,tileY:2,workers:[unit.npcs[0].id],complete:true,progress:100,buffer:{input:{steel:2,copper:2},output:{}}}];initializeLogistics(unit);initializePower(unit);refreshPower(unit);const plant=unit.buildings[1];processLocalRecipe(unit,plant);assert.equal(plant.buffer!.output.components,3);assert.equal(plant.buffer!.input.steel,0);assert.equal(unit.civilization.produced.components,3);assert.equal(unit.civilization.inventory.components,0);plant.buffer!.input={steel:2,copper:2};setPower(unit,'gen',false,1);const held=structuredClone(plant.buffer);processLocalRecipe(unit,plant);assert.deepEqual(plant.buffer,held);setPower(unit,'gen',true,1);plant.buffer!.output.components=59;processLocalRecipe(unit,plant);assert.equal(plant.buffer!.input.steel,2,'Blocked output holds inputs');setPower(unit,'plant',false,1);unit.civilization.inventory.steel=10;assert(!haulJobs(unit).some(j=>j.target==='plant'));assert.equal(upgradeCost(plant,unit).goods!.components,6);assert.equal(maxBuildingWorkers({...plant,level:2}),3);console.log('PASS factory fixture: exact metal recipe/onsite output, power loss/full output preserve inputs, off stops requests, six-component upgrade sink and three workers.');
const data=decodeSave(readFileSync('artifacts/modern-ready-save.json','utf8')),s=data.island,c=s.civilization!;reserveEntityIds(s);let sim=new SimulationSession(s,data.map),seq=0;const start=s.tick;const send=(command:PlayerCommand)=>{const r=sim.submit({playerId:'modern-chain',sequence:++seq,command});assert(r.accepted,JSON.stringify({command,r}));};
const until=(ok:()=>boolean,max=2500)=>{for(let i=0;i<max&&!ok();i++){sim.advanceTicks(1);assert.equal(s.npcs.filter(n=>n.isAlive).length,50);}if(!ok())writeFileSync('artifacts/modern-chain-waiting-save.json',encodeSave(s,data.map,data.config));assert(ok(),JSON.stringify({tick:s.tick,food:s.sharedFood,goods:c.inventory,research:c.research,power:s.power,work:s.buildings.map(b=>[b.type,b.workers,b.workMessage,b.buffer])}));};
const investment={playerId:'modern-chain',sequence:++seq,command:{type:'develop_era' as const}},before=structuredClone(c.inventory);assert(sim.submit(investment).accepted);assert.equal(c.inventory.steel,before.steel-30);assert.equal(c.inventory.cutStone,before.cutStone-40);assert.equal(c.inventory.cloth,before.cloth-20);assert(sim.submit(investment).duplicate);for(const b of s.buildings.filter(b=>['prototype_workshop','steam_generator'].includes(b.type)))send({type:'set_power',buildingId:b.id,enabled:false,priority:1});for(let i=0;i<20;i++)sim.advanceTicks(1);const mid=decodeSave(encodeSave(s,data.map,data.config));assert.equal(mid.island.civilization!.transition!.workTicks,20);for(let i=0;i<29;i++)sim.advanceTicks(1);assert.equal(c.era,'iron');sim.advanceTicks(1);assert.equal(c.era,'modern');assert.equal(c.inventory.components,0);
const crew=s.npcs.filter(n=>n.isAlive&&n.age>=18&&n.occupation!=='child'&&!n.guardDuty&&n.laborRole==='food'&&!s.buildings.some(b=>b.workers.includes(n.id))).slice(-5);assert.equal(crew.length,5);for(const n of crew)send({type:'assign_labor',npcId:n.id,role:'idle'});const [researcher,builder,worker,miner,smith]=crew;
const tech=TECH_TREE.find(t=>t.id==='industrial_assembly')!;until(()=>!researcher.cargo&&!researcher.freight&&!researcher.haulTask&&canAfford(s,{wood:tech.costWood,stone:tech.costStone,food:tech.costFood,goods:tech.costGoods}));const parts=c.inventory.machineParts;send({type:'start_research',techId:tech.id});assert.equal(c.inventory.machineParts,parts-4);send({type:'assign_researcher',npcId:researcher.id});until(()=>c.unlocks.includes(tech.id));assert.equal(buildingLock(s,'component_factory'),null);
const site=data.map.landTiles.find(t=>t.x>=4&&t.x<=22&&t.y>=10&&t.y<=20&&['grass','sand'].includes(data.map.tiles[t.y][t.x])&&!s.buildings.some(b=>b.tileX===t.x&&b.tileY===t.y)&&!s.npcs.some(n=>n.position?.tileX===t.x&&n.position?.tileY===t.y)&&!s.animals.some(a=>a.tileX===t.x&&a.tileY===t.y)&&findPath(data.map,builder.position!.tileX,builder.position!.tileY,t.x,t.y)!==null)!;assert(site);until(()=>canAfford(s,BUILD_COSTS.component_factory));send({type:'build',buildingType:'component_factory',tileX:site.x,tileY:site.y});const factory=s.buildings.at(-1)!;send({type:'assign_worker',buildingId:factory.id,npcId:builder.id});until(()=>factory.complete);send({type:'remove_worker',buildingId:factory.id,npcId:builder.id});send({type:'set_power',buildingId:factory.id,enabled:false,priority:2});
// The fee and factory consumed the spare warehouse steel; earn the next batch by real ore trade.
const post=s.buildings.find(b=>b.type==='tradepost')!,smelter=s.buildings.find(b=>b.type==='iron_smelter')!,furnace=s.buildings.find(b=>b.type==='steelworks')!;
send({type:'assign_worker',buildingId:smelter.id,npcId:miner.id});send({type:'assign_worker',buildingId:furnace.id,npcId:smith.id});send({type:'assign_worker',buildingId:post.id,npcId:builder.id});until(()=>!builder.cargo&&!builder.freight&&!builder.haulTask&&!builder.actionTarget);send({type:'start_trade',buildingId:post.id,offerId:'cloth_for_ore'});until(()=>!post.shipment);send({type:'remove_worker',buildingId:post.id,npcId:builder.id});until(()=>c.inventory.steel+(factory.buffer?.input.steel??0)>=4);send({type:'remove_worker',buildingId:furnace.id,npcId:smith.id});send({type:'remove_worker',buildingId:smelter.id,npcId:miner.id});// Replenish the operating fuel with copper extracted and smelted from the surviving real vein.
const copperMine=s.buildings.find(b=>b.type==='copper_mine')!,copperFurnace=s.buildings.find(b=>b.type==='smelter')!;
send({type:'assign_worker',buildingId:copperMine.id,npcId:miner.id});send({type:'assign_worker',buildingId:copperFurnace.id,npcId:smith.id});until(()=>c.inventory.copper>=24);send({type:'remove_worker',buildingId:copperMine.id,npcId:miner.id});send({type:'remove_worker',buildingId:copperFurnace.id,npcId:smith.id});send({type:'assign_labor',npcId:miner.id,role:'food'});send({type:'assign_labor',npcId:smith.id,role:'food'});send({type:'assign_worker',buildingId:post.id,npcId:builder.id});until(()=>!builder.cargo&&!builder.freight&&!builder.haulTask&&!builder.actionTarget);send({type:'start_trade',buildingId:post.id,offerId:'copper_for_coal'});until(()=>!post.shipment);send({type:'remove_worker',buildingId:post.id,npcId:builder.id});

send({type:'assign_worker',buildingId:factory.id,npcId:worker.id});const gen=s.buildings.find(b=>b.type==='steam_generator')!;send({type:'set_power',buildingId:factory.id,enabled:true,priority:2});until(()=>(factory.buffer?.input.steel??0)>=4&&(factory.buffer?.input.copper??0)>=4);send({type:'set_power',buildingId:gen.id,enabled:true,priority:1});writeFileSync('artifacts/modern-factory-prepower-save.json',encodeSave(s,data.map,data.config));until(()=>c.inventory.components>=6);writeFileSync('artifacts/modern-factory-played-save.json',encodeSave(s,data.map,data.config));const cost=upgradeCost(factory,s);until(()=>canAfford(s,cost));const components=c.inventory.components;send({type:'upgrade_building',buildingId:factory.id});assert.equal(c.inventory.components,components-6);send({type:'assign_worker',buildingId:factory.id,npcId:builder.id});until(()=>factory.level===2&&!factory.upgrade);assert.equal(maxBuildingWorkers(factory),3);send({type:'assign_worker',buildingId:factory.id,npcId:researcher.id});assert.equal(factory.workers.length,3);const final=encodeSave(s,data.map,data.config);assert.deepEqual(decodeSave(final).island.civilization,JSON.parse(JSON.stringify(c))); writeFileSync('artifacts/modern-factory-upgraded-save.json',final);assert.equal(c.anomalyBranch,undefined);console.log(`PASS public Modern chain: real fee/duplicate/50 steps, paid assembly research, real built factory and metal delivery, ${c.produced.components} components produced/paid6 upgrade/three workers, 50 alive, Food ${s.sharedFood.toFixed(1)}, ${s.tick-start} steps; Anomaly locked.`);
