import assert from 'node:assert/strict';
import {createIsland} from '../src/core/factory';
import {createCivilization} from '../src/core/civilization';
import {tickDailyLife} from '../src/core/dailyLife';
import {initializeLogistics,haulJobs,tickLogistics} from '../src/core/logistics';
import {decodeSave,encodeSave} from '../src/core/SaveSystem';
import type {WorldMap} from '../src/renderer/WorldMap';
const map:WorldMap={width:14,height:12,tiles:Array.from({length:12},()=>Array(14).fill('grass')),landTiles:[]};for(let y=0;y<12;y++)for(let x=0;x<14;x++)map.landTiles.push({x,y});
const cfg={mode:'local' as const,seed:1,size:'small' as const,width:14,height:12,population:1};
function world(){const s=createIsland('Bữa ăn khẩn cấp',1);s.civilization=createCivilization();s.sharedFood=0;s.dailyLife={settlementVersion:1,campfire:{tileX:10,tileY:10,fuel:12,lit:true,graceUntil:30}};const n=s.npcs[0];n.age=25;n.occupation='gatherer';n.position={tileX:2,tileY:2};n.privateFood=0;n.needs.hunger=90;n.needs.rest=0;n.laborMode='manual';n.laborRole='haul';n.freight={good:'wood',amount:10,target:'@warehouse'};n.buildingWork={buildingId:'wood',ticks:3};s.buildings=[{id:'food',type:'farm',tileX:8,tileY:2,complete:true,progress:100,workers:[],productionBatches:7,buffer:{input:{},output:{food:30}}},{id:'wood',type:'lumbercamp',tileX:2,tileY:2,complete:true,progress:100,workers:[]}];initializeLogistics(s);return s;}
const s=world(),n=s.npcs[0];tickDailyLife(s,map);assert.deepEqual(n.position,{tileX:8,tileY:2});assert.equal(n.needs.hunger,90,'Walking cannot eat remotely');assert.equal(s.buildings[0].buffer!.output.food,30);assert(n.survivalBlocked);const mid=decodeSave(encodeSave(s,map,cfg));assert.deepEqual(mid.island.npcs[0].freight,n.freight);s.tick++;tickDailyLife(s,map);assert.equal(s.buildings[0].buffer!.output.food,10);assert.equal(s.sharedFood,0);assert.equal(n.needs.hunger,55);assert.equal(n.freight!.amount,10);assert.equal(n.buildingWork!.ticks,3);assert.equal(n.laborMode,'manual');assert.equal(s.buildings[0].productionBatches,7);assert.equal(s.logistics!.completedTrips,undefined,'Eating is not a delivered trip');assert.match(n.laborMessage!,/tại xưởng/);
const blocked=world(),wall={...map,tiles:map.tiles.map(row=>[...row])};for(let y=0;y<12;y++)wall.tiles[y][5]='deep_water';tickDailyLife(blocked,wall);assert.deepEqual(blocked.npcs[0].position,{tileX:2,tileY:2});assert.equal(blocked.buildings[0].buffer!.output.food,30);assert.equal(blocked.npcs[0].needs.hunger,90,'No food across blocked route');
const limited=world();limited.npcs[0].position={tileX:8,tileY:2};limited.buildings[0].buffer!.output.food=5;tickDailyLife(limited,map);assert.equal(limited.buildings[0].buffer!.output.food,0);assert.equal(limited.npcs[0].needs.hunger,81.25,'Recovery proportional to exactly five food');decodeSave(encodeSave(limited,map,cfg));console.log('PASS emergency meals: physical route/two-step meal, exact onsite Food debit, no warehouse/production/trip credit, held freight and partial work, blocked routes, partial meal and valid save.');

const urgent=world();urgent.wood=100;urgent.buildings.push({id:'grain',type:'wheat_field',tileX:3,tileY:3,complete:true,progress:100,workers:[],buffer:{input:{},output:{wheat:60}}},{id:'oven',type:'bakery',tileX:4,tileY:3,complete:true,progress:100,workers:[urgent.npcs[0].id],buffer:{input:{wheat:24},output:{}}});urgent.buildings[0].buffer!.output.food=0;assert.equal(haulJobs(urgent)[0].target,'oven','Supply starving food chain before shipping surplus wheat');assert.equal(haulJobs(urgent)[0].good,'wood');console.log('PASS low Food: replenish bakery wood before clearing surplus grain.');

const spread=world();spread.npcs[0].freight=undefined;spread.npcs[0].buildingWork=undefined;spread.npcs.push({...structuredClone(spread.npcs[0]),id:'second-carrier'});spread.buildings.push({...structuredClone(spread.buildings[0]),id:'second-food',tileY:3});tickLogistics(spread,map);assert.equal(spread.npcs[0].haulTask!.source,'food');assert.equal(spread.npcs[1].haulTask!.source,'second-food','Walking carriers reserve their pickup instead of all chasing one batch');console.log('PASS concurrent pickup: crew distributes across real onsite food batches.');

for(const value of [-1,1.5,'2',Number.MAX_SAFE_INTEGER+1]){const invalid=JSON.parse(encodeSave(limited,map,cfg));invalid.island.logistics.completedTrips=value;assert.throws(()=>decodeSave(JSON.stringify(invalid)),/Hậu cần/);}limited.logistics!.completedTrips=3;assert.equal(decodeSave(encodeSave(limited,map,cfg)).island.logistics!.completedTrips,3);console.log('PASS delivery proof: exact save/load and malformed trip counters rejected.');

for(const status of ['sleeping','eating','chatting'] as const){const dawn=world(),n=dawn.npcs[0];n.status=status;n.needs.hunger=0;n.survival={reason:'rest'};tickDailyLife(dawn,map);assert.equal(n.status,'idle');assert.equal(n.survivalBlocked,false);assert.equal(n.buildingWork!.ticks,3);assert.equal(n.freight!.amount,10);}console.log('PASS dawn: stale sleep/meal/social status released, manual work and freight kept.');
