import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {decodeSave,encodeSave} from '../src/core/SaveSystem';
import {reserveEntityIds} from '../src/core/factory';
import {SimulationSession,type PlayerCommand} from '../src/core/SimulationSession';
import {anomalyRequirements} from '../src/core/AnomalyManager';
import {maxBuildingWorkers} from '../src/renderer/BuildingManager';
let d=decodeSave(readFileSync('artifacts/mystic-prepared-save.json','utf8')),s=d.island,c=s.civilization!;reserveEntityIds(s);let sim=new SimulationSession(s,d.map),seq=0;const initial=s.tick,identity=s.npcs.filter(n=>n.isAlive).map(n=>({id:n.id,name:n.name,occupation:n.occupation}));
const send=(command:PlayerCommand)=>{const r=sim.submit({playerId:'mystic',sequence:++seq,command});assert(r.accepted,JSON.stringify({command,r}));};
const until=(ok:()=>boolean,max=2000)=>{for(let i=0;i<max&&!ok();i++){sim.advanceTicks(1);assert.equal(s.npcs.filter(n=>n.isAlive).length,50);}if(!ok())writeFileSync('artifacts/mystic-waiting-save.json',encodeSave(s,d.map,d.config));assert(ok(),JSON.stringify({tick:s.tick,food:s.sharedFood,goods:c.inventory,project:c.branchDevelopment,message:c.branchMessage}));};
// Redirect idle industrial crew into real food production before undertaking the next project.
for(const b of s.buildings.filter(b=>['component_factory','prototype_workshop','spirit_extractor','resonance_tower','coal_mine'].includes(b.type))){for(const id of [...b.workers]){send({type:'remove_worker',buildingId:b.id,npcId:id});const farm=s.buildings.find(f=>f.type==='farm'&&f.workers.length<maxBuildingWorkers(f));if(farm)send({type:'assign_worker',buildingId:farm.id,npcId:id});else send({type:'assign_labor',npcId:id,role:'food'});}}
until(()=>s.sharedFood>=350);writeFileSync('artifacts/mystic-food-recovered-save.json',encodeSave(s,d.map,d.config));
let lab=s.buildings.find(b=>b.type==='measurement_lab')!,gen=s.buildings.find(b=>b.type==='steam_generator')!;const scientist=s.npcs.find(n=>n.id==='npc_15')!;send({type:'assign_worker',buildingId:lab.id,npcId:scientist.id});send({type:'set_power',buildingId:lab.id,enabled:true,priority:2});send({type:'set_power',buildingId:gen.id,enabled:true,priority:1});until(()=>anomalyRequirements(s,lab.id,'mystic').every(r=>r.met));writeFileSync('artifacts/mystic-ready-save.json',encodeSave(s,d.map,d.config));
const components=c.inventory.components,steel=c.inventory.steel;const env={playerId:'mystic',sequence:++seq,command:{type:'start_branch' as const,branch:'mystic',labId:lab.id}};assert(sim.submit(env).accepted);assert(sim.submit(env).duplicate);assert.equal(c.inventory.components,components-50);assert.equal(c.inventory.steel,steel-20);assert(!sim.submit({playerId:'mystic',sequence:++seq,command:env.command}).accepted);until(()=>c.branchDevelopment!.workTicks>=5);const held=c.branchDevelopment!.workTicks;send({type:'set_power',buildingId:lab.id,enabled:false,priority:2});sim.advanceTicks(5);assert.equal(c.branchDevelopment!.workTicks,held);assert.equal(lab.labPoweredTicks,0);const paused=encodeSave(s,d.map,d.config);writeFileSync('artifacts/mystic-paused-save.json',paused);assert.equal(decodeSave(paused).island.civilization!.branchDevelopment!.branch,'mystic');send({type:'cancel_branch'});assert.equal(c.inventory.components,components);assert.equal(c.inventory.steel,steel);assert(!sim.submit({playerId:'mystic',sequence:++seq,command:{type:'cancel_branch'}}).accepted);send({type:'set_power',buildingId:lab.id,enabled:true,priority:2});until(()=>anomalyRequirements(s,lab.id,'mystic').every(r=>r.met));send(env.command);
d=decodeSave(encodeSave(s,d.map,d.config));s=d.island;c=s.civilization!;sim=new SimulationSession(s,d.map);seq=0;until(()=>c.era==='anomaly');assert.equal(c.anomalyBranch,'mystic');assert.equal(c.inventory.components,components-50);assert.equal(c.inventory.steel,steel-20);assert.deepEqual(s.npcs.filter(n=>n.isAlive).map(n=>({id:n.id,name:n.name,occupation:n.occupation})),identity);assert(!sim.submit({playerId:'mystic',sequence:++seq,command:{type:'cancel_branch'}}).accepted);assert(!sim.submit({playerId:'mystic',sequence:++seq,command:{type:'start_branch',branch:'hightech',labId:lab.id}}).accepted);const raw=encodeSave(s,d.map,d.config);decodeSave(raw);writeFileSync('artifacts/mystic-played-save.json',raw);console.log(JSON.stringify({passed:true,alternateEarned:true,steps:s.tick-initial,alive:50,food:s.sharedFood,inventory:c.inventory,branch:c.anomalyBranch,proof:s.buildings.find(b=>b.type==='measurement_lab')!.labPoweredTicks,identityPreserved:true}));
for(const change of ['proof','care','essence','foundation','stability','eldritch']){const f=decodeSave(readFileSync('artifacts/mystic-ready-save.json','utf8'));const fl=f.island.buildings.find(b=>b.type==='measurement_lab')!;if(change==='proof')fl.labPoweredTicks=49;if(change==='care')f.island.buildings.find(b=>b.type==='resonance_tower')!.resonanceCareTicks=19;if(change==='essence')f.island.civilization!.produced.spiritEssence=8;if(change==='foundation')f.island.surveys!.sites.find(p=>p.kind==='mystic')!.foundationComplete=false;if(change==='stability')f.island.spiritVein!.stability=39;const before=f.island.civilization!.inventory.components;assert(!new SimulationSession(f.island,f.map).submit({playerId:'fixture',sequence:1,command:{type:'start_branch',branch:change==='eldritch'?'eldritch':'mystic',labId:fl.id}}).accepted);assert.equal(f.island.civilization!.inventory.components,before);}
const invalid=JSON.parse(raw);invalid.island.civilization.anomalyBranch='eldritch';assert.throws(()=>decodeSave(JSON.stringify(invalid)),/Nhánh Dị Tượng|Bằng chứng/);const broken=JSON.parse(raw);broken.island.civilization.produced.spiritEssence=8;assert.throws(()=>decodeSave(JSON.stringify(broken)),/Bằng chứng/);const noCare=JSON.parse(raw);noCare.island.buildings.find((b:any)=>b.type==='resonance_tower').resonanceCareTicks=19;assert.throws(()=>decodeSave(JSON.stringify(noCare)),/Bằng chứng/);console.log('PASS Mystic negative fixtures: proof49/care19/essence8/no foundation/stability39/eldritch rejected without charge; corrupt chosen branch/economic proof saves rejected.');
