import assert from 'node:assert/strict';
import {createIsland} from '../src/core/factory';
import {createCivilization} from '../src/core/civilization';
import {enableSettlement,tickCargo} from '../src/core/settlement';
import {initializeEquipment,startToolCraft,cancelToolCraft,tickToolCraft,tickEquipment,harvestToolMultiplier,cargoUsed} from '../src/core/equipment';
import {SimulationSession} from '../src/core/SimulationSession';
import {encodeSave,decodeSave} from '../src/core/SaveSystem';
import {assignWorker,tickBuildings} from '../src/renderer/BuildingManager';
import type {WorldMap} from '../src/renderer/WorldMap';
const map:WorldMap={width:18,height:12,tiles:Array.from({length:12},()=>Array(18).fill('grass')),landTiles:[]};
for(let y=0;y<12;y++)for(let x=0;x<18;x++)map.landTiles.push({x,y});
const island=createIsland('Trang bị',5);island.civilization=createCivilization();enableSettlement(island);initializeEquipment(island);island.dailyLife!.campfire={tileX:2,tileY:2,fuel:12,graceUntil:30,lit:true};island.wood=20;island.stone=20;island.sharedFood=100;
island.npcs.forEach(n=>{n.age=25;n.occupation='gatherer';n.position={tileX:2,tileY:2};n.laborRole='idle';n.needs={hunger:0,rest:0,safety:0,social:0};});
assert(startToolCraft(island,'axe'));assert.equal(island.wood,20);island.civilization.unlocks=['stone_tools'];
assert.equal(startToolCraft(island,'axe'),null);assert.equal(island.wood,16);assert.equal(island.stone,17);assert(startToolCraft(island,'axe'));assert.equal(island.wood,16);
const crafter=island.npcs.find(n=>n.id===island.equipment!.order!.workerId)!;crafter.position={tileX:16,tileY:2};
tickToolCraft(island,map);assert.equal(island.equipment!.order!.workTicks,0);assert.equal(crafter.position.tileX,10);
crafter.survivalBlocked=false;tickToolCraft(island,map);crafter.survivalBlocked=false;tickToolCraft(island,map);
assert.equal(island.equipment!.order!.workTicks,0,'Walking does not create tools');
for(let i=0;i<2;i++){crafter.survivalBlocked=false;tickToolCraft(island,map);}assert.equal(island.equipment!.order!.workTicks,2);
const cfg={seed:42,shape:'circle',size:'small',startPop:5,mode:'local'} as const;
const loaded=decodeSave(encodeSave(island,map,cfg));assert.equal(loaded.island.equipment!.order!.workTicks,2);
crafter.survivalBlocked=true;tickToolCraft(island,map);assert.equal(island.equipment!.order!.workTicks,2);
for(let i=0;i<3;i++){crafter.survivalBlocked=false;tickToolCraft(island,map);}assert.equal(island.equipment!.stock.axe,1);assert.equal(island.equipment!.crafted.axe,1);assert.equal(island.equipment!.order,undefined);
const npc=island.npcs[1];npc.laborRole='wood';npc.position={tileX:16,tileY:2};tickEquipment(island,map);assert.equal(npc.equippedTool,undefined);assert.equal(island.equipment!.stock.axe,1);
for(let i=0;i<4&&!npc.equippedTool;i++){npc.survivalBlocked=false;tickEquipment(island,map);}assert.equal(npc.equippedTool,'axe');assert.equal(island.equipment!.stock.axe,0);assert.equal(harvestToolMultiplier(island,npc,'chop_wood'),1.75);assert.equal(harvestToolMultiplier(island,npc,'gather_stone'),1.5);
npc.cargo={food:0,wood:12,stone:0,herbs:0};npc.toolChoice='none';npc.survivalBlocked=false;tickEquipment(island,map);assert.equal(npc.equippedTool,'axe');assert.equal(cargoUsed(npc),12);
const midway=decodeSave(encodeSave(island,map,cfg));assert.equal(midway.island.npcs[1].equippedTool,'axe');assert.equal(midway.island.npcs[1].cargo!.wood,12);
npc.survivalBlocked=false;tickCargo(island,map);npc.survivalBlocked=false;tickEquipment(island,map);assert.equal(npc.equippedTool,undefined);assert.equal(island.equipment!.stock.axe,1);
const wood=island.wood,stone=island.stone;assert.equal(startToolCraft(island,'pickaxe'),null);assert.equal(cancelToolCraft(island),null);assert.equal(island.wood,wood);assert.equal(island.stone,stone);assert(cancelToolCraft(island));
const bad=JSON.parse(encodeSave(island,map,cfg));bad.island.equipment.stock.axe++;assert.throws(()=>decodeSave(JSON.stringify(bad)),/bảo toàn/);
const session=new SimulationSession(island,map);island.resources.set('2,2',{type:'wood_tree',amount:100,maxAmount:100,regenRate:0});npc.toolChoice='axe';npc.survivalBlocked=false;tickEquipment(island,map);npc.survivalBlocked=false;
assert(session.submit({playerId:'test',sequence:1,command:{type:'manual_action',npcId:npc.id,action:'chop_wood'}}).accepted);assert.equal(npc.cargo!.wood,5.25,'3 × max(1.5,1.75), no double tools bonus');assert.equal(island.resources.get('2,2')!.amount,94.75);
console.log('PASS: paid onsite crafting/walking/rest/save, no double payment, equipment transport/exchange, cargo protection, cancellation/refund, inventory conservation and non-stacking harvest.');
assert.equal(startToolCraft(island,'fishing_rod'),null);const rodCrafter=island.npcs.find(n=>n.id===island.equipment!.order!.workerId)!;rodCrafter.position={tileX:2,tileY:2};
for(let i=0;i<5;i++){rodCrafter.survivalBlocked=false;tickToolCraft(island,map);}
const fisher=island.npcs[3];fisher.toolChoice='fishing_rod';fisher.attributes={str:5,dex:10,int:5};fisher.survivalBlocked=false;tickEquipment(island,map);assert.equal(fisher.equippedTool,'fishing_rod');
island.buildings.push({id:'dock',type:'fishing_dock',tileX:3,tileY:2,complete:true,progress:100,workers:[]});island.resources.set('3,3',{type:'fish_spot',amount:100,maxAmount:100,regenRate:0});island.sharedFood=0;
assert(assignWorker(island,'dock',fisher.id));fisher.position={tileX:3,tileY:2};fisher.survivalBlocked=false;for(let i=0;i<5;i++)tickBuildings(island,island.resources,map);
assert.equal(fisher.cargo!.food,30,'24 ×1.2 DEX ×1.2 rod is limited by bag capacity');assert.equal(island.resources.get('3,3')!.amount,70);assert.equal(island.sharedFood,0);
decodeSave(encodeSave(island,map,cfg));console.log('PASS: rod boosts actual dock output, source debited exactly, 30-unit bag cap and equipment ledger survives save.');
