import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {decodeSave,encodeSave} from '../src/core/SaveSystem';
import {reserveEntityIds} from '../src/core/factory';
import {SimulationSession,type PlayerCommand} from '../src/core/SimulationSession';
import {tickClinic,prepareClinic,requestClinic} from '../src/core/ClinicManager';
import {findPath} from '../src/core/pathfinding';
const d=decodeSave(readFileSync('artifacts/care-industry-stable-save.json','utf8')),s=d.island,c=s.civilization!;reserveEntityIds(s);const sim=new SimulationSession(s,d.map);let seq=0;const initial=s.tick;const send=(command:PlayerCommand)=>{const r=sim.submit({playerId:'clinic-earned',sequence:++seq,command});assert(r.accepted,JSON.stringify({command,r}));};
const until=(ok:()=>boolean,max=2000)=>{for(let i=0;i<max&&!ok();i++){sim.advanceTicks(1);assert.equal(s.npcs.filter(n=>n.isAlive).length,50);}if(!ok())writeFileSync('artifacts/clinic-waiting-save.json',encodeSave(s,d.map,d.config));assert(ok(),JSON.stringify({tick:s.tick,food:s.sharedFood,goods:c.inventory,power:s.power,buildings:s.buildings.slice(-2)}));};
const people=s.npcs.filter(n=>n.isAlive&&n.position&&n.age>=18&&!n.guardDuty&&!n.researching&&!s.buildings.some(b=>b.workers.includes(n.id)));assert(people.length>=3);const [scientist,compounder,doctor]=people;const gen=s.buildings.find(b=>b.type==='steam_generator')!;send({type:'assign_labor',npcId:compounder.id,role:'stone'});until(()=>s.stone>=45);send({type:'assign_labor',npcId:compounder.id,role:'idle'});until(()=>!compounder.cargo&&!compounder.freight&&!compounder.haulTask&&!compounder.actionTarget);const post=s.buildings.find(b=>b.type==='tradepost')!;send({type:'assign_worker',buildingId:post.id,npcId:compounder.id});for(let i=0;i<6;i++){until(()=>!compounder.cargo&&!compounder.freight&&!compounder.actionTarget&&!compounder.haulTask);const cloth=c.inventory.cloth;send({type:'start_trade',buildingId:post.id,offerId:'cloth_for_coal'});assert.equal(c.inventory.cloth,cloth-8);until(()=>!post.shipment);}send({type:'remove_worker',buildingId:post.id,npcId:compounder.id});const fee=c.inventory.components;send({type:'start_research',techId:'modern_medicine'});assert.equal(c.inventory.components,fee-4);send({type:'assign_researcher',npcId:scientist.id});until(()=>c.unlocks.includes('modern_medicine'));
const camp=s.dailyLife!.campfire!;const tile=()=>d.map.landTiles.find(t=>Math.max(Math.abs(t.x-camp.tileX),Math.abs(t.y-camp.tileY))<=4&&['grass','sand'].includes(d.map.tiles[t.y][t.x])&&!s.buildings.some(b=>b.tileX===t.x&&b.tileY===t.y)&&!s.npcs.some(n=>n.position?.tileX===t.x&&n.position?.tileY===t.y)&&findPath(d.map,compounder.position!.tileX,compounder.position!.tileY,t.x,t.y)!==null)!;
let p=tile();send({type:'build',buildingType:'apothecary',tileX:p.x,tileY:p.y});const pharmacy=s.buildings.at(-1)!;send({type:'assign_worker',buildingId:pharmacy.id,npcId:compounder.id});until(()=>pharmacy.complete);p=tile();send({type:'build',buildingType:'clinic',tileX:p.x,tileY:p.y});const clinic=s.buildings.at(-1)!;send({type:'assign_worker',buildingId:clinic.id,npcId:doctor.id});until(()=>clinic.complete);send({type:'set_power',buildingId:pharmacy.id,enabled:true,priority:2});send({type:'set_power',buildingId:clinic.id,enabled:true,priority:2});send({type:'set_power',buildingId:gen.id,enabled:false,priority:1});until(()=>(pharmacy.buffer?.input.herbs??0)>=2&&(pharmacy.buffer?.input.cloth??0)>=1);send({type:'set_power',buildingId:gen.id,enabled:true,priority:1});writeFileSync('artifacts/clinic-production-ready-save.json',encodeSave(s,d.map,d.config));until(()=>c.produced.medicine>=6);send({type:'set_power',buildingId:pharmacy.id,enabled:false,priority:2});until(()=>c.inventory.medicine>=3&&(clinic.buffer?.input.medicine??0)>=1);assert.equal(c.produced.medicine,6);assert.equal(c.anomalyBranch,'mystic');assert.equal(s.npcs.filter(n=>n.isAlive).length,50);const raw=encodeSave(s,d.map,d.config);decodeSave(raw);writeFileSync('artifacts/clinic-played-save.json',raw);console.log(JSON.stringify({passed:true,earned:true,steps:s.tick-initial,alive:50,food:s.sharedFood,newMedicine:6,warehouseMedicine:c.inventory.medicine,onsiteMedicine:clinic.buffer?.input.medicine,components:c.inventory.components,cloth:c.inventory.cloth,coal:c.inventory.coal}));
// Controlled clinical fixture uses medicine from the earned route; only patient age/health/needs and staff position are set.
const f=decodeSave(raw).island,fc=f.buildings.find(b=>b.type==='clinic')!,doc=f.npcs.find(n=>fc.workers.includes(n.id))!,patient=f.npcs.find(n=>n.id===scientist.id)!;doc.position={tileX:fc.tileX,tileY:fc.tileY};doc.status='working';doc.laborMessage='Chăm sóc tại phòng khám';doc.survivalBlocked=false;doc.needs.hunger=0;doc.needs.rest=0;patient.age=12;patient.occupation='child';patient.health=60;patient.position={tileX:fc.tileX+1,tileY:fc.tileY};patient.needs.hunger=0;patient.needs.rest=0;patient.survival=undefined;patient.researching=false;patient.survivalBlocked=false;assert.equal(requestClinic(f,patient.id,fc.id),null);writeFileSync('artifacts/clinic-child-fixture-save.json',encodeSave(f,d.map,d.config));const meds=fc.buffer!.input.medicine!;prepareClinic(f,d.map);const doctorSite=doc.position;doc.position={tileX:fc.tileX+5,tileY:fc.tileY};tickClinic(f);assert.equal(patient.health,60);assert.equal(fc.buffer!.input.medicine,meds);doc.position=doctorSite;tickClinic(f);assert.equal(patient.health,68);assert.equal(fc.buffer!.input.medicine,meds-1);assert.equal(patient.clinicalCare!.workTicks,1);const partial=encodeSave(f,d.map,d.config);decodeSave(partial);writeFileSync('artifacts/clinic-partial-fixture-save.json',partial);fc.powerEnabled=false;const held=patient.health;tickClinic(f);assert.equal(patient.health,held);assert.equal(fc.buffer!.input.medicine,meds-1);fc.powerEnabled=true;for(let i=0;i<4;i++){patient.survivalBlocked=false;prepareClinic(f,d.map);tickClinic(f);}assert.equal(patient.health,100);assert(!patient.clinicalCare);assert.equal(fc.completedCare,1);assert.equal(fc.buffer!.input.medicine,meds-1);const bad=JSON.parse(partial);bad.island.npcs.find((n:any)=>n.id===patient.id).clinicalCare.workTicks=5;assert.throws(()=>decodeSave(JSON.stringify(bad)),/Lịch khám/);const missingDose=JSON.parse(partial);delete missingDose.island.buildings.find((b:any)=>b.id===fc.id).clinicalDoses;assert.throws(()=>decodeSave(JSON.stringify(missingDose)),/liều thuốc/);console.log('PASS clinical child fixture: onsite doctor/patient/exact1earned medicine/5steps40HP, outage holds partial dose, load retains progress, invalid partial timer rejected.');
