import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE??'playwright');const root=path.resolve('web');
const server=createServer(async(req,res)=>{const file=path.resolve(root,'.'+new URL(req.url??'/','http://localhost').pathname.replace(/\/$/,'/index.html'));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{res.setHeader('content-type',({'.html':'text/html','.css':'text/css','.js':'text/javascript','.svg':'image/svg+xml','.png':'image/png'} as Record<string,string>)[path.extname(file)]??'application/octet-stream');res.end(await readFile(file));}catch{res.writeHead(404).end();}});
async function main(){
 await mkdir('artifacts',{recursive:true});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors:string[]=[],failed:string[]=[];page.on('pageerror',(e:Error)=>errors.push(e.message));page.on('response',(r:any)=>{if(r.status()>=400)failed.push(r.url());});const url=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
 const close=async()=>{if(await page.locator('#building-inspector').isVisible())await page.locator('#bi-close').click();if(await page.locator('#panel-overlay').evaluate((e:HTMLElement)=>e.classList.contains('open')))await page.locator('#panel-close').click();};
 const pause=async(on:boolean)=>{await close();if((await page.locator('#btn-pause').evaluate((e:HTMLElement)=>e.classList.contains('active')))!==on)await page.locator('#btn-pause').click();};
 const save=async()=>{await close();await page.locator('#btn-save-local').click();return page.evaluate(()=>JSON.parse(localStorage.getItem('dao_thien_nguyen_v2')!));};
 const load=async(raw:string)=>{await page.goto(url);await page.evaluate((raw:string)=>localStorage.setItem('dao_thien_nguyen_v2',raw),raw);await page.reload();await page.locator('#btn-resume-game').click();await page.locator('.era-roadmap').waitFor();await pause(true);};
 const open=async()=>{await close();await page.locator('#sb-quests').click();await page.locator('.era-roadmap').waitFor();await page.waitForTimeout(300);};
 const inspect=async(id:string)=>{await close();await page.locator('#btn-build').click();await page.locator(`[data-inspect-building="${id}"]`).click();await page.locator('#building-inspector').waitFor({state:'visible'});await page.waitForTimeout(300);};
 try{
 const raw=await readFile('artifacts/spirit-channel-played-save.json','utf8'),ready=JSON.parse(raw),extractor=ready.island.buildings.find((b:any)=>b.type==='spirit_extractor');await load(raw);await inspect(extractor.id);assert.match(await page.locator('.bi-level').innerText(),/Cấp 1 \/ 1.*mẫu Linh Mạch/);await page.waitForFunction(()=>[...document.querySelectorAll<HTMLImageElement>('.bi-texture')].every(i=>i.complete&&i.naturalWidth>0));await page.screenshot({path:'artifacts/spirit-extractor-desktop.png'});await page.locator('#bi-spirit-toggle').click();const enabled=await save();assert.equal(enabled.island.buildings.find((b:any)=>b.id===extractor.id).spiritEnabled,true);await load(JSON.stringify(enabled));await pause(false);await page.locator('.speed-btn[data-speed="2"]').click();await page.waitForTimeout(16000);await pause(true);const harvested=await save();assert(harvested.island.civilization.produced.spiritStone>ready.island.civilization.produced.spiritStone);assert.equal(harvested.island.npcs.filter((n:any)=>n.isAlive).length,50);
 const pausedRaw=await readFile('artifacts/spirit-refinery-paused-save.json','utf8'),paused=JSON.parse(pausedRaw),refinery=paused.island.buildings.find((b:any)=>b.type==='spirit_refinery');await load(pausedRaw);await open();await page.locator(`[data-power-toggle="${refinery.id}"]`).click();await inspect(refinery.id);assert.match(await page.locator('.bi-state').innerText(),/Đủ 2 công suất/);assert.match(await page.locator('#building-inspector').innerText(),/2linh thạch.*1thảo dược/);await page.screenshot({path:'artifacts/spirit-refinery-desktop.png'});await pause(false);await page.locator('.speed-btn[data-speed="2"]').click();await page.waitForTimeout(16000);await pause(true);const made=await save();assert(made.island.civilization.produced.spiritEssence>paused.island.civilization.produced.spiritEssence);
 const towerRaw=await readFile('artifacts/spirit-tower-ready-save.json','utf8'),towerState=JSON.parse(towerRaw),tower=towerState.island.buildings.find((b:any)=>b.type==='resonance_tower');await load(towerRaw);await inspect(tower.id);assert.match(await page.locator('.bi-state').innerText(),/Đang chăm sóc/);await page.screenshot({path:'artifacts/spirit-tower-desktop.png'});await open();await page.locator(`[data-power-toggle="${tower.id}"]`).click();const held=await save();assert.equal(held.island.buildings.find((b:any)=>b.id===tower.id).resonanceFuelTicks,tower.resonanceFuelTicks);await load(JSON.stringify(held));await inspect(tower.id);assert.match(await page.locator('.bi-state').innerText(),/Đã tắt máy/);await open();await page.locator(`[data-power-toggle="${tower.id}"]`).click();await pause(false);await page.locator('.speed-btn[data-speed="2"]').click();await page.waitForTimeout(16000);await pause(true);const cared=await save();assert(cared.island.buildings.find((b:any)=>b.id===tower.id).resonanceCareTicks>tower.resonanceCareTicks);assert.equal(cared.island.npcs.filter((n:any)=>n.isAlive).length,50);
 await page.setViewportSize({width:390,height:844});await load(await readFile('artifacts/spirit-played-save.json','utf8'));await open();await page.locator('.spirit-panel h3').scrollIntoViewIfNeeded();assert.match(await page.locator('.spirit-panel').innerText(),/chưa chốt nhánh Linh Mạch/);assert.match(await page.locator('.spirit-panel').innerText(),/Trữ lượng 24\/24/);await page.screenshot({path:'artifacts/spirit-mobile.png'});await inspect(tower.id);await page.locator('.resonance-care').scrollIntoViewIfNeeded();await page.screenshot({path:'artifacts/spirit-tower-mobile.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);console.log('PASS browser alternate earned spirit: own extraction texture/public pause-resume-save/live harvesting/50alive, refinery power/UI/live essence, tower fuel hold/reload/power restore/live care/50alive, mobile/source counters/no errors/overflow, Mystic remains locked in this checkpoint because fee/proof are missing.');
 }catch(e){console.error(e);try{await page.screenshot({path:'artifacts/spirit-ui-failure.png'});}catch{}throw e;}finally{await browser.close();server.close();}
}
main().catch(e=>{console.error(e);server.close();process.exitCode=1;});
