import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE??'playwright');const root=path.resolve('web');
const server=createServer(async(req,res)=>{const file=path.resolve(root,'.'+new URL(req.url??'/','http://localhost').pathname.replace(/\/$/,'/index.html'));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{res.setHeader('content-type',({'.html':'text/html','.css':'text/css','.js':'text/javascript','.svg':'image/svg+xml','.png':'image/png'} as Record<string,string>)[path.extname(file)]??'application/octet-stream');res.end(await readFile(file));}catch{res.writeHead(404).end();}});
async function main(){
 await mkdir('artifacts',{recursive:true});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors:string[]=[],failed:string[]=[];page.on('pageerror',(e:Error)=>errors.push(e.message));page.on('response',(r:any)=>{if(r.status()>=400)failed.push(r.url());});
 const url=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
 const close=async()=>{if(await page.locator('#panel-overlay').evaluate((e:HTMLElement)=>e.classList.contains('open')))await page.locator('#panel-close').click();await page.waitForTimeout(350);};
 const pause=async(on:boolean)=>{await close();if((await page.locator('#btn-pause').evaluate((e:HTMLElement)=>e.classList.contains('active')))!==on)await page.locator('#btn-pause').click();};
 const save=async()=>{await close();await page.locator('#btn-save-local').click();return page.evaluate(()=>JSON.parse(localStorage.getItem('dao_thien_nguyen_v2')!));};
 const load=async(raw:string)=>{await page.goto(url);await page.evaluate((raw:string)=>localStorage.setItem('dao_thien_nguyen_v2',raw),raw);await page.reload();await page.locator('#btn-resume-game').click();await page.locator('.era-roadmap').waitFor();await pause(true);};
 try{
  const prior=JSON.parse(await readFile('artifacts/management-targets-save.json','utf8'));await load(JSON.stringify(prior));const migrated=await save();assert(migrated.island.raids);assert.equal(migrated.island.faith.amount,prior.island.faith.amount);const r=migrated.island.raids,fire=migrated.island.dailyLife.campfire;r.phase='warning';r.untilMs=r.clockMs+20000;r.target={x:fire.tileX,y:fire.tileY};r.budget=Math.min(40,migrated.island.sharedFood*.2);r.stolen=0;
  // Stage the incident only; all resources and earned Faith come from the actual village save.
  await load(JSON.stringify(migrated));await page.locator('[data-panel="military"]').click();await page.waitForTimeout(350);assert.match(await page.locator('#raid-status').innerText(),/Báo động/);await page.screenshot({path:'artifacts/raids-warning-desktop.png'});await page.locator('[data-guard]').first().check();const assigned=await save();assert(assigned.island.npcs.some((n:any)=>n.guardDuty));await load(JSON.stringify(assigned));await page.locator('[data-panel="military"]').click();assert(await page.locator('[data-guard]').first().isChecked());await close();await page.locator('.speed-btn[data-speed="2"]').click();await pause(false);await page.locator('[data-panel="military"]').click();await page.waitForFunction(()=>document.querySelector('#raid-status')?.textContent?.includes('Đang đột kích'),undefined,{timeout:18000});await pause(true);const active=await save();assert.equal(active.island.raids.phase,'active');assert.equal(active.island.raids.enemies.length,2);await load(JSON.stringify(active));assert.deepEqual((await save()).island.raids,active.island.raids);await page.locator('[data-panel="military"]').click();await page.locator('#cast-shield').click();const cast=await save();assert.equal(cast.island.faith.amount,active.island.faith.amount-70);assert.equal(cast.island.raids.shieldUntilMs-cast.island.raids.clockMs,30000);assert.equal(cast.island.raids.shieldCooldownUntilMs-cast.island.raids.clockMs,90000);await writeFile('artifacts/raids-shield-save.json',JSON.stringify(cast));await page.waitForTimeout(1000);assert.deepEqual((await save()).island.raids,cast.island.raids);
  await load(JSON.stringify(cast));await page.locator('[data-panel="military"]').click();assert(await page.locator('#cast-shield').isDisabled());await page.screenshot({path:'artifacts/raids-shield-desktop.png'});await page.setViewportSize({width:390,height:844});await page.waitForTimeout(350);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'artifacts/raids-shield-mobile.png'});await close();await page.locator('#faith-hud').click();await page.locator('#cast-shield').scrollIntoViewIfNeeded();assert(await page.locator('#cast-shield').isDisabled());await page.screenshot({path:'artifacts/raids-faith-mobile.png'});await close();await page.locator('.speed-btn[data-speed="2"]').click();await pause(false);await page.locator('[data-panel="military"]').click();await page.waitForFunction(()=>document.querySelector('#raid-status')?.textContent?.includes('không mất thức ăn'),undefined,{timeout:25000});await pause(true);const won=await save();assert.equal(won.island.raids.phase,'peace');assert.equal(won.island.raids.stolen,0);assert.equal(won.island.npcs.filter((n:any)=>n.isAlive).length,12);await writeFile('artifacts/raids-played-save.json',JSON.stringify(won));
  await pause(false);await page.locator('[data-panel="military"]').click();await page.locator('#cast-shield:enabled').waitFor({timeout:50000});await pause(true);const ready=await save();assert(ready.island.raids.clockMs>=cast.island.raids.shieldCooldownUntilMs);assert(ready.island.sharedFood>0);assert.equal(ready.island.npcs.filter((n:any)=>n.isAlive).length,12);
  // Contact fixture: keep actual stocks/health/needs; stage one attacker beside an eligible adult in morning.
  const contact=JSON.parse(JSON.stringify(ready)),defender=contact.island.npcs.find((n:any)=>n.isAlive&&n.position&&n.age>=18&&n.needs.hunger<75&&n.needs.rest<75&&(n.health??100)>40);assert(defender);defender.guardDuty=true;contact.island.tick=Math.floor(contact.island.tick/10)*10;const cr=contact.island.raids;cr.phase='active';cr.untilMs=cr.clockMs+30000;cr.target={x:fire.tileX,y:fire.tileY};cr.budget=40;cr.stolen=0;cr.enemies=[{id:'contact-test',x:defender.position.tileX,y:defender.position.tileY,health:36}];
  await load(JSON.stringify(contact));await page.setViewportSize({width:1440,height:1000});await page.locator('.speed-btn[data-speed="1"]').click();await pause(false);await page.locator('[data-panel="military"]').click();await page.waitForFunction(()=>[...document.querySelectorAll('[data-guard-state]')].some(e=>e.textContent?.includes('Đang chống đỡ')),undefined,{timeout:12000});await page.waitForTimeout(350);await page.screenshot({path:'artifacts/raids-combat-desktop.png'});await pause(true);const fought=await save();assert((fought.island.npcs.find((n:any)=>n.id===defender.id).health??100)<(defender.health??100),'Actual guard loses health in contact');assert(fought.island.npcs.every((n:any)=>n.isAlive||!contact.island.npcs.find((old:any)=>old.id===n.id)?.isAlive));await writeFile('artifacts/raids-combat-save.json',JSON.stringify(fought));
  assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);console.log(`PASS browser: actual village / staged warning, guards saved, natural spawn, paid Shield from earned Faith, pause and exact active reload, shielded raid ends without theft, ×2 expiry/90s cooldown, desktop/mobile controls, 12 alive Food ${ready.island.sharedFood.toFixed(1)}, no page errors.`);
 }catch(e){await page.screenshot({path:'artifacts/raids-ui-failure.png'});throw e;}finally{await browser.close();await new Promise<void>(r=>server.close(()=>r()));}
}
void main().catch(e=>{console.error(e);server.close();process.exitCode=1;});
