import {harvestRelic} from '../src/core/EldritchManager';
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {decodeSave,encodeSave} from '../src/core/SaveSystem';
import {reserveEntityIds} from '../src/core/factory';
import {SimulationSession,type PlayerCommand} from '../src/core/SimulationSession';
import {anomalyRequirements} from '../src/core/AnomalyManager';
import {maxBuildingWorkers} from '../src/renderer/BuildingManager';
let d=decodeSave(readFileSync('artifacts/eldritch-prepared-save.json','utf8')),s=d.island,c=s.civilization!;reserveEntityIds(s);let sim=new SimulationSession(s,d.map),seq=0;const initial=s.tick,identity=s.npcs.filter(n=>n.isAlive).map(n=>({id:n.id,name:n.name,occupation:n.occupation}));
const send=(command:PlayerCommand)=>{const r=sim.submit({playerId:'eldritch',sequence:++seq,command});assert(r.accepted,JSON.stringify({command,r}));};
const until=(ok:()=>boolean,max=2000)=>{for(let i=0;i<max&&!ok();i++){sim.advanceTicks(1);assert.equal(s.npcs.filter(n=>n.isAlive).length,50);}if(!ok())writeFileSync('artifacts/eldritch-waiting-save.json',encodeSave(s,d.map,d.config));assert(ok(),JSON.stringify({tick:s.tick,food:s.sharedFood,goods:c.inventory,project:c.branchDevelopment,message:c.branchMessage}));};
// Redirect idle industrial crew into real food production before undertaking the next project.
for(const b of s.buildings.filter(b=>['component_factory','prototype_workshop','relic_extractor','quarantine','coal_mine'].includes(b.type))){for(const id of [...b.workers]){send({type:'remove_worker',buildingId:b.id,npcId:id});const farm=s.buildings.find(f=>f.type==='farm'&&f.workers.length<maxBuildingWorkers(f));if(farm)send({type:'assign_worker',buildingId:farm.id,npcId:id});else send({type:'assign_labor',npcId:id,role:'food'});}}
until(()=>s.sharedFood>=350);writeFileSync('artifacts/eldritch-food-recovered-save.json',encodeSave(s,d.map,d.config));
let lab=s.buildings.find(b=>b.type==='measurement_lab')!,gen=s.buildings.find(b=>b.type==='steam_generator')!;const scientist=s.npcs.find(n=>n.id==='npc_15')!;send({type:'assign_worker',buildingId:lab.id,npcId:scientist.id});send({type:'set_power',buildingId:lab.id,enabled:true,priority:2});send({type:'set_power',buildingId:gen.id,enabled:true,priority:1});until(()=>anomalyRequirements(s,lab.id,'eldritch').every(r=>r.met));writeFileSync('artifacts/eldritch-ready-save.json',encodeSave(s,d.map,d.config));
const components=c.inventory.components,steel=c.inventory.steel;const env={playerId:'eldritch',sequence:++seq,command:{type:'start_branch' as const,branch:'eldritch',labId:lab.id}};assert(sim.submit(env).accepted);assert(sim.submit(env).duplicate);assert.equal(c.inventory.components,components-50);assert.equal(c.inventory.steel,steel-20);assert(!sim.submit({playerId:'eldritch',sequence:++seq,command:env.command}).accepted);until(()=>c.branchDevelopment!.workTicks>=5);const held=c.branchDevelopment!.workTicks;send({type:'set_power',buildingId:lab.id,enabled:false,priority:2});sim.advanceTicks(5);assert.equal(c.branchDevelopment!.workTicks,held);assert.equal(lab.labPoweredTicks,0);const paused=encodeSave(s,d.map,d.config);writeFileSync('artifacts/eldritch-paused-save.json',paused);assert.equal(decodeSave(paused).island.civilization!.branchDevelopment!.branch,'eldritch');send({type:'cancel_branch'});assert.equal(c.inventory.components,components);assert.equal(c.inventory.steel,steel);assert(!sim.submit({playerId:'eldritch',sequence:++seq,command:{type:'cancel_branch'}}).accepted);send({type:'set_power',buildingId:lab.id,enabled:true,priority:2});until(()=>anomalyRequirements(s,lab.id,'eldritch').every(r=>r.met));send(env.command);
d=decodeSave(encodeSave(s,d.map,d.config));s=d.island;c=s.civilization!;sim=new SimulationSession(s,d.map);seq=0;until(()=>c.era==='anomaly');assert.equal(c.anomalyBranch,'eldritch');assert.equal(c.inventory.components,components-50);assert.equal(c.inventory.steel,steel-20);assert.deepEqual(s.npcs.filter(n=>n.isAlive).map(n=>({id:n.id,name:n.name,occupation:n.occupation})),identity);assert(!sim.submit({playerId:'eldritch',sequence:++seq,command:{type:'cancel_branch'}}).accepted);assert(!sim.submit({playerId:'eldritch',sequence:++seq,command:{type:'start_branch',branch:'hightech',labId:lab.id}}).accepted);const raw=encodeSave(s,d.map,d.config);decodeSave(raw);writeFileSync('artifacts/eldritch-entered-save.json',raw);console.log(JSON.stringify({passed:true,alternateEarned:true,steps:s.tick-initial,alive:50,food:s.sharedFood,inventory:c.inventory,branch:c.anomalyBranch,proof:s.buildings.find(b=>b.type==='measurement_lab')!.labPoweredTicks,identityPreserved:true}));
for(const change of ['proof','care','bio','foundation','contamination','exposure','hightech']){const f=decodeSave(readFileSync('artifacts/eldritch-ready-save.json','utf8'));const fl=f.island.buildings.find(b=>b.type==='measurement_lab')!;if(change==='proof')fl.labPoweredTicks=49;if(change==='care')f.island.buildings.find(b=>b.type==='quarantine')!.quarantineCareTicks=19;if(change==='bio')f.island.civilization!.produced.biomatter=8;if(change==='foundation')f.island.surveys!.sites.find(p=>p.kind==='eldritch')!.foundationComplete=false;if(change==='contamination')f.island.eldritchSource!.contamination=40;if(change==='exposure')f.island.npcs[0].exposure=30;const before=f.island.civilization!.inventory.components;assert(!new SimulationSession(f.island,f.map).submit({playerId:'fixture',sequence:1,command:{type:'start_branch',branch:change==='hightech'?'hightech':'eldritch',labId:fl.id}}).accepted);assert.equal(f.island.civilization!.inventory.components,before);}
const invalid=JSON.parse(raw);invalid.island.civilization.anomalyBranch='unknown';assert.throws(()=>decodeSave(JSON.stringify(invalid)),/Nhánh Dị Tượng/);const broken=JSON.parse(raw);broken.island.civilization.produced.biomatter=8;assert.throws(()=>decodeSave(JSON.stringify(broken)),/Bằng chứng/);const noCare=JSON.parse(raw);noCare.island.buildings.find((b:any)=>b.type==='quarantine').quarantineCareTicks=19;assert.throws(()=>decodeSave(JSON.stringify(noCare)),/Bằng chứng/);console.log('PASS Eldritch negative fixtures: proof49/care19/bio8/no foundation/contamination40/exposure30/Hightech rejected without charge; corrupt chosen branch/economic proof saves rejected.');

// Paid branch unlocks a material-consuming safety program, without changing NPCs.
const extractor=s.buildings.find(b=>b.type==='relic_extractor')!;const original=decodeSave(readFileSync('artifacts/eldritch-played-save.json','utf8')).island.buildings.find(b=>b.type==='relic_extractor')!.workers[0];lab=s.buildings.find(b=>b.type==='measurement_lab')!;gen=s.buildings.find(b=>b.type==='steam_generator')!;send({type:'set_power',buildingId:lab.id,enabled:false,priority:2});send({type:'set_power',buildingId:gen.id,enabled:false,priority:1});send({type:'remove_worker',buildingId:lab.id,npcId:scientist.id});send({type:'assign_labor',npcId:scientist.id,role:'food'});send({type:'assign_worker',buildingId:extractor.id,npcId:original});send({type:'set_relic_safety',buildingId:extractor.id,enabled:true});until(()=>(extractor.buffer?.input.biomatter??0)>=1);writeFileSync('artifacts/eldritch-safety-ready-save.json',encodeSave(s,d.map,d.config));const beforeBone=c.produced.relicBone,beforeBlood=c.produced.bloodstone,batches=extractor.productionBatches??0,bio=extractor.buffer!.input.biomatter!;send({type:'set_relic_extraction',buildingId:extractor.id,enabled:true});until(()=>(extractor.productionBatches??0)>=batches+5);send({type:'set_relic_extraction',buildingId:extractor.id,enabled:false});assert.equal(c.produced.relicBone,beforeBone+10);assert.equal(c.produced.bloodstone,beforeBlood+5);assert.equal(extractor.relicSafetyBatches,0);assert.equal(extractor.buffer!.input.biomatter,bio-1);const played=encodeSave(s,d.map,d.config);decodeSave(played);writeFileSync('artifacts/eldritch-transition-played-save.json',played);console.log(JSON.stringify({passed:true,alternateEarned:true,finalSteps:s.tick-initial,alive:50,food:s.sharedFood,branch:c.anomalyBranch,newFilteredBone:10,newFilteredBlood:5,exactBioConsumed:1,source:s.eldritchSource,inventory:c.inventory}));

const safe=decodeSave(played).island,ex=safe.buildings.find(b=>b.type==='relic_extractor')!,worker=safe.npcs.find(n=>n.id===original)!,v=safe.eldritchSource!;ex.relicEnabled=true;v.charge=24;v.contamination=0;worker.exposure=0;ex.relicSafetyBatches=0;ex.buffer!.input.biomatter=0;const heldBone=safe.civilization!.produced.relicBone;harvestRelic(safe,ex,worker);assert.equal(safe.civilization!.produced.relicBone,heldBone);assert.equal(v.charge,24);ex.relicSafetyBatches=5;for(let i=0;i<5;i++)harvestRelic(safe,ex,worker);assert.equal(v.contamination,20);assert.equal(worker.exposure,10);assert.equal(ex.relicSafetyBatches,0);assert.equal(v.charge,19);const invalidFuel=JSON.parse(played);invalidFuel.island.buildings.find((b:any)=>b.type==='relic_extractor').relicSafetyBatches=6;assert.throws(()=>decodeSave(JSON.stringify(invalidFuel)),/Lọc mẫu/);console.log('PASS paid branch safety: no bio/fuel holds deposit,5filtered batches+20source/+10worker/exact charge5, invalid fuel6 rejected. Fixture fuel5 separate from earned1bio5batches above.');
