import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {decodeSave,encodeSave} from '../src/core/SaveSystem';
import {SimulationSession,type PlayerCommand} from '../src/core/SimulationSession';
import {reserveEntityIds} from '../src/core/factory';
import {initializeWildlife,encounterWildlife,unsafeWildlifePath,tickWildlife} from '../src/core/WildlifeManager';
import {refreshVisibility,startExploration,tickExploration} from '../src/core/ExplorationManager';
import {tickCare,startTreatment} from '../src/core/CareManager';
import {findPath} from '../src/core/pathfinding';
const base=readFileSync('artifacts/patrol-browser-played-save.json','utf8');
const fixture=()=>{const d=decodeSave(base);reserveEntityIds(d.island);initializeWildlife(d.island,d.map);return d;};
const d=fixture(),s=d.island,id=s.npcs.find(n=>n.torch)!.id,n=s.npcs.find(n=>n.id===id)!;assert.equal(s.wilderness!.territories.length,2);
let sim=new SimulationSession(s,d.map),seq=0,steps=0;const send=(command:PlayerCommand)=>{const r=sim.submit({playerId:'wild-earned',sequence:++seq,command});assert(r.accepted,JSON.stringify({command,r}));};
while(s.tick%10!==0&&steps++<20)sim.advanceTicks(1);assert(n.torch!.fuel>0);const wolf=s.wilderness!.territories.find(t=>t.species==='wolf')!;const hp=n.health,roles=s.npcs.map(n=>n.laborRole),fuel=n.torch!.fuel;writeFileSync('artifacts/wildlife-ready-save.json',encodeSave(s,d.map,d.config));send({type:'explore',npcId:id,tileX:wolf.x,tileY:wolf.y});
let mid=false;while(s.exploration!.active&&steps++<50){sim.advanceTicks(1);if(s.wilderness!.repelled&&!mid){writeFileSync('artifacts/wildlife-repelled-save.json',encodeSave(s,d.map,d.config));const r=decodeSave(encodeSave(s,d.map,d.config));assert.equal(r.island.wilderness!.territories.find(t=>t.id===wolf.id)!.retreatUntil,wolf.retreatUntil);mid=true;}}
assert(mid&&s.wilderness!.repelled>=1);assert.equal(n.health,hp);assert.equal(s.npcs.filter(n=>n.isAlive).length,8);assert.deepEqual(s.npcs.map(n=>n.laborRole),roles);assert(!s.exploration!.active);writeFileSync('artifacts/wildlife-played-save.json',encodeSave(s,d.map,d.config));
// These boundary/combat/treatment situations are controlled fixtures, not earned events.
const adjacent=(f:ReturnType<typeof fixture>,species:'wolf'|'boar')=>{const actor=f.island.npcs.find(n=>n.id===id)!,t=f.island.wilderness!.territories.find(t=>t.species===species)!;f.island.tick=(Math.floor(f.island.tick/10)+1)*10;actor.position={tileX:t.animalX,tileY:t.animalY};actor.needs.hunger=0;actor.needs.rest=0;actor.health=100;actor.survivalBlocked=false;return {actor,t};};
{const f=fixture(),{actor,t}=adjacent(f,'wolf'),before={x:t.animalX,y:t.animalY};assert.equal(encounterWildlife(f.island,f.map,actor),null);assert.equal(actor.health,100);assert.equal(t.retreatUntil,f.island.tick+10);assert(Math.max(Math.abs(t.animalX-t.x),Math.abs(t.animalY-t.y))<=2);assert(Math.max(Math.abs(t.animalX-before.x),Math.abs(t.animalY-before.y))<=1);decodeSave(encodeSave(f.island,f.map,f.config));}
{const f=fixture(),{actor,t}=adjacent(f,'wolf');actor.torch!.fuel=0;assert(encounterWildlife(f.island,f.map,actor));assert.equal(actor.health,88);encounterWildlife(f.island,f.map,actor);assert.equal(actor.health,88,'attack cooldown survives repeated checks in one interval');const restored=decodeSave(encodeSave(f.island,f.map,f.config));assert.equal(restored.island.wilderness!.territories[0].cooldownUntil,t.cooldownUntil);}
for(const spear of [false,true]){const f=fixture(),{actor}=adjacent(f,'boar');actor.weapon=spear?'spear':undefined;actor.torch!.fuel=0;encounterWildlife(f.island,f.map,actor);assert.equal(actor.health,spear?92:84);}
{const f=fixture(),{actor}=adjacent(f,'boar');actor.weapon='spear';actor.armor='padded_vest';actor.torch!.fuel=0;encounterWildlife(f.island,f.map,actor);assert.equal(actor.health,96);}
{const f=fixture(),{actor,t}=adjacent(f,'boar');actor.torch!.fuel=0;actor.health=24;encounterWildlife(f.island,f.map,actor);assert.equal(actor.health,20);f.island.tick+=5;encounterWildlife(f.island,f.map,actor);assert.equal(actor.health,20,'no lethal damage while escape is blocked');assert(actor.isAlive);}
{const f=fixture(),{actor,t}=adjacent(f,'wolf');actor.torch!.fuel=0;for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1],[1,1],[1,-1],[-1,1],[-1,-1]])f.map.tiles[t.animalY+dy][t.animalX+dx]='deep_water';const other=f.map.landTiles.find(p=>Math.max(Math.abs(p.x-t.animalX),Math.abs(p.y-t.animalY))===3)!;actor.position={tileX:other.x,tileY:other.y};assert.equal(encounterWildlife(f.island,f.map,actor),null);assert.equal(actor.health,100);}
{const f=fixture(),{actor,t}=adjacent(f,'wolf');t.seen=true;actor.torch!.fuel=0;assert(unsafeWildlifePath(f.island,actor,[{x:t.x,y:t.y}]));actor.torch!.fuel=1;assert(!unsafeWildlifePath(f.island,actor,[{x:t.x,y:t.y}]));const boar=f.island.wilderness!.territories.find(t=>t.species==='boar')!;boar.seen=true;assert(unsafeWildlifePath(f.island,actor,[{x:boar.x,y:boar.y}]));}
{const f=fixture();for(let i=0;i<40;i++){f.island.tick++;tickWildlife(f.island,f.map);for(const t of f.island.wilderness!.territories)assert(Math.max(Math.abs(t.animalX-t.x),Math.abs(t.animalY-t.y))<=2);}const raw=JSON.parse(encodeSave(f.island,f.map,f.config));raw.island.wilderness.territories[0].animalX=raw.island.wilderness.territories[0].x+3;assert.throws(()=>decodeSave(JSON.stringify(raw)));}
{const f=fixture(),fs=f.island,{actor,t}=adjacent(f,'wolf');actor.torch!.fuel=1;assert.equal(startExploration(fs,f.map,id,t.x,t.y),null);fs.tick+=9;tickExploration(fs,f.map);assert.equal(actor.torch!.fuel,0);assert.equal(fs.wilderness!.repelled,0,'a torch burning its last fuel cannot repel');assert.equal(actor.health,88);}
{const f=fixture(),fs=f.island,actor=fs.npcs.find(n=>n.id===id)!,fire=fs.dailyLife!.campfire!;actor.torch!.fuel=0;actor.position={tileX:fire.tileX,tileY:fire.tileY};const wolf=fs.wilderness!.territories[0];wolf.animalX=fire.tileX;wolf.animalY=fire.tileY;assert.equal(encounterWildlife(fs,f.map,actor),null);assert.equal(actor.health,100,'village safe area');}
{const f=fixture(),fs=f.island,{actor,t}=adjacent(f,'boar');actor.torch!.fuel=0;assert.equal(startExploration(fs,f.map,id,t.x,t.y),null);actor.cargo={food:0,wood:2,stone:0,herbs:0};const position={...actor.position!};for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1],[1,1],[1,-1],[-1,1],[-1,-1]])f.map.tiles[position.tileY+dy][position.tileX+dx]='deep_water';const test=new SimulationSession(fs,f.map);for(let i=0;i<30;i++){test.advanceTicks(1);assert.deepEqual(actor.position,position);assert(actor.isAlive);assert((actor.health??100)>=20);assert.equal(actor.cargo!.wood,2);}assert(fs.exploration!.active);decodeSave(encodeSave(fs,f.map,f.config));}
// Prepare a saved public injury -> physical return -> paid existing treatment fixture.
{const f=fixture(),fs=f.island,{actor,t}=adjacent(f,'boar');const route=findPath(f.map,t.animalX,t.animalY,fs.dailyLife!.campfire!.tileX,fs.dailyLife!.campfire!.tileY)!;assert(route.length>4);fs.exploration!.torchStock.push(actor.torch!.fuel);actor.torch=undefined;actor.torchChoice=false;fs.civilization!.unlocks.push('herbalism');assert.equal(startExploration(fs,f.map,id,t.x,t.y),null);fs.exploration!.patrol={npcId:id,enabled:true,nextTick:fs.tick,trips:0};fs.exploration!.active!.automatic=true;writeFileSync('artifacts/wildlife-injury-fixture-save.json',encodeSave(fs,f.map,f.config));
 const test=new SimulationSession(fs,f.map);test.advanceTicks(1);assert(fs.wilderness!.injuries===1);assert(!fs.exploration!.patrol!.enabled);assert.equal(fs.exploration!.active!.stage,'returning');assert((actor.health??100)<90);let count=0;while(fs.exploration!.active&&count++<30)test.advanceTicks(1);assert(!fs.exploration!.active);assert(fs.npcs.every(n=>n.isAlive));
 // Exact medicine formula is isolated from the natural rest clock.
 actor.position={tileX:fs.dailyLife!.campfire!.tileX,tileY:fs.dailyLife!.campfire!.tileY};actor.health=84;actor.survivalBlocked=false;const herbs=fs.herbs;assert.equal(startTreatment(fs,id),null);for(let i=0;i<4;i++){actor.survivalBlocked=false;tickCare(fs,f.map);}assert.equal(fs.herbs,herbs-2);assert.equal(actor.health,100);assert(!actor.treatment);decodeSave(encodeSave(fs,f.map,f.config));
}
writeFileSync('artifacts/wildlife-core-result.json',JSON.stringify({earned:{steps,alive:8,food:s.sharedFood,repelled:s.wilderness!.repelled,injuries:s.wilderness!.injuries,hpBefore:hp,hpAfter:n.health,torchFuelBefore:fuel,torchFuelAfter:n.torch!.fuel,returned:true,rolesPreserved:true},fixtures:{wolfEmptyDamage:12,boarDamage:16,spearBoarDamage:8,spearVestBoarDamage:4,attackCooldown:5,territoryRadius:2,nonlethalFloor:20,herbsPaid:2,medicineWork:4}},null,2));
console.log('PASS earned real walk/torch scares wolf/physical return/8alive/save; separate fixtures empty torch/boar/spear/armor/cooldown/no lethal stuck damage/territory/path/paid herb treatment.');
